server:
  port: 9020
  tomcat:
    max-threads: 20
    uri-encoding: UTF-8
    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.165.167:3306/train_all?characterEncoding=utf8&useSSL=false
    username: root
    password: m$%$:Tmd4ei0V5/A?p+v
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: false
          useLocalTransactionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
  redis:    # REDIS (RedisProperties)
    database: 0 # Redis数据库索引（默认为0）
    host: 47.94.160.44 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: qoGEgJ83BX6vKUmS # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true

logging:
  level:
      root : INFO
      org.jasig.cas: INFO
      org.springframework.security: DEBUG
      com.coxautodev.graphql: DEBUG
      com.aobei.train.mapper: DEBUG
      graphql: DEBUG
      com.coxautodev: DEBUG
      com.oembedler: DEBUG
  path: /var/log/apps/trainapi
 # path: /Users/aobei-dev/logs

custom:
  oauth2key: |
    -----BEGIN PUBLIC KEY-----
    MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDiIOYohBCSgKHkH8TWyGpNaZ7n
    5LipKopcKgu4XOAGlXpnCijgK6DCLDt+yUpZgm4nUFE9MvGAj8GI6d1Mg3rXelTd
    do3cIX4J6I5zvj44IGcprZXfXCU4snCNnoqORYeAtpkPIh/Smj/7ZGOsrLALFO0k
    ZqgeTrQnt0bUFKv1DwIDAQAB
    -----END PUBLIC KEY-----
  aliyun:
    access-key-id : LTAIYlFXdaXPDOej
    access-key-secret : yKVGJOwWrmmx3wAJG0nupzU46PVZou
    oss:
      endpoint: http://oss-cn-beijing.aliyuncs.com       
      access-key-id: LTAIYlFXdaXPDOej
      access-key-secret: yKVGJOwWrmmx3wAJG0nupzU46PVZou
      public-bucket: aobei-test-public
      private-bucket: aobei-test
    sms:
      region-id : cn-hangzhou  #固定值不需要更改
      endpoint : cn-hangzhou  #固定值不需要更改
      product: Dysmsapi #固定值不需要更改
      domain : dysmsapi.aliyuncs.com #固定值不需要更改
      topic: aobei_topic
      producer-id: PID_aobei_Producer
      consumer-id: CID_aobei_Consumer
  igtpush:
    host: http://sdk.open.api.igexin.com/apiex.htm
    customer:
      app-id: F3I5V5kiByArgh0JoUQZ02
      app-key: uQMIzY5rDQ8V2m67EfRc41
      master-secret: VFuY1ncyLG7dkvJM0XK5M1
    partner:
      app-id: F3I5V5kiByArgh0JoUQZ02
      app-key: uQMIzY5rDQ8V2m67EfRc41
      master-secret: VFuY1ncyLG7dkvJM0XK5M1
    student:
      app-id: F3I5V5kiByArgh0JoUQZ02
      app-key: uQMIzY5rDQ8V2m67EfRc41
      master-secret: VFuY1ncyLG7dkvJM0XK5M1
    teacher:
      app-id: F3I5V5kiByArgh0JoUQZ02
      app-key: uQMIzY5rDQ8V2m67EfRc41
      master-secret: VFuY1ncyLG7dkvJM0XK5M1

  wx:
    pay_notify_url: https://dev-api.aobei.com/callback/{path}/wxpay
    refund_notify_url: https://dev-api.aobei.com/callback/{path}/wxpay

