package com.aobei.train.model;

import com.aobei.train.model.AliPayExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class AliPayExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ali_pay
     *
     * @mbg.generated Thu May 31 11:36:01 CST 2018
     */
    public AliPayExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ali_pay
     *
     * @mbg.generated Thu May 31 11:36:01 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ali_pay
     *
     * @mbg.generated Thu May 31 11:36:01 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ali_pay
     *
     * @mbg.generated Thu May 31 11:36:01 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ali_pay
     *
     * @mbg.generated Thu May 31 11:36:01 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andApp_idIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andApp_idIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andApp_idEqualTo(String value) {
            addCriterion("app_id =", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idNotEqualTo(String value) {
            addCriterion("app_id <>", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idGreaterThan(String value) {
            addCriterion("app_id >", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idLessThan(String value) {
            addCriterion("app_id <", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idLike(String value) {
            addCriterion("app_id like", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idNotLike(String value) {
            addCriterion("app_id not like", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idIn(List<String> values) {
            addCriterion("app_id in", values, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idNotIn(List<String> values) {
            addCriterion("app_id not in", values, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "app_id");
            return (Criteria) this;
        }

        public Criteria andPublic_keyIsNull() {
            addCriterion("public_key is null");
            return (Criteria) this;
        }

        public Criteria andPublic_keyIsNotNull() {
            addCriterion("public_key is not null");
            return (Criteria) this;
        }

        public Criteria andPublic_keyEqualTo(String value) {
            addCriterion("public_key =", value, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyNotEqualTo(String value) {
            addCriterion("public_key <>", value, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyGreaterThan(String value) {
            addCriterion("public_key >", value, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyGreaterThanOrEqualTo(String value) {
            addCriterion("public_key >=", value, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyLessThan(String value) {
            addCriterion("public_key <", value, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyLessThanOrEqualTo(String value) {
            addCriterion("public_key <=", value, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyLike(String value) {
            addCriterion("public_key like", value, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyNotLike(String value) {
            addCriterion("public_key not like", value, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyIn(List<String> values) {
            addCriterion("public_key in", values, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyNotIn(List<String> values) {
            addCriterion("public_key not in", values, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyBetween(String value1, String value2) {
            addCriterion("public_key between", value1, value2, "public_key");
            return (Criteria) this;
        }

        public Criteria andPublic_keyNotBetween(String value1, String value2) {
            addCriterion("public_key not between", value1, value2, "public_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyIsNull() {
            addCriterion("private_key is null");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyIsNotNull() {
            addCriterion("private_key is not null");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyEqualTo(String value) {
            addCriterion("private_key =", value, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyNotEqualTo(String value) {
            addCriterion("private_key <>", value, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyGreaterThan(String value) {
            addCriterion("private_key >", value, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyGreaterThanOrEqualTo(String value) {
            addCriterion("private_key >=", value, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyLessThan(String value) {
            addCriterion("private_key <", value, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyLessThanOrEqualTo(String value) {
            addCriterion("private_key <=", value, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyLike(String value) {
            addCriterion("private_key like", value, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyNotLike(String value) {
            addCriterion("private_key not like", value, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyIn(List<String> values) {
            addCriterion("private_key in", values, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyNotIn(List<String> values) {
            addCriterion("private_key not in", values, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyBetween(String value1, String value2) {
            addCriterion("private_key between", value1, value2, "private_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyNotBetween(String value1, String value2) {
            addCriterion("private_key not between", value1, value2, "private_key");
            return (Criteria) this;
        }

        public Criteria andApp_idLikeInsensitive(String value) {
            addCriterion("upper(app_id) like", value.toUpperCase(), "app_id");
            return (Criteria) this;
        }

        public Criteria andPublic_keyLikeInsensitive(String value) {
            addCriterion("upper(public_key) like", value.toUpperCase(), "public_key");
            return (Criteria) this;
        }

        public Criteria andPrivate_keyLikeInsensitive(String value) {
            addCriterion("upper(private_key) like", value.toUpperCase(), "private_key");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ali_pay
     *
     * @mbg.generated do_not_delete_during_merge Thu May 31 11:36:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table ali_pay
     *
     * @mbg.generated Thu May 31 11:36:01 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]
		//--------------------------------------------------					
						app_id(1,Types.VARCHAR,false),					
						public_key(2,Types.VARCHAR,false),					
						private_key(2,Types.VARCHAR,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}