package com.aobei.train.model;

import com.aobei.train.model.AppPackExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class AppPackExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_pack
     *
     * @mbg.generated Tue Jun 19 18:19:05 CST 2018
     */
    public AppPackExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_pack
     *
     * @mbg.generated Tue Jun 19 18:19:05 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_pack
     *
     * @mbg.generated Tue Jun 19 18:19:05 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_pack
     *
     * @mbg.generated Tue Jun 19 18:19:05 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_pack
     *
     * @mbg.generated Tue Jun 19 18:19:05 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andApp_pack_idIsNull() {
            addCriterion("app_pack_id is null");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idIsNotNull() {
            addCriterion("app_pack_id is not null");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idEqualTo(String value) {
            addCriterion("app_pack_id =", value, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idNotEqualTo(String value) {
            addCriterion("app_pack_id <>", value, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idGreaterThan(String value) {
            addCriterion("app_pack_id >", value, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idGreaterThanOrEqualTo(String value) {
            addCriterion("app_pack_id >=", value, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idLessThan(String value) {
            addCriterion("app_pack_id <", value, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idLessThanOrEqualTo(String value) {
            addCriterion("app_pack_id <=", value, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idLike(String value) {
            addCriterion("app_pack_id like", value, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idNotLike(String value) {
            addCriterion("app_pack_id not like", value, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idIn(List<String> values) {
            addCriterion("app_pack_id in", values, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idNotIn(List<String> values) {
            addCriterion("app_pack_id not in", values, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idBetween(String value1, String value2) {
            addCriterion("app_pack_id between", value1, value2, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idNotBetween(String value1, String value2) {
            addCriterion("app_pack_id not between", value1, value2, "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameIsNull() {
            addCriterion("app_pack_name is null");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameIsNotNull() {
            addCriterion("app_pack_name is not null");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameEqualTo(String value) {
            addCriterion("app_pack_name =", value, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameNotEqualTo(String value) {
            addCriterion("app_pack_name <>", value, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameGreaterThan(String value) {
            addCriterion("app_pack_name >", value, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameGreaterThanOrEqualTo(String value) {
            addCriterion("app_pack_name >=", value, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameLessThan(String value) {
            addCriterion("app_pack_name <", value, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameLessThanOrEqualTo(String value) {
            addCriterion("app_pack_name <=", value, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameLike(String value) {
            addCriterion("app_pack_name like", value, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameNotLike(String value) {
            addCriterion("app_pack_name not like", value, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameIn(List<String> values) {
            addCriterion("app_pack_name in", values, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameNotIn(List<String> values) {
            addCriterion("app_pack_name not in", values, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameBetween(String value1, String value2) {
            addCriterion("app_pack_name between", value1, value2, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameNotBetween(String value1, String value2) {
            addCriterion("app_pack_name not between", value1, value2, "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameIsNull() {
            addCriterion("group_name is null");
            return (Criteria) this;
        }

        public Criteria andGroup_nameIsNotNull() {
            addCriterion("group_name is not null");
            return (Criteria) this;
        }

        public Criteria andGroup_nameEqualTo(String value) {
            addCriterion("group_name =", value, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameNotEqualTo(String value) {
            addCriterion("group_name <>", value, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameGreaterThan(String value) {
            addCriterion("group_name >", value, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameGreaterThanOrEqualTo(String value) {
            addCriterion("group_name >=", value, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameLessThan(String value) {
            addCriterion("group_name <", value, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameLessThanOrEqualTo(String value) {
            addCriterion("group_name <=", value, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameLike(String value) {
            addCriterion("group_name like", value, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameNotLike(String value) {
            addCriterion("group_name not like", value, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameIn(List<String> values) {
            addCriterion("group_name in", values, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameNotIn(List<String> values) {
            addCriterion("group_name not in", values, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameBetween(String value1, String value2) {
            addCriterion("group_name between", value1, value2, "group_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameNotBetween(String value1, String value2) {
            addCriterion("group_name not between", value1, value2, "group_name");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andApp_urlIsNull() {
            addCriterion("app_url is null");
            return (Criteria) this;
        }

        public Criteria andApp_urlIsNotNull() {
            addCriterion("app_url is not null");
            return (Criteria) this;
        }

        public Criteria andApp_urlEqualTo(String value) {
            addCriterion("app_url =", value, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlNotEqualTo(String value) {
            addCriterion("app_url <>", value, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlGreaterThan(String value) {
            addCriterion("app_url >", value, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlGreaterThanOrEqualTo(String value) {
            addCriterion("app_url >=", value, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlLessThan(String value) {
            addCriterion("app_url <", value, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlLessThanOrEqualTo(String value) {
            addCriterion("app_url <=", value, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlLike(String value) {
            addCriterion("app_url like", value, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlNotLike(String value) {
            addCriterion("app_url not like", value, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlIn(List<String> values) {
            addCriterion("app_url in", values, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlNotIn(List<String> values) {
            addCriterion("app_url not in", values, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlBetween(String value1, String value2) {
            addCriterion("app_url between", value1, value2, "app_url");
            return (Criteria) this;
        }

        public Criteria andApp_urlNotBetween(String value1, String value2) {
            addCriterion("app_url not between", value1, value2, "app_url");
            return (Criteria) this;
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Integer value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Integer value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Integer value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Integer value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Integer value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Integer> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Integer> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Integer value1, Integer value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Integer value1, Integer value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andApp_pack_idLikeInsensitive(String value) {
            addCriterion("upper(app_pack_id) like", value.toUpperCase(), "app_pack_id");
            return (Criteria) this;
        }

        public Criteria andApp_pack_nameLikeInsensitive(String value) {
            addCriterion("upper(app_pack_name) like", value.toUpperCase(), "app_pack_name");
            return (Criteria) this;
        }

        public Criteria andGroup_nameLikeInsensitive(String value) {
            addCriterion("upper(group_name) like", value.toUpperCase(), "group_name");
            return (Criteria) this;
        }

        public Criteria andApp_urlLikeInsensitive(String value) {
            addCriterion("upper(app_url) like", value.toUpperCase(), "app_url");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_pack
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 19 18:19:05 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table app_pack
     *
     * @mbg.generated Tue Jun 19 18:19:05 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	app 应用
		//--------------------------------------------------					
														app_pack_id(1,Types.VARCHAR,false),
		/** 应用名称 */									app_pack_name(2,Types.VARCHAR,false),
		/** 分组名称 */									group_name(2,Types.VARCHAR,false),
		/** 1 微信小程序   2  h5   3 安卓  4 ios */		type(2,Types.INTEGER,false),
		/** 小程序  appid, h5 应用 URL 地址, 安卓  下载地址 url , IOS 应用商店地址 */
														app_url(2,Types.VARCHAR,false),
		/** 数字 id */									sid(2,Types.INTEGER,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}