package com.aobei.train.model;

import com.aobei.train.model.BespeakExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class BespeakExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bespeak_strategy
     *
     * @mbg.generated Mon Apr 16 14:13:01 CST 2018
     */
    public BespeakExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bespeak_strategy
     *
     * @mbg.generated Mon Apr 16 14:13:01 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bespeak_strategy
     *
     * @mbg.generated Mon Apr 16 14:13:01 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bespeak_strategy
     *
     * @mbg.generated Mon Apr 16 14:13:01 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bespeak_strategy
     *
     * @mbg.generated Mon Apr 16 14:13:01 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andBespeak_strategy_idIsNull() {
            addCriterion("bespeak_strategy_id is null");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idIsNotNull() {
            addCriterion("bespeak_strategy_id is not null");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idEqualTo(Integer value) {
            addCriterion("bespeak_strategy_id =", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idNotEqualTo(Integer value) {
            addCriterion("bespeak_strategy_id <>", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idGreaterThan(Integer value) {
            addCriterion("bespeak_strategy_id >", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("bespeak_strategy_id >=", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idLessThan(Integer value) {
            addCriterion("bespeak_strategy_id <", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idLessThanOrEqualTo(Integer value) {
            addCriterion("bespeak_strategy_id <=", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idIn(List<Integer> values) {
            addCriterion("bespeak_strategy_id in", values, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idNotIn(List<Integer> values) {
            addCriterion("bespeak_strategy_id not in", values, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idBetween(Integer value1, Integer value2) {
            addCriterion("bespeak_strategy_id between", value1, value2, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idNotBetween(Integer value1, Integer value2) {
            addCriterion("bespeak_strategy_id not between", value1, value2, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyIsNull() {
            addCriterion("bespeak_strategy is null");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyIsNotNull() {
            addCriterion("bespeak_strategy is not null");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyEqualTo(String value) {
            addCriterion("bespeak_strategy =", value, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyNotEqualTo(String value) {
            addCriterion("bespeak_strategy <>", value, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyGreaterThan(String value) {
            addCriterion("bespeak_strategy >", value, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyGreaterThanOrEqualTo(String value) {
            addCriterion("bespeak_strategy >=", value, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyLessThan(String value) {
            addCriterion("bespeak_strategy <", value, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyLessThanOrEqualTo(String value) {
            addCriterion("bespeak_strategy <=", value, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyLike(String value) {
            addCriterion("bespeak_strategy like", value, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyNotLike(String value) {
            addCriterion("bespeak_strategy not like", value, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyIn(List<String> values) {
            addCriterion("bespeak_strategy in", values, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyNotIn(List<String> values) {
            addCriterion("bespeak_strategy not in", values, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyBetween(String value1, String value2) {
            addCriterion("bespeak_strategy between", value1, value2, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyNotBetween(String value1, String value2) {
            addCriterion("bespeak_strategy not between", value1, value2, "bespeak_strategy");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(name) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategyLikeInsensitive(String value) {
            addCriterion("upper(bespeak_strategy) like", value.toUpperCase(), "bespeak_strategy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bespeak_strategy
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 16 14:13:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table bespeak_strategy
     *
     * @mbg.generated Mon Apr 16 14:13:01 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	预约策略
		//--------------------------------------------------
		/** 自增长 */									bespeak_strategy_id(1,Types.INTEGER,false),					
														name(2,Types.VARCHAR,false),
		/** 预约策略JSON 数据 [{“before_hour” : 9  , "after_hours" :  3}, {“before_hour” : 13  , "after_hours" :  12}] */
														bespeak_strategy(2,Types.VARCHAR,false),					
														create_datetime(2,Types.TIMESTAMP,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}