package com.aobei.train.model;

import com.aobei.train.model.BillBatchExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class BillBatchExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_batch
     *
     * @mbg.generated Mon May 14 16:47:32 CST 2018
     */
    public BillBatchExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_batch
     *
     * @mbg.generated Mon May 14 16:47:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_batch
     *
     * @mbg.generated Mon May 14 16:47:32 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_batch
     *
     * @mbg.generated Mon May 14 16:47:32 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill_batch
     *
     * @mbg.generated Mon May 14 16:47:32 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andBill_batch_idIsNull() {
            addCriterion("bill_batch_id is null");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idIsNotNull() {
            addCriterion("bill_batch_id is not null");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idEqualTo(String value) {
            addCriterion("bill_batch_id =", value, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idNotEqualTo(String value) {
            addCriterion("bill_batch_id <>", value, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idGreaterThan(String value) {
            addCriterion("bill_batch_id >", value, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idGreaterThanOrEqualTo(String value) {
            addCriterion("bill_batch_id >=", value, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idLessThan(String value) {
            addCriterion("bill_batch_id <", value, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idLessThanOrEqualTo(String value) {
            addCriterion("bill_batch_id <=", value, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idLike(String value) {
            addCriterion("bill_batch_id like", value, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idNotLike(String value) {
            addCriterion("bill_batch_id not like", value, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idIn(List<String> values) {
            addCriterion("bill_batch_id in", values, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idNotIn(List<String> values) {
            addCriterion("bill_batch_id not in", values, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idBetween(String value1, String value2) {
            addCriterion("bill_batch_id between", value1, value2, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idNotBetween(String value1, String value2) {
            addCriterion("bill_batch_id not between", value1, value2, "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andPay_typeIsNull() {
            addCriterion("pay_type is null");
            return (Criteria) this;
        }

        public Criteria andPay_typeIsNotNull() {
            addCriterion("pay_type is not null");
            return (Criteria) this;
        }

        public Criteria andPay_typeEqualTo(Integer value) {
            addCriterion("pay_type =", value, "pay_type");
            return (Criteria) this;
        }

        public Criteria andPay_typeNotEqualTo(Integer value) {
            addCriterion("pay_type <>", value, "pay_type");
            return (Criteria) this;
        }

        public Criteria andPay_typeGreaterThan(Integer value) {
            addCriterion("pay_type >", value, "pay_type");
            return (Criteria) this;
        }

        public Criteria andPay_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_type >=", value, "pay_type");
            return (Criteria) this;
        }

        public Criteria andPay_typeLessThan(Integer value) {
            addCriterion("pay_type <", value, "pay_type");
            return (Criteria) this;
        }

        public Criteria andPay_typeLessThanOrEqualTo(Integer value) {
            addCriterion("pay_type <=", value, "pay_type");
            return (Criteria) this;
        }

        public Criteria andPay_typeIn(List<Integer> values) {
            addCriterion("pay_type in", values, "pay_type");
            return (Criteria) this;
        }

        public Criteria andPay_typeNotIn(List<Integer> values) {
            addCriterion("pay_type not in", values, "pay_type");
            return (Criteria) this;
        }

        public Criteria andPay_typeBetween(Integer value1, Integer value2) {
            addCriterion("pay_type between", value1, value2, "pay_type");
            return (Criteria) this;
        }

        public Criteria andPay_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_type not between", value1, value2, "pay_type");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeIsNull() {
            addCriterion("bill_datetime is null");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeIsNotNull() {
            addCriterion("bill_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeEqualTo(Date value) {
            addCriterion("bill_datetime =", value, "bill_datetime");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeNotEqualTo(Date value) {
            addCriterion("bill_datetime <>", value, "bill_datetime");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeGreaterThan(Date value) {
            addCriterion("bill_datetime >", value, "bill_datetime");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("bill_datetime >=", value, "bill_datetime");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeLessThan(Date value) {
            addCriterion("bill_datetime <", value, "bill_datetime");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("bill_datetime <=", value, "bill_datetime");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeIn(List<Date> values) {
            addCriterion("bill_datetime in", values, "bill_datetime");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeNotIn(List<Date> values) {
            addCriterion("bill_datetime not in", values, "bill_datetime");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeBetween(Date value1, Date value2) {
            addCriterion("bill_datetime between", value1, value2, "bill_datetime");
            return (Criteria) this;
        }

        public Criteria andBill_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("bill_datetime not between", value1, value2, "bill_datetime");
            return (Criteria) this;
        }

        public Criteria andBill_dateIsNull() {
            addCriterion("bill_date is null");
            return (Criteria) this;
        }

        public Criteria andBill_dateIsNotNull() {
            addCriterion("bill_date is not null");
            return (Criteria) this;
        }

        public Criteria andBill_dateEqualTo(Date value) {
            addCriterionForJDBCDate("bill_date =", value, "bill_date");
            return (Criteria) this;
        }

        public Criteria andBill_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("bill_date <>", value, "bill_date");
            return (Criteria) this;
        }

        public Criteria andBill_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("bill_date >", value, "bill_date");
            return (Criteria) this;
        }

        public Criteria andBill_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("bill_date >=", value, "bill_date");
            return (Criteria) this;
        }

        public Criteria andBill_dateLessThan(Date value) {
            addCriterionForJDBCDate("bill_date <", value, "bill_date");
            return (Criteria) this;
        }

        public Criteria andBill_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("bill_date <=", value, "bill_date");
            return (Criteria) this;
        }

        public Criteria andBill_dateIn(List<Date> values) {
            addCriterionForJDBCDate("bill_date in", values, "bill_date");
            return (Criteria) this;
        }

        public Criteria andBill_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("bill_date not in", values, "bill_date");
            return (Criteria) this;
        }

        public Criteria andBill_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("bill_date between", value1, value2, "bill_date");
            return (Criteria) this;
        }

        public Criteria andBill_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("bill_date not between", value1, value2, "bill_date");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersIsNull() {
            addCriterion("my_total_orders is null");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersIsNotNull() {
            addCriterion("my_total_orders is not null");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersEqualTo(Integer value) {
            addCriterion("my_total_orders =", value, "my_total_orders");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersNotEqualTo(Integer value) {
            addCriterion("my_total_orders <>", value, "my_total_orders");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersGreaterThan(Integer value) {
            addCriterion("my_total_orders >", value, "my_total_orders");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersGreaterThanOrEqualTo(Integer value) {
            addCriterion("my_total_orders >=", value, "my_total_orders");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersLessThan(Integer value) {
            addCriterion("my_total_orders <", value, "my_total_orders");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersLessThanOrEqualTo(Integer value) {
            addCriterion("my_total_orders <=", value, "my_total_orders");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersIn(List<Integer> values) {
            addCriterion("my_total_orders in", values, "my_total_orders");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersNotIn(List<Integer> values) {
            addCriterion("my_total_orders not in", values, "my_total_orders");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersBetween(Integer value1, Integer value2) {
            addCriterion("my_total_orders between", value1, value2, "my_total_orders");
            return (Criteria) this;
        }

        public Criteria andMy_total_ordersNotBetween(Integer value1, Integer value2) {
            addCriterion("my_total_orders not between", value1, value2, "my_total_orders");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeIsNull() {
            addCriterion("my_total_fee is null");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeIsNotNull() {
            addCriterion("my_total_fee is not null");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeEqualTo(Integer value) {
            addCriterion("my_total_fee =", value, "my_total_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeNotEqualTo(Integer value) {
            addCriterion("my_total_fee <>", value, "my_total_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeGreaterThan(Integer value) {
            addCriterion("my_total_fee >", value, "my_total_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeGreaterThanOrEqualTo(Integer value) {
            addCriterion("my_total_fee >=", value, "my_total_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeLessThan(Integer value) {
            addCriterion("my_total_fee <", value, "my_total_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeLessThanOrEqualTo(Integer value) {
            addCriterion("my_total_fee <=", value, "my_total_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeIn(List<Integer> values) {
            addCriterion("my_total_fee in", values, "my_total_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeNotIn(List<Integer> values) {
            addCriterion("my_total_fee not in", values, "my_total_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeBetween(Integer value1, Integer value2) {
            addCriterion("my_total_fee between", value1, value2, "my_total_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_feeNotBetween(Integer value1, Integer value2) {
            addCriterion("my_total_fee not between", value1, value2, "my_total_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeIsNull() {
            addCriterion("my_total_refund_fee is null");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeIsNotNull() {
            addCriterion("my_total_refund_fee is not null");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeEqualTo(Integer value) {
            addCriterion("my_total_refund_fee =", value, "my_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeNotEqualTo(Integer value) {
            addCriterion("my_total_refund_fee <>", value, "my_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeGreaterThan(Integer value) {
            addCriterion("my_total_refund_fee >", value, "my_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeGreaterThanOrEqualTo(Integer value) {
            addCriterion("my_total_refund_fee >=", value, "my_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeLessThan(Integer value) {
            addCriterion("my_total_refund_fee <", value, "my_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeLessThanOrEqualTo(Integer value) {
            addCriterion("my_total_refund_fee <=", value, "my_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeIn(List<Integer> values) {
            addCriterion("my_total_refund_fee in", values, "my_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeNotIn(List<Integer> values) {
            addCriterion("my_total_refund_fee not in", values, "my_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeBetween(Integer value1, Integer value2) {
            addCriterion("my_total_refund_fee between", value1, value2, "my_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andMy_total_refund_feeNotBetween(Integer value1, Integer value2) {
            addCriterion("my_total_refund_fee not between", value1, value2, "my_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersIsNull() {
            addCriterion("p_total_orders is null");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersIsNotNull() {
            addCriterion("p_total_orders is not null");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersEqualTo(Integer value) {
            addCriterion("p_total_orders =", value, "p_total_orders");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersNotEqualTo(Integer value) {
            addCriterion("p_total_orders <>", value, "p_total_orders");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersGreaterThan(Integer value) {
            addCriterion("p_total_orders >", value, "p_total_orders");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_total_orders >=", value, "p_total_orders");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersLessThan(Integer value) {
            addCriterion("p_total_orders <", value, "p_total_orders");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersLessThanOrEqualTo(Integer value) {
            addCriterion("p_total_orders <=", value, "p_total_orders");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersIn(List<Integer> values) {
            addCriterion("p_total_orders in", values, "p_total_orders");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersNotIn(List<Integer> values) {
            addCriterion("p_total_orders not in", values, "p_total_orders");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersBetween(Integer value1, Integer value2) {
            addCriterion("p_total_orders between", value1, value2, "p_total_orders");
            return (Criteria) this;
        }

        public Criteria andP_total_ordersNotBetween(Integer value1, Integer value2) {
            addCriterion("p_total_orders not between", value1, value2, "p_total_orders");
            return (Criteria) this;
        }

        public Criteria andP_total_feeIsNull() {
            addCriterion("p_total_fee is null");
            return (Criteria) this;
        }

        public Criteria andP_total_feeIsNotNull() {
            addCriterion("p_total_fee is not null");
            return (Criteria) this;
        }

        public Criteria andP_total_feeEqualTo(Integer value) {
            addCriterion("p_total_fee =", value, "p_total_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_feeNotEqualTo(Integer value) {
            addCriterion("p_total_fee <>", value, "p_total_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_feeGreaterThan(Integer value) {
            addCriterion("p_total_fee >", value, "p_total_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_feeGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_total_fee >=", value, "p_total_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_feeLessThan(Integer value) {
            addCriterion("p_total_fee <", value, "p_total_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_feeLessThanOrEqualTo(Integer value) {
            addCriterion("p_total_fee <=", value, "p_total_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_feeIn(List<Integer> values) {
            addCriterion("p_total_fee in", values, "p_total_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_feeNotIn(List<Integer> values) {
            addCriterion("p_total_fee not in", values, "p_total_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_feeBetween(Integer value1, Integer value2) {
            addCriterion("p_total_fee between", value1, value2, "p_total_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_feeNotBetween(Integer value1, Integer value2) {
            addCriterion("p_total_fee not between", value1, value2, "p_total_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeIsNull() {
            addCriterion("p_total_service_charge is null");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeIsNotNull() {
            addCriterion("p_total_service_charge is not null");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeEqualTo(Integer value) {
            addCriterion("p_total_service_charge =", value, "p_total_service_charge");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeNotEqualTo(Integer value) {
            addCriterion("p_total_service_charge <>", value, "p_total_service_charge");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeGreaterThan(Integer value) {
            addCriterion("p_total_service_charge >", value, "p_total_service_charge");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_total_service_charge >=", value, "p_total_service_charge");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeLessThan(Integer value) {
            addCriterion("p_total_service_charge <", value, "p_total_service_charge");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeLessThanOrEqualTo(Integer value) {
            addCriterion("p_total_service_charge <=", value, "p_total_service_charge");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeIn(List<Integer> values) {
            addCriterion("p_total_service_charge in", values, "p_total_service_charge");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeNotIn(List<Integer> values) {
            addCriterion("p_total_service_charge not in", values, "p_total_service_charge");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeBetween(Integer value1, Integer value2) {
            addCriterion("p_total_service_charge between", value1, value2, "p_total_service_charge");
            return (Criteria) this;
        }

        public Criteria andP_total_service_chargeNotBetween(Integer value1, Integer value2) {
            addCriterion("p_total_service_charge not between", value1, value2, "p_total_service_charge");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeIsNull() {
            addCriterion("p_total_refund_fee is null");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeIsNotNull() {
            addCriterion("p_total_refund_fee is not null");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeEqualTo(Integer value) {
            addCriterion("p_total_refund_fee =", value, "p_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeNotEqualTo(Integer value) {
            addCriterion("p_total_refund_fee <>", value, "p_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeGreaterThan(Integer value) {
            addCriterion("p_total_refund_fee >", value, "p_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_total_refund_fee >=", value, "p_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeLessThan(Integer value) {
            addCriterion("p_total_refund_fee <", value, "p_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeLessThanOrEqualTo(Integer value) {
            addCriterion("p_total_refund_fee <=", value, "p_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeIn(List<Integer> values) {
            addCriterion("p_total_refund_fee in", values, "p_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeNotIn(List<Integer> values) {
            addCriterion("p_total_refund_fee not in", values, "p_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeBetween(Integer value1, Integer value2) {
            addCriterion("p_total_refund_fee between", value1, value2, "p_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andP_total_refund_feeNotBetween(Integer value1, Integer value2) {
            addCriterion("p_total_refund_fee not between", value1, value2, "p_total_refund_fee");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1IsNull() {
            addCriterion("status_count_1 is null");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1IsNotNull() {
            addCriterion("status_count_1 is not null");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1EqualTo(Integer value) {
            addCriterion("status_count_1 =", value, "status_count_1");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1NotEqualTo(Integer value) {
            addCriterion("status_count_1 <>", value, "status_count_1");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1GreaterThan(Integer value) {
            addCriterion("status_count_1 >", value, "status_count_1");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1GreaterThanOrEqualTo(Integer value) {
            addCriterion("status_count_1 >=", value, "status_count_1");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1LessThan(Integer value) {
            addCriterion("status_count_1 <", value, "status_count_1");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1LessThanOrEqualTo(Integer value) {
            addCriterion("status_count_1 <=", value, "status_count_1");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1In(List<Integer> values) {
            addCriterion("status_count_1 in", values, "status_count_1");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1NotIn(List<Integer> values) {
            addCriterion("status_count_1 not in", values, "status_count_1");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1Between(Integer value1, Integer value2) {
            addCriterion("status_count_1 between", value1, value2, "status_count_1");
            return (Criteria) this;
        }

        public Criteria andStatus_count_1NotBetween(Integer value1, Integer value2) {
            addCriterion("status_count_1 not between", value1, value2, "status_count_1");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2IsNull() {
            addCriterion("status_count_2 is null");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2IsNotNull() {
            addCriterion("status_count_2 is not null");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2EqualTo(Integer value) {
            addCriterion("status_count_2 =", value, "status_count_2");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2NotEqualTo(Integer value) {
            addCriterion("status_count_2 <>", value, "status_count_2");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2GreaterThan(Integer value) {
            addCriterion("status_count_2 >", value, "status_count_2");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2GreaterThanOrEqualTo(Integer value) {
            addCriterion("status_count_2 >=", value, "status_count_2");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2LessThan(Integer value) {
            addCriterion("status_count_2 <", value, "status_count_2");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2LessThanOrEqualTo(Integer value) {
            addCriterion("status_count_2 <=", value, "status_count_2");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2In(List<Integer> values) {
            addCriterion("status_count_2 in", values, "status_count_2");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2NotIn(List<Integer> values) {
            addCriterion("status_count_2 not in", values, "status_count_2");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2Between(Integer value1, Integer value2) {
            addCriterion("status_count_2 between", value1, value2, "status_count_2");
            return (Criteria) this;
        }

        public Criteria andStatus_count_2NotBetween(Integer value1, Integer value2) {
            addCriterion("status_count_2 not between", value1, value2, "status_count_2");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3IsNull() {
            addCriterion("status_count_3 is null");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3IsNotNull() {
            addCriterion("status_count_3 is not null");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3EqualTo(Integer value) {
            addCriterion("status_count_3 =", value, "status_count_3");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3NotEqualTo(Integer value) {
            addCriterion("status_count_3 <>", value, "status_count_3");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3GreaterThan(Integer value) {
            addCriterion("status_count_3 >", value, "status_count_3");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3GreaterThanOrEqualTo(Integer value) {
            addCriterion("status_count_3 >=", value, "status_count_3");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3LessThan(Integer value) {
            addCriterion("status_count_3 <", value, "status_count_3");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3LessThanOrEqualTo(Integer value) {
            addCriterion("status_count_3 <=", value, "status_count_3");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3In(List<Integer> values) {
            addCriterion("status_count_3 in", values, "status_count_3");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3NotIn(List<Integer> values) {
            addCriterion("status_count_3 not in", values, "status_count_3");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3Between(Integer value1, Integer value2) {
            addCriterion("status_count_3 between", value1, value2, "status_count_3");
            return (Criteria) this;
        }

        public Criteria andStatus_count_3NotBetween(Integer value1, Integer value2) {
            addCriterion("status_count_3 not between", value1, value2, "status_count_3");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4IsNull() {
            addCriterion("status_count_4 is null");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4IsNotNull() {
            addCriterion("status_count_4 is not null");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4EqualTo(Integer value) {
            addCriterion("status_count_4 =", value, "status_count_4");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4NotEqualTo(Integer value) {
            addCriterion("status_count_4 <>", value, "status_count_4");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4GreaterThan(Integer value) {
            addCriterion("status_count_4 >", value, "status_count_4");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4GreaterThanOrEqualTo(Integer value) {
            addCriterion("status_count_4 >=", value, "status_count_4");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4LessThan(Integer value) {
            addCriterion("status_count_4 <", value, "status_count_4");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4LessThanOrEqualTo(Integer value) {
            addCriterion("status_count_4 <=", value, "status_count_4");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4In(List<Integer> values) {
            addCriterion("status_count_4 in", values, "status_count_4");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4NotIn(List<Integer> values) {
            addCriterion("status_count_4 not in", values, "status_count_4");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4Between(Integer value1, Integer value2) {
            addCriterion("status_count_4 between", value1, value2, "status_count_4");
            return (Criteria) this;
        }

        public Criteria andStatus_count_4NotBetween(Integer value1, Integer value2) {
            addCriterion("status_count_4 not between", value1, value2, "status_count_4");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5IsNull() {
            addCriterion("status_count_5 is null");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5IsNotNull() {
            addCriterion("status_count_5 is not null");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5EqualTo(Integer value) {
            addCriterion("status_count_5 =", value, "status_count_5");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5NotEqualTo(Integer value) {
            addCriterion("status_count_5 <>", value, "status_count_5");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5GreaterThan(Integer value) {
            addCriterion("status_count_5 >", value, "status_count_5");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5GreaterThanOrEqualTo(Integer value) {
            addCriterion("status_count_5 >=", value, "status_count_5");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5LessThan(Integer value) {
            addCriterion("status_count_5 <", value, "status_count_5");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5LessThanOrEqualTo(Integer value) {
            addCriterion("status_count_5 <=", value, "status_count_5");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5In(List<Integer> values) {
            addCriterion("status_count_5 in", values, "status_count_5");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5NotIn(List<Integer> values) {
            addCriterion("status_count_5 not in", values, "status_count_5");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5Between(Integer value1, Integer value2) {
            addCriterion("status_count_5 between", value1, value2, "status_count_5");
            return (Criteria) this;
        }

        public Criteria andStatus_count_5NotBetween(Integer value1, Integer value2) {
            addCriterion("status_count_5 not between", value1, value2, "status_count_5");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeIsNull() {
            addCriterion("start_datetime is null");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeIsNotNull() {
            addCriterion("start_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeEqualTo(Date value) {
            addCriterion("start_datetime =", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeNotEqualTo(Date value) {
            addCriterion("start_datetime <>", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeGreaterThan(Date value) {
            addCriterion("start_datetime >", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_datetime >=", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeLessThan(Date value) {
            addCriterion("start_datetime <", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("start_datetime <=", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeIn(List<Date> values) {
            addCriterion("start_datetime in", values, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeNotIn(List<Date> values) {
            addCriterion("start_datetime not in", values, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeBetween(Date value1, Date value2) {
            addCriterion("start_datetime between", value1, value2, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("start_datetime not between", value1, value2, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeIsNull() {
            addCriterion("end_datetime is null");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeIsNotNull() {
            addCriterion("end_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeEqualTo(Date value) {
            addCriterion("end_datetime =", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeNotEqualTo(Date value) {
            addCriterion("end_datetime <>", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeGreaterThan(Date value) {
            addCriterion("end_datetime >", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_datetime >=", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeLessThan(Date value) {
            addCriterion("end_datetime <", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("end_datetime <=", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeIn(List<Date> values) {
            addCriterion("end_datetime in", values, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeNotIn(List<Date> values) {
            addCriterion("end_datetime not in", values, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeBetween(Date value1, Date value2) {
            addCriterion("end_datetime between", value1, value2, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("end_datetime not between", value1, value2, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andError_infoIsNull() {
            addCriterion("error_info is null");
            return (Criteria) this;
        }

        public Criteria andError_infoIsNotNull() {
            addCriterion("error_info is not null");
            return (Criteria) this;
        }

        public Criteria andError_infoEqualTo(String value) {
            addCriterion("error_info =", value, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoNotEqualTo(String value) {
            addCriterion("error_info <>", value, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoGreaterThan(String value) {
            addCriterion("error_info >", value, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoGreaterThanOrEqualTo(String value) {
            addCriterion("error_info >=", value, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoLessThan(String value) {
            addCriterion("error_info <", value, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoLessThanOrEqualTo(String value) {
            addCriterion("error_info <=", value, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoLike(String value) {
            addCriterion("error_info like", value, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoNotLike(String value) {
            addCriterion("error_info not like", value, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoIn(List<String> values) {
            addCriterion("error_info in", values, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoNotIn(List<String> values) {
            addCriterion("error_info not in", values, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoBetween(String value1, String value2) {
            addCriterion("error_info between", value1, value2, "error_info");
            return (Criteria) this;
        }

        public Criteria andError_infoNotBetween(String value1, String value2) {
            addCriterion("error_info not between", value1, value2, "error_info");
            return (Criteria) this;
        }

        public Criteria andException_infoIsNull() {
            addCriterion("exception_info is null");
            return (Criteria) this;
        }

        public Criteria andException_infoIsNotNull() {
            addCriterion("exception_info is not null");
            return (Criteria) this;
        }

        public Criteria andException_infoEqualTo(String value) {
            addCriterion("exception_info =", value, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoNotEqualTo(String value) {
            addCriterion("exception_info <>", value, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoGreaterThan(String value) {
            addCriterion("exception_info >", value, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoGreaterThanOrEqualTo(String value) {
            addCriterion("exception_info >=", value, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoLessThan(String value) {
            addCriterion("exception_info <", value, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoLessThanOrEqualTo(String value) {
            addCriterion("exception_info <=", value, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoLike(String value) {
            addCriterion("exception_info like", value, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoNotLike(String value) {
            addCriterion("exception_info not like", value, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoIn(List<String> values) {
            addCriterion("exception_info in", values, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoNotIn(List<String> values) {
            addCriterion("exception_info not in", values, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoBetween(String value1, String value2) {
            addCriterion("exception_info between", value1, value2, "exception_info");
            return (Criteria) this;
        }

        public Criteria andException_infoNotBetween(String value1, String value2) {
            addCriterion("exception_info not between", value1, value2, "exception_info");
            return (Criteria) this;
        }

        public Criteria andBill_batch_idLikeInsensitive(String value) {
            addCriterion("upper(bill_batch_id) like", value.toUpperCase(), "bill_batch_id");
            return (Criteria) this;
        }

        public Criteria andError_infoLikeInsensitive(String value) {
            addCriterion("upper(error_info) like", value.toUpperCase(), "error_info");
            return (Criteria) this;
        }

        public Criteria andException_infoLikeInsensitive(String value) {
            addCriterion("upper(exception_info) like", value.toUpperCase(), "exception_info");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill_batch
     *
     * @mbg.generated do_not_delete_during_merge Mon May 14 16:47:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table bill_batch
     *
     * @mbg.generated Mon May 14 16:47:32 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	对账批次
		//--------------------------------------------------					
												bill_batch_id(1,Types.VARCHAR,false),
		/** 支付方式 1 微信 */					pay_type(2,Types.INTEGER,false),
		/** 对账日期时间 */						bill_datetime(2,Types.TIMESTAMP,false),
		/** 对账日期 */							bill_date(2,Types.DATE,false),
		/** 我方总单数 */						my_total_orders(2,Types.INTEGER,false),
		/** 我方总金额   单位分 */				my_total_fee(2,Types.INTEGER,false),
		/** 我方总退款金额 */					my_total_refund_fee(2,Types.INTEGER,false),
		/** 第三方平台总订单数 */				p_total_orders(2,Types.INTEGER,false),
		/** 第三方平台总金额  单位分 */			p_total_fee(2,Types.INTEGER,false),
		/** 第三方平台总手续费 */				p_total_service_charge(2,Types.INTEGER,false),
		/** 第三方平台总退款金额 */				p_total_refund_fee(2,Types.INTEGER,false),
		/** 对账正常 的总数 */					status_count_1(2,Types.INTEGER,false),
		/** 对账长账 总数 */					status_count_2(2,Types.INTEGER,false),
		/** 对账短账 总数 */					status_count_3(2,Types.INTEGER,false),
		/** 对账支付金额不一致总数 */			status_count_4(2,Types.INTEGER,false),
		/** 对账退款金额不一致总数 */			status_count_5(2,Types.INTEGER,false),
		/** 对账时间范围 开始 */				start_datetime(2,Types.TIMESTAMP,false),
		/** 对账时间范围 结束 */				end_datetime(2,Types.TIMESTAMP,false),
		/** 第三方平台返回错误信息 */			error_info(2,Types.VARCHAR,false),
		/** 程序异常信息 */						exception_info(2,Types.VARCHAR,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}