package com.aobei.train.model;

import com.aobei.train.model.CancleStrategyExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class CancleStrategyExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancle_strategy
     *
     * @mbg.generated Wed Jun 20 16:11:43 CST 2018
     */
    public CancleStrategyExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancle_strategy
     *
     * @mbg.generated Wed Jun 20 16:11:43 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancle_strategy
     *
     * @mbg.generated Wed Jun 20 16:11:43 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancle_strategy
     *
     * @mbg.generated Wed Jun 20 16:11:43 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cancle_strategy
     *
     * @mbg.generated Wed Jun 20 16:11:43 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andCancle_strategy_idIsNull() {
            addCriterion("cancle_strategy_id is null");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idIsNotNull() {
            addCriterion("cancle_strategy_id is not null");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idEqualTo(Integer value) {
            addCriterion("cancle_strategy_id =", value, "cancle_strategy_id");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idNotEqualTo(Integer value) {
            addCriterion("cancle_strategy_id <>", value, "cancle_strategy_id");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idGreaterThan(Integer value) {
            addCriterion("cancle_strategy_id >", value, "cancle_strategy_id");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("cancle_strategy_id >=", value, "cancle_strategy_id");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idLessThan(Integer value) {
            addCriterion("cancle_strategy_id <", value, "cancle_strategy_id");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idLessThanOrEqualTo(Integer value) {
            addCriterion("cancle_strategy_id <=", value, "cancle_strategy_id");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idIn(List<Integer> values) {
            addCriterion("cancle_strategy_id in", values, "cancle_strategy_id");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idNotIn(List<Integer> values) {
            addCriterion("cancle_strategy_id not in", values, "cancle_strategy_id");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idBetween(Integer value1, Integer value2) {
            addCriterion("cancle_strategy_id between", value1, value2, "cancle_strategy_id");
            return (Criteria) this;
        }

        public Criteria andCancle_strategy_idNotBetween(Integer value1, Integer value2) {
            addCriterion("cancle_strategy_id not between", value1, value2, "cancle_strategy_id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyIsNull() {
            addCriterion("cancle_strategy is null");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyIsNotNull() {
            addCriterion("cancle_strategy is not null");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyEqualTo(String value) {
            addCriterion("cancle_strategy =", value, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyNotEqualTo(String value) {
            addCriterion("cancle_strategy <>", value, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyGreaterThan(String value) {
            addCriterion("cancle_strategy >", value, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyGreaterThanOrEqualTo(String value) {
            addCriterion("cancle_strategy >=", value, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyLessThan(String value) {
            addCriterion("cancle_strategy <", value, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyLessThanOrEqualTo(String value) {
            addCriterion("cancle_strategy <=", value, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyLike(String value) {
            addCriterion("cancle_strategy like", value, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyNotLike(String value) {
            addCriterion("cancle_strategy not like", value, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyIn(List<String> values) {
            addCriterion("cancle_strategy in", values, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyNotIn(List<String> values) {
            addCriterion("cancle_strategy not in", values, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyBetween(String value1, String value2) {
            addCriterion("cancle_strategy between", value1, value2, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyNotBetween(String value1, String value2) {
            addCriterion("cancle_strategy not between", value1, value2, "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andCancle_typeIsNull() {
            addCriterion("cancle_type is null");
            return (Criteria) this;
        }

        public Criteria andCancle_typeIsNotNull() {
            addCriterion("cancle_type is not null");
            return (Criteria) this;
        }

        public Criteria andCancle_typeEqualTo(Integer value) {
            addCriterion("cancle_type =", value, "cancle_type");
            return (Criteria) this;
        }

        public Criteria andCancle_typeNotEqualTo(Integer value) {
            addCriterion("cancle_type <>", value, "cancle_type");
            return (Criteria) this;
        }

        public Criteria andCancle_typeGreaterThan(Integer value) {
            addCriterion("cancle_type >", value, "cancle_type");
            return (Criteria) this;
        }

        public Criteria andCancle_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("cancle_type >=", value, "cancle_type");
            return (Criteria) this;
        }

        public Criteria andCancle_typeLessThan(Integer value) {
            addCriterion("cancle_type <", value, "cancle_type");
            return (Criteria) this;
        }

        public Criteria andCancle_typeLessThanOrEqualTo(Integer value) {
            addCriterion("cancle_type <=", value, "cancle_type");
            return (Criteria) this;
        }

        public Criteria andCancle_typeIn(List<Integer> values) {
            addCriterion("cancle_type in", values, "cancle_type");
            return (Criteria) this;
        }

        public Criteria andCancle_typeNotIn(List<Integer> values) {
            addCriterion("cancle_type not in", values, "cancle_type");
            return (Criteria) this;
        }

        public Criteria andCancle_typeBetween(Integer value1, Integer value2) {
            addCriterion("cancle_type between", value1, value2, "cancle_type");
            return (Criteria) this;
        }

        public Criteria andCancle_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("cancle_type not between", value1, value2, "cancle_type");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_idIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperator_idIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperator_idEqualTo(Long value) {
            addCriterion("operator_id =", value, "operator_id");
            return (Criteria) this;
        }

        public Criteria andOperator_idNotEqualTo(Long value) {
            addCriterion("operator_id <>", value, "operator_id");
            return (Criteria) this;
        }

        public Criteria andOperator_idGreaterThan(Long value) {
            addCriterion("operator_id >", value, "operator_id");
            return (Criteria) this;
        }

        public Criteria andOperator_idGreaterThanOrEqualTo(Long value) {
            addCriterion("operator_id >=", value, "operator_id");
            return (Criteria) this;
        }

        public Criteria andOperator_idLessThan(Long value) {
            addCriterion("operator_id <", value, "operator_id");
            return (Criteria) this;
        }

        public Criteria andOperator_idLessThanOrEqualTo(Long value) {
            addCriterion("operator_id <=", value, "operator_id");
            return (Criteria) this;
        }

        public Criteria andOperator_idIn(List<Long> values) {
            addCriterion("operator_id in", values, "operator_id");
            return (Criteria) this;
        }

        public Criteria andOperator_idNotIn(List<Long> values) {
            addCriterion("operator_id not in", values, "operator_id");
            return (Criteria) this;
        }

        public Criteria andOperator_idBetween(Long value1, Long value2) {
            addCriterion("operator_id between", value1, value2, "operator_id");
            return (Criteria) this;
        }

        public Criteria andOperator_idNotBetween(Long value1, Long value2) {
            addCriterion("operator_id not between", value1, value2, "operator_id");
            return (Criteria) this;
        }

        public Criteria andOperator_nameIsNull() {
            addCriterion("operator_name is null");
            return (Criteria) this;
        }

        public Criteria andOperator_nameIsNotNull() {
            addCriterion("operator_name is not null");
            return (Criteria) this;
        }

        public Criteria andOperator_nameEqualTo(String value) {
            addCriterion("operator_name =", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameNotEqualTo(String value) {
            addCriterion("operator_name <>", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameGreaterThan(String value) {
            addCriterion("operator_name >", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameGreaterThanOrEqualTo(String value) {
            addCriterion("operator_name >=", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameLessThan(String value) {
            addCriterion("operator_name <", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameLessThanOrEqualTo(String value) {
            addCriterion("operator_name <=", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameLike(String value) {
            addCriterion("operator_name like", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameNotLike(String value) {
            addCriterion("operator_name not like", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameIn(List<String> values) {
            addCriterion("operator_name in", values, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameNotIn(List<String> values) {
            addCriterion("operator_name not in", values, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameBetween(String value1, String value2) {
            addCriterion("operator_name between", value1, value2, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameNotBetween(String value1, String value2) {
            addCriterion("operator_name not between", value1, value2, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeIsNull() {
            addCriterion("operator_datetime is null");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeIsNotNull() {
            addCriterion("operator_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeEqualTo(Date value) {
            addCriterion("operator_datetime =", value, "operator_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeNotEqualTo(Date value) {
            addCriterion("operator_datetime <>", value, "operator_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeGreaterThan(Date value) {
            addCriterion("operator_datetime >", value, "operator_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("operator_datetime >=", value, "operator_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeLessThan(Date value) {
            addCriterion("operator_datetime <", value, "operator_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("operator_datetime <=", value, "operator_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeIn(List<Date> values) {
            addCriterion("operator_datetime in", values, "operator_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeNotIn(List<Date> values) {
            addCriterion("operator_datetime not in", values, "operator_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeBetween(Date value1, Date value2) {
            addCriterion("operator_datetime between", value1, value2, "operator_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("operator_datetime not between", value1, value2, "operator_datetime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(name) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andCancle_strategyLikeInsensitive(String value) {
            addCriterion("upper(cancle_strategy) like", value.toUpperCase(), "cancle_strategy");
            return (Criteria) this;
        }

        public Criteria andOperator_nameLikeInsensitive(String value) {
            addCriterion("upper(operator_name) like", value.toUpperCase(), "operator_name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cancle_strategy
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 20 16:11:43 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table cancle_strategy
     *
     * @mbg.generated Wed Jun 20 16:11:43 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	取消策略
		//--------------------------------------------------
		/** 自增长 */									cancle_strategy_id(1,Types.INTEGER,false),					
														name(2,Types.VARCHAR,false),
		/** 取消策略JSON 数据 [{“d” : 9  , "v" :  3}, {“d” : 13  , "v" :  12}] */
														cancle_strategy(2,Types.VARCHAR,false),
		/** 取消策略方式  1 订单金额  2 实付金额   3 固定金额 */
														cancle_type(2,Types.INTEGER,false),					
														create_datetime(2,Types.TIMESTAMP,false),
		/** 是后一人操作人id    system_user_id */		operator_id(2,Types.BIGINT,false),
		/** 操作人名称 */								operator_name(2,Types.VARCHAR,false),
		/** 操作时间 */									operator_datetime(2,Types.TIMESTAMP,false),
		/** 0 未删除  1 已删除 */						deleted(2,Types.INTEGER,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}