package com.aobei.train.model;

import com.aobei.train.model.ChapterExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class ChapterExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public ChapterExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chapter
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chapter
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andChapter_idIsNull() {
            addCriterion("chapter_id is null");
            return (Criteria) this;
        }

        public Criteria andChapter_idIsNotNull() {
            addCriterion("chapter_id is not null");
            return (Criteria) this;
        }

        public Criteria andChapter_idEqualTo(Long value) {
            addCriterion("chapter_id =", value, "chapter_id");
            return (Criteria) this;
        }

        public Criteria andChapter_idNotEqualTo(Long value) {
            addCriterion("chapter_id <>", value, "chapter_id");
            return (Criteria) this;
        }

        public Criteria andChapter_idGreaterThan(Long value) {
            addCriterion("chapter_id >", value, "chapter_id");
            return (Criteria) this;
        }

        public Criteria andChapter_idGreaterThanOrEqualTo(Long value) {
            addCriterion("chapter_id >=", value, "chapter_id");
            return (Criteria) this;
        }

        public Criteria andChapter_idLessThan(Long value) {
            addCriterion("chapter_id <", value, "chapter_id");
            return (Criteria) this;
        }

        public Criteria andChapter_idLessThanOrEqualTo(Long value) {
            addCriterion("chapter_id <=", value, "chapter_id");
            return (Criteria) this;
        }

        public Criteria andChapter_idIn(List<Long> values) {
            addCriterion("chapter_id in", values, "chapter_id");
            return (Criteria) this;
        }

        public Criteria andChapter_idNotIn(List<Long> values) {
            addCriterion("chapter_id not in", values, "chapter_id");
            return (Criteria) this;
        }

        public Criteria andChapter_idBetween(Long value1, Long value2) {
            addCriterion("chapter_id between", value1, value2, "chapter_id");
            return (Criteria) this;
        }

        public Criteria andChapter_idNotBetween(Long value1, Long value2) {
            addCriterion("chapter_id not between", value1, value2, "chapter_id");
            return (Criteria) this;
        }

        public Criteria andHeadlineIsNull() {
            addCriterion("headline is null");
            return (Criteria) this;
        }

        public Criteria andHeadlineIsNotNull() {
            addCriterion("headline is not null");
            return (Criteria) this;
        }

        public Criteria andHeadlineEqualTo(String value) {
            addCriterion("headline =", value, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineNotEqualTo(String value) {
            addCriterion("headline <>", value, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineGreaterThan(String value) {
            addCriterion("headline >", value, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineGreaterThanOrEqualTo(String value) {
            addCriterion("headline >=", value, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineLessThan(String value) {
            addCriterion("headline <", value, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineLessThanOrEqualTo(String value) {
            addCriterion("headline <=", value, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineLike(String value) {
            addCriterion("headline like", value, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineNotLike(String value) {
            addCriterion("headline not like", value, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineIn(List<String> values) {
            addCriterion("headline in", values, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineNotIn(List<String> values) {
            addCriterion("headline not in", values, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineBetween(String value1, String value2) {
            addCriterion("headline between", value1, value2, "headline");
            return (Criteria) this;
        }

        public Criteria andHeadlineNotBetween(String value1, String value2) {
            addCriterion("headline not between", value1, value2, "headline");
            return (Criteria) this;
        }

        public Criteria andSection_contentIsNull() {
            addCriterion("section_content is null");
            return (Criteria) this;
        }

        public Criteria andSection_contentIsNotNull() {
            addCriterion("section_content is not null");
            return (Criteria) this;
        }

        public Criteria andSection_contentEqualTo(String value) {
            addCriterion("section_content =", value, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentNotEqualTo(String value) {
            addCriterion("section_content <>", value, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentGreaterThan(String value) {
            addCriterion("section_content >", value, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentGreaterThanOrEqualTo(String value) {
            addCriterion("section_content >=", value, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentLessThan(String value) {
            addCriterion("section_content <", value, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentLessThanOrEqualTo(String value) {
            addCriterion("section_content <=", value, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentLike(String value) {
            addCriterion("section_content like", value, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentNotLike(String value) {
            addCriterion("section_content not like", value, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentIn(List<String> values) {
            addCriterion("section_content in", values, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentNotIn(List<String> values) {
            addCriterion("section_content not in", values, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentBetween(String value1, String value2) {
            addCriterion("section_content between", value1, value2, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_contentNotBetween(String value1, String value2) {
            addCriterion("section_content not between", value1, value2, "section_content");
            return (Criteria) this;
        }

        public Criteria andSection_nameIsNull() {
            addCriterion("section_name is null");
            return (Criteria) this;
        }

        public Criteria andSection_nameIsNotNull() {
            addCriterion("section_name is not null");
            return (Criteria) this;
        }

        public Criteria andSection_nameEqualTo(Integer value) {
            addCriterion("section_name =", value, "section_name");
            return (Criteria) this;
        }

        public Criteria andSection_nameNotEqualTo(Integer value) {
            addCriterion("section_name <>", value, "section_name");
            return (Criteria) this;
        }

        public Criteria andSection_nameGreaterThan(Integer value) {
            addCriterion("section_name >", value, "section_name");
            return (Criteria) this;
        }

        public Criteria andSection_nameGreaterThanOrEqualTo(Integer value) {
            addCriterion("section_name >=", value, "section_name");
            return (Criteria) this;
        }

        public Criteria andSection_nameLessThan(Integer value) {
            addCriterion("section_name <", value, "section_name");
            return (Criteria) this;
        }

        public Criteria andSection_nameLessThanOrEqualTo(Integer value) {
            addCriterion("section_name <=", value, "section_name");
            return (Criteria) this;
        }

        public Criteria andSection_nameIn(List<Integer> values) {
            addCriterion("section_name in", values, "section_name");
            return (Criteria) this;
        }

        public Criteria andSection_nameNotIn(List<Integer> values) {
            addCriterion("section_name not in", values, "section_name");
            return (Criteria) this;
        }

        public Criteria andSection_nameBetween(Integer value1, Integer value2) {
            addCriterion("section_name between", value1, value2, "section_name");
            return (Criteria) this;
        }

        public Criteria andSection_nameNotBetween(Integer value1, Integer value2) {
            addCriterion("section_name not between", value1, value2, "section_name");
            return (Criteria) this;
        }

        public Criteria andTime_lengthIsNull() {
            addCriterion("time_length is null");
            return (Criteria) this;
        }

        public Criteria andTime_lengthIsNotNull() {
            addCriterion("time_length is not null");
            return (Criteria) this;
        }

        public Criteria andTime_lengthEqualTo(Integer value) {
            addCriterion("time_length =", value, "time_length");
            return (Criteria) this;
        }

        public Criteria andTime_lengthNotEqualTo(Integer value) {
            addCriterion("time_length <>", value, "time_length");
            return (Criteria) this;
        }

        public Criteria andTime_lengthGreaterThan(Integer value) {
            addCriterion("time_length >", value, "time_length");
            return (Criteria) this;
        }

        public Criteria andTime_lengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_length >=", value, "time_length");
            return (Criteria) this;
        }

        public Criteria andTime_lengthLessThan(Integer value) {
            addCriterion("time_length <", value, "time_length");
            return (Criteria) this;
        }

        public Criteria andTime_lengthLessThanOrEqualTo(Integer value) {
            addCriterion("time_length <=", value, "time_length");
            return (Criteria) this;
        }

        public Criteria andTime_lengthIn(List<Integer> values) {
            addCriterion("time_length in", values, "time_length");
            return (Criteria) this;
        }

        public Criteria andTime_lengthNotIn(List<Integer> values) {
            addCriterion("time_length not in", values, "time_length");
            return (Criteria) this;
        }

        public Criteria andTime_lengthBetween(Integer value1, Integer value2) {
            addCriterion("time_length between", value1, value2, "time_length");
            return (Criteria) this;
        }

        public Criteria andTime_lengthNotBetween(Integer value1, Integer value2) {
            addCriterion("time_length not between", value1, value2, "time_length");
            return (Criteria) this;
        }

        public Criteria andCourse_idIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourse_idIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourse_idEqualTo(Long value) {
            addCriterion("course_id =", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idNotEqualTo(Long value) {
            addCriterion("course_id <>", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idGreaterThan(Long value) {
            addCriterion("course_id >", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idGreaterThanOrEqualTo(Long value) {
            addCriterion("course_id >=", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idLessThan(Long value) {
            addCriterion("course_id <", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idLessThanOrEqualTo(Long value) {
            addCriterion("course_id <=", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idIn(List<Long> values) {
            addCriterion("course_id in", values, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idNotIn(List<Long> values) {
            addCriterion("course_id not in", values, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idBetween(Long value1, Long value2) {
            addCriterion("course_id between", value1, value2, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idNotBetween(Long value1, Long value2) {
            addCriterion("course_id not between", value1, value2, "course_id");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andHeadlineLikeInsensitive(String value) {
            addCriterion("upper(headline) like", value.toUpperCase(), "headline");
            return (Criteria) this;
        }

        public Criteria andSection_contentLikeInsensitive(String value) {
            addCriterion("upper(section_content) like", value.toUpperCase(), "section_content");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chapter
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 01 11:23:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table chapter
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	课节
		//--------------------------------------------------
		/** 课节id */								chapter_id(1,Types.BIGINT,false),
		/** 标题 */									headline(2,Types.VARCHAR,false),
		/** 内容 */									section_content(2,Types.VARCHAR,false),
		/** 第 N 节 */								section_name(2,Types.INTEGER,false),
		/** 课节上课时长 ，单位分钟 */				time_length(2,Types.INTEGER,false),
		/** 课程id */								course_id(2,Types.BIGINT,false),
		/** 0 未删除，1 已删除 [DV=>0] */			deleted(2,Types.INTEGER,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}