package com.aobei.train.model;

import com.aobei.train.model.ClassroomExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class ClassroomExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public ClassroomExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classroom
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classroom
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andClassroom_idIsNull() {
            addCriterion("classroom_id is null");
            return (Criteria) this;
        }

        public Criteria andClassroom_idIsNotNull() {
            addCriterion("classroom_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassroom_idEqualTo(Long value) {
            addCriterion("classroom_id =", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idNotEqualTo(Long value) {
            addCriterion("classroom_id <>", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idGreaterThan(Long value) {
            addCriterion("classroom_id >", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idGreaterThanOrEqualTo(Long value) {
            addCriterion("classroom_id >=", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idLessThan(Long value) {
            addCriterion("classroom_id <", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idLessThanOrEqualTo(Long value) {
            addCriterion("classroom_id <=", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idIn(List<Long> values) {
            addCriterion("classroom_id in", values, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idNotIn(List<Long> values) {
            addCriterion("classroom_id not in", values, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idBetween(Long value1, Long value2) {
            addCriterion("classroom_id between", value1, value2, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idNotBetween(Long value1, Long value2) {
            addCriterion("classroom_id not between", value1, value2, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idIsNull() {
            addCriterion("school_id is null");
            return (Criteria) this;
        }

        public Criteria andSchool_idIsNotNull() {
            addCriterion("school_id is not null");
            return (Criteria) this;
        }

        public Criteria andSchool_idEqualTo(Long value) {
            addCriterion("school_id =", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idNotEqualTo(Long value) {
            addCriterion("school_id <>", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idGreaterThan(Long value) {
            addCriterion("school_id >", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idGreaterThanOrEqualTo(Long value) {
            addCriterion("school_id >=", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idLessThan(Long value) {
            addCriterion("school_id <", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idLessThanOrEqualTo(Long value) {
            addCriterion("school_id <=", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idIn(List<Long> values) {
            addCriterion("school_id in", values, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idNotIn(List<Long> values) {
            addCriterion("school_id not in", values, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idBetween(Long value1, Long value2) {
            addCriterion("school_id between", value1, value2, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idNotBetween(Long value1, Long value2) {
            addCriterion("school_id not between", value1, value2, "school_id");
            return (Criteria) this;
        }

        public Criteria andBlock_numberIsNull() {
            addCriterion("block_number is null");
            return (Criteria) this;
        }

        public Criteria andBlock_numberIsNotNull() {
            addCriterion("block_number is not null");
            return (Criteria) this;
        }

        public Criteria andBlock_numberEqualTo(String value) {
            addCriterion("block_number =", value, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberNotEqualTo(String value) {
            addCriterion("block_number <>", value, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberGreaterThan(String value) {
            addCriterion("block_number >", value, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberGreaterThanOrEqualTo(String value) {
            addCriterion("block_number >=", value, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberLessThan(String value) {
            addCriterion("block_number <", value, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberLessThanOrEqualTo(String value) {
            addCriterion("block_number <=", value, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberLike(String value) {
            addCriterion("block_number like", value, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberNotLike(String value) {
            addCriterion("block_number not like", value, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberIn(List<String> values) {
            addCriterion("block_number in", values, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberNotIn(List<String> values) {
            addCriterion("block_number not in", values, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberBetween(String value1, String value2) {
            addCriterion("block_number between", value1, value2, "block_number");
            return (Criteria) this;
        }

        public Criteria andBlock_numberNotBetween(String value1, String value2) {
            addCriterion("block_number not between", value1, value2, "block_number");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNull() {
            addCriterion("capacity is null");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNotNull() {
            addCriterion("capacity is not null");
            return (Criteria) this;
        }

        public Criteria andCapacityEqualTo(Integer value) {
            addCriterion("capacity =", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotEqualTo(Integer value) {
            addCriterion("capacity <>", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThan(Integer value) {
            addCriterion("capacity >", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThanOrEqualTo(Integer value) {
            addCriterion("capacity >=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThan(Integer value) {
            addCriterion("capacity <", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThanOrEqualTo(Integer value) {
            addCriterion("capacity <=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityIn(List<Integer> values) {
            addCriterion("capacity in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotIn(List<Integer> values) {
            addCriterion("capacity not in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityBetween(Integer value1, Integer value2) {
            addCriterion("capacity between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotBetween(Integer value1, Integer value2) {
            addCriterion("capacity not between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andUseableIsNull() {
            addCriterion("useable is null");
            return (Criteria) this;
        }

        public Criteria andUseableIsNotNull() {
            addCriterion("useable is not null");
            return (Criteria) this;
        }

        public Criteria andUseableEqualTo(Integer value) {
            addCriterion("useable =", value, "useable");
            return (Criteria) this;
        }

        public Criteria andUseableNotEqualTo(Integer value) {
            addCriterion("useable <>", value, "useable");
            return (Criteria) this;
        }

        public Criteria andUseableGreaterThan(Integer value) {
            addCriterion("useable >", value, "useable");
            return (Criteria) this;
        }

        public Criteria andUseableGreaterThanOrEqualTo(Integer value) {
            addCriterion("useable >=", value, "useable");
            return (Criteria) this;
        }

        public Criteria andUseableLessThan(Integer value) {
            addCriterion("useable <", value, "useable");
            return (Criteria) this;
        }

        public Criteria andUseableLessThanOrEqualTo(Integer value) {
            addCriterion("useable <=", value, "useable");
            return (Criteria) this;
        }

        public Criteria andUseableIn(List<Integer> values) {
            addCriterion("useable in", values, "useable");
            return (Criteria) this;
        }

        public Criteria andUseableNotIn(List<Integer> values) {
            addCriterion("useable not in", values, "useable");
            return (Criteria) this;
        }

        public Criteria andUseableBetween(Integer value1, Integer value2) {
            addCriterion("useable between", value1, value2, "useable");
            return (Criteria) this;
        }

        public Criteria andUseableNotBetween(Integer value1, Integer value2) {
            addCriterion("useable not between", value1, value2, "useable");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonIsNull() {
            addCriterion("timescope_json is null");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonIsNotNull() {
            addCriterion("timescope_json is not null");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonEqualTo(String value) {
            addCriterion("timescope_json =", value, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonNotEqualTo(String value) {
            addCriterion("timescope_json <>", value, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonGreaterThan(String value) {
            addCriterion("timescope_json >", value, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonGreaterThanOrEqualTo(String value) {
            addCriterion("timescope_json >=", value, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonLessThan(String value) {
            addCriterion("timescope_json <", value, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonLessThanOrEqualTo(String value) {
            addCriterion("timescope_json <=", value, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonLike(String value) {
            addCriterion("timescope_json like", value, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonNotLike(String value) {
            addCriterion("timescope_json not like", value, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonIn(List<String> values) {
            addCriterion("timescope_json in", values, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonNotIn(List<String> values) {
            addCriterion("timescope_json not in", values, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonBetween(String value1, String value2) {
            addCriterion("timescope_json between", value1, value2, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonNotBetween(String value1, String value2) {
            addCriterion("timescope_json not between", value1, value2, "timescope_json");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andBlock_numberLikeInsensitive(String value) {
            addCriterion("upper(block_number) like", value.toUpperCase(), "block_number");
            return (Criteria) this;
        }

        public Criteria andTimescope_jsonLikeInsensitive(String value) {
            addCriterion("upper(timescope_json) like", value.toUpperCase(), "timescope_json");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table classroom
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 01 11:23:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table classroom
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	教室信息表
		//--------------------------------------------------
		/** 教室编号 */									classroom_id(1,Types.BIGINT,false),
		/** 隶属学校编号 */								school_id(2,Types.BIGINT,false),
		/** 教学楼号 */									block_number(2,Types.VARCHAR,false),
		/** 容量(教室可容纳人数) */						capacity(2,Types.INTEGER,false),
		/** 是否可用 "0"为不可用,"1"为可用 */			useable(2,Types.INTEGER,false),
		/** 有效的时间范围JSON 数据 */					timescope_json(2,Types.VARCHAR,false),
		/** 创建时间 [DV=>CURRENT_TIMESTAMP] */			create_time(2,Types.TIMESTAMP,false),
		/** 0 未删除 1 已删除 [DV=>0] */				deleted(2,Types.INTEGER,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}