package com.aobei.train.model;

import com.aobei.train.model.CmsBannerExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class CmsBannerExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbg.generated Tue May 22 16:54:43 CST 2018
     */
    public CmsBannerExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbg.generated Tue May 22 16:54:43 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbg.generated Tue May 22 16:54:43 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbg.generated Tue May 22 16:54:43 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cms_banner
     *
     * @mbg.generated Tue May 22 16:54:43 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andCms_banner_idIsNull() {
            addCriterion("cms_banner_id is null");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idIsNotNull() {
            addCriterion("cms_banner_id is not null");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idEqualTo(Long value) {
            addCriterion("cms_banner_id =", value, "cms_banner_id");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idNotEqualTo(Long value) {
            addCriterion("cms_banner_id <>", value, "cms_banner_id");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idGreaterThan(Long value) {
            addCriterion("cms_banner_id >", value, "cms_banner_id");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idGreaterThanOrEqualTo(Long value) {
            addCriterion("cms_banner_id >=", value, "cms_banner_id");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idLessThan(Long value) {
            addCriterion("cms_banner_id <", value, "cms_banner_id");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idLessThanOrEqualTo(Long value) {
            addCriterion("cms_banner_id <=", value, "cms_banner_id");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idIn(List<Long> values) {
            addCriterion("cms_banner_id in", values, "cms_banner_id");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idNotIn(List<Long> values) {
            addCriterion("cms_banner_id not in", values, "cms_banner_id");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idBetween(Long value1, Long value2) {
            addCriterion("cms_banner_id between", value1, value2, "cms_banner_id");
            return (Criteria) this;
        }

        public Criteria andCms_banner_idNotBetween(Long value1, Long value2) {
            addCriterion("cms_banner_id not between", value1, value2, "cms_banner_id");
            return (Criteria) this;
        }

        public Criteria andImg_coverIsNull() {
            addCriterion("img_cover is null");
            return (Criteria) this;
        }

        public Criteria andImg_coverIsNotNull() {
            addCriterion("img_cover is not null");
            return (Criteria) this;
        }

        public Criteria andImg_coverEqualTo(String value) {
            addCriterion("img_cover =", value, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverNotEqualTo(String value) {
            addCriterion("img_cover <>", value, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverGreaterThan(String value) {
            addCriterion("img_cover >", value, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverGreaterThanOrEqualTo(String value) {
            addCriterion("img_cover >=", value, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverLessThan(String value) {
            addCriterion("img_cover <", value, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverLessThanOrEqualTo(String value) {
            addCriterion("img_cover <=", value, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverLike(String value) {
            addCriterion("img_cover like", value, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverNotLike(String value) {
            addCriterion("img_cover not like", value, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverIn(List<String> values) {
            addCriterion("img_cover in", values, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverNotIn(List<String> values) {
            addCriterion("img_cover not in", values, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverBetween(String value1, String value2) {
            addCriterion("img_cover between", value1, value2, "img_cover");
            return (Criteria) this;
        }

        public Criteria andImg_coverNotBetween(String value1, String value2) {
            addCriterion("img_cover not between", value1, value2, "img_cover");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andIntroIsNull() {
            addCriterion("intro is null");
            return (Criteria) this;
        }

        public Criteria andIntroIsNotNull() {
            addCriterion("intro is not null");
            return (Criteria) this;
        }

        public Criteria andIntroEqualTo(String value) {
            addCriterion("intro =", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotEqualTo(String value) {
            addCriterion("intro <>", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThan(String value) {
            addCriterion("intro >", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroGreaterThanOrEqualTo(String value) {
            addCriterion("intro >=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThan(String value) {
            addCriterion("intro <", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLessThanOrEqualTo(String value) {
            addCriterion("intro <=", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroLike(String value) {
            addCriterion("intro like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotLike(String value) {
            addCriterion("intro not like", value, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroIn(List<String> values) {
            addCriterion("intro in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotIn(List<String> values) {
            addCriterion("intro not in", values, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroBetween(String value1, String value2) {
            addCriterion("intro between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andIntroNotBetween(String value1, String value2) {
            addCriterion("intro not between", value1, value2, "intro");
            return (Criteria) this;
        }

        public Criteria andAppIsNull() {
            addCriterion("app is null");
            return (Criteria) this;
        }

        public Criteria andAppIsNotNull() {
            addCriterion("app is not null");
            return (Criteria) this;
        }

        public Criteria andAppEqualTo(String value) {
            addCriterion("app =", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotEqualTo(String value) {
            addCriterion("app <>", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppGreaterThan(String value) {
            addCriterion("app >", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppGreaterThanOrEqualTo(String value) {
            addCriterion("app >=", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppLessThan(String value) {
            addCriterion("app <", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppLessThanOrEqualTo(String value) {
            addCriterion("app <=", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppLike(String value) {
            addCriterion("app like", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotLike(String value) {
            addCriterion("app not like", value, "app");
            return (Criteria) this;
        }

        public Criteria andAppIn(List<String> values) {
            addCriterion("app in", values, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotIn(List<String> values) {
            addCriterion("app not in", values, "app");
            return (Criteria) this;
        }

        public Criteria andAppBetween(String value1, String value2) {
            addCriterion("app between", value1, value2, "app");
            return (Criteria) this;
        }

        public Criteria andAppNotBetween(String value1, String value2) {
            addCriterion("app not between", value1, value2, "app");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeIsNull() {
            addCriterion("online_datetime is null");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeIsNotNull() {
            addCriterion("online_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeEqualTo(Date value) {
            addCriterion("online_datetime =", value, "online_datetime");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeNotEqualTo(Date value) {
            addCriterion("online_datetime <>", value, "online_datetime");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeGreaterThan(Date value) {
            addCriterion("online_datetime >", value, "online_datetime");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("online_datetime >=", value, "online_datetime");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeLessThan(Date value) {
            addCriterion("online_datetime <", value, "online_datetime");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("online_datetime <=", value, "online_datetime");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeIn(List<Date> values) {
            addCriterion("online_datetime in", values, "online_datetime");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeNotIn(List<Date> values) {
            addCriterion("online_datetime not in", values, "online_datetime");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeBetween(Date value1, Date value2) {
            addCriterion("online_datetime between", value1, value2, "online_datetime");
            return (Criteria) this;
        }

        public Criteria andOnline_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("online_datetime not between", value1, value2, "online_datetime");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeIsNull() {
            addCriterion("offline_datetime is null");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeIsNotNull() {
            addCriterion("offline_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeEqualTo(Date value) {
            addCriterion("offline_datetime =", value, "offline_datetime");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeNotEqualTo(Date value) {
            addCriterion("offline_datetime <>", value, "offline_datetime");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeGreaterThan(Date value) {
            addCriterion("offline_datetime >", value, "offline_datetime");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("offline_datetime >=", value, "offline_datetime");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeLessThan(Date value) {
            addCriterion("offline_datetime <", value, "offline_datetime");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("offline_datetime <=", value, "offline_datetime");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeIn(List<Date> values) {
            addCriterion("offline_datetime in", values, "offline_datetime");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeNotIn(List<Date> values) {
            addCriterion("offline_datetime not in", values, "offline_datetime");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeBetween(Date value1, Date value2) {
            addCriterion("offline_datetime between", value1, value2, "offline_datetime");
            return (Criteria) this;
        }

        public Criteria andOffline_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("offline_datetime not between", value1, value2, "offline_datetime");
            return (Criteria) this;
        }

        public Criteria andSerial_numberIsNull() {
            addCriterion("serial_number is null");
            return (Criteria) this;
        }

        public Criteria andSerial_numberIsNotNull() {
            addCriterion("serial_number is not null");
            return (Criteria) this;
        }

        public Criteria andSerial_numberEqualTo(Integer value) {
            addCriterion("serial_number =", value, "serial_number");
            return (Criteria) this;
        }

        public Criteria andSerial_numberNotEqualTo(Integer value) {
            addCriterion("serial_number <>", value, "serial_number");
            return (Criteria) this;
        }

        public Criteria andSerial_numberGreaterThan(Integer value) {
            addCriterion("serial_number >", value, "serial_number");
            return (Criteria) this;
        }

        public Criteria andSerial_numberGreaterThanOrEqualTo(Integer value) {
            addCriterion("serial_number >=", value, "serial_number");
            return (Criteria) this;
        }

        public Criteria andSerial_numberLessThan(Integer value) {
            addCriterion("serial_number <", value, "serial_number");
            return (Criteria) this;
        }

        public Criteria andSerial_numberLessThanOrEqualTo(Integer value) {
            addCriterion("serial_number <=", value, "serial_number");
            return (Criteria) this;
        }

        public Criteria andSerial_numberIn(List<Integer> values) {
            addCriterion("serial_number in", values, "serial_number");
            return (Criteria) this;
        }

        public Criteria andSerial_numberNotIn(List<Integer> values) {
            addCriterion("serial_number not in", values, "serial_number");
            return (Criteria) this;
        }

        public Criteria andSerial_numberBetween(Integer value1, Integer value2) {
            addCriterion("serial_number between", value1, value2, "serial_number");
            return (Criteria) this;
        }

        public Criteria andSerial_numberNotBetween(Integer value1, Integer value2) {
            addCriterion("serial_number not between", value1, value2, "serial_number");
            return (Criteria) this;
        }

        public Criteria andSignIsNull() {
            addCriterion("sign is null");
            return (Criteria) this;
        }

        public Criteria andSignIsNotNull() {
            addCriterion("sign is not null");
            return (Criteria) this;
        }

        public Criteria andSignEqualTo(Integer value) {
            addCriterion("sign =", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotEqualTo(Integer value) {
            addCriterion("sign <>", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThan(Integer value) {
            addCriterion("sign >", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign >=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThan(Integer value) {
            addCriterion("sign <", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThanOrEqualTo(Integer value) {
            addCriterion("sign <=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignIn(List<Integer> values) {
            addCriterion("sign in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotIn(List<Integer> values) {
            addCriterion("sign not in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignBetween(Integer value1, Integer value2) {
            addCriterion("sign between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotBetween(Integer value1, Integer value2) {
            addCriterion("sign not between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("position =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("position <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("position >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("position >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("position <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("position <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("position like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("position not like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<String> values) {
            addCriterion("position in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            addCriterion("position not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("position between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("position not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andHrefIsNull() {
            addCriterion("href is null");
            return (Criteria) this;
        }

        public Criteria andHrefIsNotNull() {
            addCriterion("href is not null");
            return (Criteria) this;
        }

        public Criteria andHrefEqualTo(String value) {
            addCriterion("href =", value, "href");
            return (Criteria) this;
        }

        public Criteria andHrefNotEqualTo(String value) {
            addCriterion("href <>", value, "href");
            return (Criteria) this;
        }

        public Criteria andHrefGreaterThan(String value) {
            addCriterion("href >", value, "href");
            return (Criteria) this;
        }

        public Criteria andHrefGreaterThanOrEqualTo(String value) {
            addCriterion("href >=", value, "href");
            return (Criteria) this;
        }

        public Criteria andHrefLessThan(String value) {
            addCriterion("href <", value, "href");
            return (Criteria) this;
        }

        public Criteria andHrefLessThanOrEqualTo(String value) {
            addCriterion("href <=", value, "href");
            return (Criteria) this;
        }

        public Criteria andHrefLike(String value) {
            addCriterion("href like", value, "href");
            return (Criteria) this;
        }

        public Criteria andHrefNotLike(String value) {
            addCriterion("href not like", value, "href");
            return (Criteria) this;
        }

        public Criteria andHrefIn(List<String> values) {
            addCriterion("href in", values, "href");
            return (Criteria) this;
        }

        public Criteria andHrefNotIn(List<String> values) {
            addCriterion("href not in", values, "href");
            return (Criteria) this;
        }

        public Criteria andHrefBetween(String value1, String value2) {
            addCriterion("href between", value1, value2, "href");
            return (Criteria) this;
        }

        public Criteria andHrefNotBetween(String value1, String value2) {
            addCriterion("href not between", value1, value2, "href");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andImg_coverLikeInsensitive(String value) {
            addCriterion("upper(img_cover) like", value.toUpperCase(), "img_cover");
            return (Criteria) this;
        }

        public Criteria andTitleLikeInsensitive(String value) {
            addCriterion("upper(title) like", value.toUpperCase(), "title");
            return (Criteria) this;
        }

        public Criteria andIntroLikeInsensitive(String value) {
            addCriterion("upper(intro) like", value.toUpperCase(), "intro");
            return (Criteria) this;
        }

        public Criteria andAppLikeInsensitive(String value) {
            addCriterion("upper(app) like", value.toUpperCase(), "app");
            return (Criteria) this;
        }

        public Criteria andPositionLikeInsensitive(String value) {
            addCriterion("upper(position) like", value.toUpperCase(), "position");
            return (Criteria) this;
        }

        public Criteria andHrefLikeInsensitive(String value) {
            addCriterion("upper(href) like", value.toUpperCase(), "href");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cms_banner
     *
     * @mbg.generated do_not_delete_during_merge Tue May 22 16:54:43 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table cms_banner
     *
     * @mbg.generated Tue May 22 16:54:43 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	banner 图
		//--------------------------------------------------
		/** 内容推荐id */								cms_banner_id(1,Types.BIGINT,false),
		/** 封面图片id */								img_cover(2,Types.VARCHAR,false),
		/** 标题 */										title(2,Types.CHAR,false),
		/** 简介 */										intro(2,Types.VARCHAR,false),
		/** 使用的端 'wx_m_custom'为顾客端,'wx_m_teacher'为教师端,'wx_m_student'为学员端,'wx_m_partner'为合伙人端 */
														app(2,Types.VARCHAR,false),
		/** 上线时间 */									online_datetime(2,Types.TIMESTAMP,false),
		/** 下线时间 */									offline_datetime(2,Types.TIMESTAMP,false),
		/** 序号，表示banner图的顺序 */					serial_number(2,Types.INTEGER,false),
		/** '1'为已上线,'0'为已下线 [DV=>1] */			sign(2,Types.INTEGER,false),
		/** 0 未删除，1 已删除 [DV=>0] */				deleted(2,Types.INTEGER,false),
		/** 具体页面（保留字段） [DV=>0] */				position(2,Types.VARCHAR,false),
		/** 跳转页面地址（保留字段） [DV=>0] */			href(2,Types.VARCHAR,false),
		/** 跳转类型。1 http url 跳转 2 应用内跳转 */	type(2,Types.INTEGER,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}