package com.aobei.train.model;

import com.aobei.train.model.CompensationExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class CompensationExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compensation
     *
     * @mbg.generated Tue Jun 12 19:13:57 CST 2018
     */
    public CompensationExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compensation
     *
     * @mbg.generated Tue Jun 12 19:13:57 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compensation
     *
     * @mbg.generated Tue Jun 12 19:13:57 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compensation
     *
     * @mbg.generated Tue Jun 12 19:13:57 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table compensation
     *
     * @mbg.generated Tue Jun 12 19:13:57 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andCompensation_idIsNull() {
            addCriterion("compensation_id is null");
            return (Criteria) this;
        }

        public Criteria andCompensation_idIsNotNull() {
            addCriterion("compensation_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompensation_idEqualTo(Long value) {
            addCriterion("compensation_id =", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idNotEqualTo(Long value) {
            addCriterion("compensation_id <>", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idGreaterThan(Long value) {
            addCriterion("compensation_id >", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idGreaterThanOrEqualTo(Long value) {
            addCriterion("compensation_id >=", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idLessThan(Long value) {
            addCriterion("compensation_id <", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idLessThanOrEqualTo(Long value) {
            addCriterion("compensation_id <=", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idIn(List<Long> values) {
            addCriterion("compensation_id in", values, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idNotIn(List<Long> values) {
            addCriterion("compensation_id not in", values, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idBetween(Long value1, Long value2) {
            addCriterion("compensation_id between", value1, value2, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idNotBetween(Long value1, Long value2) {
            addCriterion("compensation_id not between", value1, value2, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIsNull() {
            addCriterion("pay_order_id is null");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIsNotNull() {
            addCriterion("pay_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andPay_order_idEqualTo(String value) {
            addCriterion("pay_order_id =", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotEqualTo(String value) {
            addCriterion("pay_order_id <>", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idGreaterThan(String value) {
            addCriterion("pay_order_id >", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idGreaterThanOrEqualTo(String value) {
            addCriterion("pay_order_id >=", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLessThan(String value) {
            addCriterion("pay_order_id <", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLessThanOrEqualTo(String value) {
            addCriterion("pay_order_id <=", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLike(String value) {
            addCriterion("pay_order_id like", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotLike(String value) {
            addCriterion("pay_order_id not like", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIn(List<String> values) {
            addCriterion("pay_order_id in", values, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotIn(List<String> values) {
            addCriterion("pay_order_id not in", values, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idBetween(String value1, String value2) {
            addCriterion("pay_order_id between", value1, value2, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotBetween(String value1, String value2) {
            addCriterion("pay_order_id not between", value1, value2, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idIsNull() {
            addCriterion("partner_id is null");
            return (Criteria) this;
        }

        public Criteria andPartner_idIsNotNull() {
            addCriterion("partner_id is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_idEqualTo(Long value) {
            addCriterion("partner_id =", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotEqualTo(Long value) {
            addCriterion("partner_id <>", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idGreaterThan(Long value) {
            addCriterion("partner_id >", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idGreaterThanOrEqualTo(Long value) {
            addCriterion("partner_id >=", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idLessThan(Long value) {
            addCriterion("partner_id <", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idLessThanOrEqualTo(Long value) {
            addCriterion("partner_id <=", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idIn(List<Long> values) {
            addCriterion("partner_id in", values, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotIn(List<Long> values) {
            addCriterion("partner_id not in", values, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idBetween(Long value1, Long value2) {
            addCriterion("partner_id between", value1, value2, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotBetween(Long value1, Long value2) {
            addCriterion("partner_id not between", value1, value2, "partner_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoIsNull() {
            addCriterion("compensation_info is null");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoIsNotNull() {
            addCriterion("compensation_info is not null");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoEqualTo(String value) {
            addCriterion("compensation_info =", value, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoNotEqualTo(String value) {
            addCriterion("compensation_info <>", value, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoGreaterThan(String value) {
            addCriterion("compensation_info >", value, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoGreaterThanOrEqualTo(String value) {
            addCriterion("compensation_info >=", value, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoLessThan(String value) {
            addCriterion("compensation_info <", value, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoLessThanOrEqualTo(String value) {
            addCriterion("compensation_info <=", value, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoLike(String value) {
            addCriterion("compensation_info like", value, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoNotLike(String value) {
            addCriterion("compensation_info not like", value, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoIn(List<String> values) {
            addCriterion("compensation_info in", values, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoNotIn(List<String> values) {
            addCriterion("compensation_info not in", values, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoBetween(String value1, String value2) {
            addCriterion("compensation_info between", value1, value2, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoNotBetween(String value1, String value2) {
            addCriterion("compensation_info not between", value1, value2, "compensation_info");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Integer value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Integer value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Integer value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Integer value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Integer value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Integer> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Integer> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Integer value1, Integer value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountIsNull() {
            addCriterion("partner_bear_amount is null");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountIsNotNull() {
            addCriterion("partner_bear_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountEqualTo(Integer value) {
            addCriterion("partner_bear_amount =", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountNotEqualTo(Integer value) {
            addCriterion("partner_bear_amount <>", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountGreaterThan(Integer value) {
            addCriterion("partner_bear_amount >", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("partner_bear_amount >=", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountLessThan(Integer value) {
            addCriterion("partner_bear_amount <", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountLessThanOrEqualTo(Integer value) {
            addCriterion("partner_bear_amount <=", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountIn(List<Integer> values) {
            addCriterion("partner_bear_amount in", values, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountNotIn(List<Integer> values) {
            addCriterion("partner_bear_amount not in", values, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountBetween(Integer value1, Integer value2) {
            addCriterion("partner_bear_amount between", value1, value2, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("partner_bear_amount not between", value1, value2, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountIsNull() {
            addCriterion("partner_bear_coupon_amount is null");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountIsNotNull() {
            addCriterion("partner_bear_coupon_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountEqualTo(Integer value) {
            addCriterion("partner_bear_coupon_amount =", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountNotEqualTo(Integer value) {
            addCriterion("partner_bear_coupon_amount <>", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountGreaterThan(Integer value) {
            addCriterion("partner_bear_coupon_amount >", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("partner_bear_coupon_amount >=", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountLessThan(Integer value) {
            addCriterion("partner_bear_coupon_amount <", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountLessThanOrEqualTo(Integer value) {
            addCriterion("partner_bear_coupon_amount <=", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountIn(List<Integer> values) {
            addCriterion("partner_bear_coupon_amount in", values, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountNotIn(List<Integer> values) {
            addCriterion("partner_bear_coupon_amount not in", values, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountBetween(Integer value1, Integer value2) {
            addCriterion("partner_bear_coupon_amount between", value1, value2, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("partner_bear_coupon_amount not between", value1, value2, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPayeeIsNull() {
            addCriterion("payee is null");
            return (Criteria) this;
        }

        public Criteria andPayeeIsNotNull() {
            addCriterion("payee is not null");
            return (Criteria) this;
        }

        public Criteria andPayeeEqualTo(String value) {
            addCriterion("payee =", value, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeNotEqualTo(String value) {
            addCriterion("payee <>", value, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeGreaterThan(String value) {
            addCriterion("payee >", value, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeGreaterThanOrEqualTo(String value) {
            addCriterion("payee >=", value, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeLessThan(String value) {
            addCriterion("payee <", value, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeLessThanOrEqualTo(String value) {
            addCriterion("payee <=", value, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeLike(String value) {
            addCriterion("payee like", value, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeNotLike(String value) {
            addCriterion("payee not like", value, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeIn(List<String> values) {
            addCriterion("payee in", values, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeNotIn(List<String> values) {
            addCriterion("payee not in", values, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeBetween(String value1, String value2) {
            addCriterion("payee between", value1, value2, "payee");
            return (Criteria) this;
        }

        public Criteria andPayeeNotBetween(String value1, String value2) {
            addCriterion("payee not between", value1, value2, "payee");
            return (Criteria) this;
        }

        public Criteria andPayee_cardIsNull() {
            addCriterion("payee_card is null");
            return (Criteria) this;
        }

        public Criteria andPayee_cardIsNotNull() {
            addCriterion("payee_card is not null");
            return (Criteria) this;
        }

        public Criteria andPayee_cardEqualTo(String value) {
            addCriterion("payee_card =", value, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardNotEqualTo(String value) {
            addCriterion("payee_card <>", value, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardGreaterThan(String value) {
            addCriterion("payee_card >", value, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardGreaterThanOrEqualTo(String value) {
            addCriterion("payee_card >=", value, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardLessThan(String value) {
            addCriterion("payee_card <", value, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardLessThanOrEqualTo(String value) {
            addCriterion("payee_card <=", value, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardLike(String value) {
            addCriterion("payee_card like", value, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardNotLike(String value) {
            addCriterion("payee_card not like", value, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardIn(List<String> values) {
            addCriterion("payee_card in", values, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardNotIn(List<String> values) {
            addCriterion("payee_card not in", values, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardBetween(String value1, String value2) {
            addCriterion("payee_card between", value1, value2, "payee_card");
            return (Criteria) this;
        }

        public Criteria andPayee_cardNotBetween(String value1, String value2) {
            addCriterion("payee_card not between", value1, value2, "payee_card");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankIsNull() {
            addCriterion("receiving_bank is null");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankIsNotNull() {
            addCriterion("receiving_bank is not null");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankEqualTo(String value) {
            addCriterion("receiving_bank =", value, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankNotEqualTo(String value) {
            addCriterion("receiving_bank <>", value, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankGreaterThan(String value) {
            addCriterion("receiving_bank >", value, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankGreaterThanOrEqualTo(String value) {
            addCriterion("receiving_bank >=", value, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankLessThan(String value) {
            addCriterion("receiving_bank <", value, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankLessThanOrEqualTo(String value) {
            addCriterion("receiving_bank <=", value, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankLike(String value) {
            addCriterion("receiving_bank like", value, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankNotLike(String value) {
            addCriterion("receiving_bank not like", value, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankIn(List<String> values) {
            addCriterion("receiving_bank in", values, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankNotIn(List<String> values) {
            addCriterion("receiving_bank not in", values, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankBetween(String value1, String value2) {
            addCriterion("receiving_bank between", value1, value2, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankNotBetween(String value1, String value2) {
            addCriterion("receiving_bank not between", value1, value2, "receiving_bank");
            return (Criteria) this;
        }

        public Criteria andOperator_createIsNull() {
            addCriterion("operator_create is null");
            return (Criteria) this;
        }

        public Criteria andOperator_createIsNotNull() {
            addCriterion("operator_create is not null");
            return (Criteria) this;
        }

        public Criteria andOperator_createEqualTo(Long value) {
            addCriterion("operator_create =", value, "operator_create");
            return (Criteria) this;
        }

        public Criteria andOperator_createNotEqualTo(Long value) {
            addCriterion("operator_create <>", value, "operator_create");
            return (Criteria) this;
        }

        public Criteria andOperator_createGreaterThan(Long value) {
            addCriterion("operator_create >", value, "operator_create");
            return (Criteria) this;
        }

        public Criteria andOperator_createGreaterThanOrEqualTo(Long value) {
            addCriterion("operator_create >=", value, "operator_create");
            return (Criteria) this;
        }

        public Criteria andOperator_createLessThan(Long value) {
            addCriterion("operator_create <", value, "operator_create");
            return (Criteria) this;
        }

        public Criteria andOperator_createLessThanOrEqualTo(Long value) {
            addCriterion("operator_create <=", value, "operator_create");
            return (Criteria) this;
        }

        public Criteria andOperator_createIn(List<Long> values) {
            addCriterion("operator_create in", values, "operator_create");
            return (Criteria) this;
        }

        public Criteria andOperator_createNotIn(List<Long> values) {
            addCriterion("operator_create not in", values, "operator_create");
            return (Criteria) this;
        }

        public Criteria andOperator_createBetween(Long value1, Long value2) {
            addCriterion("operator_create between", value1, value2, "operator_create");
            return (Criteria) this;
        }

        public Criteria andOperator_createNotBetween(Long value1, Long value2) {
            addCriterion("operator_create not between", value1, value2, "operator_create");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmIsNull() {
            addCriterion("operator_confirm is null");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmIsNotNull() {
            addCriterion("operator_confirm is not null");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmEqualTo(Long value) {
            addCriterion("operator_confirm =", value, "operator_confirm");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmNotEqualTo(Long value) {
            addCriterion("operator_confirm <>", value, "operator_confirm");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmGreaterThan(Long value) {
            addCriterion("operator_confirm >", value, "operator_confirm");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmGreaterThanOrEqualTo(Long value) {
            addCriterion("operator_confirm >=", value, "operator_confirm");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmLessThan(Long value) {
            addCriterion("operator_confirm <", value, "operator_confirm");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmLessThanOrEqualTo(Long value) {
            addCriterion("operator_confirm <=", value, "operator_confirm");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmIn(List<Long> values) {
            addCriterion("operator_confirm in", values, "operator_confirm");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmNotIn(List<Long> values) {
            addCriterion("operator_confirm not in", values, "operator_confirm");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmBetween(Long value1, Long value2) {
            addCriterion("operator_confirm between", value1, value2, "operator_confirm");
            return (Criteria) this;
        }

        public Criteria andOperator_confirmNotBetween(Long value1, Long value2) {
            addCriterion("operator_confirm not between", value1, value2, "operator_confirm");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeIsNull() {
            addCriterion("confirm_datetime is null");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeIsNotNull() {
            addCriterion("confirm_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeEqualTo(Date value) {
            addCriterion("confirm_datetime =", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeNotEqualTo(Date value) {
            addCriterion("confirm_datetime <>", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeGreaterThan(Date value) {
            addCriterion("confirm_datetime >", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("confirm_datetime >=", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeLessThan(Date value) {
            addCriterion("confirm_datetime <", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("confirm_datetime <=", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeIn(List<Date> values) {
            addCriterion("confirm_datetime in", values, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeNotIn(List<Date> values) {
            addCriterion("confirm_datetime not in", values, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeBetween(Date value1, Date value2) {
            addCriterion("confirm_datetime between", value1, value2, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("confirm_datetime not between", value1, value2, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusIsNull() {
            addCriterion("compensation_status is null");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusIsNotNull() {
            addCriterion("compensation_status is not null");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusEqualTo(Integer value) {
            addCriterion("compensation_status =", value, "compensation_status");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusNotEqualTo(Integer value) {
            addCriterion("compensation_status <>", value, "compensation_status");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusGreaterThan(Integer value) {
            addCriterion("compensation_status >", value, "compensation_status");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("compensation_status >=", value, "compensation_status");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusLessThan(Integer value) {
            addCriterion("compensation_status <", value, "compensation_status");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusLessThanOrEqualTo(Integer value) {
            addCriterion("compensation_status <=", value, "compensation_status");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusIn(List<Integer> values) {
            addCriterion("compensation_status in", values, "compensation_status");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusNotIn(List<Integer> values) {
            addCriterion("compensation_status not in", values, "compensation_status");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusBetween(Integer value1, Integer value2) {
            addCriterion("compensation_status between", value1, value2, "compensation_status");
            return (Criteria) this;
        }

        public Criteria andCompensation_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("compensation_status not between", value1, value2, "compensation_status");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNull() {
            addCriterion("coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNotNull() {
            addCriterion("coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idEqualTo(Long value) {
            addCriterion("coupon_id =", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotEqualTo(Long value) {
            addCriterion("coupon_id <>", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThan(Long value) {
            addCriterion("coupon_id >", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_id >=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThan(Long value) {
            addCriterion("coupon_id <", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThanOrEqualTo(Long value) {
            addCriterion("coupon_id <=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIn(List<Long> values) {
            addCriterion("coupon_id in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotIn(List<Long> values) {
            addCriterion("coupon_id not in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idBetween(Long value1, Long value2) {
            addCriterion("coupon_id between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotBetween(Long value1, Long value2) {
            addCriterion("coupon_id not between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idIsNull() {
            addCriterion("coupon_receive_id is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idIsNotNull() {
            addCriterion("coupon_receive_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idEqualTo(Long value) {
            addCriterion("coupon_receive_id =", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idNotEqualTo(Long value) {
            addCriterion("coupon_receive_id <>", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idGreaterThan(Long value) {
            addCriterion("coupon_receive_id >", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_receive_id >=", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idLessThan(Long value) {
            addCriterion("coupon_receive_id <", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idLessThanOrEqualTo(Long value) {
            addCriterion("coupon_receive_id <=", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idIn(List<Long> values) {
            addCriterion("coupon_receive_id in", values, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idNotIn(List<Long> values) {
            addCriterion("coupon_receive_id not in", values, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idBetween(Long value1, Long value2) {
            addCriterion("coupon_receive_id between", value1, value2, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idNotBetween(Long value1, Long value2) {
            addCriterion("coupon_receive_id not between", value1, value2, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLikeInsensitive(String value) {
            addCriterion("upper(pay_order_id) like", value.toUpperCase(), "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_infoLikeInsensitive(String value) {
            addCriterion("upper(compensation_info) like", value.toUpperCase(), "compensation_info");
            return (Criteria) this;
        }

        public Criteria andPayeeLikeInsensitive(String value) {
            addCriterion("upper(payee) like", value.toUpperCase(), "payee");
            return (Criteria) this;
        }

        public Criteria andPayee_cardLikeInsensitive(String value) {
            addCriterion("upper(payee_card) like", value.toUpperCase(), "payee_card");
            return (Criteria) this;
        }

        public Criteria andReceiving_bankLikeInsensitive(String value) {
            addCriterion("upper(receiving_bank) like", value.toUpperCase(), "receiving_bank");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table compensation
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 12 19:13:57 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table compensation
     *
     * @mbg.generated Tue Jun 12 19:13:57 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	赔偿申请 
		//--------------------------------------------------					
													compensation_id(1,Types.BIGINT,false),
		/** 订单id */								pay_order_id(2,Types.VARCHAR,false),
		/** 合伙人id */								partner_id(2,Types.BIGINT,false),
		/** 赔偿原因 */								compensation_info(2,Types.VARCHAR,false),
		/** 赔偿金额 单位 分 */						amount(2,Types.INTEGER,false),
		/** 合伙人承当金额 */						partner_bear_amount(2,Types.INTEGER,false),
		/** 合伙人承当卷金额 */						partner_bear_coupon_amount(2,Types.INTEGER,false),
		/** 收款人姓名 */							payee(2,Types.VARCHAR,false),
		/** 收款人卡号 */							payee_card(2,Types.VARCHAR,false),
		/** 收款银行 */								receiving_bank(2,Types.VARCHAR,false),
		/** 创建操作人 */							operator_create(2,Types.BIGINT,false),
		/** 创建时间 */								create_datetime(2,Types.TIMESTAMP,false),
		/** 确认操作人 */							operator_confirm(2,Types.BIGINT,false),
		/** 确认时间 */								confirm_datetime(2,Types.TIMESTAMP,false),
		/** 状态   1 待处理 2 完成 3 驳回 */		compensation_status(2,Types.INTEGER,false),
		/** 优惠卷id */								coupon_id(2,Types.BIGINT,false),
		/** 优惠卷领用id */							coupon_receive_id(2,Types.BIGINT,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}