package com.aobei.train.model;

import com.aobei.train.model.CouponAndCouponEnvExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class CouponAndCouponEnvExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon__coupon_env
     *
     * @mbg.generated Tue Jul 24 16:41:31 CST 2018
     */
    public CouponAndCouponEnvExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon__coupon_env
     *
     * @mbg.generated Tue Jul 24 16:41:31 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon__coupon_env
     *
     * @mbg.generated Tue Jul 24 16:41:31 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon__coupon_env
     *
     * @mbg.generated Tue Jul 24 16:41:31 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon__coupon_env
     *
     * @mbg.generated Tue Jul 24 16:41:31 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andCoupon_env_idIsNull() {
            addCriterion("coupon_env_id is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idIsNotNull() {
            addCriterion("coupon_env_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idEqualTo(Long value) {
            addCriterion("coupon_env_id =", value, "coupon_env_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idNotEqualTo(Long value) {
            addCriterion("coupon_env_id <>", value, "coupon_env_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idGreaterThan(Long value) {
            addCriterion("coupon_env_id >", value, "coupon_env_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_env_id >=", value, "coupon_env_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idLessThan(Long value) {
            addCriterion("coupon_env_id <", value, "coupon_env_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idLessThanOrEqualTo(Long value) {
            addCriterion("coupon_env_id <=", value, "coupon_env_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idIn(List<Long> values) {
            addCriterion("coupon_env_id in", values, "coupon_env_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idNotIn(List<Long> values) {
            addCriterion("coupon_env_id not in", values, "coupon_env_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idBetween(Long value1, Long value2) {
            addCriterion("coupon_env_id between", value1, value2, "coupon_env_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_env_idNotBetween(Long value1, Long value2) {
            addCriterion("coupon_env_id not between", value1, value2, "coupon_env_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNull() {
            addCriterion("coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNotNull() {
            addCriterion("coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idEqualTo(Long value) {
            addCriterion("coupon_id =", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotEqualTo(Long value) {
            addCriterion("coupon_id <>", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThan(Long value) {
            addCriterion("coupon_id >", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_id >=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThan(Long value) {
            addCriterion("coupon_id <", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThanOrEqualTo(Long value) {
            addCriterion("coupon_id <=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIn(List<Long> values) {
            addCriterion("coupon_id in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotIn(List<Long> values) {
            addCriterion("coupon_id not in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idBetween(Long value1, Long value2) {
            addCriterion("coupon_id between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotBetween(Long value1, Long value2) {
            addCriterion("coupon_id not between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andNoneIsNull() {
            addCriterion("none is null");
            return (Criteria) this;
        }

        public Criteria andNoneIsNotNull() {
            addCriterion("none is not null");
            return (Criteria) this;
        }

        public Criteria andNoneEqualTo(String value) {
            addCriterion("none =", value, "none");
            return (Criteria) this;
        }

        public Criteria andNoneNotEqualTo(String value) {
            addCriterion("none <>", value, "none");
            return (Criteria) this;
        }

        public Criteria andNoneGreaterThan(String value) {
            addCriterion("none >", value, "none");
            return (Criteria) this;
        }

        public Criteria andNoneGreaterThanOrEqualTo(String value) {
            addCriterion("none >=", value, "none");
            return (Criteria) this;
        }

        public Criteria andNoneLessThan(String value) {
            addCriterion("none <", value, "none");
            return (Criteria) this;
        }

        public Criteria andNoneLessThanOrEqualTo(String value) {
            addCriterion("none <=", value, "none");
            return (Criteria) this;
        }

        public Criteria andNoneLike(String value) {
            addCriterion("none like", value, "none");
            return (Criteria) this;
        }

        public Criteria andNoneNotLike(String value) {
            addCriterion("none not like", value, "none");
            return (Criteria) this;
        }

        public Criteria andNoneIn(List<String> values) {
            addCriterion("none in", values, "none");
            return (Criteria) this;
        }

        public Criteria andNoneNotIn(List<String> values) {
            addCriterion("none not in", values, "none");
            return (Criteria) this;
        }

        public Criteria andNoneBetween(String value1, String value2) {
            addCriterion("none between", value1, value2, "none");
            return (Criteria) this;
        }

        public Criteria andNoneNotBetween(String value1, String value2) {
            addCriterion("none not between", value1, value2, "none");
            return (Criteria) this;
        }

        public Criteria andNoneLikeInsensitive(String value) {
            addCriterion("upper(none) like", value.toUpperCase(), "none");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon__coupon_env
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 24 16:41:31 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table coupon__coupon_env
     *
     * @mbg.generated Tue Jul 24 16:41:31 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	优惠券和优惠策略中间表
		//--------------------------------------------------
		/** 优惠策略id */			coupon_env_id(1,Types.BIGINT,false),
		/** 优惠券id */				coupon_id(2,Types.BIGINT,false),
		/** 无用字段 */				none(2,Types.VARCHAR,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}