package com.aobei.train.model;

import com.aobei.train.model.CouponExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class CouponExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated Fri Jul 06 19:03:36 CST 2018
     */
    public CouponExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated Fri Jul 06 19:03:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated Fri Jul 06 19:03:36 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon
     *
     * @mbg.generated Fri Jul 06 19:03:36 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon
     *
     * @mbg.generated Fri Jul 06 19:03:36 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andCoupon_idIsNull() {
            addCriterion("coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNotNull() {
            addCriterion("coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idEqualTo(Long value) {
            addCriterion("coupon_id =", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotEqualTo(Long value) {
            addCriterion("coupon_id <>", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThan(Long value) {
            addCriterion("coupon_id >", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_id >=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThan(Long value) {
            addCriterion("coupon_id <", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThanOrEqualTo(Long value) {
            addCriterion("coupon_id <=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIn(List<Long> values) {
            addCriterion("coupon_id in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotIn(List<Long> values) {
            addCriterion("coupon_id not in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idBetween(Long value1, Long value2) {
            addCriterion("coupon_id between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotBetween(Long value1, Long value2) {
            addCriterion("coupon_id not between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptIsNull() {
            addCriterion("descript is null");
            return (Criteria) this;
        }

        public Criteria andDescriptIsNotNull() {
            addCriterion("descript is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptEqualTo(String value) {
            addCriterion("descript =", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotEqualTo(String value) {
            addCriterion("descript <>", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptGreaterThan(String value) {
            addCriterion("descript >", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptGreaterThanOrEqualTo(String value) {
            addCriterion("descript >=", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLessThan(String value) {
            addCriterion("descript <", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLessThanOrEqualTo(String value) {
            addCriterion("descript <=", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLike(String value) {
            addCriterion("descript like", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotLike(String value) {
            addCriterion("descript not like", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptIn(List<String> values) {
            addCriterion("descript in", values, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotIn(List<String> values) {
            addCriterion("descript not in", values, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptBetween(String value1, String value2) {
            addCriterion("descript between", value1, value2, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotBetween(String value1, String value2) {
            addCriterion("descript not between", value1, value2, "descript");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyIsNull() {
            addCriterion("plan_money is null");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyIsNotNull() {
            addCriterion("plan_money is not null");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyEqualTo(Integer value) {
            addCriterion("plan_money =", value, "plan_money");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyNotEqualTo(Integer value) {
            addCriterion("plan_money <>", value, "plan_money");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyGreaterThan(Integer value) {
            addCriterion("plan_money >", value, "plan_money");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("plan_money >=", value, "plan_money");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyLessThan(Integer value) {
            addCriterion("plan_money <", value, "plan_money");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyLessThanOrEqualTo(Integer value) {
            addCriterion("plan_money <=", value, "plan_money");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyIn(List<Integer> values) {
            addCriterion("plan_money in", values, "plan_money");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyNotIn(List<Integer> values) {
            addCriterion("plan_money not in", values, "plan_money");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyBetween(Integer value1, Integer value2) {
            addCriterion("plan_money between", value1, value2, "plan_money");
            return (Criteria) this;
        }

        public Criteria andPlan_moneyNotBetween(Integer value1, Integer value2) {
            addCriterion("plan_money not between", value1, value2, "plan_money");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("valid is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("valid is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Integer value) {
            addCriterion("valid =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Integer value) {
            addCriterion("valid <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Integer value) {
            addCriterion("valid >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Integer value) {
            addCriterion("valid >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Integer value) {
            addCriterion("valid <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Integer value) {
            addCriterion("valid <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Integer> values) {
            addCriterion("valid in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Integer> values) {
            addCriterion("valid not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Integer value1, Integer value2) {
            addCriterion("valid between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Integer value1, Integer value2) {
            addCriterion("valid not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andExclusiveIsNull() {
            addCriterion("exclusive is null");
            return (Criteria) this;
        }

        public Criteria andExclusiveIsNotNull() {
            addCriterion("exclusive is not null");
            return (Criteria) this;
        }

        public Criteria andExclusiveEqualTo(Integer value) {
            addCriterion("exclusive =", value, "exclusive");
            return (Criteria) this;
        }

        public Criteria andExclusiveNotEqualTo(Integer value) {
            addCriterion("exclusive <>", value, "exclusive");
            return (Criteria) this;
        }

        public Criteria andExclusiveGreaterThan(Integer value) {
            addCriterion("exclusive >", value, "exclusive");
            return (Criteria) this;
        }

        public Criteria andExclusiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("exclusive >=", value, "exclusive");
            return (Criteria) this;
        }

        public Criteria andExclusiveLessThan(Integer value) {
            addCriterion("exclusive <", value, "exclusive");
            return (Criteria) this;
        }

        public Criteria andExclusiveLessThanOrEqualTo(Integer value) {
            addCriterion("exclusive <=", value, "exclusive");
            return (Criteria) this;
        }

        public Criteria andExclusiveIn(List<Integer> values) {
            addCriterion("exclusive in", values, "exclusive");
            return (Criteria) this;
        }

        public Criteria andExclusiveNotIn(List<Integer> values) {
            addCriterion("exclusive not in", values, "exclusive");
            return (Criteria) this;
        }

        public Criteria andExclusiveBetween(Integer value1, Integer value2) {
            addCriterion("exclusive between", value1, value2, "exclusive");
            return (Criteria) this;
        }

        public Criteria andExclusiveNotBetween(Integer value1, Integer value2) {
            addCriterion("exclusive not between", value1, value2, "exclusive");
            return (Criteria) this;
        }

        public Criteria andNum_limitIsNull() {
            addCriterion("num_limit is null");
            return (Criteria) this;
        }

        public Criteria andNum_limitIsNotNull() {
            addCriterion("num_limit is not null");
            return (Criteria) this;
        }

        public Criteria andNum_limitEqualTo(Integer value) {
            addCriterion("num_limit =", value, "num_limit");
            return (Criteria) this;
        }

        public Criteria andNum_limitNotEqualTo(Integer value) {
            addCriterion("num_limit <>", value, "num_limit");
            return (Criteria) this;
        }

        public Criteria andNum_limitGreaterThan(Integer value) {
            addCriterion("num_limit >", value, "num_limit");
            return (Criteria) this;
        }

        public Criteria andNum_limitGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_limit >=", value, "num_limit");
            return (Criteria) this;
        }

        public Criteria andNum_limitLessThan(Integer value) {
            addCriterion("num_limit <", value, "num_limit");
            return (Criteria) this;
        }

        public Criteria andNum_limitLessThanOrEqualTo(Integer value) {
            addCriterion("num_limit <=", value, "num_limit");
            return (Criteria) this;
        }

        public Criteria andNum_limitIn(List<Integer> values) {
            addCriterion("num_limit in", values, "num_limit");
            return (Criteria) this;
        }

        public Criteria andNum_limitNotIn(List<Integer> values) {
            addCriterion("num_limit not in", values, "num_limit");
            return (Criteria) this;
        }

        public Criteria andNum_limitBetween(Integer value1, Integer value2) {
            addCriterion("num_limit between", value1, value2, "num_limit");
            return (Criteria) this;
        }

        public Criteria andNum_limitNotBetween(Integer value1, Integer value2) {
            addCriterion("num_limit not between", value1, value2, "num_limit");
            return (Criteria) this;
        }

        public Criteria andNum_totalIsNull() {
            addCriterion("num_total is null");
            return (Criteria) this;
        }

        public Criteria andNum_totalIsNotNull() {
            addCriterion("num_total is not null");
            return (Criteria) this;
        }

        public Criteria andNum_totalEqualTo(Integer value) {
            addCriterion("num_total =", value, "num_total");
            return (Criteria) this;
        }

        public Criteria andNum_totalNotEqualTo(Integer value) {
            addCriterion("num_total <>", value, "num_total");
            return (Criteria) this;
        }

        public Criteria andNum_totalGreaterThan(Integer value) {
            addCriterion("num_total >", value, "num_total");
            return (Criteria) this;
        }

        public Criteria andNum_totalGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_total >=", value, "num_total");
            return (Criteria) this;
        }

        public Criteria andNum_totalLessThan(Integer value) {
            addCriterion("num_total <", value, "num_total");
            return (Criteria) this;
        }

        public Criteria andNum_totalLessThanOrEqualTo(Integer value) {
            addCriterion("num_total <=", value, "num_total");
            return (Criteria) this;
        }

        public Criteria andNum_totalIn(List<Integer> values) {
            addCriterion("num_total in", values, "num_total");
            return (Criteria) this;
        }

        public Criteria andNum_totalNotIn(List<Integer> values) {
            addCriterion("num_total not in", values, "num_total");
            return (Criteria) this;
        }

        public Criteria andNum_totalBetween(Integer value1, Integer value2) {
            addCriterion("num_total between", value1, value2, "num_total");
            return (Criteria) this;
        }

        public Criteria andNum_totalNotBetween(Integer value1, Integer value2) {
            addCriterion("num_total not between", value1, value2, "num_total");
            return (Criteria) this;
        }

        public Criteria andNum_ableIsNull() {
            addCriterion("num_able is null");
            return (Criteria) this;
        }

        public Criteria andNum_ableIsNotNull() {
            addCriterion("num_able is not null");
            return (Criteria) this;
        }

        public Criteria andNum_ableEqualTo(Integer value) {
            addCriterion("num_able =", value, "num_able");
            return (Criteria) this;
        }

        public Criteria andNum_ableNotEqualTo(Integer value) {
            addCriterion("num_able <>", value, "num_able");
            return (Criteria) this;
        }

        public Criteria andNum_ableGreaterThan(Integer value) {
            addCriterion("num_able >", value, "num_able");
            return (Criteria) this;
        }

        public Criteria andNum_ableGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_able >=", value, "num_able");
            return (Criteria) this;
        }

        public Criteria andNum_ableLessThan(Integer value) {
            addCriterion("num_able <", value, "num_able");
            return (Criteria) this;
        }

        public Criteria andNum_ableLessThanOrEqualTo(Integer value) {
            addCriterion("num_able <=", value, "num_able");
            return (Criteria) this;
        }

        public Criteria andNum_ableIn(List<Integer> values) {
            addCriterion("num_able in", values, "num_able");
            return (Criteria) this;
        }

        public Criteria andNum_ableNotIn(List<Integer> values) {
            addCriterion("num_able not in", values, "num_able");
            return (Criteria) this;
        }

        public Criteria andNum_ableBetween(Integer value1, Integer value2) {
            addCriterion("num_able between", value1, value2, "num_able");
            return (Criteria) this;
        }

        public Criteria andNum_ableNotBetween(Integer value1, Integer value2) {
            addCriterion("num_able not between", value1, value2, "num_able");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("priority is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("priority is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(Integer value) {
            addCriterion("priority =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(Integer value) {
            addCriterion("priority <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(Integer value) {
            addCriterion("priority >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("priority >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(Integer value) {
            addCriterion("priority <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("priority <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<Integer> values) {
            addCriterion("priority in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<Integer> values) {
            addCriterion("priority not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(Integer value1, Integer value2) {
            addCriterion("priority between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("priority not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andConditionIsNull() {
            addCriterion("`condition` is null");
            return (Criteria) this;
        }

        public Criteria andConditionIsNotNull() {
            addCriterion("`condition` is not null");
            return (Criteria) this;
        }

        public Criteria andConditionEqualTo(String value) {
            addCriterion("`condition` =", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotEqualTo(String value) {
            addCriterion("`condition` <>", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionGreaterThan(String value) {
            addCriterion("`condition` >", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionGreaterThanOrEqualTo(String value) {
            addCriterion("`condition` >=", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionLessThan(String value) {
            addCriterion("`condition` <", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionLessThanOrEqualTo(String value) {
            addCriterion("`condition` <=", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionLike(String value) {
            addCriterion("`condition` like", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotLike(String value) {
            addCriterion("`condition` not like", value, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionIn(List<String> values) {
            addCriterion("`condition` in", values, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotIn(List<String> values) {
            addCriterion("`condition` not in", values, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionBetween(String value1, String value2) {
            addCriterion("`condition` between", value1, value2, "condition");
            return (Criteria) this;
        }

        public Criteria andConditionNotBetween(String value1, String value2) {
            addCriterion("`condition` not between", value1, value2, "condition");
            return (Criteria) this;
        }

        public Criteria andCondition_typeIsNull() {
            addCriterion("condition_type is null");
            return (Criteria) this;
        }

        public Criteria andCondition_typeIsNotNull() {
            addCriterion("condition_type is not null");
            return (Criteria) this;
        }

        public Criteria andCondition_typeEqualTo(Integer value) {
            addCriterion("condition_type =", value, "condition_type");
            return (Criteria) this;
        }

        public Criteria andCondition_typeNotEqualTo(Integer value) {
            addCriterion("condition_type <>", value, "condition_type");
            return (Criteria) this;
        }

        public Criteria andCondition_typeGreaterThan(Integer value) {
            addCriterion("condition_type >", value, "condition_type");
            return (Criteria) this;
        }

        public Criteria andCondition_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("condition_type >=", value, "condition_type");
            return (Criteria) this;
        }

        public Criteria andCondition_typeLessThan(Integer value) {
            addCriterion("condition_type <", value, "condition_type");
            return (Criteria) this;
        }

        public Criteria andCondition_typeLessThanOrEqualTo(Integer value) {
            addCriterion("condition_type <=", value, "condition_type");
            return (Criteria) this;
        }

        public Criteria andCondition_typeIn(List<Integer> values) {
            addCriterion("condition_type in", values, "condition_type");
            return (Criteria) this;
        }

        public Criteria andCondition_typeNotIn(List<Integer> values) {
            addCriterion("condition_type not in", values, "condition_type");
            return (Criteria) this;
        }

        public Criteria andCondition_typeBetween(Integer value1, Integer value2) {
            addCriterion("condition_type between", value1, value2, "condition_type");
            return (Criteria) this;
        }

        public Criteria andCondition_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("condition_type not between", value1, value2, "condition_type");
            return (Criteria) this;
        }

        public Criteria andProgrammeIsNull() {
            addCriterion("programme is null");
            return (Criteria) this;
        }

        public Criteria andProgrammeIsNotNull() {
            addCriterion("programme is not null");
            return (Criteria) this;
        }

        public Criteria andProgrammeEqualTo(String value) {
            addCriterion("programme =", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeNotEqualTo(String value) {
            addCriterion("programme <>", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeGreaterThan(String value) {
            addCriterion("programme >", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeGreaterThanOrEqualTo(String value) {
            addCriterion("programme >=", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeLessThan(String value) {
            addCriterion("programme <", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeLessThanOrEqualTo(String value) {
            addCriterion("programme <=", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeLike(String value) {
            addCriterion("programme like", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeNotLike(String value) {
            addCriterion("programme not like", value, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeIn(List<String> values) {
            addCriterion("programme in", values, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeNotIn(List<String> values) {
            addCriterion("programme not in", values, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeBetween(String value1, String value2) {
            addCriterion("programme between", value1, value2, "programme");
            return (Criteria) this;
        }

        public Criteria andProgrammeNotBetween(String value1, String value2) {
            addCriterion("programme not between", value1, value2, "programme");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeIsNull() {
            addCriterion("programme_type is null");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeIsNotNull() {
            addCriterion("programme_type is not null");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeEqualTo(Integer value) {
            addCriterion("programme_type =", value, "programme_type");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeNotEqualTo(Integer value) {
            addCriterion("programme_type <>", value, "programme_type");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeGreaterThan(Integer value) {
            addCriterion("programme_type >", value, "programme_type");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("programme_type >=", value, "programme_type");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeLessThan(Integer value) {
            addCriterion("programme_type <", value, "programme_type");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeLessThanOrEqualTo(Integer value) {
            addCriterion("programme_type <=", value, "programme_type");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeIn(List<Integer> values) {
            addCriterion("programme_type in", values, "programme_type");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeNotIn(List<Integer> values) {
            addCriterion("programme_type not in", values, "programme_type");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeBetween(Integer value1, Integer value2) {
            addCriterion("programme_type between", value1, value2, "programme_type");
            return (Criteria) this;
        }

        public Criteria andProgramme_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("programme_type not between", value1, value2, "programme_type");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeIsNull() {
            addCriterion("use_start_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeIsNotNull() {
            addCriterion("use_start_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeEqualTo(Date value) {
            addCriterion("use_start_datetime =", value, "use_start_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeNotEqualTo(Date value) {
            addCriterion("use_start_datetime <>", value, "use_start_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeGreaterThan(Date value) {
            addCriterion("use_start_datetime >", value, "use_start_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("use_start_datetime >=", value, "use_start_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeLessThan(Date value) {
            addCriterion("use_start_datetime <", value, "use_start_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("use_start_datetime <=", value, "use_start_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeIn(List<Date> values) {
            addCriterion("use_start_datetime in", values, "use_start_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeNotIn(List<Date> values) {
            addCriterion("use_start_datetime not in", values, "use_start_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeBetween(Date value1, Date value2) {
            addCriterion("use_start_datetime between", value1, value2, "use_start_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_start_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("use_start_datetime not between", value1, value2, "use_start_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeIsNull() {
            addCriterion("use_end_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeIsNotNull() {
            addCriterion("use_end_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeEqualTo(Date value) {
            addCriterion("use_end_datetime =", value, "use_end_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeNotEqualTo(Date value) {
            addCriterion("use_end_datetime <>", value, "use_end_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeGreaterThan(Date value) {
            addCriterion("use_end_datetime >", value, "use_end_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("use_end_datetime >=", value, "use_end_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeLessThan(Date value) {
            addCriterion("use_end_datetime <", value, "use_end_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("use_end_datetime <=", value, "use_end_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeIn(List<Date> values) {
            addCriterion("use_end_datetime in", values, "use_end_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeNotIn(List<Date> values) {
            addCriterion("use_end_datetime not in", values, "use_end_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeBetween(Date value1, Date value2) {
            addCriterion("use_end_datetime between", value1, value2, "use_end_datetime");
            return (Criteria) this;
        }

        public Criteria andUse_end_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("use_end_datetime not between", value1, value2, "use_end_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeIsNull() {
            addCriterion("receive_start_datetime is null");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeIsNotNull() {
            addCriterion("receive_start_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeEqualTo(Date value) {
            addCriterion("receive_start_datetime =", value, "receive_start_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeNotEqualTo(Date value) {
            addCriterion("receive_start_datetime <>", value, "receive_start_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeGreaterThan(Date value) {
            addCriterion("receive_start_datetime >", value, "receive_start_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("receive_start_datetime >=", value, "receive_start_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeLessThan(Date value) {
            addCriterion("receive_start_datetime <", value, "receive_start_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("receive_start_datetime <=", value, "receive_start_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeIn(List<Date> values) {
            addCriterion("receive_start_datetime in", values, "receive_start_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeNotIn(List<Date> values) {
            addCriterion("receive_start_datetime not in", values, "receive_start_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeBetween(Date value1, Date value2) {
            addCriterion("receive_start_datetime between", value1, value2, "receive_start_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_start_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("receive_start_datetime not between", value1, value2, "receive_start_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeIsNull() {
            addCriterion("receive_end_datetime is null");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeIsNotNull() {
            addCriterion("receive_end_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeEqualTo(Date value) {
            addCriterion("receive_end_datetime =", value, "receive_end_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeNotEqualTo(Date value) {
            addCriterion("receive_end_datetime <>", value, "receive_end_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeGreaterThan(Date value) {
            addCriterion("receive_end_datetime >", value, "receive_end_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("receive_end_datetime >=", value, "receive_end_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeLessThan(Date value) {
            addCriterion("receive_end_datetime <", value, "receive_end_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("receive_end_datetime <=", value, "receive_end_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeIn(List<Date> values) {
            addCriterion("receive_end_datetime in", values, "receive_end_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeNotIn(List<Date> values) {
            addCriterion("receive_end_datetime not in", values, "receive_end_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeBetween(Date value1, Date value2) {
            addCriterion("receive_end_datetime between", value1, value2, "receive_end_datetime");
            return (Criteria) this;
        }

        public Criteria andReceive_end_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("receive_end_datetime not between", value1, value2, "receive_end_datetime");
            return (Criteria) this;
        }

        public Criteria andVerifyIsNull() {
            addCriterion("verify is null");
            return (Criteria) this;
        }

        public Criteria andVerifyIsNotNull() {
            addCriterion("verify is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyEqualTo(Integer value) {
            addCriterion("verify =", value, "verify");
            return (Criteria) this;
        }

        public Criteria andVerifyNotEqualTo(Integer value) {
            addCriterion("verify <>", value, "verify");
            return (Criteria) this;
        }

        public Criteria andVerifyGreaterThan(Integer value) {
            addCriterion("verify >", value, "verify");
            return (Criteria) this;
        }

        public Criteria andVerifyGreaterThanOrEqualTo(Integer value) {
            addCriterion("verify >=", value, "verify");
            return (Criteria) this;
        }

        public Criteria andVerifyLessThan(Integer value) {
            addCriterion("verify <", value, "verify");
            return (Criteria) this;
        }

        public Criteria andVerifyLessThanOrEqualTo(Integer value) {
            addCriterion("verify <=", value, "verify");
            return (Criteria) this;
        }

        public Criteria andVerifyIn(List<Integer> values) {
            addCriterion("verify in", values, "verify");
            return (Criteria) this;
        }

        public Criteria andVerifyNotIn(List<Integer> values) {
            addCriterion("verify not in", values, "verify");
            return (Criteria) this;
        }

        public Criteria andVerifyBetween(Integer value1, Integer value2) {
            addCriterion("verify between", value1, value2, "verify");
            return (Criteria) this;
        }

        public Criteria andVerifyNotBetween(Integer value1, Integer value2) {
            addCriterion("verify not between", value1, value2, "verify");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsIsNull() {
            addCriterion("verify_comments is null");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsIsNotNull() {
            addCriterion("verify_comments is not null");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsEqualTo(String value) {
            addCriterion("verify_comments =", value, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsNotEqualTo(String value) {
            addCriterion("verify_comments <>", value, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsGreaterThan(String value) {
            addCriterion("verify_comments >", value, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsGreaterThanOrEqualTo(String value) {
            addCriterion("verify_comments >=", value, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsLessThan(String value) {
            addCriterion("verify_comments <", value, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsLessThanOrEqualTo(String value) {
            addCriterion("verify_comments <=", value, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsLike(String value) {
            addCriterion("verify_comments like", value, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsNotLike(String value) {
            addCriterion("verify_comments not like", value, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsIn(List<String> values) {
            addCriterion("verify_comments in", values, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsNotIn(List<String> values) {
            addCriterion("verify_comments not in", values, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsBetween(String value1, String value2) {
            addCriterion("verify_comments between", value1, value2, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsNotBetween(String value1, String value2) {
            addCriterion("verify_comments not between", value1, value2, "verify_comments");
            return (Criteria) this;
        }

        public Criteria andCreate_userIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreate_userIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_userEqualTo(Long value) {
            addCriterion("create_user =", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userNotEqualTo(Long value) {
            addCriterion("create_user <>", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userGreaterThan(Long value) {
            addCriterion("create_user >", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userGreaterThanOrEqualTo(Long value) {
            addCriterion("create_user >=", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userLessThan(Long value) {
            addCriterion("create_user <", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userLessThanOrEqualTo(Long value) {
            addCriterion("create_user <=", value, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userIn(List<Long> values) {
            addCriterion("create_user in", values, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userNotIn(List<Long> values) {
            addCriterion("create_user not in", values, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userBetween(Long value1, Long value2) {
            addCriterion("create_user between", value1, value2, "create_user");
            return (Criteria) this;
        }

        public Criteria andCreate_userNotBetween(Long value1, Long value2) {
            addCriterion("create_user not between", value1, value2, "create_user");
            return (Criteria) this;
        }

        public Criteria andVerify_userIsNull() {
            addCriterion("verify_user is null");
            return (Criteria) this;
        }

        public Criteria andVerify_userIsNotNull() {
            addCriterion("verify_user is not null");
            return (Criteria) this;
        }

        public Criteria andVerify_userEqualTo(Long value) {
            addCriterion("verify_user =", value, "verify_user");
            return (Criteria) this;
        }

        public Criteria andVerify_userNotEqualTo(Long value) {
            addCriterion("verify_user <>", value, "verify_user");
            return (Criteria) this;
        }

        public Criteria andVerify_userGreaterThan(Long value) {
            addCriterion("verify_user >", value, "verify_user");
            return (Criteria) this;
        }

        public Criteria andVerify_userGreaterThanOrEqualTo(Long value) {
            addCriterion("verify_user >=", value, "verify_user");
            return (Criteria) this;
        }

        public Criteria andVerify_userLessThan(Long value) {
            addCriterion("verify_user <", value, "verify_user");
            return (Criteria) this;
        }

        public Criteria andVerify_userLessThanOrEqualTo(Long value) {
            addCriterion("verify_user <=", value, "verify_user");
            return (Criteria) this;
        }

        public Criteria andVerify_userIn(List<Long> values) {
            addCriterion("verify_user in", values, "verify_user");
            return (Criteria) this;
        }

        public Criteria andVerify_userNotIn(List<Long> values) {
            addCriterion("verify_user not in", values, "verify_user");
            return (Criteria) this;
        }

        public Criteria andVerify_userBetween(Long value1, Long value2) {
            addCriterion("verify_user between", value1, value2, "verify_user");
            return (Criteria) this;
        }

        public Criteria andVerify_userNotBetween(Long value1, Long value2) {
            addCriterion("verify_user not between", value1, value2, "verify_user");
            return (Criteria) this;
        }

        public Criteria andIs_validIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIs_validIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIs_validEqualTo(Integer value) {
            addCriterion("is_valid =", value, "is_valid");
            return (Criteria) this;
        }

        public Criteria andIs_validNotEqualTo(Integer value) {
            addCriterion("is_valid <>", value, "is_valid");
            return (Criteria) this;
        }

        public Criteria andIs_validGreaterThan(Integer value) {
            addCriterion("is_valid >", value, "is_valid");
            return (Criteria) this;
        }

        public Criteria andIs_validGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_valid >=", value, "is_valid");
            return (Criteria) this;
        }

        public Criteria andIs_validLessThan(Integer value) {
            addCriterion("is_valid <", value, "is_valid");
            return (Criteria) this;
        }

        public Criteria andIs_validLessThanOrEqualTo(Integer value) {
            addCriterion("is_valid <=", value, "is_valid");
            return (Criteria) this;
        }

        public Criteria andIs_validIn(List<Integer> values) {
            addCriterion("is_valid in", values, "is_valid");
            return (Criteria) this;
        }

        public Criteria andIs_validNotIn(List<Integer> values) {
            addCriterion("is_valid not in", values, "is_valid");
            return (Criteria) this;
        }

        public Criteria andIs_validBetween(Integer value1, Integer value2) {
            addCriterion("is_valid between", value1, value2, "is_valid");
            return (Criteria) this;
        }

        public Criteria andIs_validNotBetween(Integer value1, Integer value2) {
            addCriterion("is_valid not between", value1, value2, "is_valid");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeIsNull() {
            addCriterion("deliver_datetime is null");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeIsNotNull() {
            addCriterion("deliver_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeEqualTo(Date value) {
            addCriterion("deliver_datetime =", value, "deliver_datetime");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeNotEqualTo(Date value) {
            addCriterion("deliver_datetime <>", value, "deliver_datetime");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeGreaterThan(Date value) {
            addCriterion("deliver_datetime >", value, "deliver_datetime");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("deliver_datetime >=", value, "deliver_datetime");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeLessThan(Date value) {
            addCriterion("deliver_datetime <", value, "deliver_datetime");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("deliver_datetime <=", value, "deliver_datetime");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeIn(List<Date> values) {
            addCriterion("deliver_datetime in", values, "deliver_datetime");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeNotIn(List<Date> values) {
            addCriterion("deliver_datetime not in", values, "deliver_datetime");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeBetween(Date value1, Date value2) {
            addCriterion("deliver_datetime between", value1, value2, "deliver_datetime");
            return (Criteria) this;
        }

        public Criteria andDeliver_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("deliver_datetime not between", value1, value2, "deliver_datetime");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(name) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andDescriptLikeInsensitive(String value) {
            addCriterion("upper(descript) like", value.toUpperCase(), "descript");
            return (Criteria) this;
        }

        public Criteria andConditionLikeInsensitive(String value) {
            addCriterion("upper(`condition`) like", value.toUpperCase(), "condition");
            return (Criteria) this;
        }

        public Criteria andProgrammeLikeInsensitive(String value) {
            addCriterion("upper(programme) like", value.toUpperCase(), "programme");
            return (Criteria) this;
        }

        public Criteria andVerify_commentsLikeInsensitive(String value) {
            addCriterion("upper(verify_comments) like", value.toUpperCase(), "verify_comments");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coupon
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 06 19:03:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table coupon
     *
     * @mbg.generated Fri Jul 06 19:03:36 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	优惠卷 模板
		//--------------------------------------------------
		/** 优惠卷id */									coupon_id(1,Types.BIGINT,false),
		/** 名称 */										name(2,Types.VARCHAR,false),
		/** 描述 */										descript(2,Types.VARCHAR,false),
		/** 财务预算金额，单位 分 */					plan_money(2,Types.INTEGER,false),
		/** 是否用效  1 有效  0 无效 2 已过期 */		valid(2,Types.INTEGER,false),
		/** 是否排他  1 排他  0 不排他 */				exclusive(2,Types.INTEGER,false),
		/** 是否有发放数量限制  1 有限制  0 无限制 */	num_limit(2,Types.INTEGER,false),
		/** 总数量 ，仅 num_limit=1 时有数据 */			num_total(2,Types.INTEGER,false),
		/** 可发放数量 ，仅 num_limit=1 时有数据 */		num_able(2,Types.INTEGER,false),
		/** 优先级  1-99  99 最大 */					priority(2,Types.INTEGER,false),
		/** 优惠条件模板{"title":"消费满300元减时，对指定商品优惠","value":"30000","product":"{[productId,productid,...]}"} */
														condition(2,Types.VARCHAR,true),
		/** 优惠条件类型  1 订单总价满X时，对所有商品优惠  2 订单满X时对指定商品，3，多所有商品优惠，4对指定商品优惠 */
														condition_type(2,Types.INTEGER,false),
		/** 优惠方案模板{"title":"减30元","value":"3000"} */
														programme(2,Types.VARCHAR,false),
		/** 优惠方案类型  1，打折  2满减 */				programme_type(2,Types.INTEGER,false),
		/** 1,派发券2,赔偿券3,领取券4,兑换券 */			type(2,Types.INTEGER,false),
		/** 优惠卷有效使用开始日期时间 */				use_start_datetime(2,Types.TIMESTAMP,false),
		/** 优惠卷有效使用结束日期时间 */				use_end_datetime(2,Types.TIMESTAMP,false),
		/** 优惠卷有效领取开始日期时间 */				receive_start_datetime(2,Types.TIMESTAMP,false),					
														create_time(2,Types.TIMESTAMP,false),
		/** 优惠卷有效领取结束日期时间 */				receive_end_datetime(2,Types.TIMESTAMP,false),
		/**  0 未提审，1待审核，2审核通过 ，3 审核未通过  [DV=>0] */
														verify(2,Types.INTEGER,false),
		/** 审核意见 限制在50个汉字 */					verify_comments(2,Types.VARCHAR,false),
		/** 优惠券创建者id */							create_user(2,Types.BIGINT,false),
		/** 优惠券审核者id */							verify_user(2,Types.BIGINT,false),
		/** 表示是否已经标记过有效。0未标记 1已标记过 ，标记过的不能进行修改 [DV=>0] */
														is_valid(2,Types.INTEGER,false),
		/** 优惠券提审时间 */							deliver_datetime(2,Types.TIMESTAMP,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}