package com.aobei.train.model;

import com.aobei.train.model.CustomerAddressExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class CustomerAddressExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_address
     *
     * @mbg.generated Wed Jun 27 15:16:07 CST 2018
     */
    public CustomerAddressExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_address
     *
     * @mbg.generated Wed Jun 27 15:16:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_address
     *
     * @mbg.generated Wed Jun 27 15:16:07 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_address
     *
     * @mbg.generated Wed Jun 27 15:16:07 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_address
     *
     * @mbg.generated Wed Jun 27 15:16:07 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andCustomer_address_idIsNull() {
            addCriterion("customer_address_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idIsNotNull() {
            addCriterion("customer_address_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idEqualTo(Long value) {
            addCriterion("customer_address_id =", value, "customer_address_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idNotEqualTo(Long value) {
            addCriterion("customer_address_id <>", value, "customer_address_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idGreaterThan(Long value) {
            addCriterion("customer_address_id >", value, "customer_address_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idGreaterThanOrEqualTo(Long value) {
            addCriterion("customer_address_id >=", value, "customer_address_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idLessThan(Long value) {
            addCriterion("customer_address_id <", value, "customer_address_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idLessThanOrEqualTo(Long value) {
            addCriterion("customer_address_id <=", value, "customer_address_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idIn(List<Long> values) {
            addCriterion("customer_address_id in", values, "customer_address_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idNotIn(List<Long> values) {
            addCriterion("customer_address_id not in", values, "customer_address_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idBetween(Long value1, Long value2) {
            addCriterion("customer_address_id between", value1, value2, "customer_address_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_address_idNotBetween(Long value1, Long value2) {
            addCriterion("customer_address_id not between", value1, value2, "customer_address_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomer_idIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer_idEqualTo(Long value) {
            addCriterion("customer_id =", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idNotEqualTo(Long value) {
            addCriterion("customer_id <>", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idGreaterThan(Long value) {
            addCriterion("customer_id >", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idGreaterThanOrEqualTo(Long value) {
            addCriterion("customer_id >=", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idLessThan(Long value) {
            addCriterion("customer_id <", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idLessThanOrEqualTo(Long value) {
            addCriterion("customer_id <=", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idIn(List<Long> values) {
            addCriterion("customer_id in", values, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idNotIn(List<Long> values) {
            addCriterion("customer_id not in", values, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idBetween(Long value1, Long value2) {
            addCriterion("customer_id between", value1, value2, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idNotBetween(Long value1, Long value2) {
            addCriterion("customer_id not between", value1, value2, "customer_id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(Integer value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(Integer value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(Integer value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(Integer value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(Integer value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(Integer value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<Integer> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<Integer> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(Integer value1, Integer value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(Integer value1, Integer value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(Integer value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(Integer value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(Integer value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(Integer value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(Integer value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(Integer value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<Integer> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<Integer> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(Integer value1, Integer value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(Integer value1, Integer value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(Integer value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(Integer value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(Integer value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(Integer value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(Integer value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(Integer value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<Integer> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<Integer> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(Integer value1, Integer value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(Integer value1, Integer value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andLbs_latIsNull() {
            addCriterion("lbs_lat is null");
            return (Criteria) this;
        }

        public Criteria andLbs_latIsNotNull() {
            addCriterion("lbs_lat is not null");
            return (Criteria) this;
        }

        public Criteria andLbs_latEqualTo(String value) {
            addCriterion("lbs_lat =", value, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latNotEqualTo(String value) {
            addCriterion("lbs_lat <>", value, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latGreaterThan(String value) {
            addCriterion("lbs_lat >", value, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latGreaterThanOrEqualTo(String value) {
            addCriterion("lbs_lat >=", value, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latLessThan(String value) {
            addCriterion("lbs_lat <", value, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latLessThanOrEqualTo(String value) {
            addCriterion("lbs_lat <=", value, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latLike(String value) {
            addCriterion("lbs_lat like", value, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latNotLike(String value) {
            addCriterion("lbs_lat not like", value, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latIn(List<String> values) {
            addCriterion("lbs_lat in", values, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latNotIn(List<String> values) {
            addCriterion("lbs_lat not in", values, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latBetween(String value1, String value2) {
            addCriterion("lbs_lat between", value1, value2, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_latNotBetween(String value1, String value2) {
            addCriterion("lbs_lat not between", value1, value2, "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_lngIsNull() {
            addCriterion("lbs_lng is null");
            return (Criteria) this;
        }

        public Criteria andLbs_lngIsNotNull() {
            addCriterion("lbs_lng is not null");
            return (Criteria) this;
        }

        public Criteria andLbs_lngEqualTo(String value) {
            addCriterion("lbs_lng =", value, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngNotEqualTo(String value) {
            addCriterion("lbs_lng <>", value, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngGreaterThan(String value) {
            addCriterion("lbs_lng >", value, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngGreaterThanOrEqualTo(String value) {
            addCriterion("lbs_lng >=", value, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngLessThan(String value) {
            addCriterion("lbs_lng <", value, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngLessThanOrEqualTo(String value) {
            addCriterion("lbs_lng <=", value, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngLike(String value) {
            addCriterion("lbs_lng like", value, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngNotLike(String value) {
            addCriterion("lbs_lng not like", value, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngIn(List<String> values) {
            addCriterion("lbs_lng in", values, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngNotIn(List<String> values) {
            addCriterion("lbs_lng not in", values, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngBetween(String value1, String value2) {
            addCriterion("lbs_lng between", value1, value2, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andLbs_lngNotBetween(String value1, String value2) {
            addCriterion("lbs_lng not between", value1, value2, "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andSub_addressIsNull() {
            addCriterion("sub_address is null");
            return (Criteria) this;
        }

        public Criteria andSub_addressIsNotNull() {
            addCriterion("sub_address is not null");
            return (Criteria) this;
        }

        public Criteria andSub_addressEqualTo(String value) {
            addCriterion("sub_address =", value, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressNotEqualTo(String value) {
            addCriterion("sub_address <>", value, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressGreaterThan(String value) {
            addCriterion("sub_address >", value, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressGreaterThanOrEqualTo(String value) {
            addCriterion("sub_address >=", value, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressLessThan(String value) {
            addCriterion("sub_address <", value, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressLessThanOrEqualTo(String value) {
            addCriterion("sub_address <=", value, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressLike(String value) {
            addCriterion("sub_address like", value, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressNotLike(String value) {
            addCriterion("sub_address not like", value, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressIn(List<String> values) {
            addCriterion("sub_address in", values, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressNotIn(List<String> values) {
            addCriterion("sub_address not in", values, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressBetween(String value1, String value2) {
            addCriterion("sub_address between", value1, value2, "sub_address");
            return (Criteria) this;
        }

        public Criteria andSub_addressNotBetween(String value1, String value2) {
            addCriterion("sub_address not between", value1, value2, "sub_address");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeEqualTo(Date value) {
            addCriterion("update_datetime =", value, "update_datetime");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeNotEqualTo(Date value) {
            addCriterion("update_datetime <>", value, "update_datetime");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeGreaterThan(Date value) {
            addCriterion("update_datetime >", value, "update_datetime");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_datetime >=", value, "update_datetime");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeLessThan(Date value) {
            addCriterion("update_datetime <", value, "update_datetime");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("update_datetime <=", value, "update_datetime");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeIn(List<Date> values) {
            addCriterion("update_datetime in", values, "update_datetime");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeNotIn(List<Date> values) {
            addCriterion("update_datetime not in", values, "update_datetime");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeBetween(Date value1, Date value2) {
            addCriterion("update_datetime between", value1, value2, "update_datetime");
            return (Criteria) this;
        }

        public Criteria andUpdate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("update_datetime not between", value1, value2, "update_datetime");
            return (Criteria) this;
        }

        public Criteria andDefault_addressIsNull() {
            addCriterion("default_address is null");
            return (Criteria) this;
        }

        public Criteria andDefault_addressIsNotNull() {
            addCriterion("default_address is not null");
            return (Criteria) this;
        }

        public Criteria andDefault_addressEqualTo(Integer value) {
            addCriterion("default_address =", value, "default_address");
            return (Criteria) this;
        }

        public Criteria andDefault_addressNotEqualTo(Integer value) {
            addCriterion("default_address <>", value, "default_address");
            return (Criteria) this;
        }

        public Criteria andDefault_addressGreaterThan(Integer value) {
            addCriterion("default_address >", value, "default_address");
            return (Criteria) this;
        }

        public Criteria andDefault_addressGreaterThanOrEqualTo(Integer value) {
            addCriterion("default_address >=", value, "default_address");
            return (Criteria) this;
        }

        public Criteria andDefault_addressLessThan(Integer value) {
            addCriterion("default_address <", value, "default_address");
            return (Criteria) this;
        }

        public Criteria andDefault_addressLessThanOrEqualTo(Integer value) {
            addCriterion("default_address <=", value, "default_address");
            return (Criteria) this;
        }

        public Criteria andDefault_addressIn(List<Integer> values) {
            addCriterion("default_address in", values, "default_address");
            return (Criteria) this;
        }

        public Criteria andDefault_addressNotIn(List<Integer> values) {
            addCriterion("default_address not in", values, "default_address");
            return (Criteria) this;
        }

        public Criteria andDefault_addressBetween(Integer value1, Integer value2) {
            addCriterion("default_address between", value1, value2, "default_address");
            return (Criteria) this;
        }

        public Criteria andDefault_addressNotBetween(Integer value1, Integer value2) {
            addCriterion("default_address not between", value1, value2, "default_address");
            return (Criteria) this;
        }

        public Criteria andLast_usedIsNull() {
            addCriterion("last_used is null");
            return (Criteria) this;
        }

        public Criteria andLast_usedIsNotNull() {
            addCriterion("last_used is not null");
            return (Criteria) this;
        }

        public Criteria andLast_usedEqualTo(Integer value) {
            addCriterion("last_used =", value, "last_used");
            return (Criteria) this;
        }

        public Criteria andLast_usedNotEqualTo(Integer value) {
            addCriterion("last_used <>", value, "last_used");
            return (Criteria) this;
        }

        public Criteria andLast_usedGreaterThan(Integer value) {
            addCriterion("last_used >", value, "last_used");
            return (Criteria) this;
        }

        public Criteria andLast_usedGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_used >=", value, "last_used");
            return (Criteria) this;
        }

        public Criteria andLast_usedLessThan(Integer value) {
            addCriterion("last_used <", value, "last_used");
            return (Criteria) this;
        }

        public Criteria andLast_usedLessThanOrEqualTo(Integer value) {
            addCriterion("last_used <=", value, "last_used");
            return (Criteria) this;
        }

        public Criteria andLast_usedIn(List<Integer> values) {
            addCriterion("last_used in", values, "last_used");
            return (Criteria) this;
        }

        public Criteria andLast_usedNotIn(List<Integer> values) {
            addCriterion("last_used not in", values, "last_used");
            return (Criteria) this;
        }

        public Criteria andLast_usedBetween(Integer value1, Integer value2) {
            addCriterion("last_used between", value1, value2, "last_used");
            return (Criteria) this;
        }

        public Criteria andLast_usedNotBetween(Integer value1, Integer value2) {
            addCriterion("last_used not between", value1, value2, "last_used");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andUsernameLikeInsensitive(String value) {
            addCriterion("upper(username) like", value.toUpperCase(), "username");
            return (Criteria) this;
        }

        public Criteria andPhoneLikeInsensitive(String value) {
            addCriterion("upper(phone) like", value.toUpperCase(), "phone");
            return (Criteria) this;
        }

        public Criteria andAddressLikeInsensitive(String value) {
            addCriterion("upper(address) like", value.toUpperCase(), "address");
            return (Criteria) this;
        }

        public Criteria andLbs_latLikeInsensitive(String value) {
            addCriterion("upper(lbs_lat) like", value.toUpperCase(), "lbs_lat");
            return (Criteria) this;
        }

        public Criteria andLbs_lngLikeInsensitive(String value) {
            addCriterion("upper(lbs_lng) like", value.toUpperCase(), "lbs_lng");
            return (Criteria) this;
        }

        public Criteria andSub_addressLikeInsensitive(String value) {
            addCriterion("upper(sub_address) like", value.toUpperCase(), "sub_address");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_address
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 27 15:16:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table customer_address
     *
     * @mbg.generated Wed Jun 27 15:16:07 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	顾客服务地址
		//--------------------------------------------------					
														customer_address_id(1,Types.BIGINT,false),
		/** 顾客id */									customer_id(2,Types.BIGINT,false),
		/** 联系人 */									username(2,Types.VARCHAR,false),
		/** 手机号 */									phone(2,Types.VARCHAR,false),
		/** 省 */										province(2,Types.INTEGER,false),
		/** 市 */										city(2,Types.INTEGER,false),
		/** 地区 */										area(2,Types.INTEGER,false),
		/** 完整地址 ，空格分割 省，市 ，地 */			address(2,Types.VARCHAR,false),
		/** 坐标 纬度 */								lbs_lat(2,Types.VARCHAR,false),
		/** 坐标 经度 */								lbs_lng(2,Types.VARCHAR,false),
		/** 补充的地址信息 */							sub_address(2,Types.VARCHAR,false),
		/** 创建时间 [DV=>CURRENT_TIMESTAMP] */			create_datetime(2,Types.TIMESTAMP,false),
		/** 更新时间 [DV=>CURRENT_TIMESTAMP] */			update_datetime(2,Types.TIMESTAMP,false),
		/** 用户默认地址 1 默认地址 0 常规地址  [DV=>0] */
														default_address(2,Types.INTEGER,false),
		/** 是否是最后一次选择的地址。1是。2不是 */		last_used(2,Types.INTEGER,false),
		/** 删除状态0未删除，1已删除 [DV=>0] */			deleted(2,Types.INTEGER,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}