package com.aobei.train.model;

import com.aobei.train.model.FallintoCompensationExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class FallintoCompensationExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fallinto_compensation
     *
     * @mbg.generated Wed Jun 27 13:58:59 CST 2018
     */
    public FallintoCompensationExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fallinto_compensation
     *
     * @mbg.generated Wed Jun 27 13:58:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fallinto_compensation
     *
     * @mbg.generated Wed Jun 27 13:58:59 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fallinto_compensation
     *
     * @mbg.generated Wed Jun 27 13:58:59 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fallinto_compensation
     *
     * @mbg.generated Wed Jun 27 13:58:59 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andFallinto_compensation_idIsNull() {
            addCriterion("fallinto_compensation_id is null");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idIsNotNull() {
            addCriterion("fallinto_compensation_id is not null");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idEqualTo(Long value) {
            addCriterion("fallinto_compensation_id =", value, "fallinto_compensation_id");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idNotEqualTo(Long value) {
            addCriterion("fallinto_compensation_id <>", value, "fallinto_compensation_id");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idGreaterThan(Long value) {
            addCriterion("fallinto_compensation_id >", value, "fallinto_compensation_id");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idGreaterThanOrEqualTo(Long value) {
            addCriterion("fallinto_compensation_id >=", value, "fallinto_compensation_id");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idLessThan(Long value) {
            addCriterion("fallinto_compensation_id <", value, "fallinto_compensation_id");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idLessThanOrEqualTo(Long value) {
            addCriterion("fallinto_compensation_id <=", value, "fallinto_compensation_id");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idIn(List<Long> values) {
            addCriterion("fallinto_compensation_id in", values, "fallinto_compensation_id");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idNotIn(List<Long> values) {
            addCriterion("fallinto_compensation_id not in", values, "fallinto_compensation_id");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idBetween(Long value1, Long value2) {
            addCriterion("fallinto_compensation_id between", value1, value2, "fallinto_compensation_id");
            return (Criteria) this;
        }

        public Criteria andFallinto_compensation_idNotBetween(Long value1, Long value2) {
            addCriterion("fallinto_compensation_id not between", value1, value2, "fallinto_compensation_id");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleIsNull() {
            addCriterion("balance_cycle is null");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleIsNotNull() {
            addCriterion("balance_cycle is not null");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleEqualTo(String value) {
            addCriterion("balance_cycle =", value, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleNotEqualTo(String value) {
            addCriterion("balance_cycle <>", value, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleGreaterThan(String value) {
            addCriterion("balance_cycle >", value, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleGreaterThanOrEqualTo(String value) {
            addCriterion("balance_cycle >=", value, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleLessThan(String value) {
            addCriterion("balance_cycle <", value, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleLessThanOrEqualTo(String value) {
            addCriterion("balance_cycle <=", value, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleLike(String value) {
            addCriterion("balance_cycle like", value, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleNotLike(String value) {
            addCriterion("balance_cycle not like", value, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleIn(List<String> values) {
            addCriterion("balance_cycle in", values, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleNotIn(List<String> values) {
            addCriterion("balance_cycle not in", values, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleBetween(String value1, String value2) {
            addCriterion("balance_cycle between", value1, value2, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleNotBetween(String value1, String value2) {
            addCriterion("balance_cycle not between", value1, value2, "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andCompensation_idIsNull() {
            addCriterion("compensation_id is null");
            return (Criteria) this;
        }

        public Criteria andCompensation_idIsNotNull() {
            addCriterion("compensation_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompensation_idEqualTo(Long value) {
            addCriterion("compensation_id =", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idNotEqualTo(Long value) {
            addCriterion("compensation_id <>", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idGreaterThan(Long value) {
            addCriterion("compensation_id >", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idGreaterThanOrEqualTo(Long value) {
            addCriterion("compensation_id >=", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idLessThan(Long value) {
            addCriterion("compensation_id <", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idLessThanOrEqualTo(Long value) {
            addCriterion("compensation_id <=", value, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idIn(List<Long> values) {
            addCriterion("compensation_id in", values, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idNotIn(List<Long> values) {
            addCriterion("compensation_id not in", values, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idBetween(Long value1, Long value2) {
            addCriterion("compensation_id between", value1, value2, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andCompensation_idNotBetween(Long value1, Long value2) {
            addCriterion("compensation_id not between", value1, value2, "compensation_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIsNull() {
            addCriterion("pay_order_id is null");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIsNotNull() {
            addCriterion("pay_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andPay_order_idEqualTo(String value) {
            addCriterion("pay_order_id =", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotEqualTo(String value) {
            addCriterion("pay_order_id <>", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idGreaterThan(String value) {
            addCriterion("pay_order_id >", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idGreaterThanOrEqualTo(String value) {
            addCriterion("pay_order_id >=", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLessThan(String value) {
            addCriterion("pay_order_id <", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLessThanOrEqualTo(String value) {
            addCriterion("pay_order_id <=", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLike(String value) {
            addCriterion("pay_order_id like", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotLike(String value) {
            addCriterion("pay_order_id not like", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIn(List<String> values) {
            addCriterion("pay_order_id in", values, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotIn(List<String> values) {
            addCriterion("pay_order_id not in", values, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idBetween(String value1, String value2) {
            addCriterion("pay_order_id between", value1, value2, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotBetween(String value1, String value2) {
            addCriterion("pay_order_id not between", value1, value2, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idIsNull() {
            addCriterion("serviceunit_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idIsNotNull() {
            addCriterion("serviceunit_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idEqualTo(Long value) {
            addCriterion("serviceunit_id =", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idNotEqualTo(Long value) {
            addCriterion("serviceunit_id <>", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idGreaterThan(Long value) {
            addCriterion("serviceunit_id >", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idGreaterThanOrEqualTo(Long value) {
            addCriterion("serviceunit_id >=", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idLessThan(Long value) {
            addCriterion("serviceunit_id <", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idLessThanOrEqualTo(Long value) {
            addCriterion("serviceunit_id <=", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idIn(List<Long> values) {
            addCriterion("serviceunit_id in", values, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idNotIn(List<Long> values) {
            addCriterion("serviceunit_id not in", values, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idBetween(Long value1, Long value2) {
            addCriterion("serviceunit_id between", value1, value2, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idNotBetween(Long value1, Long value2) {
            addCriterion("serviceunit_id not between", value1, value2, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andOrder_nameIsNull() {
            addCriterion("order_name is null");
            return (Criteria) this;
        }

        public Criteria andOrder_nameIsNotNull() {
            addCriterion("order_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_nameEqualTo(String value) {
            addCriterion("order_name =", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameNotEqualTo(String value) {
            addCriterion("order_name <>", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameGreaterThan(String value) {
            addCriterion("order_name >", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameGreaterThanOrEqualTo(String value) {
            addCriterion("order_name >=", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameLessThan(String value) {
            addCriterion("order_name <", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameLessThanOrEqualTo(String value) {
            addCriterion("order_name <=", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameLike(String value) {
            addCriterion("order_name like", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameNotLike(String value) {
            addCriterion("order_name not like", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameIn(List<String> values) {
            addCriterion("order_name in", values, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameNotIn(List<String> values) {
            addCriterion("order_name not in", values, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameBetween(String value1, String value2) {
            addCriterion("order_name between", value1, value2, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameNotBetween(String value1, String value2) {
            addCriterion("order_name not between", value1, value2, "order_name");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeIsNull() {
            addCriterion("compensation_create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeIsNotNull() {
            addCriterion("compensation_create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeEqualTo(Date value) {
            addCriterion("compensation_create_datetime =", value, "compensation_create_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeNotEqualTo(Date value) {
            addCriterion("compensation_create_datetime <>", value, "compensation_create_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeGreaterThan(Date value) {
            addCriterion("compensation_create_datetime >", value, "compensation_create_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("compensation_create_datetime >=", value, "compensation_create_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeLessThan(Date value) {
            addCriterion("compensation_create_datetime <", value, "compensation_create_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("compensation_create_datetime <=", value, "compensation_create_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeIn(List<Date> values) {
            addCriterion("compensation_create_datetime in", values, "compensation_create_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeNotIn(List<Date> values) {
            addCriterion("compensation_create_datetime not in", values, "compensation_create_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeBetween(Date value1, Date value2) {
            addCriterion("compensation_create_datetime between", value1, value2, "compensation_create_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_create_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("compensation_create_datetime not between", value1, value2, "compensation_create_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeIsNull() {
            addCriterion("compensation_confirm_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeIsNotNull() {
            addCriterion("compensation_confirm_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeEqualTo(Date value) {
            addCriterion("compensation_confirm_datetime =", value, "compensation_confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeNotEqualTo(Date value) {
            addCriterion("compensation_confirm_datetime <>", value, "compensation_confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeGreaterThan(Date value) {
            addCriterion("compensation_confirm_datetime >", value, "compensation_confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("compensation_confirm_datetime >=", value, "compensation_confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeLessThan(Date value) {
            addCriterion("compensation_confirm_datetime <", value, "compensation_confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("compensation_confirm_datetime <=", value, "compensation_confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeIn(List<Date> values) {
            addCriterion("compensation_confirm_datetime in", values, "compensation_confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeNotIn(List<Date> values) {
            addCriterion("compensation_confirm_datetime not in", values, "compensation_confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeBetween(Date value1, Date value2) {
            addCriterion("compensation_confirm_datetime between", value1, value2, "compensation_confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andCompensation_confirm_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("compensation_confirm_datetime not between", value1, value2, "compensation_confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountIsNull() {
            addCriterion("partner_bear_amount is null");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountIsNotNull() {
            addCriterion("partner_bear_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountEqualTo(Integer value) {
            addCriterion("partner_bear_amount =", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountNotEqualTo(Integer value) {
            addCriterion("partner_bear_amount <>", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountGreaterThan(Integer value) {
            addCriterion("partner_bear_amount >", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("partner_bear_amount >=", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountLessThan(Integer value) {
            addCriterion("partner_bear_amount <", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountLessThanOrEqualTo(Integer value) {
            addCriterion("partner_bear_amount <=", value, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountIn(List<Integer> values) {
            addCriterion("partner_bear_amount in", values, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountNotIn(List<Integer> values) {
            addCriterion("partner_bear_amount not in", values, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountBetween(Integer value1, Integer value2) {
            addCriterion("partner_bear_amount between", value1, value2, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("partner_bear_amount not between", value1, value2, "partner_bear_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountIsNull() {
            addCriterion("partner_bear_coupon_amount is null");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountIsNotNull() {
            addCriterion("partner_bear_coupon_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountEqualTo(Integer value) {
            addCriterion("partner_bear_coupon_amount =", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountNotEqualTo(Integer value) {
            addCriterion("partner_bear_coupon_amount <>", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountGreaterThan(Integer value) {
            addCriterion("partner_bear_coupon_amount >", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("partner_bear_coupon_amount >=", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountLessThan(Integer value) {
            addCriterion("partner_bear_coupon_amount <", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountLessThanOrEqualTo(Integer value) {
            addCriterion("partner_bear_coupon_amount <=", value, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountIn(List<Integer> values) {
            addCriterion("partner_bear_coupon_amount in", values, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountNotIn(List<Integer> values) {
            addCriterion("partner_bear_coupon_amount not in", values, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountBetween(Integer value1, Integer value2) {
            addCriterion("partner_bear_coupon_amount between", value1, value2, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andPartner_bear_coupon_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("partner_bear_coupon_amount not between", value1, value2, "partner_bear_coupon_amount");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNull() {
            addCriterion("coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIsNotNull() {
            addCriterion("coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_idEqualTo(Long value) {
            addCriterion("coupon_id =", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotEqualTo(Long value) {
            addCriterion("coupon_id <>", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThan(Long value) {
            addCriterion("coupon_id >", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_id >=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThan(Long value) {
            addCriterion("coupon_id <", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idLessThanOrEqualTo(Long value) {
            addCriterion("coupon_id <=", value, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idIn(List<Long> values) {
            addCriterion("coupon_id in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotIn(List<Long> values) {
            addCriterion("coupon_id not in", values, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idBetween(Long value1, Long value2) {
            addCriterion("coupon_id between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_idNotBetween(Long value1, Long value2) {
            addCriterion("coupon_id not between", value1, value2, "coupon_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idIsNull() {
            addCriterion("coupon_receive_id is null");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idIsNotNull() {
            addCriterion("coupon_receive_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idEqualTo(Long value) {
            addCriterion("coupon_receive_id =", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idNotEqualTo(Long value) {
            addCriterion("coupon_receive_id <>", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idGreaterThan(Long value) {
            addCriterion("coupon_receive_id >", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_receive_id >=", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idLessThan(Long value) {
            addCriterion("coupon_receive_id <", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idLessThanOrEqualTo(Long value) {
            addCriterion("coupon_receive_id <=", value, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idIn(List<Long> values) {
            addCriterion("coupon_receive_id in", values, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idNotIn(List<Long> values) {
            addCriterion("coupon_receive_id not in", values, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idBetween(Long value1, Long value2) {
            addCriterion("coupon_receive_id between", value1, value2, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andCoupon_receive_idNotBetween(Long value1, Long value2) {
            addCriterion("coupon_receive_id not between", value1, value2, "coupon_receive_id");
            return (Criteria) this;
        }

        public Criteria andPrice_totalIsNull() {
            addCriterion("price_total is null");
            return (Criteria) this;
        }

        public Criteria andPrice_totalIsNotNull() {
            addCriterion("price_total is not null");
            return (Criteria) this;
        }

        public Criteria andPrice_totalEqualTo(Integer value) {
            addCriterion("price_total =", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalNotEqualTo(Integer value) {
            addCriterion("price_total <>", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalGreaterThan(Integer value) {
            addCriterion("price_total >", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalGreaterThanOrEqualTo(Integer value) {
            addCriterion("price_total >=", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalLessThan(Integer value) {
            addCriterion("price_total <", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalLessThanOrEqualTo(Integer value) {
            addCriterion("price_total <=", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalIn(List<Integer> values) {
            addCriterion("price_total in", values, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalNotIn(List<Integer> values) {
            addCriterion("price_total not in", values, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalBetween(Integer value1, Integer value2) {
            addCriterion("price_total between", value1, value2, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalNotBetween(Integer value1, Integer value2) {
            addCriterion("price_total not between", value1, value2, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_discountIsNull() {
            addCriterion("price_discount is null");
            return (Criteria) this;
        }

        public Criteria andPrice_discountIsNotNull() {
            addCriterion("price_discount is not null");
            return (Criteria) this;
        }

        public Criteria andPrice_discountEqualTo(Integer value) {
            addCriterion("price_discount =", value, "price_discount");
            return (Criteria) this;
        }

        public Criteria andPrice_discountNotEqualTo(Integer value) {
            addCriterion("price_discount <>", value, "price_discount");
            return (Criteria) this;
        }

        public Criteria andPrice_discountGreaterThan(Integer value) {
            addCriterion("price_discount >", value, "price_discount");
            return (Criteria) this;
        }

        public Criteria andPrice_discountGreaterThanOrEqualTo(Integer value) {
            addCriterion("price_discount >=", value, "price_discount");
            return (Criteria) this;
        }

        public Criteria andPrice_discountLessThan(Integer value) {
            addCriterion("price_discount <", value, "price_discount");
            return (Criteria) this;
        }

        public Criteria andPrice_discountLessThanOrEqualTo(Integer value) {
            addCriterion("price_discount <=", value, "price_discount");
            return (Criteria) this;
        }

        public Criteria andPrice_discountIn(List<Integer> values) {
            addCriterion("price_discount in", values, "price_discount");
            return (Criteria) this;
        }

        public Criteria andPrice_discountNotIn(List<Integer> values) {
            addCriterion("price_discount not in", values, "price_discount");
            return (Criteria) this;
        }

        public Criteria andPrice_discountBetween(Integer value1, Integer value2) {
            addCriterion("price_discount between", value1, value2, "price_discount");
            return (Criteria) this;
        }

        public Criteria andPrice_discountNotBetween(Integer value1, Integer value2) {
            addCriterion("price_discount not between", value1, value2, "price_discount");
            return (Criteria) this;
        }

        public Criteria andPrice_payIsNull() {
            addCriterion("price_pay is null");
            return (Criteria) this;
        }

        public Criteria andPrice_payIsNotNull() {
            addCriterion("price_pay is not null");
            return (Criteria) this;
        }

        public Criteria andPrice_payEqualTo(Integer value) {
            addCriterion("price_pay =", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payNotEqualTo(Integer value) {
            addCriterion("price_pay <>", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payGreaterThan(Integer value) {
            addCriterion("price_pay >", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payGreaterThanOrEqualTo(Integer value) {
            addCriterion("price_pay >=", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payLessThan(Integer value) {
            addCriterion("price_pay <", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payLessThanOrEqualTo(Integer value) {
            addCriterion("price_pay <=", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payIn(List<Integer> values) {
            addCriterion("price_pay in", values, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payNotIn(List<Integer> values) {
            addCriterion("price_pay not in", values, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payBetween(Integer value1, Integer value2) {
            addCriterion("price_pay between", value1, value2, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payNotBetween(Integer value1, Integer value2) {
            addCriterion("price_pay not between", value1, value2, "price_pay");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Integer value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Integer value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Integer value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Integer value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Integer value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Integer> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Integer> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Integer value1, Integer value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andPartner_idIsNull() {
            addCriterion("partner_id is null");
            return (Criteria) this;
        }

        public Criteria andPartner_idIsNotNull() {
            addCriterion("partner_id is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_idEqualTo(Long value) {
            addCriterion("partner_id =", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotEqualTo(Long value) {
            addCriterion("partner_id <>", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idGreaterThan(Long value) {
            addCriterion("partner_id >", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idGreaterThanOrEqualTo(Long value) {
            addCriterion("partner_id >=", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idLessThan(Long value) {
            addCriterion("partner_id <", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idLessThanOrEqualTo(Long value) {
            addCriterion("partner_id <=", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idIn(List<Long> values) {
            addCriterion("partner_id in", values, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotIn(List<Long> values) {
            addCriterion("partner_id not in", values, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idBetween(Long value1, Long value2) {
            addCriterion("partner_id between", value1, value2, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotBetween(Long value1, Long value2) {
            addCriterion("partner_id not between", value1, value2, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_nameIsNull() {
            addCriterion("partner_name is null");
            return (Criteria) this;
        }

        public Criteria andPartner_nameIsNotNull() {
            addCriterion("partner_name is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_nameEqualTo(String value) {
            addCriterion("partner_name =", value, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameNotEqualTo(String value) {
            addCriterion("partner_name <>", value, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameGreaterThan(String value) {
            addCriterion("partner_name >", value, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameGreaterThanOrEqualTo(String value) {
            addCriterion("partner_name >=", value, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameLessThan(String value) {
            addCriterion("partner_name <", value, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameLessThanOrEqualTo(String value) {
            addCriterion("partner_name <=", value, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameLike(String value) {
            addCriterion("partner_name like", value, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameNotLike(String value) {
            addCriterion("partner_name not like", value, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameIn(List<String> values) {
            addCriterion("partner_name in", values, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameNotIn(List<String> values) {
            addCriterion("partner_name not in", values, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameBetween(String value1, String value2) {
            addCriterion("partner_name between", value1, value2, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameNotBetween(String value1, String value2) {
            addCriterion("partner_name not between", value1, value2, "partner_name");
            return (Criteria) this;
        }

        public Criteria andPartner_levelIsNull() {
            addCriterion("partner_level is null");
            return (Criteria) this;
        }

        public Criteria andPartner_levelIsNotNull() {
            addCriterion("partner_level is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_levelEqualTo(Integer value) {
            addCriterion("partner_level =", value, "partner_level");
            return (Criteria) this;
        }

        public Criteria andPartner_levelNotEqualTo(Integer value) {
            addCriterion("partner_level <>", value, "partner_level");
            return (Criteria) this;
        }

        public Criteria andPartner_levelGreaterThan(Integer value) {
            addCriterion("partner_level >", value, "partner_level");
            return (Criteria) this;
        }

        public Criteria andPartner_levelGreaterThanOrEqualTo(Integer value) {
            addCriterion("partner_level >=", value, "partner_level");
            return (Criteria) this;
        }

        public Criteria andPartner_levelLessThan(Integer value) {
            addCriterion("partner_level <", value, "partner_level");
            return (Criteria) this;
        }

        public Criteria andPartner_levelLessThanOrEqualTo(Integer value) {
            addCriterion("partner_level <=", value, "partner_level");
            return (Criteria) this;
        }

        public Criteria andPartner_levelIn(List<Integer> values) {
            addCriterion("partner_level in", values, "partner_level");
            return (Criteria) this;
        }

        public Criteria andPartner_levelNotIn(List<Integer> values) {
            addCriterion("partner_level not in", values, "partner_level");
            return (Criteria) this;
        }

        public Criteria andPartner_levelBetween(Integer value1, Integer value2) {
            addCriterion("partner_level between", value1, value2, "partner_level");
            return (Criteria) this;
        }

        public Criteria andPartner_levelNotBetween(Integer value1, Integer value2) {
            addCriterion("partner_level not between", value1, value2, "partner_level");
            return (Criteria) this;
        }

        public Criteria andCooperation_startIsNull() {
            addCriterion("cooperation_start is null");
            return (Criteria) this;
        }

        public Criteria andCooperation_startIsNotNull() {
            addCriterion("cooperation_start is not null");
            return (Criteria) this;
        }

        public Criteria andCooperation_startEqualTo(Date value) {
            addCriterion("cooperation_start =", value, "cooperation_start");
            return (Criteria) this;
        }

        public Criteria andCooperation_startNotEqualTo(Date value) {
            addCriterion("cooperation_start <>", value, "cooperation_start");
            return (Criteria) this;
        }

        public Criteria andCooperation_startGreaterThan(Date value) {
            addCriterion("cooperation_start >", value, "cooperation_start");
            return (Criteria) this;
        }

        public Criteria andCooperation_startGreaterThanOrEqualTo(Date value) {
            addCriterion("cooperation_start >=", value, "cooperation_start");
            return (Criteria) this;
        }

        public Criteria andCooperation_startLessThan(Date value) {
            addCriterion("cooperation_start <", value, "cooperation_start");
            return (Criteria) this;
        }

        public Criteria andCooperation_startLessThanOrEqualTo(Date value) {
            addCriterion("cooperation_start <=", value, "cooperation_start");
            return (Criteria) this;
        }

        public Criteria andCooperation_startIn(List<Date> values) {
            addCriterion("cooperation_start in", values, "cooperation_start");
            return (Criteria) this;
        }

        public Criteria andCooperation_startNotIn(List<Date> values) {
            addCriterion("cooperation_start not in", values, "cooperation_start");
            return (Criteria) this;
        }

        public Criteria andCooperation_startBetween(Date value1, Date value2) {
            addCriterion("cooperation_start between", value1, value2, "cooperation_start");
            return (Criteria) this;
        }

        public Criteria andCooperation_startNotBetween(Date value1, Date value2) {
            addCriterion("cooperation_start not between", value1, value2, "cooperation_start");
            return (Criteria) this;
        }

        public Criteria andCooperation_endIsNull() {
            addCriterion("cooperation_end is null");
            return (Criteria) this;
        }

        public Criteria andCooperation_endIsNotNull() {
            addCriterion("cooperation_end is not null");
            return (Criteria) this;
        }

        public Criteria andCooperation_endEqualTo(Date value) {
            addCriterion("cooperation_end =", value, "cooperation_end");
            return (Criteria) this;
        }

        public Criteria andCooperation_endNotEqualTo(Date value) {
            addCriterion("cooperation_end <>", value, "cooperation_end");
            return (Criteria) this;
        }

        public Criteria andCooperation_endGreaterThan(Date value) {
            addCriterion("cooperation_end >", value, "cooperation_end");
            return (Criteria) this;
        }

        public Criteria andCooperation_endGreaterThanOrEqualTo(Date value) {
            addCriterion("cooperation_end >=", value, "cooperation_end");
            return (Criteria) this;
        }

        public Criteria andCooperation_endLessThan(Date value) {
            addCriterion("cooperation_end <", value, "cooperation_end");
            return (Criteria) this;
        }

        public Criteria andCooperation_endLessThanOrEqualTo(Date value) {
            addCriterion("cooperation_end <=", value, "cooperation_end");
            return (Criteria) this;
        }

        public Criteria andCooperation_endIn(List<Date> values) {
            addCriterion("cooperation_end in", values, "cooperation_end");
            return (Criteria) this;
        }

        public Criteria andCooperation_endNotIn(List<Date> values) {
            addCriterion("cooperation_end not in", values, "cooperation_end");
            return (Criteria) this;
        }

        public Criteria andCooperation_endBetween(Date value1, Date value2) {
            addCriterion("cooperation_end between", value1, value2, "cooperation_end");
            return (Criteria) this;
        }

        public Criteria andCooperation_endNotBetween(Date value1, Date value2) {
            addCriterion("cooperation_end not between", value1, value2, "cooperation_end");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeIsNull() {
            addCriterion("order_create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeIsNotNull() {
            addCriterion("order_create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeEqualTo(Date value) {
            addCriterion("order_create_datetime =", value, "order_create_datetime");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeNotEqualTo(Date value) {
            addCriterion("order_create_datetime <>", value, "order_create_datetime");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeGreaterThan(Date value) {
            addCriterion("order_create_datetime >", value, "order_create_datetime");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_create_datetime >=", value, "order_create_datetime");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeLessThan(Date value) {
            addCriterion("order_create_datetime <", value, "order_create_datetime");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("order_create_datetime <=", value, "order_create_datetime");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeIn(List<Date> values) {
            addCriterion("order_create_datetime in", values, "order_create_datetime");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeNotIn(List<Date> values) {
            addCriterion("order_create_datetime not in", values, "order_create_datetime");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeBetween(Date value1, Date value2) {
            addCriterion("order_create_datetime between", value1, value2, "order_create_datetime");
            return (Criteria) this;
        }

        public Criteria andOrder_create_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("order_create_datetime not between", value1, value2, "order_create_datetime");
            return (Criteria) this;
        }

        public Criteria andBalance_cycleLikeInsensitive(String value) {
            addCriterion("upper(balance_cycle) like", value.toUpperCase(), "balance_cycle");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLikeInsensitive(String value) {
            addCriterion("upper(pay_order_id) like", value.toUpperCase(), "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_nameLikeInsensitive(String value) {
            addCriterion("upper(order_name) like", value.toUpperCase(), "order_name");
            return (Criteria) this;
        }

        public Criteria andPartner_nameLikeInsensitive(String value) {
            addCriterion("upper(partner_name) like", value.toUpperCase(), "partner_name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fallinto_compensation
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 27 13:58:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table fallinto_compensation
     *
     * @mbg.generated Wed Jun 27 13:58:59 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	赔偿结算
		//--------------------------------------------------					
													fallinto_compensation_id(1,Types.BIGINT,false),
		/** 结算期 */								balance_cycle(2,Types.VARCHAR,false),
		/** 赔偿id */								compensation_id(2,Types.BIGINT,false),
		/** 订单号 */								pay_order_id(2,Types.VARCHAR,false),
		/** 服务单号 */								serviceunit_id(2,Types.BIGINT,false),
		/** 订单名称 */								order_name(2,Types.VARCHAR,false),
		/** 赔偿创建时间 */							compensation_create_datetime(2,Types.TIMESTAMP,false),
		/** 赔偿完成时间 */							compensation_confirm_datetime(2,Types.TIMESTAMP,false),
		/** 合伙人赔偿金额 */						partner_bear_amount(2,Types.INTEGER,false),
		/** 合伙人承担卷额 */						partner_bear_coupon_amount(2,Types.INTEGER,false),
		/** 优惠卷id */								coupon_id(2,Types.BIGINT,false),
		/** 优惠卷领用id */							coupon_receive_id(2,Types.BIGINT,false),
		/** 订单总价  单位分 */						price_total(2,Types.INTEGER,false),
		/** 优惠金额，单位分 */						price_discount(2,Types.INTEGER,false),
		/** 实际支付金额 单位分 */					price_pay(2,Types.INTEGER,false),
		/** 赔偿金额 单位分 */						amount(2,Types.INTEGER,false),
		/** 合伙人id */								partner_id(2,Types.BIGINT,false),
		/** 合伙人名称 */							partner_name(2,Types.VARCHAR,false),
		/** 合伙人级别 */							partner_level(2,Types.INTEGER,false),
		/** 合作开始日期 */							cooperation_start(2,Types.TIMESTAMP,false),
		/** 合作结束日期 */							cooperation_end(2,Types.TIMESTAMP,false),
		/** 1 待结算  2 已结算  3 挂起 */			status(2,Types.INTEGER,false),
		/** 订单创建时间 */							order_create_datetime(2,Types.TIMESTAMP,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}