package com.aobei.train.model;

import com.aobei.train.model.FineMoneyExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class FineMoneyExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine_money
     *
     * @mbg.generated Wed Jun 20 16:07:23 CST 2018
     */
    public FineMoneyExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine_money
     *
     * @mbg.generated Wed Jun 20 16:07:23 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine_money
     *
     * @mbg.generated Wed Jun 20 16:07:23 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fine_money
     *
     * @mbg.generated Wed Jun 20 16:07:23 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fine_money
     *
     * @mbg.generated Wed Jun 20 16:07:23 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andFine_money_idIsNull() {
            addCriterion("fine_money_id is null");
            return (Criteria) this;
        }

        public Criteria andFine_money_idIsNotNull() {
            addCriterion("fine_money_id is not null");
            return (Criteria) this;
        }

        public Criteria andFine_money_idEqualTo(Long value) {
            addCriterion("fine_money_id =", value, "fine_money_id");
            return (Criteria) this;
        }

        public Criteria andFine_money_idNotEqualTo(Long value) {
            addCriterion("fine_money_id <>", value, "fine_money_id");
            return (Criteria) this;
        }

        public Criteria andFine_money_idGreaterThan(Long value) {
            addCriterion("fine_money_id >", value, "fine_money_id");
            return (Criteria) this;
        }

        public Criteria andFine_money_idGreaterThanOrEqualTo(Long value) {
            addCriterion("fine_money_id >=", value, "fine_money_id");
            return (Criteria) this;
        }

        public Criteria andFine_money_idLessThan(Long value) {
            addCriterion("fine_money_id <", value, "fine_money_id");
            return (Criteria) this;
        }

        public Criteria andFine_money_idLessThanOrEqualTo(Long value) {
            addCriterion("fine_money_id <=", value, "fine_money_id");
            return (Criteria) this;
        }

        public Criteria andFine_money_idIn(List<Long> values) {
            addCriterion("fine_money_id in", values, "fine_money_id");
            return (Criteria) this;
        }

        public Criteria andFine_money_idNotIn(List<Long> values) {
            addCriterion("fine_money_id not in", values, "fine_money_id");
            return (Criteria) this;
        }

        public Criteria andFine_money_idBetween(Long value1, Long value2) {
            addCriterion("fine_money_id between", value1, value2, "fine_money_id");
            return (Criteria) this;
        }

        public Criteria andFine_money_idNotBetween(Long value1, Long value2) {
            addCriterion("fine_money_id not between", value1, value2, "fine_money_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIsNull() {
            addCriterion("pay_order_id is null");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIsNotNull() {
            addCriterion("pay_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andPay_order_idEqualTo(String value) {
            addCriterion("pay_order_id =", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotEqualTo(String value) {
            addCriterion("pay_order_id <>", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idGreaterThan(String value) {
            addCriterion("pay_order_id >", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idGreaterThanOrEqualTo(String value) {
            addCriterion("pay_order_id >=", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLessThan(String value) {
            addCriterion("pay_order_id <", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLessThanOrEqualTo(String value) {
            addCriterion("pay_order_id <=", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLike(String value) {
            addCriterion("pay_order_id like", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotLike(String value) {
            addCriterion("pay_order_id not like", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIn(List<String> values) {
            addCriterion("pay_order_id in", values, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotIn(List<String> values) {
            addCriterion("pay_order_id not in", values, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idBetween(String value1, String value2) {
            addCriterion("pay_order_id between", value1, value2, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotBetween(String value1, String value2) {
            addCriterion("pay_order_id not between", value1, value2, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idIsNull() {
            addCriterion("serviceunit_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idIsNotNull() {
            addCriterion("serviceunit_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idEqualTo(Long value) {
            addCriterion("serviceunit_id =", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idNotEqualTo(Long value) {
            addCriterion("serviceunit_id <>", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idGreaterThan(Long value) {
            addCriterion("serviceunit_id >", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idGreaterThanOrEqualTo(Long value) {
            addCriterion("serviceunit_id >=", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idLessThan(Long value) {
            addCriterion("serviceunit_id <", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idLessThanOrEqualTo(Long value) {
            addCriterion("serviceunit_id <=", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idIn(List<Long> values) {
            addCriterion("serviceunit_id in", values, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idNotIn(List<Long> values) {
            addCriterion("serviceunit_id not in", values, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idBetween(Long value1, Long value2) {
            addCriterion("serviceunit_id between", value1, value2, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idNotBetween(Long value1, Long value2) {
            addCriterion("serviceunit_id not between", value1, value2, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idIsNull() {
            addCriterion("partner_id is null");
            return (Criteria) this;
        }

        public Criteria andPartner_idIsNotNull() {
            addCriterion("partner_id is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_idEqualTo(Long value) {
            addCriterion("partner_id =", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotEqualTo(Long value) {
            addCriterion("partner_id <>", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idGreaterThan(Long value) {
            addCriterion("partner_id >", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idGreaterThanOrEqualTo(Long value) {
            addCriterion("partner_id >=", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idLessThan(Long value) {
            addCriterion("partner_id <", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idLessThanOrEqualTo(Long value) {
            addCriterion("partner_id <=", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idIn(List<Long> values) {
            addCriterion("partner_id in", values, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotIn(List<Long> values) {
            addCriterion("partner_id not in", values, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idBetween(Long value1, Long value2) {
            addCriterion("partner_id between", value1, value2, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotBetween(Long value1, Long value2) {
            addCriterion("partner_id not between", value1, value2, "partner_id");
            return (Criteria) this;
        }

        public Criteria andFine_amountIsNull() {
            addCriterion("fine_amount is null");
            return (Criteria) this;
        }

        public Criteria andFine_amountIsNotNull() {
            addCriterion("fine_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFine_amountEqualTo(Integer value) {
            addCriterion("fine_amount =", value, "fine_amount");
            return (Criteria) this;
        }

        public Criteria andFine_amountNotEqualTo(Integer value) {
            addCriterion("fine_amount <>", value, "fine_amount");
            return (Criteria) this;
        }

        public Criteria andFine_amountGreaterThan(Integer value) {
            addCriterion("fine_amount >", value, "fine_amount");
            return (Criteria) this;
        }

        public Criteria andFine_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("fine_amount >=", value, "fine_amount");
            return (Criteria) this;
        }

        public Criteria andFine_amountLessThan(Integer value) {
            addCriterion("fine_amount <", value, "fine_amount");
            return (Criteria) this;
        }

        public Criteria andFine_amountLessThanOrEqualTo(Integer value) {
            addCriterion("fine_amount <=", value, "fine_amount");
            return (Criteria) this;
        }

        public Criteria andFine_amountIn(List<Integer> values) {
            addCriterion("fine_amount in", values, "fine_amount");
            return (Criteria) this;
        }

        public Criteria andFine_amountNotIn(List<Integer> values) {
            addCriterion("fine_amount not in", values, "fine_amount");
            return (Criteria) this;
        }

        public Criteria andFine_amountBetween(Integer value1, Integer value2) {
            addCriterion("fine_amount between", value1, value2, "fine_amount");
            return (Criteria) this;
        }

        public Criteria andFine_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("fine_amount not between", value1, value2, "fine_amount");
            return (Criteria) this;
        }

        public Criteria andFine_infoIsNull() {
            addCriterion("fine_info is null");
            return (Criteria) this;
        }

        public Criteria andFine_infoIsNotNull() {
            addCriterion("fine_info is not null");
            return (Criteria) this;
        }

        public Criteria andFine_infoEqualTo(String value) {
            addCriterion("fine_info =", value, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoNotEqualTo(String value) {
            addCriterion("fine_info <>", value, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoGreaterThan(String value) {
            addCriterion("fine_info >", value, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoGreaterThanOrEqualTo(String value) {
            addCriterion("fine_info >=", value, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoLessThan(String value) {
            addCriterion("fine_info <", value, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoLessThanOrEqualTo(String value) {
            addCriterion("fine_info <=", value, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoLike(String value) {
            addCriterion("fine_info like", value, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoNotLike(String value) {
            addCriterion("fine_info not like", value, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoIn(List<String> values) {
            addCriterion("fine_info in", values, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoNotIn(List<String> values) {
            addCriterion("fine_info not in", values, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoBetween(String value1, String value2) {
            addCriterion("fine_info between", value1, value2, "fine_info");
            return (Criteria) this;
        }

        public Criteria andFine_infoNotBetween(String value1, String value2) {
            addCriterion("fine_info not between", value1, value2, "fine_info");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andFine_operatorIsNull() {
            addCriterion("fine_operator is null");
            return (Criteria) this;
        }

        public Criteria andFine_operatorIsNotNull() {
            addCriterion("fine_operator is not null");
            return (Criteria) this;
        }

        public Criteria andFine_operatorEqualTo(Long value) {
            addCriterion("fine_operator =", value, "fine_operator");
            return (Criteria) this;
        }

        public Criteria andFine_operatorNotEqualTo(Long value) {
            addCriterion("fine_operator <>", value, "fine_operator");
            return (Criteria) this;
        }

        public Criteria andFine_operatorGreaterThan(Long value) {
            addCriterion("fine_operator >", value, "fine_operator");
            return (Criteria) this;
        }

        public Criteria andFine_operatorGreaterThanOrEqualTo(Long value) {
            addCriterion("fine_operator >=", value, "fine_operator");
            return (Criteria) this;
        }

        public Criteria andFine_operatorLessThan(Long value) {
            addCriterion("fine_operator <", value, "fine_operator");
            return (Criteria) this;
        }

        public Criteria andFine_operatorLessThanOrEqualTo(Long value) {
            addCriterion("fine_operator <=", value, "fine_operator");
            return (Criteria) this;
        }

        public Criteria andFine_operatorIn(List<Long> values) {
            addCriterion("fine_operator in", values, "fine_operator");
            return (Criteria) this;
        }

        public Criteria andFine_operatorNotIn(List<Long> values) {
            addCriterion("fine_operator not in", values, "fine_operator");
            return (Criteria) this;
        }

        public Criteria andFine_operatorBetween(Long value1, Long value2) {
            addCriterion("fine_operator between", value1, value2, "fine_operator");
            return (Criteria) this;
        }

        public Criteria andFine_operatorNotBetween(Long value1, Long value2) {
            addCriterion("fine_operator not between", value1, value2, "fine_operator");
            return (Criteria) this;
        }

        public Criteria andFine_statusIsNull() {
            addCriterion("fine_status is null");
            return (Criteria) this;
        }

        public Criteria andFine_statusIsNotNull() {
            addCriterion("fine_status is not null");
            return (Criteria) this;
        }

        public Criteria andFine_statusEqualTo(Integer value) {
            addCriterion("fine_status =", value, "fine_status");
            return (Criteria) this;
        }

        public Criteria andFine_statusNotEqualTo(Integer value) {
            addCriterion("fine_status <>", value, "fine_status");
            return (Criteria) this;
        }

        public Criteria andFine_statusGreaterThan(Integer value) {
            addCriterion("fine_status >", value, "fine_status");
            return (Criteria) this;
        }

        public Criteria andFine_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("fine_status >=", value, "fine_status");
            return (Criteria) this;
        }

        public Criteria andFine_statusLessThan(Integer value) {
            addCriterion("fine_status <", value, "fine_status");
            return (Criteria) this;
        }

        public Criteria andFine_statusLessThanOrEqualTo(Integer value) {
            addCriterion("fine_status <=", value, "fine_status");
            return (Criteria) this;
        }

        public Criteria andFine_statusIn(List<Integer> values) {
            addCriterion("fine_status in", values, "fine_status");
            return (Criteria) this;
        }

        public Criteria andFine_statusNotIn(List<Integer> values) {
            addCriterion("fine_status not in", values, "fine_status");
            return (Criteria) this;
        }

        public Criteria andFine_statusBetween(Integer value1, Integer value2) {
            addCriterion("fine_status between", value1, value2, "fine_status");
            return (Criteria) this;
        }

        public Criteria andFine_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("fine_status not between", value1, value2, "fine_status");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeIsNull() {
            addCriterion("confirm_datetime is null");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeIsNotNull() {
            addCriterion("confirm_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeEqualTo(Date value) {
            addCriterion("confirm_datetime =", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeNotEqualTo(Date value) {
            addCriterion("confirm_datetime <>", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeGreaterThan(Date value) {
            addCriterion("confirm_datetime >", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("confirm_datetime >=", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeLessThan(Date value) {
            addCriterion("confirm_datetime <", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("confirm_datetime <=", value, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeIn(List<Date> values) {
            addCriterion("confirm_datetime in", values, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeNotIn(List<Date> values) {
            addCriterion("confirm_datetime not in", values, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeBetween(Date value1, Date value2) {
            addCriterion("confirm_datetime between", value1, value2, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("confirm_datetime not between", value1, value2, "confirm_datetime");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorIsNull() {
            addCriterion("confirm_operator is null");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorIsNotNull() {
            addCriterion("confirm_operator is not null");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorEqualTo(Long value) {
            addCriterion("confirm_operator =", value, "confirm_operator");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorNotEqualTo(Long value) {
            addCriterion("confirm_operator <>", value, "confirm_operator");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorGreaterThan(Long value) {
            addCriterion("confirm_operator >", value, "confirm_operator");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorGreaterThanOrEqualTo(Long value) {
            addCriterion("confirm_operator >=", value, "confirm_operator");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorLessThan(Long value) {
            addCriterion("confirm_operator <", value, "confirm_operator");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorLessThanOrEqualTo(Long value) {
            addCriterion("confirm_operator <=", value, "confirm_operator");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorIn(List<Long> values) {
            addCriterion("confirm_operator in", values, "confirm_operator");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorNotIn(List<Long> values) {
            addCriterion("confirm_operator not in", values, "confirm_operator");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorBetween(Long value1, Long value2) {
            addCriterion("confirm_operator between", value1, value2, "confirm_operator");
            return (Criteria) this;
        }

        public Criteria andConfirm_operatorNotBetween(Long value1, Long value2) {
            addCriterion("confirm_operator not between", value1, value2, "confirm_operator");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLikeInsensitive(String value) {
            addCriterion("upper(pay_order_id) like", value.toUpperCase(), "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andFine_infoLikeInsensitive(String value) {
            addCriterion("upper(fine_info) like", value.toUpperCase(), "fine_info");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fine_money
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 20 16:07:23 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table fine_money
     *
     * @mbg.generated Wed Jun 20 16:07:23 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	罚款单表
		//--------------------------------------------------					
													fine_money_id(1,Types.BIGINT,false),
		/** 订单id */								pay_order_id(2,Types.VARCHAR,false),
		/** 服务单id */								serviceunit_id(2,Types.BIGINT,false),
		/** 合伙人id */								partner_id(2,Types.BIGINT,false),
		/** 罚款金额 */								fine_amount(2,Types.INTEGER,false),
		/** 罚款原因 */								fine_info(2,Types.VARCHAR,false),
		/** 罚款申请日期 */							create_datetime(2,Types.TIMESTAMP,false),
		/** 罚款申请人 */							fine_operator(2,Types.BIGINT,false),
		/** 状态   1 待处理 2 完成 3 驳回 */		fine_status(2,Types.INTEGER,false),
		/** 确认时间 */								confirm_datetime(2,Types.TIMESTAMP,false),
		/** 确认人 */								confirm_operator(2,Types.BIGINT,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}