package com.aobei.train.model;

import com.aobei.train.model.InsuranceRegisterExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class InsuranceRegisterExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_register
     *
     * @mbg.generated Mon May 07 17:31:07 CST 2018
     */
    public InsuranceRegisterExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_register
     *
     * @mbg.generated Mon May 07 17:31:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_register
     *
     * @mbg.generated Mon May 07 17:31:07 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance_register
     *
     * @mbg.generated Mon May 07 17:31:07 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table insurance_register
     *
     * @mbg.generated Mon May 07 17:31:07 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andInsurance_register_idIsNull() {
            addCriterion("insurance_register_id is null");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idIsNotNull() {
            addCriterion("insurance_register_id is not null");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idEqualTo(Long value) {
            addCriterion("insurance_register_id =", value, "insurance_register_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idNotEqualTo(Long value) {
            addCriterion("insurance_register_id <>", value, "insurance_register_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idGreaterThan(Long value) {
            addCriterion("insurance_register_id >", value, "insurance_register_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idGreaterThanOrEqualTo(Long value) {
            addCriterion("insurance_register_id >=", value, "insurance_register_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idLessThan(Long value) {
            addCriterion("insurance_register_id <", value, "insurance_register_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idLessThanOrEqualTo(Long value) {
            addCriterion("insurance_register_id <=", value, "insurance_register_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idIn(List<Long> values) {
            addCriterion("insurance_register_id in", values, "insurance_register_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idNotIn(List<Long> values) {
            addCriterion("insurance_register_id not in", values, "insurance_register_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idBetween(Long value1, Long value2) {
            addCriterion("insurance_register_id between", value1, value2, "insurance_register_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_register_idNotBetween(Long value1, Long value2) {
            addCriterion("insurance_register_id not between", value1, value2, "insurance_register_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_idIsNull() {
            addCriterion("insurance_id is null");
            return (Criteria) this;
        }

        public Criteria andInsurance_idIsNotNull() {
            addCriterion("insurance_id is not null");
            return (Criteria) this;
        }

        public Criteria andInsurance_idEqualTo(Long value) {
            addCriterion("insurance_id =", value, "insurance_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_idNotEqualTo(Long value) {
            addCriterion("insurance_id <>", value, "insurance_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_idGreaterThan(Long value) {
            addCriterion("insurance_id >", value, "insurance_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_idGreaterThanOrEqualTo(Long value) {
            addCriterion("insurance_id >=", value, "insurance_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_idLessThan(Long value) {
            addCriterion("insurance_id <", value, "insurance_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_idLessThanOrEqualTo(Long value) {
            addCriterion("insurance_id <=", value, "insurance_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_idIn(List<Long> values) {
            addCriterion("insurance_id in", values, "insurance_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_idNotIn(List<Long> values) {
            addCriterion("insurance_id not in", values, "insurance_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_idBetween(Long value1, Long value2) {
            addCriterion("insurance_id between", value1, value2, "insurance_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_idNotBetween(Long value1, Long value2) {
            addCriterion("insurance_id not between", value1, value2, "insurance_id");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameIsNull() {
            addCriterion("insurance_name is null");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameIsNotNull() {
            addCriterion("insurance_name is not null");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameEqualTo(String value) {
            addCriterion("insurance_name =", value, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameNotEqualTo(String value) {
            addCriterion("insurance_name <>", value, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameGreaterThan(String value) {
            addCriterion("insurance_name >", value, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameGreaterThanOrEqualTo(String value) {
            addCriterion("insurance_name >=", value, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameLessThan(String value) {
            addCriterion("insurance_name <", value, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameLessThanOrEqualTo(String value) {
            addCriterion("insurance_name <=", value, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameLike(String value) {
            addCriterion("insurance_name like", value, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameNotLike(String value) {
            addCriterion("insurance_name not like", value, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameIn(List<String> values) {
            addCriterion("insurance_name in", values, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameNotIn(List<String> values) {
            addCriterion("insurance_name not in", values, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameBetween(String value1, String value2) {
            addCriterion("insurance_name between", value1, value2, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameNotBetween(String value1, String value2) {
            addCriterion("insurance_name not between", value1, value2, "insurance_name");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Long value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Long value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Long value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Long value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Long value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Long value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Long> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Long> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Long value1, Long value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Long value1, Long value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeIsNull() {
            addCriterion("start_datetime is null");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeIsNotNull() {
            addCriterion("start_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeEqualTo(Date value) {
            addCriterion("start_datetime =", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeNotEqualTo(Date value) {
            addCriterion("start_datetime <>", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeGreaterThan(Date value) {
            addCriterion("start_datetime >", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_datetime >=", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeLessThan(Date value) {
            addCriterion("start_datetime <", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("start_datetime <=", value, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeIn(List<Date> values) {
            addCriterion("start_datetime in", values, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeNotIn(List<Date> values) {
            addCriterion("start_datetime not in", values, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeBetween(Date value1, Date value2) {
            addCriterion("start_datetime between", value1, value2, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andStart_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("start_datetime not between", value1, value2, "start_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeIsNull() {
            addCriterion("end_datetime is null");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeIsNotNull() {
            addCriterion("end_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeEqualTo(Date value) {
            addCriterion("end_datetime =", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeNotEqualTo(Date value) {
            addCriterion("end_datetime <>", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeGreaterThan(Date value) {
            addCriterion("end_datetime >", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_datetime >=", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeLessThan(Date value) {
            addCriterion("end_datetime <", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("end_datetime <=", value, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeIn(List<Date> values) {
            addCriterion("end_datetime in", values, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeNotIn(List<Date> values) {
            addCriterion("end_datetime not in", values, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeBetween(Date value1, Date value2) {
            addCriterion("end_datetime between", value1, value2, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andEnd_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("end_datetime not between", value1, value2, "end_datetime");
            return (Criteria) this;
        }

        public Criteria andInsurance_nameLikeInsensitive(String value) {
            addCriterion("upper(insurance_name) like", value.toUpperCase(), "insurance_name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table insurance_register
     *
     * @mbg.generated do_not_delete_during_merge Mon May 07 17:31:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table insurance_register
     *
     * @mbg.generated Mon May 07 17:31:07 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	保险登记
		//--------------------------------------------------					
									insurance_register_id(1,Types.BIGINT,false),
		/** 保险id */				insurance_id(2,Types.BIGINT,false),
		/** 保险名称 */				insurance_name(2,Types.VARCHAR,false),
		/** 用户id */				uid(2,Types.BIGINT,false),
		/** 1 学员 */				type(2,Types.INTEGER,false),
		/** 创建时间 */				create_datetime(2,Types.TIMESTAMP,false),
		/** 保险开始时间 */			start_datetime(2,Types.TIMESTAMP,false),
		/** 保险结束时间 */			end_datetime(2,Types.TIMESTAMP,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}