package com.aobei.train.model;

import com.aobei.train.model.JdOrderExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class JdOrderExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_jd
     *
     * @mbg.generated Thu Jul 12 20:17:02 CST 2018
     */
    public JdOrderExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_jd
     *
     * @mbg.generated Thu Jul 12 20:17:02 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_jd
     *
     * @mbg.generated Thu Jul 12 20:17:02 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_jd
     *
     * @mbg.generated Thu Jul 12 20:17:02 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_order_jd
     *
     * @mbg.generated Thu Jul 12 20:17:02 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andPay_order_jd_idIsNull() {
            addCriterion("pay_order_jd_id is null");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idIsNotNull() {
            addCriterion("pay_order_jd_id is not null");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idEqualTo(String value) {
            addCriterion("pay_order_jd_id =", value, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idNotEqualTo(String value) {
            addCriterion("pay_order_jd_id <>", value, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idGreaterThan(String value) {
            addCriterion("pay_order_jd_id >", value, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idGreaterThanOrEqualTo(String value) {
            addCriterion("pay_order_jd_id >=", value, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idLessThan(String value) {
            addCriterion("pay_order_jd_id <", value, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idLessThanOrEqualTo(String value) {
            addCriterion("pay_order_jd_id <=", value, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idLike(String value) {
            addCriterion("pay_order_jd_id like", value, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idNotLike(String value) {
            addCriterion("pay_order_jd_id not like", value, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idIn(List<String> values) {
            addCriterion("pay_order_jd_id in", values, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idNotIn(List<String> values) {
            addCriterion("pay_order_jd_id not in", values, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idBetween(String value1, String value2) {
            addCriterion("pay_order_jd_id between", value1, value2, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idNotBetween(String value1, String value2) {
            addCriterion("pay_order_jd_id not between", value1, value2, "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceIsNull() {
            addCriterion("orderTotalPrice is null");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceIsNotNull() {
            addCriterion("orderTotalPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceEqualTo(String value) {
            addCriterion("orderTotalPrice =", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceNotEqualTo(String value) {
            addCriterion("orderTotalPrice <>", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceGreaterThan(String value) {
            addCriterion("orderTotalPrice >", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceGreaterThanOrEqualTo(String value) {
            addCriterion("orderTotalPrice >=", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceLessThan(String value) {
            addCriterion("orderTotalPrice <", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceLessThanOrEqualTo(String value) {
            addCriterion("orderTotalPrice <=", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceLike(String value) {
            addCriterion("orderTotalPrice like", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceNotLike(String value) {
            addCriterion("orderTotalPrice not like", value, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceIn(List<String> values) {
            addCriterion("orderTotalPrice in", values, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceNotIn(List<String> values) {
            addCriterion("orderTotalPrice not in", values, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceBetween(String value1, String value2) {
            addCriterion("orderTotalPrice between", value1, value2, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceNotBetween(String value1, String value2) {
            addCriterion("orderTotalPrice not between", value1, value2, "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceIsNull() {
            addCriterion("orderSellerPrice is null");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceIsNotNull() {
            addCriterion("orderSellerPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceEqualTo(String value) {
            addCriterion("orderSellerPrice =", value, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceNotEqualTo(String value) {
            addCriterion("orderSellerPrice <>", value, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceGreaterThan(String value) {
            addCriterion("orderSellerPrice >", value, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceGreaterThanOrEqualTo(String value) {
            addCriterion("orderSellerPrice >=", value, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceLessThan(String value) {
            addCriterion("orderSellerPrice <", value, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceLessThanOrEqualTo(String value) {
            addCriterion("orderSellerPrice <=", value, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceLike(String value) {
            addCriterion("orderSellerPrice like", value, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceNotLike(String value) {
            addCriterion("orderSellerPrice not like", value, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceIn(List<String> values) {
            addCriterion("orderSellerPrice in", values, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceNotIn(List<String> values) {
            addCriterion("orderSellerPrice not in", values, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceBetween(String value1, String value2) {
            addCriterion("orderSellerPrice between", value1, value2, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceNotBetween(String value1, String value2) {
            addCriterion("orderSellerPrice not between", value1, value2, "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentIsNull() {
            addCriterion("orderPayment is null");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentIsNotNull() {
            addCriterion("orderPayment is not null");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentEqualTo(String value) {
            addCriterion("orderPayment =", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentNotEqualTo(String value) {
            addCriterion("orderPayment <>", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentGreaterThan(String value) {
            addCriterion("orderPayment >", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentGreaterThanOrEqualTo(String value) {
            addCriterion("orderPayment >=", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentLessThan(String value) {
            addCriterion("orderPayment <", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentLessThanOrEqualTo(String value) {
            addCriterion("orderPayment <=", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentLike(String value) {
            addCriterion("orderPayment like", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentNotLike(String value) {
            addCriterion("orderPayment not like", value, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentIn(List<String> values) {
            addCriterion("orderPayment in", values, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentNotIn(List<String> values) {
            addCriterion("orderPayment not in", values, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentBetween(String value1, String value2) {
            addCriterion("orderPayment between", value1, value2, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentNotBetween(String value1, String value2) {
            addCriterion("orderPayment not between", value1, value2, "orderPayment");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountIsNull() {
            addCriterion("sellerDiscount is null");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountIsNotNull() {
            addCriterion("sellerDiscount is not null");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountEqualTo(String value) {
            addCriterion("sellerDiscount =", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountNotEqualTo(String value) {
            addCriterion("sellerDiscount <>", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountGreaterThan(String value) {
            addCriterion("sellerDiscount >", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountGreaterThanOrEqualTo(String value) {
            addCriterion("sellerDiscount >=", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountLessThan(String value) {
            addCriterion("sellerDiscount <", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountLessThanOrEqualTo(String value) {
            addCriterion("sellerDiscount <=", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountLike(String value) {
            addCriterion("sellerDiscount like", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountNotLike(String value) {
            addCriterion("sellerDiscount not like", value, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountIn(List<String> values) {
            addCriterion("sellerDiscount in", values, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountNotIn(List<String> values) {
            addCriterion("sellerDiscount not in", values, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountBetween(String value1, String value2) {
            addCriterion("sellerDiscount between", value1, value2, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountNotBetween(String value1, String value2) {
            addCriterion("sellerDiscount not between", value1, value2, "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNull() {
            addCriterion("orderState is null");
            return (Criteria) this;
        }

        public Criteria andOrderStateIsNotNull() {
            addCriterion("orderState is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStateEqualTo(String value) {
            addCriterion("orderState =", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotEqualTo(String value) {
            addCriterion("orderState <>", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThan(String value) {
            addCriterion("orderState >", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateGreaterThanOrEqualTo(String value) {
            addCriterion("orderState >=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThan(String value) {
            addCriterion("orderState <", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLessThanOrEqualTo(String value) {
            addCriterion("orderState <=", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateLike(String value) {
            addCriterion("orderState like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotLike(String value) {
            addCriterion("orderState not like", value, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateIn(List<String> values) {
            addCriterion("orderState in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotIn(List<String> values) {
            addCriterion("orderState not in", values, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateBetween(String value1, String value2) {
            addCriterion("orderState between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderStateNotBetween(String value1, String value2) {
            addCriterion("orderState not between", value1, value2, "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkIsNull() {
            addCriterion("orderRemark is null");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkIsNotNull() {
            addCriterion("orderRemark is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkEqualTo(String value) {
            addCriterion("orderRemark =", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotEqualTo(String value) {
            addCriterion("orderRemark <>", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkGreaterThan(String value) {
            addCriterion("orderRemark >", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("orderRemark >=", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkLessThan(String value) {
            addCriterion("orderRemark <", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkLessThanOrEqualTo(String value) {
            addCriterion("orderRemark <=", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkLike(String value) {
            addCriterion("orderRemark like", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotLike(String value) {
            addCriterion("orderRemark not like", value, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkIn(List<String> values) {
            addCriterion("orderRemark in", values, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotIn(List<String> values) {
            addCriterion("orderRemark not in", values, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkBetween(String value1, String value2) {
            addCriterion("orderRemark between", value1, value2, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkNotBetween(String value1, String value2) {
            addCriterion("orderRemark not between", value1, value2, "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeIsNull() {
            addCriterion("orderStartTime is null");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeIsNotNull() {
            addCriterion("orderStartTime is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeEqualTo(String value) {
            addCriterion("orderStartTime =", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeNotEqualTo(String value) {
            addCriterion("orderStartTime <>", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeGreaterThan(String value) {
            addCriterion("orderStartTime >", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("orderStartTime >=", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeLessThan(String value) {
            addCriterion("orderStartTime <", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeLessThanOrEqualTo(String value) {
            addCriterion("orderStartTime <=", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeLike(String value) {
            addCriterion("orderStartTime like", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeNotLike(String value) {
            addCriterion("orderStartTime not like", value, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeIn(List<String> values) {
            addCriterion("orderStartTime in", values, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeNotIn(List<String> values) {
            addCriterion("orderStartTime not in", values, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeBetween(String value1, String value2) {
            addCriterion("orderStartTime between", value1, value2, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeNotBetween(String value1, String value2) {
            addCriterion("orderStartTime not between", value1, value2, "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeIsNull() {
            addCriterion("orderEndTime is null");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeIsNotNull() {
            addCriterion("orderEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeEqualTo(String value) {
            addCriterion("orderEndTime =", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeNotEqualTo(String value) {
            addCriterion("orderEndTime <>", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeGreaterThan(String value) {
            addCriterion("orderEndTime >", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("orderEndTime >=", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeLessThan(String value) {
            addCriterion("orderEndTime <", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeLessThanOrEqualTo(String value) {
            addCriterion("orderEndTime <=", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeLike(String value) {
            addCriterion("orderEndTime like", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeNotLike(String value) {
            addCriterion("orderEndTime not like", value, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeIn(List<String> values) {
            addCriterion("orderEndTime in", values, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeNotIn(List<String> values) {
            addCriterion("orderEndTime not in", values, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeBetween(String value1, String value2) {
            addCriterion("orderEndTime between", value1, value2, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeNotBetween(String value1, String value2) {
            addCriterion("orderEndTime not between", value1, value2, "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andCustomer_idIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomer_idIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer_idEqualTo(Long value) {
            addCriterion("customer_id =", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idNotEqualTo(Long value) {
            addCriterion("customer_id <>", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idGreaterThan(Long value) {
            addCriterion("customer_id >", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idGreaterThanOrEqualTo(Long value) {
            addCriterion("customer_id >=", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idLessThan(Long value) {
            addCriterion("customer_id <", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idLessThanOrEqualTo(Long value) {
            addCriterion("customer_id <=", value, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idIn(List<Long> values) {
            addCriterion("customer_id in", values, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idNotIn(List<Long> values) {
            addCriterion("customer_id not in", values, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idBetween(Long value1, Long value2) {
            addCriterion("customer_id between", value1, value2, "customer_id");
            return (Criteria) this;
        }

        public Criteria andCustomer_idNotBetween(Long value1, Long value2) {
            addCriterion("customer_id not between", value1, value2, "customer_id");
            return (Criteria) this;
        }

        public Criteria andItemInfoListIsNull() {
            addCriterion("itemInfoList is null");
            return (Criteria) this;
        }

        public Criteria andItemInfoListIsNotNull() {
            addCriterion("itemInfoList is not null");
            return (Criteria) this;
        }

        public Criteria andItemInfoListEqualTo(String value) {
            addCriterion("itemInfoList =", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListNotEqualTo(String value) {
            addCriterion("itemInfoList <>", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListGreaterThan(String value) {
            addCriterion("itemInfoList >", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListGreaterThanOrEqualTo(String value) {
            addCriterion("itemInfoList >=", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListLessThan(String value) {
            addCriterion("itemInfoList <", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListLessThanOrEqualTo(String value) {
            addCriterion("itemInfoList <=", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListLike(String value) {
            addCriterion("itemInfoList like", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListNotLike(String value) {
            addCriterion("itemInfoList not like", value, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListIn(List<String> values) {
            addCriterion("itemInfoList in", values, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListNotIn(List<String> values) {
            addCriterion("itemInfoList not in", values, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListBetween(String value1, String value2) {
            addCriterion("itemInfoList between", value1, value2, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andItemInfoListNotBetween(String value1, String value2) {
            addCriterion("itemInfoList not between", value1, value2, "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListIsNull() {
            addCriterion("couponDetailList is null");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListIsNotNull() {
            addCriterion("couponDetailList is not null");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListEqualTo(String value) {
            addCriterion("couponDetailList =", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListNotEqualTo(String value) {
            addCriterion("couponDetailList <>", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListGreaterThan(String value) {
            addCriterion("couponDetailList >", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListGreaterThanOrEqualTo(String value) {
            addCriterion("couponDetailList >=", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListLessThan(String value) {
            addCriterion("couponDetailList <", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListLessThanOrEqualTo(String value) {
            addCriterion("couponDetailList <=", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListLike(String value) {
            addCriterion("couponDetailList like", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListNotLike(String value) {
            addCriterion("couponDetailList not like", value, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListIn(List<String> values) {
            addCriterion("couponDetailList in", values, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListNotIn(List<String> values) {
            addCriterion("couponDetailList not in", values, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListBetween(String value1, String value2) {
            addCriterion("couponDetailList between", value1, value2, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListNotBetween(String value1, String value2) {
            addCriterion("couponDetailList not between", value1, value2, "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkIsNull() {
            addCriterion("venderRemark is null");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkIsNotNull() {
            addCriterion("venderRemark is not null");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkEqualTo(String value) {
            addCriterion("venderRemark =", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkNotEqualTo(String value) {
            addCriterion("venderRemark <>", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkGreaterThan(String value) {
            addCriterion("venderRemark >", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("venderRemark >=", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkLessThan(String value) {
            addCriterion("venderRemark <", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkLessThanOrEqualTo(String value) {
            addCriterion("venderRemark <=", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkLike(String value) {
            addCriterion("venderRemark like", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkNotLike(String value) {
            addCriterion("venderRemark not like", value, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkIn(List<String> values) {
            addCriterion("venderRemark in", values, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkNotIn(List<String> values) {
            addCriterion("venderRemark not in", values, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkBetween(String value1, String value2) {
            addCriterion("venderRemark between", value1, value2, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkNotBetween(String value1, String value2) {
            addCriterion("venderRemark not between", value1, value2, "venderRemark");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeIsNull() {
            addCriterion("paymentConfirmTime is null");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeIsNotNull() {
            addCriterion("paymentConfirmTime is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeEqualTo(String value) {
            addCriterion("paymentConfirmTime =", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeNotEqualTo(String value) {
            addCriterion("paymentConfirmTime <>", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeGreaterThan(String value) {
            addCriterion("paymentConfirmTime >", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeGreaterThanOrEqualTo(String value) {
            addCriterion("paymentConfirmTime >=", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeLessThan(String value) {
            addCriterion("paymentConfirmTime <", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeLessThanOrEqualTo(String value) {
            addCriterion("paymentConfirmTime <=", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeLike(String value) {
            addCriterion("paymentConfirmTime like", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeNotLike(String value) {
            addCriterion("paymentConfirmTime not like", value, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeIn(List<String> values) {
            addCriterion("paymentConfirmTime in", values, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeNotIn(List<String> values) {
            addCriterion("paymentConfirmTime not in", values, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeBetween(String value1, String value2) {
            addCriterion("paymentConfirmTime between", value1, value2, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeNotBetween(String value1, String value2) {
            addCriterion("paymentConfirmTime not between", value1, value2, "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNull() {
            addCriterion("modified is null");
            return (Criteria) this;
        }

        public Criteria andModifiedIsNotNull() {
            addCriterion("modified is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedEqualTo(String value) {
            addCriterion("modified =", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotEqualTo(String value) {
            addCriterion("modified <>", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThan(String value) {
            addCriterion("modified >", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedGreaterThanOrEqualTo(String value) {
            addCriterion("modified >=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThan(String value) {
            addCriterion("modified <", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLessThanOrEqualTo(String value) {
            addCriterion("modified <=", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedLike(String value) {
            addCriterion("modified like", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotLike(String value) {
            addCriterion("modified not like", value, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedIn(List<String> values) {
            addCriterion("modified in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotIn(List<String> values) {
            addCriterion("modified not in", values, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedBetween(String value1, String value2) {
            addCriterion("modified between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andModifiedNotBetween(String value1, String value2) {
            addCriterion("modified not between", value1, value2, "modified");
            return (Criteria) this;
        }

        public Criteria andPay_order_jd_idLikeInsensitive(String value) {
            addCriterion("upper(pay_order_jd_id) like", value.toUpperCase(), "pay_order_jd_id");
            return (Criteria) this;
        }

        public Criteria andOrderTotalPriceLikeInsensitive(String value) {
            addCriterion("upper(orderTotalPrice) like", value.toUpperCase(), "orderTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderSellerPriceLikeInsensitive(String value) {
            addCriterion("upper(orderSellerPrice) like", value.toUpperCase(), "orderSellerPrice");
            return (Criteria) this;
        }

        public Criteria andOrderPaymentLikeInsensitive(String value) {
            addCriterion("upper(orderPayment) like", value.toUpperCase(), "orderPayment");
            return (Criteria) this;
        }

        public Criteria andSellerDiscountLikeInsensitive(String value) {
            addCriterion("upper(sellerDiscount) like", value.toUpperCase(), "sellerDiscount");
            return (Criteria) this;
        }

        public Criteria andOrderStateLikeInsensitive(String value) {
            addCriterion("upper(orderState) like", value.toUpperCase(), "orderState");
            return (Criteria) this;
        }

        public Criteria andOrderRemarkLikeInsensitive(String value) {
            addCriterion("upper(orderRemark) like", value.toUpperCase(), "orderRemark");
            return (Criteria) this;
        }

        public Criteria andOrderStartTimeLikeInsensitive(String value) {
            addCriterion("upper(orderStartTime) like", value.toUpperCase(), "orderStartTime");
            return (Criteria) this;
        }

        public Criteria andOrderEndTimeLikeInsensitive(String value) {
            addCriterion("upper(orderEndTime) like", value.toUpperCase(), "orderEndTime");
            return (Criteria) this;
        }

        public Criteria andItemInfoListLikeInsensitive(String value) {
            addCriterion("upper(itemInfoList) like", value.toUpperCase(), "itemInfoList");
            return (Criteria) this;
        }

        public Criteria andCouponDetailListLikeInsensitive(String value) {
            addCriterion("upper(couponDetailList) like", value.toUpperCase(), "couponDetailList");
            return (Criteria) this;
        }

        public Criteria andVenderRemarkLikeInsensitive(String value) {
            addCriterion("upper(venderRemark) like", value.toUpperCase(), "venderRemark");
            return (Criteria) this;
        }

        public Criteria andPaymentConfirmTimeLikeInsensitive(String value) {
            addCriterion("upper(paymentConfirmTime) like", value.toUpperCase(), "paymentConfirmTime");
            return (Criteria) this;
        }

        public Criteria andModifiedLikeInsensitive(String value) {
            addCriterion("upper(modified) like", value.toUpperCase(), "modified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_order_jd
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 12 20:17:02 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table pay_order_jd
     *
     * @mbg.generated Thu Jul 12 20:17:02 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	京东商家订单数据
		//--------------------------------------------------
		/** jd订单id */									pay_order_jd_id(1,Types.VARCHAR,false),
		/** 订单总金额。总金额=订单金额（不减优惠，不加运费服务费税费） */
														orderTotalPrice(2,Types.VARCHAR,false),
		/** 订单货款金额（订单总金额-商家优惠金额） */	orderSellerPrice(2,Types.VARCHAR,false),
		/** 用户应付金额。应付款=货款-用户优惠-余额+运费+税费+服务费。 */
														orderPayment(2,Types.VARCHAR,false),
		/** 商家优惠金额 */								sellerDiscount(2,Types.VARCHAR,false),
		/** 1）WAIT_SELLER_STOCK_OUT 等待出库 2）WAIT_GOODS_RECEIVE_CONFIRM 等待确认收货 3）WAIT_SELLER_DELIVERY等待发货 （只适用于海外购商家，含义为'等待境内发货'标签下的订单,非海外购商家无需使用） 4) POP_ORDER_PAUSE POP暂停 5）FINISHED_L 完成6）TRADE_CANCELED 取消 7）LOCKED 已锁定 8）WAIT_SEND_CODE 等待发码（LOC订单特有状态） */
														orderState(2,Types.VARCHAR,false),
		/** 买家下单时订单备注 */						orderRemark(2,Types.VARCHAR,false),
		/** 下单时间 */									orderStartTime(2,Types.VARCHAR,false),
		/** 结单时间 如返回信息为“0001-01-01 00:00:00”和“1970-01-01 00:00:00”，可认为此订单为未完成状态。 */
														orderEndTime(2,Types.VARCHAR,false),
		/** 下单顾客id（抓取到的consigneeInfo新生成的） */
														customer_id(2,Types.BIGINT,false),
		/** 用户下单数据sku数据"itemInfoList":[{"giftPoint":"0","itemTotal":"1","jdPrice":"1.00","newStoreId":"0","outerSkuId":"","productNo":"","skuId":"30152641922","skuName":"浦尔家 家庭清洁保洁服务家政服务小时钟点工2小时保洁上门服务 测试订单勿拍 北京海淀","wareId":"11789048136"}] */
														itemInfoList(2,Types.VARCHAR,false),
		/** json优惠数据couponDetailList":[{orderId :'',skuId :'',couponType :'',couponPrice :''}] */
														couponDetailList(2,Types.VARCHAR,false),
		/** 商家订单备注（不大于500字符） */			venderRemark(2,Types.VARCHAR,false),
		/** 付款确认时间 如果没有付款时间 默认返回0001-01-01 00:00:00 */
														paymentConfirmTime(2,Types.VARCHAR,false),
		/** 订单更新时间 */								modified(2,Types.VARCHAR,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}