package com.aobei.train.model;

import com.aobei.train.model.OperateLogExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class OperateLogExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Wed Mar 28 12:10:03 CST 2018
     */
    public OperateLogExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Wed Mar 28 12:10:03 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Wed Mar 28 12:10:03 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate_log
     *
     * @mbg.generated Wed Mar 28 12:10:03 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operate_log
     *
     * @mbg.generated Wed Mar 28 12:10:03 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andOperate_log_idIsNull() {
            addCriterion("operate_log_id is null");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idIsNotNull() {
            addCriterion("operate_log_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idEqualTo(Long value) {
            addCriterion("operate_log_id =", value, "operate_log_id");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idNotEqualTo(Long value) {
            addCriterion("operate_log_id <>", value, "operate_log_id");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idGreaterThan(Long value) {
            addCriterion("operate_log_id >", value, "operate_log_id");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idGreaterThanOrEqualTo(Long value) {
            addCriterion("operate_log_id >=", value, "operate_log_id");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idLessThan(Long value) {
            addCriterion("operate_log_id <", value, "operate_log_id");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idLessThanOrEqualTo(Long value) {
            addCriterion("operate_log_id <=", value, "operate_log_id");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idIn(List<Long> values) {
            addCriterion("operate_log_id in", values, "operate_log_id");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idNotIn(List<Long> values) {
            addCriterion("operate_log_id not in", values, "operate_log_id");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idBetween(Long value1, Long value2) {
            addCriterion("operate_log_id between", value1, value2, "operate_log_id");
            return (Criteria) this;
        }

        public Criteria andOperate_log_idNotBetween(Long value1, Long value2) {
            addCriterion("operate_log_id not between", value1, value2, "operate_log_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Long value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Long value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Long value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Long> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andTo_user_idIsNull() {
            addCriterion("to_user_id is null");
            return (Criteria) this;
        }

        public Criteria andTo_user_idIsNotNull() {
            addCriterion("to_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andTo_user_idEqualTo(Long value) {
            addCriterion("to_user_id =", value, "to_user_id");
            return (Criteria) this;
        }

        public Criteria andTo_user_idNotEqualTo(Long value) {
            addCriterion("to_user_id <>", value, "to_user_id");
            return (Criteria) this;
        }

        public Criteria andTo_user_idGreaterThan(Long value) {
            addCriterion("to_user_id >", value, "to_user_id");
            return (Criteria) this;
        }

        public Criteria andTo_user_idGreaterThanOrEqualTo(Long value) {
            addCriterion("to_user_id >=", value, "to_user_id");
            return (Criteria) this;
        }

        public Criteria andTo_user_idLessThan(Long value) {
            addCriterion("to_user_id <", value, "to_user_id");
            return (Criteria) this;
        }

        public Criteria andTo_user_idLessThanOrEqualTo(Long value) {
            addCriterion("to_user_id <=", value, "to_user_id");
            return (Criteria) this;
        }

        public Criteria andTo_user_idIn(List<Long> values) {
            addCriterion("to_user_id in", values, "to_user_id");
            return (Criteria) this;
        }

        public Criteria andTo_user_idNotIn(List<Long> values) {
            addCriterion("to_user_id not in", values, "to_user_id");
            return (Criteria) this;
        }

        public Criteria andTo_user_idBetween(Long value1, Long value2) {
            addCriterion("to_user_id between", value1, value2, "to_user_id");
            return (Criteria) this;
        }

        public Criteria andTo_user_idNotBetween(Long value1, Long value2) {
            addCriterion("to_user_id not between", value1, value2, "to_user_id");
            return (Criteria) this;
        }

        public Criteria andOperateIsNull() {
            addCriterion("operate is null");
            return (Criteria) this;
        }

        public Criteria andOperateIsNotNull() {
            addCriterion("operate is not null");
            return (Criteria) this;
        }

        public Criteria andOperateEqualTo(String value) {
            addCriterion("operate =", value, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateNotEqualTo(String value) {
            addCriterion("operate <>", value, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateGreaterThan(String value) {
            addCriterion("operate >", value, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateGreaterThanOrEqualTo(String value) {
            addCriterion("operate >=", value, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateLessThan(String value) {
            addCriterion("operate <", value, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateLessThanOrEqualTo(String value) {
            addCriterion("operate <=", value, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateLike(String value) {
            addCriterion("operate like", value, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateNotLike(String value) {
            addCriterion("operate not like", value, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateIn(List<String> values) {
            addCriterion("operate in", values, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateNotIn(List<String> values) {
            addCriterion("operate not in", values, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateBetween(String value1, String value2) {
            addCriterion("operate between", value1, value2, "operate");
            return (Criteria) this;
        }

        public Criteria andOperateNotBetween(String value1, String value2) {
            addCriterion("operate not between", value1, value2, "operate");
            return (Criteria) this;
        }

        public Criteria andBis_typeIsNull() {
            addCriterion("bis_type is null");
            return (Criteria) this;
        }

        public Criteria andBis_typeIsNotNull() {
            addCriterion("bis_type is not null");
            return (Criteria) this;
        }

        public Criteria andBis_typeEqualTo(Integer value) {
            addCriterion("bis_type =", value, "bis_type");
            return (Criteria) this;
        }

        public Criteria andBis_typeNotEqualTo(Integer value) {
            addCriterion("bis_type <>", value, "bis_type");
            return (Criteria) this;
        }

        public Criteria andBis_typeGreaterThan(Integer value) {
            addCriterion("bis_type >", value, "bis_type");
            return (Criteria) this;
        }

        public Criteria andBis_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("bis_type >=", value, "bis_type");
            return (Criteria) this;
        }

        public Criteria andBis_typeLessThan(Integer value) {
            addCriterion("bis_type <", value, "bis_type");
            return (Criteria) this;
        }

        public Criteria andBis_typeLessThanOrEqualTo(Integer value) {
            addCriterion("bis_type <=", value, "bis_type");
            return (Criteria) this;
        }

        public Criteria andBis_typeIn(List<Integer> values) {
            addCriterion("bis_type in", values, "bis_type");
            return (Criteria) this;
        }

        public Criteria andBis_typeNotIn(List<Integer> values) {
            addCriterion("bis_type not in", values, "bis_type");
            return (Criteria) this;
        }

        public Criteria andBis_typeBetween(Integer value1, Integer value2) {
            addCriterion("bis_type between", value1, value2, "bis_type");
            return (Criteria) this;
        }

        public Criteria andBis_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("bis_type not between", value1, value2, "bis_type");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andOperateLikeInsensitive(String value) {
            addCriterion("upper(operate) like", value.toUpperCase(), "operate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operate_log
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 28 12:10:03 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table operate_log
     *
     * @mbg.generated Wed Mar 28 12:10:03 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	操作日志
		//--------------------------------------------------					
										operate_log_id(1,Types.BIGINT,false),
		/** 操作人id */					user_id(2,Types.BIGINT,false),
		/** 被操作用户id */				to_user_id(2,Types.BIGINT,false),
		/** 操作内容 */					operate(2,Types.VARCHAR,false),
		/** 业务系统   1 all */			bis_type(2,Types.INTEGER,false),					
										create_datetime(2,Types.TIMESTAMP,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}