package com.aobei.train.model;

import com.aobei.train.model.OrderLogExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class OrderLogExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_log
     *
     * @mbg.generated Fri Feb 23 15:06:43 CST 2018
     */
    public OrderLogExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_log
     *
     * @mbg.generated Fri Feb 23 15:06:43 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_log
     *
     * @mbg.generated Fri Feb 23 15:06:43 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_log
     *
     * @mbg.generated Fri Feb 23 15:06:43 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_order_log
     *
     * @mbg.generated Fri Feb 23 15:06:43 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andPay_order_log_idIsNull() {
            addCriterion("pay_order_log_id is null");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idIsNotNull() {
            addCriterion("pay_order_log_id is not null");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idEqualTo(Long value) {
            addCriterion("pay_order_log_id =", value, "pay_order_log_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idNotEqualTo(Long value) {
            addCriterion("pay_order_log_id <>", value, "pay_order_log_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idGreaterThan(Long value) {
            addCriterion("pay_order_log_id >", value, "pay_order_log_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idGreaterThanOrEqualTo(Long value) {
            addCriterion("pay_order_log_id >=", value, "pay_order_log_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idLessThan(Long value) {
            addCriterion("pay_order_log_id <", value, "pay_order_log_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idLessThanOrEqualTo(Long value) {
            addCriterion("pay_order_log_id <=", value, "pay_order_log_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idIn(List<Long> values) {
            addCriterion("pay_order_log_id in", values, "pay_order_log_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idNotIn(List<Long> values) {
            addCriterion("pay_order_log_id not in", values, "pay_order_log_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idBetween(Long value1, Long value2) {
            addCriterion("pay_order_log_id between", value1, value2, "pay_order_log_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_log_idNotBetween(Long value1, Long value2) {
            addCriterion("pay_order_log_id not between", value1, value2, "pay_order_log_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIsNull() {
            addCriterion("pay_order_id is null");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIsNotNull() {
            addCriterion("pay_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andPay_order_idEqualTo(String value) {
            addCriterion("pay_order_id =", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotEqualTo(String value) {
            addCriterion("pay_order_id <>", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idGreaterThan(String value) {
            addCriterion("pay_order_id >", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idGreaterThanOrEqualTo(String value) {
            addCriterion("pay_order_id >=", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLessThan(String value) {
            addCriterion("pay_order_id <", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLessThanOrEqualTo(String value) {
            addCriterion("pay_order_id <=", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLike(String value) {
            addCriterion("pay_order_id like", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotLike(String value) {
            addCriterion("pay_order_id not like", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIn(List<String> values) {
            addCriterion("pay_order_id in", values, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotIn(List<String> values) {
            addCriterion("pay_order_id not in", values, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idBetween(String value1, String value2) {
            addCriterion("pay_order_id between", value1, value2, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotBetween(String value1, String value2) {
            addCriterion("pay_order_id not between", value1, value2, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andLog_textIsNull() {
            addCriterion("log_text is null");
            return (Criteria) this;
        }

        public Criteria andLog_textIsNotNull() {
            addCriterion("log_text is not null");
            return (Criteria) this;
        }

        public Criteria andLog_textEqualTo(String value) {
            addCriterion("log_text =", value, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textNotEqualTo(String value) {
            addCriterion("log_text <>", value, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textGreaterThan(String value) {
            addCriterion("log_text >", value, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textGreaterThanOrEqualTo(String value) {
            addCriterion("log_text >=", value, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textLessThan(String value) {
            addCriterion("log_text <", value, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textLessThanOrEqualTo(String value) {
            addCriterion("log_text <=", value, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textLike(String value) {
            addCriterion("log_text like", value, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textNotLike(String value) {
            addCriterion("log_text not like", value, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textIn(List<String> values) {
            addCriterion("log_text in", values, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textNotIn(List<String> values) {
            addCriterion("log_text not in", values, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textBetween(String value1, String value2) {
            addCriterion("log_text between", value1, value2, "log_text");
            return (Criteria) this;
        }

        public Criteria andLog_textNotBetween(String value1, String value2) {
            addCriterion("log_text not between", value1, value2, "log_text");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Long value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Long value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Long value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Long> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andOperator_nameIsNull() {
            addCriterion("operator_name is null");
            return (Criteria) this;
        }

        public Criteria andOperator_nameIsNotNull() {
            addCriterion("operator_name is not null");
            return (Criteria) this;
        }

        public Criteria andOperator_nameEqualTo(String value) {
            addCriterion("operator_name =", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameNotEqualTo(String value) {
            addCriterion("operator_name <>", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameGreaterThan(String value) {
            addCriterion("operator_name >", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameGreaterThanOrEqualTo(String value) {
            addCriterion("operator_name >=", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameLessThan(String value) {
            addCriterion("operator_name <", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameLessThanOrEqualTo(String value) {
            addCriterion("operator_name <=", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameLike(String value) {
            addCriterion("operator_name like", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameNotLike(String value) {
            addCriterion("operator_name not like", value, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameIn(List<String> values) {
            addCriterion("operator_name in", values, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameNotIn(List<String> values) {
            addCriterion("operator_name not in", values, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameBetween(String value1, String value2) {
            addCriterion("operator_name between", value1, value2, "operator_name");
            return (Criteria) this;
        }

        public Criteria andOperator_nameNotBetween(String value1, String value2) {
            addCriterion("operator_name not between", value1, value2, "operator_name");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLikeInsensitive(String value) {
            addCriterion("upper(pay_order_id) like", value.toUpperCase(), "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andLog_textLikeInsensitive(String value) {
            addCriterion("upper(log_text) like", value.toUpperCase(), "log_text");
            return (Criteria) this;
        }

        public Criteria andOperator_nameLikeInsensitive(String value) {
            addCriterion("upper(operator_name) like", value.toUpperCase(), "operator_name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_order_log
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 23 15:06:43 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table pay_order_log
     *
     * @mbg.generated Fri Feb 23 15:06:43 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	订单变更日志
		//--------------------------------------------------					
										pay_order_log_id(1,Types.BIGINT,false),					
										pay_order_id(2,Types.VARCHAR,false),					
										log_text(2,Types.VARCHAR,false),
		/** 系统操作人员  0 */			user_id(2,Types.BIGINT,false),
		/** 操作人名称 */				operator_name(2,Types.VARCHAR,false),					
										create_time(2,Types.TIMESTAMP,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}