package com.aobei.train.model;

import com.aobei.train.model.OssFileExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class OssFileExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_file
     *
     * @mbg.generated Wed Mar 07 14:51:40 CST 2018
     */
    public OssFileExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_file
     *
     * @mbg.generated Wed Mar 07 14:51:40 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_file
     *
     * @mbg.generated Wed Mar 07 14:51:40 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oss_file
     *
     * @mbg.generated Wed Mar 07 14:51:40 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oss_file
     *
     * @mbg.generated Wed Mar 07 14:51:40 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andOss_file_idIsNull() {
            addCriterion("oss_file_id is null");
            return (Criteria) this;
        }

        public Criteria andOss_file_idIsNotNull() {
            addCriterion("oss_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andOss_file_idEqualTo(Long value) {
            addCriterion("oss_file_id =", value, "oss_file_id");
            return (Criteria) this;
        }

        public Criteria andOss_file_idNotEqualTo(Long value) {
            addCriterion("oss_file_id <>", value, "oss_file_id");
            return (Criteria) this;
        }

        public Criteria andOss_file_idGreaterThan(Long value) {
            addCriterion("oss_file_id >", value, "oss_file_id");
            return (Criteria) this;
        }

        public Criteria andOss_file_idGreaterThanOrEqualTo(Long value) {
            addCriterion("oss_file_id >=", value, "oss_file_id");
            return (Criteria) this;
        }

        public Criteria andOss_file_idLessThan(Long value) {
            addCriterion("oss_file_id <", value, "oss_file_id");
            return (Criteria) this;
        }

        public Criteria andOss_file_idLessThanOrEqualTo(Long value) {
            addCriterion("oss_file_id <=", value, "oss_file_id");
            return (Criteria) this;
        }

        public Criteria andOss_file_idIn(List<Long> values) {
            addCriterion("oss_file_id in", values, "oss_file_id");
            return (Criteria) this;
        }

        public Criteria andOss_file_idNotIn(List<Long> values) {
            addCriterion("oss_file_id not in", values, "oss_file_id");
            return (Criteria) this;
        }

        public Criteria andOss_file_idBetween(Long value1, Long value2) {
            addCriterion("oss_file_id between", value1, value2, "oss_file_id");
            return (Criteria) this;
        }

        public Criteria andOss_file_idNotBetween(Long value1, Long value2) {
            addCriterion("oss_file_id not between", value1, value2, "oss_file_id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andFormatIsNull() {
            addCriterion("format is null");
            return (Criteria) this;
        }

        public Criteria andFormatIsNotNull() {
            addCriterion("format is not null");
            return (Criteria) this;
        }

        public Criteria andFormatEqualTo(String value) {
            addCriterion("format =", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotEqualTo(String value) {
            addCriterion("format <>", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThan(String value) {
            addCriterion("format >", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatGreaterThanOrEqualTo(String value) {
            addCriterion("format >=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThan(String value) {
            addCriterion("format <", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLessThanOrEqualTo(String value) {
            addCriterion("format <=", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatLike(String value) {
            addCriterion("format like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotLike(String value) {
            addCriterion("format not like", value, "format");
            return (Criteria) this;
        }

        public Criteria andFormatIn(List<String> values) {
            addCriterion("format in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotIn(List<String> values) {
            addCriterion("format not in", values, "format");
            return (Criteria) this;
        }

        public Criteria andFormatBetween(String value1, String value2) {
            addCriterion("format between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andFormatNotBetween(String value1, String value2) {
            addCriterion("format not between", value1, value2, "format");
            return (Criteria) this;
        }

        public Criteria andFile_sizeIsNull() {
            addCriterion("file_size is null");
            return (Criteria) this;
        }

        public Criteria andFile_sizeIsNotNull() {
            addCriterion("file_size is not null");
            return (Criteria) this;
        }

        public Criteria andFile_sizeEqualTo(Integer value) {
            addCriterion("file_size =", value, "file_size");
            return (Criteria) this;
        }

        public Criteria andFile_sizeNotEqualTo(Integer value) {
            addCriterion("file_size <>", value, "file_size");
            return (Criteria) this;
        }

        public Criteria andFile_sizeGreaterThan(Integer value) {
            addCriterion("file_size >", value, "file_size");
            return (Criteria) this;
        }

        public Criteria andFile_sizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("file_size >=", value, "file_size");
            return (Criteria) this;
        }

        public Criteria andFile_sizeLessThan(Integer value) {
            addCriterion("file_size <", value, "file_size");
            return (Criteria) this;
        }

        public Criteria andFile_sizeLessThanOrEqualTo(Integer value) {
            addCriterion("file_size <=", value, "file_size");
            return (Criteria) this;
        }

        public Criteria andFile_sizeIn(List<Integer> values) {
            addCriterion("file_size in", values, "file_size");
            return (Criteria) this;
        }

        public Criteria andFile_sizeNotIn(List<Integer> values) {
            addCriterion("file_size not in", values, "file_size");
            return (Criteria) this;
        }

        public Criteria andFile_sizeBetween(Integer value1, Integer value2) {
            addCriterion("file_size between", value1, value2, "file_size");
            return (Criteria) this;
        }

        public Criteria andFile_sizeNotBetween(Integer value1, Integer value2) {
            addCriterion("file_size not between", value1, value2, "file_size");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andBucketIsNull() {
            addCriterion("bucket is null");
            return (Criteria) this;
        }

        public Criteria andBucketIsNotNull() {
            addCriterion("bucket is not null");
            return (Criteria) this;
        }

        public Criteria andBucketEqualTo(String value) {
            addCriterion("bucket =", value, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketNotEqualTo(String value) {
            addCriterion("bucket <>", value, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketGreaterThan(String value) {
            addCriterion("bucket >", value, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketGreaterThanOrEqualTo(String value) {
            addCriterion("bucket >=", value, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketLessThan(String value) {
            addCriterion("bucket <", value, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketLessThanOrEqualTo(String value) {
            addCriterion("bucket <=", value, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketLike(String value) {
            addCriterion("bucket like", value, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketNotLike(String value) {
            addCriterion("bucket not like", value, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketIn(List<String> values) {
            addCriterion("bucket in", values, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketNotIn(List<String> values) {
            addCriterion("bucket not in", values, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketBetween(String value1, String value2) {
            addCriterion("bucket between", value1, value2, "bucket");
            return (Criteria) this;
        }

        public Criteria andBucketNotBetween(String value1, String value2) {
            addCriterion("bucket not between", value1, value2, "bucket");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsIsNull() {
            addCriterion("access_permissions is null");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsIsNotNull() {
            addCriterion("access_permissions is not null");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsEqualTo(String value) {
            addCriterion("access_permissions =", value, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsNotEqualTo(String value) {
            addCriterion("access_permissions <>", value, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsGreaterThan(String value) {
            addCriterion("access_permissions >", value, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsGreaterThanOrEqualTo(String value) {
            addCriterion("access_permissions >=", value, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsLessThan(String value) {
            addCriterion("access_permissions <", value, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsLessThanOrEqualTo(String value) {
            addCriterion("access_permissions <=", value, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsLike(String value) {
            addCriterion("access_permissions like", value, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsNotLike(String value) {
            addCriterion("access_permissions not like", value, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsIn(List<String> values) {
            addCriterion("access_permissions in", values, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsNotIn(List<String> values) {
            addCriterion("access_permissions not in", values, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsBetween(String value1, String value2) {
            addCriterion("access_permissions between", value1, value2, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsNotBetween(String value1, String value2) {
            addCriterion("access_permissions not between", value1, value2, "access_permissions");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(name) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andUrlLikeInsensitive(String value) {
            addCriterion("upper(url) like", value.toUpperCase(), "url");
            return (Criteria) this;
        }

        public Criteria andFormatLikeInsensitive(String value) {
            addCriterion("upper(format) like", value.toUpperCase(), "format");
            return (Criteria) this;
        }

        public Criteria andBucketLikeInsensitive(String value) {
            addCriterion("upper(bucket) like", value.toUpperCase(), "bucket");
            return (Criteria) this;
        }

        public Criteria andAccess_permissionsLikeInsensitive(String value) {
            addCriterion("upper(access_permissions) like", value.toUpperCase(), "access_permissions");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oss_file
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 07 14:51:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table oss_file
     *
     * @mbg.generated Wed Mar 07 14:51:40 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	对象存储 文件数据
		//--------------------------------------------------
		/** id */										oss_file_id(1,Types.BIGINT,false),
		/** 文件名称 */									name(2,Types.VARCHAR,false),
		/** 文件地址 */									url(2,Types.VARCHAR,false),
		/** 文件格式 */									format(2,Types.VARCHAR,false),
		/** 文件大小 单位 kb */							file_size(2,Types.INTEGER,false),
		/** 创建时间 [DV=>CURRENT_TIMESTAMP] */			create_time(2,Types.TIMESTAMP,false),
		/** 文件上传到阿里云oss的bucket */				bucket(2,Types.VARCHAR,false),
		/** 文件的访问权限 */							access_permissions(2,Types.VARCHAR,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}