package com.aobei.train.model;

import com.aobei.train.model.PayAliNotifyExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class PayAliNotifyExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_ali_notify
     *
     * @mbg.generated Fri Jun 01 16:58:47 CST 2018
     */
    public PayAliNotifyExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_ali_notify
     *
     * @mbg.generated Fri Jun 01 16:58:47 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_ali_notify
     *
     * @mbg.generated Fri Jun 01 16:58:47 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_ali_notify
     *
     * @mbg.generated Fri Jun 01 16:58:47 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_ali_notify
     *
     * @mbg.generated Fri Jun 01 16:58:47 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andNotify_idIsNull() {
            addCriterion("notify_id is null");
            return (Criteria) this;
        }

        public Criteria andNotify_idIsNotNull() {
            addCriterion("notify_id is not null");
            return (Criteria) this;
        }

        public Criteria andNotify_idEqualTo(String value) {
            addCriterion("notify_id =", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idNotEqualTo(String value) {
            addCriterion("notify_id <>", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idGreaterThan(String value) {
            addCriterion("notify_id >", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idGreaterThanOrEqualTo(String value) {
            addCriterion("notify_id >=", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idLessThan(String value) {
            addCriterion("notify_id <", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idLessThanOrEqualTo(String value) {
            addCriterion("notify_id <=", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idLike(String value) {
            addCriterion("notify_id like", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idNotLike(String value) {
            addCriterion("notify_id not like", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idIn(List<String> values) {
            addCriterion("notify_id in", values, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idNotIn(List<String> values) {
            addCriterion("notify_id not in", values, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idBetween(String value1, String value2) {
            addCriterion("notify_id between", value1, value2, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idNotBetween(String value1, String value2) {
            addCriterion("notify_id not between", value1, value2, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_timeIsNull() {
            addCriterion("notify_time is null");
            return (Criteria) this;
        }

        public Criteria andNotify_timeIsNotNull() {
            addCriterion("notify_time is not null");
            return (Criteria) this;
        }

        public Criteria andNotify_timeEqualTo(String value) {
            addCriterion("notify_time =", value, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeNotEqualTo(String value) {
            addCriterion("notify_time <>", value, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeGreaterThan(String value) {
            addCriterion("notify_time >", value, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeGreaterThanOrEqualTo(String value) {
            addCriterion("notify_time >=", value, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeLessThan(String value) {
            addCriterion("notify_time <", value, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeLessThanOrEqualTo(String value) {
            addCriterion("notify_time <=", value, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeLike(String value) {
            addCriterion("notify_time like", value, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeNotLike(String value) {
            addCriterion("notify_time not like", value, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeIn(List<String> values) {
            addCriterion("notify_time in", values, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeNotIn(List<String> values) {
            addCriterion("notify_time not in", values, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeBetween(String value1, String value2) {
            addCriterion("notify_time between", value1, value2, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_timeNotBetween(String value1, String value2) {
            addCriterion("notify_time not between", value1, value2, "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_typeIsNull() {
            addCriterion("notify_type is null");
            return (Criteria) this;
        }

        public Criteria andNotify_typeIsNotNull() {
            addCriterion("notify_type is not null");
            return (Criteria) this;
        }

        public Criteria andNotify_typeEqualTo(String value) {
            addCriterion("notify_type =", value, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeNotEqualTo(String value) {
            addCriterion("notify_type <>", value, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeGreaterThan(String value) {
            addCriterion("notify_type >", value, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeGreaterThanOrEqualTo(String value) {
            addCriterion("notify_type >=", value, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeLessThan(String value) {
            addCriterion("notify_type <", value, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeLessThanOrEqualTo(String value) {
            addCriterion("notify_type <=", value, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeLike(String value) {
            addCriterion("notify_type like", value, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeNotLike(String value) {
            addCriterion("notify_type not like", value, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeIn(List<String> values) {
            addCriterion("notify_type in", values, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeNotIn(List<String> values) {
            addCriterion("notify_type not in", values, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeBetween(String value1, String value2) {
            addCriterion("notify_type between", value1, value2, "notify_type");
            return (Criteria) this;
        }

        public Criteria andNotify_typeNotBetween(String value1, String value2) {
            addCriterion("notify_type not between", value1, value2, "notify_type");
            return (Criteria) this;
        }

        public Criteria andApp_idIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andApp_idIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andApp_idEqualTo(String value) {
            addCriterion("app_id =", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idNotEqualTo(String value) {
            addCriterion("app_id <>", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idGreaterThan(String value) {
            addCriterion("app_id >", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idLessThan(String value) {
            addCriterion("app_id <", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idLike(String value) {
            addCriterion("app_id like", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idNotLike(String value) {
            addCriterion("app_id not like", value, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idIn(List<String> values) {
            addCriterion("app_id in", values, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idNotIn(List<String> values) {
            addCriterion("app_id not in", values, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "app_id");
            return (Criteria) this;
        }

        public Criteria andApp_idNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "app_id");
            return (Criteria) this;
        }

        public Criteria andCharsetIsNull() {
            addCriterion("charset is null");
            return (Criteria) this;
        }

        public Criteria andCharsetIsNotNull() {
            addCriterion("charset is not null");
            return (Criteria) this;
        }

        public Criteria andCharsetEqualTo(String value) {
            addCriterion("charset =", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetNotEqualTo(String value) {
            addCriterion("charset <>", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetGreaterThan(String value) {
            addCriterion("charset >", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetGreaterThanOrEqualTo(String value) {
            addCriterion("charset >=", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetLessThan(String value) {
            addCriterion("charset <", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetLessThanOrEqualTo(String value) {
            addCriterion("charset <=", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetLike(String value) {
            addCriterion("charset like", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetNotLike(String value) {
            addCriterion("charset not like", value, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetIn(List<String> values) {
            addCriterion("charset in", values, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetNotIn(List<String> values) {
            addCriterion("charset not in", values, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetBetween(String value1, String value2) {
            addCriterion("charset between", value1, value2, "charset");
            return (Criteria) this;
        }

        public Criteria andCharsetNotBetween(String value1, String value2) {
            addCriterion("charset not between", value1, value2, "charset");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andSign_typeIsNull() {
            addCriterion("sign_type is null");
            return (Criteria) this;
        }

        public Criteria andSign_typeIsNotNull() {
            addCriterion("sign_type is not null");
            return (Criteria) this;
        }

        public Criteria andSign_typeEqualTo(String value) {
            addCriterion("sign_type =", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeNotEqualTo(String value) {
            addCriterion("sign_type <>", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeGreaterThan(String value) {
            addCriterion("sign_type >", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeGreaterThanOrEqualTo(String value) {
            addCriterion("sign_type >=", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeLessThan(String value) {
            addCriterion("sign_type <", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeLessThanOrEqualTo(String value) {
            addCriterion("sign_type <=", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeLike(String value) {
            addCriterion("sign_type like", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeNotLike(String value) {
            addCriterion("sign_type not like", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeIn(List<String> values) {
            addCriterion("sign_type in", values, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeNotIn(List<String> values) {
            addCriterion("sign_type not in", values, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeBetween(String value1, String value2) {
            addCriterion("sign_type between", value1, value2, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeNotBetween(String value1, String value2) {
            addCriterion("sign_type not between", value1, value2, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSignIsNull() {
            addCriterion("sign is null");
            return (Criteria) this;
        }

        public Criteria andSignIsNotNull() {
            addCriterion("sign is not null");
            return (Criteria) this;
        }

        public Criteria andSignEqualTo(String value) {
            addCriterion("sign =", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotEqualTo(String value) {
            addCriterion("sign <>", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThan(String value) {
            addCriterion("sign >", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThanOrEqualTo(String value) {
            addCriterion("sign >=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThan(String value) {
            addCriterion("sign <", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThanOrEqualTo(String value) {
            addCriterion("sign <=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLike(String value) {
            addCriterion("sign like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotLike(String value) {
            addCriterion("sign not like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignIn(List<String> values) {
            addCriterion("sign in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotIn(List<String> values) {
            addCriterion("sign not in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignBetween(String value1, String value2) {
            addCriterion("sign between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotBetween(String value1, String value2) {
            addCriterion("sign not between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andTrade_noIsNull() {
            addCriterion("trade_no is null");
            return (Criteria) this;
        }

        public Criteria andTrade_noIsNotNull() {
            addCriterion("trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andTrade_noEqualTo(String value) {
            addCriterion("trade_no =", value, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noNotEqualTo(String value) {
            addCriterion("trade_no <>", value, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noGreaterThan(String value) {
            addCriterion("trade_no >", value, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noGreaterThanOrEqualTo(String value) {
            addCriterion("trade_no >=", value, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noLessThan(String value) {
            addCriterion("trade_no <", value, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noLessThanOrEqualTo(String value) {
            addCriterion("trade_no <=", value, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noLike(String value) {
            addCriterion("trade_no like", value, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noNotLike(String value) {
            addCriterion("trade_no not like", value, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noIn(List<String> values) {
            addCriterion("trade_no in", values, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noNotIn(List<String> values) {
            addCriterion("trade_no not in", values, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noBetween(String value1, String value2) {
            addCriterion("trade_no between", value1, value2, "trade_no");
            return (Criteria) this;
        }

        public Criteria andTrade_noNotBetween(String value1, String value2) {
            addCriterion("trade_no not between", value1, value2, "trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noIsNull() {
            addCriterion("out_trade_no is null");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noIsNotNull() {
            addCriterion("out_trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noEqualTo(String value) {
            addCriterion("out_trade_no =", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotEqualTo(String value) {
            addCriterion("out_trade_no <>", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noGreaterThan(String value) {
            addCriterion("out_trade_no >", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noGreaterThanOrEqualTo(String value) {
            addCriterion("out_trade_no >=", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLessThan(String value) {
            addCriterion("out_trade_no <", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLessThanOrEqualTo(String value) {
            addCriterion("out_trade_no <=", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLike(String value) {
            addCriterion("out_trade_no like", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotLike(String value) {
            addCriterion("out_trade_no not like", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noIn(List<String> values) {
            addCriterion("out_trade_no in", values, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotIn(List<String> values) {
            addCriterion("out_trade_no not in", values, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noBetween(String value1, String value2) {
            addCriterion("out_trade_no between", value1, value2, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotBetween(String value1, String value2) {
            addCriterion("out_trade_no not between", value1, value2, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noIsNull() {
            addCriterion("out_biz_no is null");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noIsNotNull() {
            addCriterion("out_biz_no is not null");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noEqualTo(String value) {
            addCriterion("out_biz_no =", value, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noNotEqualTo(String value) {
            addCriterion("out_biz_no <>", value, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noGreaterThan(String value) {
            addCriterion("out_biz_no >", value, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noGreaterThanOrEqualTo(String value) {
            addCriterion("out_biz_no >=", value, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noLessThan(String value) {
            addCriterion("out_biz_no <", value, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noLessThanOrEqualTo(String value) {
            addCriterion("out_biz_no <=", value, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noLike(String value) {
            addCriterion("out_biz_no like", value, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noNotLike(String value) {
            addCriterion("out_biz_no not like", value, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noIn(List<String> values) {
            addCriterion("out_biz_no in", values, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noNotIn(List<String> values) {
            addCriterion("out_biz_no not in", values, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noBetween(String value1, String value2) {
            addCriterion("out_biz_no between", value1, value2, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noNotBetween(String value1, String value2) {
            addCriterion("out_biz_no not between", value1, value2, "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andBuyer_idIsNull() {
            addCriterion("buyer_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyer_idIsNotNull() {
            addCriterion("buyer_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyer_idEqualTo(String value) {
            addCriterion("buyer_id =", value, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idNotEqualTo(String value) {
            addCriterion("buyer_id <>", value, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idGreaterThan(String value) {
            addCriterion("buyer_id >", value, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idGreaterThanOrEqualTo(String value) {
            addCriterion("buyer_id >=", value, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idLessThan(String value) {
            addCriterion("buyer_id <", value, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idLessThanOrEqualTo(String value) {
            addCriterion("buyer_id <=", value, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idLike(String value) {
            addCriterion("buyer_id like", value, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idNotLike(String value) {
            addCriterion("buyer_id not like", value, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idIn(List<String> values) {
            addCriterion("buyer_id in", values, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idNotIn(List<String> values) {
            addCriterion("buyer_id not in", values, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idBetween(String value1, String value2) {
            addCriterion("buyer_id between", value1, value2, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_idNotBetween(String value1, String value2) {
            addCriterion("buyer_id not between", value1, value2, "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idIsNull() {
            addCriterion("buyer_logon_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idIsNotNull() {
            addCriterion("buyer_logon_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idEqualTo(String value) {
            addCriterion("buyer_logon_id =", value, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idNotEqualTo(String value) {
            addCriterion("buyer_logon_id <>", value, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idGreaterThan(String value) {
            addCriterion("buyer_logon_id >", value, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idGreaterThanOrEqualTo(String value) {
            addCriterion("buyer_logon_id >=", value, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idLessThan(String value) {
            addCriterion("buyer_logon_id <", value, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idLessThanOrEqualTo(String value) {
            addCriterion("buyer_logon_id <=", value, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idLike(String value) {
            addCriterion("buyer_logon_id like", value, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idNotLike(String value) {
            addCriterion("buyer_logon_id not like", value, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idIn(List<String> values) {
            addCriterion("buyer_logon_id in", values, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idNotIn(List<String> values) {
            addCriterion("buyer_logon_id not in", values, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idBetween(String value1, String value2) {
            addCriterion("buyer_logon_id between", value1, value2, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idNotBetween(String value1, String value2) {
            addCriterion("buyer_logon_id not between", value1, value2, "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idIsNull() {
            addCriterion("seller_id is null");
            return (Criteria) this;
        }

        public Criteria andSeller_idIsNotNull() {
            addCriterion("seller_id is not null");
            return (Criteria) this;
        }

        public Criteria andSeller_idEqualTo(String value) {
            addCriterion("seller_id =", value, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idNotEqualTo(String value) {
            addCriterion("seller_id <>", value, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idGreaterThan(String value) {
            addCriterion("seller_id >", value, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idGreaterThanOrEqualTo(String value) {
            addCriterion("seller_id >=", value, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idLessThan(String value) {
            addCriterion("seller_id <", value, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idLessThanOrEqualTo(String value) {
            addCriterion("seller_id <=", value, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idLike(String value) {
            addCriterion("seller_id like", value, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idNotLike(String value) {
            addCriterion("seller_id not like", value, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idIn(List<String> values) {
            addCriterion("seller_id in", values, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idNotIn(List<String> values) {
            addCriterion("seller_id not in", values, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idBetween(String value1, String value2) {
            addCriterion("seller_id between", value1, value2, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idNotBetween(String value1, String value2) {
            addCriterion("seller_id not between", value1, value2, "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_emailIsNull() {
            addCriterion("seller_email is null");
            return (Criteria) this;
        }

        public Criteria andSeller_emailIsNotNull() {
            addCriterion("seller_email is not null");
            return (Criteria) this;
        }

        public Criteria andSeller_emailEqualTo(String value) {
            addCriterion("seller_email =", value, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailNotEqualTo(String value) {
            addCriterion("seller_email <>", value, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailGreaterThan(String value) {
            addCriterion("seller_email >", value, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailGreaterThanOrEqualTo(String value) {
            addCriterion("seller_email >=", value, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailLessThan(String value) {
            addCriterion("seller_email <", value, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailLessThanOrEqualTo(String value) {
            addCriterion("seller_email <=", value, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailLike(String value) {
            addCriterion("seller_email like", value, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailNotLike(String value) {
            addCriterion("seller_email not like", value, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailIn(List<String> values) {
            addCriterion("seller_email in", values, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailNotIn(List<String> values) {
            addCriterion("seller_email not in", values, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailBetween(String value1, String value2) {
            addCriterion("seller_email between", value1, value2, "seller_email");
            return (Criteria) this;
        }

        public Criteria andSeller_emailNotBetween(String value1, String value2) {
            addCriterion("seller_email not between", value1, value2, "seller_email");
            return (Criteria) this;
        }

        public Criteria andTrade_statusIsNull() {
            addCriterion("trade_status is null");
            return (Criteria) this;
        }

        public Criteria andTrade_statusIsNotNull() {
            addCriterion("trade_status is not null");
            return (Criteria) this;
        }

        public Criteria andTrade_statusEqualTo(String value) {
            addCriterion("trade_status =", value, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusNotEqualTo(String value) {
            addCriterion("trade_status <>", value, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusGreaterThan(String value) {
            addCriterion("trade_status >", value, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusGreaterThanOrEqualTo(String value) {
            addCriterion("trade_status >=", value, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusLessThan(String value) {
            addCriterion("trade_status <", value, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusLessThanOrEqualTo(String value) {
            addCriterion("trade_status <=", value, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusLike(String value) {
            addCriterion("trade_status like", value, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusNotLike(String value) {
            addCriterion("trade_status not like", value, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusIn(List<String> values) {
            addCriterion("trade_status in", values, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusNotIn(List<String> values) {
            addCriterion("trade_status not in", values, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusBetween(String value1, String value2) {
            addCriterion("trade_status between", value1, value2, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTrade_statusNotBetween(String value1, String value2) {
            addCriterion("trade_status not between", value1, value2, "trade_status");
            return (Criteria) this;
        }

        public Criteria andTotal_amountIsNull() {
            addCriterion("total_amount is null");
            return (Criteria) this;
        }

        public Criteria andTotal_amountIsNotNull() {
            addCriterion("total_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTotal_amountEqualTo(Integer value) {
            addCriterion("total_amount =", value, "total_amount");
            return (Criteria) this;
        }

        public Criteria andTotal_amountNotEqualTo(Integer value) {
            addCriterion("total_amount <>", value, "total_amount");
            return (Criteria) this;
        }

        public Criteria andTotal_amountGreaterThan(Integer value) {
            addCriterion("total_amount >", value, "total_amount");
            return (Criteria) this;
        }

        public Criteria andTotal_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_amount >=", value, "total_amount");
            return (Criteria) this;
        }

        public Criteria andTotal_amountLessThan(Integer value) {
            addCriterion("total_amount <", value, "total_amount");
            return (Criteria) this;
        }

        public Criteria andTotal_amountLessThanOrEqualTo(Integer value) {
            addCriterion("total_amount <=", value, "total_amount");
            return (Criteria) this;
        }

        public Criteria andTotal_amountIn(List<Integer> values) {
            addCriterion("total_amount in", values, "total_amount");
            return (Criteria) this;
        }

        public Criteria andTotal_amountNotIn(List<Integer> values) {
            addCriterion("total_amount not in", values, "total_amount");
            return (Criteria) this;
        }

        public Criteria andTotal_amountBetween(Integer value1, Integer value2) {
            addCriterion("total_amount between", value1, value2, "total_amount");
            return (Criteria) this;
        }

        public Criteria andTotal_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("total_amount not between", value1, value2, "total_amount");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountIsNull() {
            addCriterion("receipt_amount is null");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountIsNotNull() {
            addCriterion("receipt_amount is not null");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountEqualTo(Integer value) {
            addCriterion("receipt_amount =", value, "receipt_amount");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountNotEqualTo(Integer value) {
            addCriterion("receipt_amount <>", value, "receipt_amount");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountGreaterThan(Integer value) {
            addCriterion("receipt_amount >", value, "receipt_amount");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("receipt_amount >=", value, "receipt_amount");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountLessThan(Integer value) {
            addCriterion("receipt_amount <", value, "receipt_amount");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountLessThanOrEqualTo(Integer value) {
            addCriterion("receipt_amount <=", value, "receipt_amount");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountIn(List<Integer> values) {
            addCriterion("receipt_amount in", values, "receipt_amount");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountNotIn(List<Integer> values) {
            addCriterion("receipt_amount not in", values, "receipt_amount");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountBetween(Integer value1, Integer value2) {
            addCriterion("receipt_amount between", value1, value2, "receipt_amount");
            return (Criteria) this;
        }

        public Criteria andReceipt_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("receipt_amount not between", value1, value2, "receipt_amount");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountIsNull() {
            addCriterion("invoice_amount is null");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountIsNotNull() {
            addCriterion("invoice_amount is not null");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountEqualTo(Integer value) {
            addCriterion("invoice_amount =", value, "invoice_amount");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountNotEqualTo(Integer value) {
            addCriterion("invoice_amount <>", value, "invoice_amount");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountGreaterThan(Integer value) {
            addCriterion("invoice_amount >", value, "invoice_amount");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("invoice_amount >=", value, "invoice_amount");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountLessThan(Integer value) {
            addCriterion("invoice_amount <", value, "invoice_amount");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountLessThanOrEqualTo(Integer value) {
            addCriterion("invoice_amount <=", value, "invoice_amount");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountIn(List<Integer> values) {
            addCriterion("invoice_amount in", values, "invoice_amount");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountNotIn(List<Integer> values) {
            addCriterion("invoice_amount not in", values, "invoice_amount");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountBetween(Integer value1, Integer value2) {
            addCriterion("invoice_amount between", value1, value2, "invoice_amount");
            return (Criteria) this;
        }

        public Criteria andInvoice_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("invoice_amount not between", value1, value2, "invoice_amount");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountIsNull() {
            addCriterion("buyer_pay_amount is null");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountIsNotNull() {
            addCriterion("buyer_pay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountEqualTo(Integer value) {
            addCriterion("buyer_pay_amount =", value, "buyer_pay_amount");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountNotEqualTo(Integer value) {
            addCriterion("buyer_pay_amount <>", value, "buyer_pay_amount");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountGreaterThan(Integer value) {
            addCriterion("buyer_pay_amount >", value, "buyer_pay_amount");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("buyer_pay_amount >=", value, "buyer_pay_amount");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountLessThan(Integer value) {
            addCriterion("buyer_pay_amount <", value, "buyer_pay_amount");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountLessThanOrEqualTo(Integer value) {
            addCriterion("buyer_pay_amount <=", value, "buyer_pay_amount");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountIn(List<Integer> values) {
            addCriterion("buyer_pay_amount in", values, "buyer_pay_amount");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountNotIn(List<Integer> values) {
            addCriterion("buyer_pay_amount not in", values, "buyer_pay_amount");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountBetween(Integer value1, Integer value2) {
            addCriterion("buyer_pay_amount between", value1, value2, "buyer_pay_amount");
            return (Criteria) this;
        }

        public Criteria andBuyer_pay_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("buyer_pay_amount not between", value1, value2, "buyer_pay_amount");
            return (Criteria) this;
        }

        public Criteria andPoint_amountIsNull() {
            addCriterion("point_amount is null");
            return (Criteria) this;
        }

        public Criteria andPoint_amountIsNotNull() {
            addCriterion("point_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPoint_amountEqualTo(Integer value) {
            addCriterion("point_amount =", value, "point_amount");
            return (Criteria) this;
        }

        public Criteria andPoint_amountNotEqualTo(Integer value) {
            addCriterion("point_amount <>", value, "point_amount");
            return (Criteria) this;
        }

        public Criteria andPoint_amountGreaterThan(Integer value) {
            addCriterion("point_amount >", value, "point_amount");
            return (Criteria) this;
        }

        public Criteria andPoint_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("point_amount >=", value, "point_amount");
            return (Criteria) this;
        }

        public Criteria andPoint_amountLessThan(Integer value) {
            addCriterion("point_amount <", value, "point_amount");
            return (Criteria) this;
        }

        public Criteria andPoint_amountLessThanOrEqualTo(Integer value) {
            addCriterion("point_amount <=", value, "point_amount");
            return (Criteria) this;
        }

        public Criteria andPoint_amountIn(List<Integer> values) {
            addCriterion("point_amount in", values, "point_amount");
            return (Criteria) this;
        }

        public Criteria andPoint_amountNotIn(List<Integer> values) {
            addCriterion("point_amount not in", values, "point_amount");
            return (Criteria) this;
        }

        public Criteria andPoint_amountBetween(Integer value1, Integer value2) {
            addCriterion("point_amount between", value1, value2, "point_amount");
            return (Criteria) this;
        }

        public Criteria andPoint_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("point_amount not between", value1, value2, "point_amount");
            return (Criteria) this;
        }

        public Criteria andRefund_feeIsNull() {
            addCriterion("refund_fee is null");
            return (Criteria) this;
        }

        public Criteria andRefund_feeIsNotNull() {
            addCriterion("refund_fee is not null");
            return (Criteria) this;
        }

        public Criteria andRefund_feeEqualTo(Integer value) {
            addCriterion("refund_fee =", value, "refund_fee");
            return (Criteria) this;
        }

        public Criteria andRefund_feeNotEqualTo(Integer value) {
            addCriterion("refund_fee <>", value, "refund_fee");
            return (Criteria) this;
        }

        public Criteria andRefund_feeGreaterThan(Integer value) {
            addCriterion("refund_fee >", value, "refund_fee");
            return (Criteria) this;
        }

        public Criteria andRefund_feeGreaterThanOrEqualTo(Integer value) {
            addCriterion("refund_fee >=", value, "refund_fee");
            return (Criteria) this;
        }

        public Criteria andRefund_feeLessThan(Integer value) {
            addCriterion("refund_fee <", value, "refund_fee");
            return (Criteria) this;
        }

        public Criteria andRefund_feeLessThanOrEqualTo(Integer value) {
            addCriterion("refund_fee <=", value, "refund_fee");
            return (Criteria) this;
        }

        public Criteria andRefund_feeIn(List<Integer> values) {
            addCriterion("refund_fee in", values, "refund_fee");
            return (Criteria) this;
        }

        public Criteria andRefund_feeNotIn(List<Integer> values) {
            addCriterion("refund_fee not in", values, "refund_fee");
            return (Criteria) this;
        }

        public Criteria andRefund_feeBetween(Integer value1, Integer value2) {
            addCriterion("refund_fee between", value1, value2, "refund_fee");
            return (Criteria) this;
        }

        public Criteria andRefund_feeNotBetween(Integer value1, Integer value2) {
            addCriterion("refund_fee not between", value1, value2, "refund_fee");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("subject is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("subject =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("subject <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("subject >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("subject >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("subject <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("subject <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("subject like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("subject not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("subject in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("subject not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("subject between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("subject not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andBodyIsNull() {
            addCriterion("body is null");
            return (Criteria) this;
        }

        public Criteria andBodyIsNotNull() {
            addCriterion("body is not null");
            return (Criteria) this;
        }

        public Criteria andBodyEqualTo(String value) {
            addCriterion("body =", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotEqualTo(String value) {
            addCriterion("body <>", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThan(String value) {
            addCriterion("body >", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThanOrEqualTo(String value) {
            addCriterion("body >=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThan(String value) {
            addCriterion("body <", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThanOrEqualTo(String value) {
            addCriterion("body <=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLike(String value) {
            addCriterion("body like", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotLike(String value) {
            addCriterion("body not like", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyIn(List<String> values) {
            addCriterion("body in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotIn(List<String> values) {
            addCriterion("body not in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyBetween(String value1, String value2) {
            addCriterion("body between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotBetween(String value1, String value2) {
            addCriterion("body not between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andGmt_createIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmt_createIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmt_createEqualTo(String value) {
            addCriterion("gmt_create =", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createNotEqualTo(String value) {
            addCriterion("gmt_create <>", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createGreaterThan(String value) {
            addCriterion("gmt_create >", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createGreaterThanOrEqualTo(String value) {
            addCriterion("gmt_create >=", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createLessThan(String value) {
            addCriterion("gmt_create <", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createLessThanOrEqualTo(String value) {
            addCriterion("gmt_create <=", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createLike(String value) {
            addCriterion("gmt_create like", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createNotLike(String value) {
            addCriterion("gmt_create not like", value, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createIn(List<String> values) {
            addCriterion("gmt_create in", values, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createNotIn(List<String> values) {
            addCriterion("gmt_create not in", values, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createBetween(String value1, String value2) {
            addCriterion("gmt_create between", value1, value2, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_createNotBetween(String value1, String value2) {
            addCriterion("gmt_create not between", value1, value2, "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentIsNull() {
            addCriterion("gmt_payment is null");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentIsNotNull() {
            addCriterion("gmt_payment is not null");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentEqualTo(String value) {
            addCriterion("gmt_payment =", value, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentNotEqualTo(String value) {
            addCriterion("gmt_payment <>", value, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentGreaterThan(String value) {
            addCriterion("gmt_payment >", value, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentGreaterThanOrEqualTo(String value) {
            addCriterion("gmt_payment >=", value, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentLessThan(String value) {
            addCriterion("gmt_payment <", value, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentLessThanOrEqualTo(String value) {
            addCriterion("gmt_payment <=", value, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentLike(String value) {
            addCriterion("gmt_payment like", value, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentNotLike(String value) {
            addCriterion("gmt_payment not like", value, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentIn(List<String> values) {
            addCriterion("gmt_payment in", values, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentNotIn(List<String> values) {
            addCriterion("gmt_payment not in", values, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentBetween(String value1, String value2) {
            addCriterion("gmt_payment between", value1, value2, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentNotBetween(String value1, String value2) {
            addCriterion("gmt_payment not between", value1, value2, "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_refundIsNull() {
            addCriterion("gmt_refund is null");
            return (Criteria) this;
        }

        public Criteria andGmt_refundIsNotNull() {
            addCriterion("gmt_refund is not null");
            return (Criteria) this;
        }

        public Criteria andGmt_refundEqualTo(String value) {
            addCriterion("gmt_refund =", value, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundNotEqualTo(String value) {
            addCriterion("gmt_refund <>", value, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundGreaterThan(String value) {
            addCriterion("gmt_refund >", value, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundGreaterThanOrEqualTo(String value) {
            addCriterion("gmt_refund >=", value, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundLessThan(String value) {
            addCriterion("gmt_refund <", value, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundLessThanOrEqualTo(String value) {
            addCriterion("gmt_refund <=", value, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundLike(String value) {
            addCriterion("gmt_refund like", value, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundNotLike(String value) {
            addCriterion("gmt_refund not like", value, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundIn(List<String> values) {
            addCriterion("gmt_refund in", values, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundNotIn(List<String> values) {
            addCriterion("gmt_refund not in", values, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundBetween(String value1, String value2) {
            addCriterion("gmt_refund between", value1, value2, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_refundNotBetween(String value1, String value2) {
            addCriterion("gmt_refund not between", value1, value2, "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_closeIsNull() {
            addCriterion("gmt_close is null");
            return (Criteria) this;
        }

        public Criteria andGmt_closeIsNotNull() {
            addCriterion("gmt_close is not null");
            return (Criteria) this;
        }

        public Criteria andGmt_closeEqualTo(String value) {
            addCriterion("gmt_close =", value, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeNotEqualTo(String value) {
            addCriterion("gmt_close <>", value, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeGreaterThan(String value) {
            addCriterion("gmt_close >", value, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeGreaterThanOrEqualTo(String value) {
            addCriterion("gmt_close >=", value, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeLessThan(String value) {
            addCriterion("gmt_close <", value, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeLessThanOrEqualTo(String value) {
            addCriterion("gmt_close <=", value, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeLike(String value) {
            addCriterion("gmt_close like", value, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeNotLike(String value) {
            addCriterion("gmt_close not like", value, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeIn(List<String> values) {
            addCriterion("gmt_close in", values, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeNotIn(List<String> values) {
            addCriterion("gmt_close not in", values, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeBetween(String value1, String value2) {
            addCriterion("gmt_close between", value1, value2, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andGmt_closeNotBetween(String value1, String value2) {
            addCriterion("gmt_close not between", value1, value2, "gmt_close");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listIsNull() {
            addCriterion("fund_bill_list is null");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listIsNotNull() {
            addCriterion("fund_bill_list is not null");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listEqualTo(String value) {
            addCriterion("fund_bill_list =", value, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listNotEqualTo(String value) {
            addCriterion("fund_bill_list <>", value, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listGreaterThan(String value) {
            addCriterion("fund_bill_list >", value, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listGreaterThanOrEqualTo(String value) {
            addCriterion("fund_bill_list >=", value, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listLessThan(String value) {
            addCriterion("fund_bill_list <", value, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listLessThanOrEqualTo(String value) {
            addCriterion("fund_bill_list <=", value, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listLike(String value) {
            addCriterion("fund_bill_list like", value, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listNotLike(String value) {
            addCriterion("fund_bill_list not like", value, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listIn(List<String> values) {
            addCriterion("fund_bill_list in", values, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listNotIn(List<String> values) {
            addCriterion("fund_bill_list not in", values, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listBetween(String value1, String value2) {
            addCriterion("fund_bill_list between", value1, value2, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listNotBetween(String value1, String value2) {
            addCriterion("fund_bill_list not between", value1, value2, "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsIsNull() {
            addCriterion("passback_params is null");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsIsNotNull() {
            addCriterion("passback_params is not null");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsEqualTo(String value) {
            addCriterion("passback_params =", value, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsNotEqualTo(String value) {
            addCriterion("passback_params <>", value, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsGreaterThan(String value) {
            addCriterion("passback_params >", value, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsGreaterThanOrEqualTo(String value) {
            addCriterion("passback_params >=", value, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsLessThan(String value) {
            addCriterion("passback_params <", value, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsLessThanOrEqualTo(String value) {
            addCriterion("passback_params <=", value, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsLike(String value) {
            addCriterion("passback_params like", value, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsNotLike(String value) {
            addCriterion("passback_params not like", value, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsIn(List<String> values) {
            addCriterion("passback_params in", values, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsNotIn(List<String> values) {
            addCriterion("passback_params not in", values, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsBetween(String value1, String value2) {
            addCriterion("passback_params between", value1, value2, "passback_params");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsNotBetween(String value1, String value2) {
            addCriterion("passback_params not between", value1, value2, "passback_params");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listIsNull() {
            addCriterion("voucher_detail_list is null");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listIsNotNull() {
            addCriterion("voucher_detail_list is not null");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listEqualTo(String value) {
            addCriterion("voucher_detail_list =", value, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listNotEqualTo(String value) {
            addCriterion("voucher_detail_list <>", value, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listGreaterThan(String value) {
            addCriterion("voucher_detail_list >", value, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listGreaterThanOrEqualTo(String value) {
            addCriterion("voucher_detail_list >=", value, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listLessThan(String value) {
            addCriterion("voucher_detail_list <", value, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listLessThanOrEqualTo(String value) {
            addCriterion("voucher_detail_list <=", value, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listLike(String value) {
            addCriterion("voucher_detail_list like", value, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listNotLike(String value) {
            addCriterion("voucher_detail_list not like", value, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listIn(List<String> values) {
            addCriterion("voucher_detail_list in", values, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listNotIn(List<String> values) {
            addCriterion("voucher_detail_list not in", values, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listBetween(String value1, String value2) {
            addCriterion("voucher_detail_list between", value1, value2, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listNotBetween(String value1, String value2) {
            addCriterion("voucher_detail_list not between", value1, value2, "voucher_detail_list");
            return (Criteria) this;
        }

        public Criteria andNotify_idLikeInsensitive(String value) {
            addCriterion("upper(notify_id) like", value.toUpperCase(), "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_timeLikeInsensitive(String value) {
            addCriterion("upper(notify_time) like", value.toUpperCase(), "notify_time");
            return (Criteria) this;
        }

        public Criteria andNotify_typeLikeInsensitive(String value) {
            addCriterion("upper(notify_type) like", value.toUpperCase(), "notify_type");
            return (Criteria) this;
        }

        public Criteria andApp_idLikeInsensitive(String value) {
            addCriterion("upper(app_id) like", value.toUpperCase(), "app_id");
            return (Criteria) this;
        }

        public Criteria andCharsetLikeInsensitive(String value) {
            addCriterion("upper(charset) like", value.toUpperCase(), "charset");
            return (Criteria) this;
        }

        public Criteria andVersionLikeInsensitive(String value) {
            addCriterion("upper(version) like", value.toUpperCase(), "version");
            return (Criteria) this;
        }

        public Criteria andSign_typeLikeInsensitive(String value) {
            addCriterion("upper(sign_type) like", value.toUpperCase(), "sign_type");
            return (Criteria) this;
        }

        public Criteria andSignLikeInsensitive(String value) {
            addCriterion("upper(sign) like", value.toUpperCase(), "sign");
            return (Criteria) this;
        }

        public Criteria andTrade_noLikeInsensitive(String value) {
            addCriterion("upper(trade_no) like", value.toUpperCase(), "trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLikeInsensitive(String value) {
            addCriterion("upper(out_trade_no) like", value.toUpperCase(), "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_biz_noLikeInsensitive(String value) {
            addCriterion("upper(out_biz_no) like", value.toUpperCase(), "out_biz_no");
            return (Criteria) this;
        }

        public Criteria andBuyer_idLikeInsensitive(String value) {
            addCriterion("upper(buyer_id) like", value.toUpperCase(), "buyer_id");
            return (Criteria) this;
        }

        public Criteria andBuyer_logon_idLikeInsensitive(String value) {
            addCriterion("upper(buyer_logon_id) like", value.toUpperCase(), "buyer_logon_id");
            return (Criteria) this;
        }

        public Criteria andSeller_idLikeInsensitive(String value) {
            addCriterion("upper(seller_id) like", value.toUpperCase(), "seller_id");
            return (Criteria) this;
        }

        public Criteria andSeller_emailLikeInsensitive(String value) {
            addCriterion("upper(seller_email) like", value.toUpperCase(), "seller_email");
            return (Criteria) this;
        }

        public Criteria andTrade_statusLikeInsensitive(String value) {
            addCriterion("upper(trade_status) like", value.toUpperCase(), "trade_status");
            return (Criteria) this;
        }

        public Criteria andSubjectLikeInsensitive(String value) {
            addCriterion("upper(subject) like", value.toUpperCase(), "subject");
            return (Criteria) this;
        }

        public Criteria andBodyLikeInsensitive(String value) {
            addCriterion("upper(body) like", value.toUpperCase(), "body");
            return (Criteria) this;
        }

        public Criteria andGmt_createLikeInsensitive(String value) {
            addCriterion("upper(gmt_create) like", value.toUpperCase(), "gmt_create");
            return (Criteria) this;
        }

        public Criteria andGmt_paymentLikeInsensitive(String value) {
            addCriterion("upper(gmt_payment) like", value.toUpperCase(), "gmt_payment");
            return (Criteria) this;
        }

        public Criteria andGmt_refundLikeInsensitive(String value) {
            addCriterion("upper(gmt_refund) like", value.toUpperCase(), "gmt_refund");
            return (Criteria) this;
        }

        public Criteria andGmt_closeLikeInsensitive(String value) {
            addCriterion("upper(gmt_close) like", value.toUpperCase(), "gmt_close");
            return (Criteria) this;
        }

        public Criteria andFund_bill_listLikeInsensitive(String value) {
            addCriterion("upper(fund_bill_list) like", value.toUpperCase(), "fund_bill_list");
            return (Criteria) this;
        }

        public Criteria andPassback_paramsLikeInsensitive(String value) {
            addCriterion("upper(passback_params) like", value.toUpperCase(), "passback_params");
            return (Criteria) this;
        }

        public Criteria andVoucher_detail_listLikeInsensitive(String value) {
            addCriterion("upper(voucher_detail_list) like", value.toUpperCase(), "voucher_detail_list");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_ali_notify
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 01 16:58:47 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table pay_ali_notify
     *
     * @mbg.generated Fri Jun 01 16:58:47 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]
		//--------------------------------------------------					
						notify_id(1,Types.VARCHAR,false),					
						notify_time(2,Types.VARCHAR,false),					
						notify_type(2,Types.VARCHAR,false),					
						app_id(2,Types.VARCHAR,false),					
						charset(2,Types.VARCHAR,false),					
						version(2,Types.VARCHAR,false),					
						sign_type(2,Types.VARCHAR,false),					
						sign(2,Types.VARCHAR,false),					
						trade_no(2,Types.VARCHAR,false),					
						out_trade_no(2,Types.VARCHAR,false),					
						out_biz_no(2,Types.VARCHAR,false),					
						buyer_id(2,Types.VARCHAR,false),					
						buyer_logon_id(2,Types.VARCHAR,false),					
						seller_id(2,Types.VARCHAR,false),					
						seller_email(2,Types.VARCHAR,false),					
						trade_status(2,Types.VARCHAR,false),					
						total_amount(2,Types.INTEGER,false),					
						receipt_amount(2,Types.INTEGER,false),					
						invoice_amount(2,Types.INTEGER,false),					
						buyer_pay_amount(2,Types.INTEGER,false),					
						point_amount(2,Types.INTEGER,false),					
						refund_fee(2,Types.INTEGER,false),					
						subject(2,Types.VARCHAR,false),					
						body(2,Types.VARCHAR,false),					
						gmt_create(2,Types.VARCHAR,false),					
						gmt_payment(2,Types.VARCHAR,false),					
						gmt_refund(2,Types.VARCHAR,false),					
						gmt_close(2,Types.VARCHAR,false),					
						fund_bill_list(2,Types.VARCHAR,false),					
						passback_params(2,Types.VARCHAR,false),					
						voucher_detail_list(2,Types.VARCHAR,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}