package com.aobei.train.model;

import com.aobei.train.model.PayWxNotifyExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class PayWxNotifyExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_wx_notify
     *
     * @mbg.generated Mon Feb 12 10:00:28 CST 2018
     */
    public PayWxNotifyExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_wx_notify
     *
     * @mbg.generated Mon Feb 12 10:00:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_wx_notify
     *
     * @mbg.generated Mon Feb 12 10:00:28 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_wx_notify
     *
     * @mbg.generated Mon Feb 12 10:00:28 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_wx_notify
     *
     * @mbg.generated Mon Feb 12 10:00:28 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andTransaction_idIsNull() {
            addCriterion("transaction_id is null");
            return (Criteria) this;
        }

        public Criteria andTransaction_idIsNotNull() {
            addCriterion("transaction_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransaction_idEqualTo(String value) {
            addCriterion("transaction_id =", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idNotEqualTo(String value) {
            addCriterion("transaction_id <>", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idGreaterThan(String value) {
            addCriterion("transaction_id >", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_id >=", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idLessThan(String value) {
            addCriterion("transaction_id <", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idLessThanOrEqualTo(String value) {
            addCriterion("transaction_id <=", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idLike(String value) {
            addCriterion("transaction_id like", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idNotLike(String value) {
            addCriterion("transaction_id not like", value, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idIn(List<String> values) {
            addCriterion("transaction_id in", values, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idNotIn(List<String> values) {
            addCriterion("transaction_id not in", values, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idBetween(String value1, String value2) {
            addCriterion("transaction_id between", value1, value2, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andTransaction_idNotBetween(String value1, String value2) {
            addCriterion("transaction_id not between", value1, value2, "transaction_id");
            return (Criteria) this;
        }

        public Criteria andAppidIsNull() {
            addCriterion("appid is null");
            return (Criteria) this;
        }

        public Criteria andAppidIsNotNull() {
            addCriterion("appid is not null");
            return (Criteria) this;
        }

        public Criteria andAppidEqualTo(String value) {
            addCriterion("appid =", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotEqualTo(String value) {
            addCriterion("appid <>", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThan(String value) {
            addCriterion("appid >", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThanOrEqualTo(String value) {
            addCriterion("appid >=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThan(String value) {
            addCriterion("appid <", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThanOrEqualTo(String value) {
            addCriterion("appid <=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLike(String value) {
            addCriterion("appid like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotLike(String value) {
            addCriterion("appid not like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidIn(List<String> values) {
            addCriterion("appid in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotIn(List<String> values) {
            addCriterion("appid not in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidBetween(String value1, String value2) {
            addCriterion("appid between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotBetween(String value1, String value2) {
            addCriterion("appid not between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andSign_typeIsNull() {
            addCriterion("sign_type is null");
            return (Criteria) this;
        }

        public Criteria andSign_typeIsNotNull() {
            addCriterion("sign_type is not null");
            return (Criteria) this;
        }

        public Criteria andSign_typeEqualTo(String value) {
            addCriterion("sign_type =", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeNotEqualTo(String value) {
            addCriterion("sign_type <>", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeGreaterThan(String value) {
            addCriterion("sign_type >", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeGreaterThanOrEqualTo(String value) {
            addCriterion("sign_type >=", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeLessThan(String value) {
            addCriterion("sign_type <", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeLessThanOrEqualTo(String value) {
            addCriterion("sign_type <=", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeLike(String value) {
            addCriterion("sign_type like", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeNotLike(String value) {
            addCriterion("sign_type not like", value, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeIn(List<String> values) {
            addCriterion("sign_type in", values, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeNotIn(List<String> values) {
            addCriterion("sign_type not in", values, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeBetween(String value1, String value2) {
            addCriterion("sign_type between", value1, value2, "sign_type");
            return (Criteria) this;
        }

        public Criteria andSign_typeNotBetween(String value1, String value2) {
            addCriterion("sign_type not between", value1, value2, "sign_type");
            return (Criteria) this;
        }

        public Criteria andInput_charsetIsNull() {
            addCriterion("input_charset is null");
            return (Criteria) this;
        }

        public Criteria andInput_charsetIsNotNull() {
            addCriterion("input_charset is not null");
            return (Criteria) this;
        }

        public Criteria andInput_charsetEqualTo(String value) {
            addCriterion("input_charset =", value, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetNotEqualTo(String value) {
            addCriterion("input_charset <>", value, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetGreaterThan(String value) {
            addCriterion("input_charset >", value, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetGreaterThanOrEqualTo(String value) {
            addCriterion("input_charset >=", value, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetLessThan(String value) {
            addCriterion("input_charset <", value, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetLessThanOrEqualTo(String value) {
            addCriterion("input_charset <=", value, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetLike(String value) {
            addCriterion("input_charset like", value, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetNotLike(String value) {
            addCriterion("input_charset not like", value, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetIn(List<String> values) {
            addCriterion("input_charset in", values, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetNotIn(List<String> values) {
            addCriterion("input_charset not in", values, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetBetween(String value1, String value2) {
            addCriterion("input_charset between", value1, value2, "input_charset");
            return (Criteria) this;
        }

        public Criteria andInput_charsetNotBetween(String value1, String value2) {
            addCriterion("input_charset not between", value1, value2, "input_charset");
            return (Criteria) this;
        }

        public Criteria andSignIsNull() {
            addCriterion("sign is null");
            return (Criteria) this;
        }

        public Criteria andSignIsNotNull() {
            addCriterion("sign is not null");
            return (Criteria) this;
        }

        public Criteria andSignEqualTo(String value) {
            addCriterion("sign =", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotEqualTo(String value) {
            addCriterion("sign <>", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThan(String value) {
            addCriterion("sign >", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignGreaterThanOrEqualTo(String value) {
            addCriterion("sign >=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThan(String value) {
            addCriterion("sign <", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLessThanOrEqualTo(String value) {
            addCriterion("sign <=", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignLike(String value) {
            addCriterion("sign like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotLike(String value) {
            addCriterion("sign not like", value, "sign");
            return (Criteria) this;
        }

        public Criteria andSignIn(List<String> values) {
            addCriterion("sign in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotIn(List<String> values) {
            addCriterion("sign not in", values, "sign");
            return (Criteria) this;
        }

        public Criteria andSignBetween(String value1, String value2) {
            addCriterion("sign between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andSignNotBetween(String value1, String value2) {
            addCriterion("sign not between", value1, value2, "sign");
            return (Criteria) this;
        }

        public Criteria andTrade_modeIsNull() {
            addCriterion("trade_mode is null");
            return (Criteria) this;
        }

        public Criteria andTrade_modeIsNotNull() {
            addCriterion("trade_mode is not null");
            return (Criteria) this;
        }

        public Criteria andTrade_modeEqualTo(Integer value) {
            addCriterion("trade_mode =", value, "trade_mode");
            return (Criteria) this;
        }

        public Criteria andTrade_modeNotEqualTo(Integer value) {
            addCriterion("trade_mode <>", value, "trade_mode");
            return (Criteria) this;
        }

        public Criteria andTrade_modeGreaterThan(Integer value) {
            addCriterion("trade_mode >", value, "trade_mode");
            return (Criteria) this;
        }

        public Criteria andTrade_modeGreaterThanOrEqualTo(Integer value) {
            addCriterion("trade_mode >=", value, "trade_mode");
            return (Criteria) this;
        }

        public Criteria andTrade_modeLessThan(Integer value) {
            addCriterion("trade_mode <", value, "trade_mode");
            return (Criteria) this;
        }

        public Criteria andTrade_modeLessThanOrEqualTo(Integer value) {
            addCriterion("trade_mode <=", value, "trade_mode");
            return (Criteria) this;
        }

        public Criteria andTrade_modeIn(List<Integer> values) {
            addCriterion("trade_mode in", values, "trade_mode");
            return (Criteria) this;
        }

        public Criteria andTrade_modeNotIn(List<Integer> values) {
            addCriterion("trade_mode not in", values, "trade_mode");
            return (Criteria) this;
        }

        public Criteria andTrade_modeBetween(Integer value1, Integer value2) {
            addCriterion("trade_mode between", value1, value2, "trade_mode");
            return (Criteria) this;
        }

        public Criteria andTrade_modeNotBetween(Integer value1, Integer value2) {
            addCriterion("trade_mode not between", value1, value2, "trade_mode");
            return (Criteria) this;
        }

        public Criteria andTrade_stateIsNull() {
            addCriterion("trade_state is null");
            return (Criteria) this;
        }

        public Criteria andTrade_stateIsNotNull() {
            addCriterion("trade_state is not null");
            return (Criteria) this;
        }

        public Criteria andTrade_stateEqualTo(Integer value) {
            addCriterion("trade_state =", value, "trade_state");
            return (Criteria) this;
        }

        public Criteria andTrade_stateNotEqualTo(Integer value) {
            addCriterion("trade_state <>", value, "trade_state");
            return (Criteria) this;
        }

        public Criteria andTrade_stateGreaterThan(Integer value) {
            addCriterion("trade_state >", value, "trade_state");
            return (Criteria) this;
        }

        public Criteria andTrade_stateGreaterThanOrEqualTo(Integer value) {
            addCriterion("trade_state >=", value, "trade_state");
            return (Criteria) this;
        }

        public Criteria andTrade_stateLessThan(Integer value) {
            addCriterion("trade_state <", value, "trade_state");
            return (Criteria) this;
        }

        public Criteria andTrade_stateLessThanOrEqualTo(Integer value) {
            addCriterion("trade_state <=", value, "trade_state");
            return (Criteria) this;
        }

        public Criteria andTrade_stateIn(List<Integer> values) {
            addCriterion("trade_state in", values, "trade_state");
            return (Criteria) this;
        }

        public Criteria andTrade_stateNotIn(List<Integer> values) {
            addCriterion("trade_state not in", values, "trade_state");
            return (Criteria) this;
        }

        public Criteria andTrade_stateBetween(Integer value1, Integer value2) {
            addCriterion("trade_state between", value1, value2, "trade_state");
            return (Criteria) this;
        }

        public Criteria andTrade_stateNotBetween(Integer value1, Integer value2) {
            addCriterion("trade_state not between", value1, value2, "trade_state");
            return (Criteria) this;
        }

        public Criteria andPartnerIsNull() {
            addCriterion("partner is null");
            return (Criteria) this;
        }

        public Criteria andPartnerIsNotNull() {
            addCriterion("partner is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerEqualTo(String value) {
            addCriterion("partner =", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerNotEqualTo(String value) {
            addCriterion("partner <>", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerGreaterThan(String value) {
            addCriterion("partner >", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerGreaterThanOrEqualTo(String value) {
            addCriterion("partner >=", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerLessThan(String value) {
            addCriterion("partner <", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerLessThanOrEqualTo(String value) {
            addCriterion("partner <=", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerLike(String value) {
            addCriterion("partner like", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerNotLike(String value) {
            addCriterion("partner not like", value, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerIn(List<String> values) {
            addCriterion("partner in", values, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerNotIn(List<String> values) {
            addCriterion("partner not in", values, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerBetween(String value1, String value2) {
            addCriterion("partner between", value1, value2, "partner");
            return (Criteria) this;
        }

        public Criteria andPartnerNotBetween(String value1, String value2) {
            addCriterion("partner not between", value1, value2, "partner");
            return (Criteria) this;
        }

        public Criteria andBank_typeIsNull() {
            addCriterion("bank_type is null");
            return (Criteria) this;
        }

        public Criteria andBank_typeIsNotNull() {
            addCriterion("bank_type is not null");
            return (Criteria) this;
        }

        public Criteria andBank_typeEqualTo(String value) {
            addCriterion("bank_type =", value, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeNotEqualTo(String value) {
            addCriterion("bank_type <>", value, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeGreaterThan(String value) {
            addCriterion("bank_type >", value, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeGreaterThanOrEqualTo(String value) {
            addCriterion("bank_type >=", value, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeLessThan(String value) {
            addCriterion("bank_type <", value, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeLessThanOrEqualTo(String value) {
            addCriterion("bank_type <=", value, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeLike(String value) {
            addCriterion("bank_type like", value, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeNotLike(String value) {
            addCriterion("bank_type not like", value, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeIn(List<String> values) {
            addCriterion("bank_type in", values, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeNotIn(List<String> values) {
            addCriterion("bank_type not in", values, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeBetween(String value1, String value2) {
            addCriterion("bank_type between", value1, value2, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_typeNotBetween(String value1, String value2) {
            addCriterion("bank_type not between", value1, value2, "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_billnoIsNull() {
            addCriterion("bank_billno is null");
            return (Criteria) this;
        }

        public Criteria andBank_billnoIsNotNull() {
            addCriterion("bank_billno is not null");
            return (Criteria) this;
        }

        public Criteria andBank_billnoEqualTo(String value) {
            addCriterion("bank_billno =", value, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoNotEqualTo(String value) {
            addCriterion("bank_billno <>", value, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoGreaterThan(String value) {
            addCriterion("bank_billno >", value, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoGreaterThanOrEqualTo(String value) {
            addCriterion("bank_billno >=", value, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoLessThan(String value) {
            addCriterion("bank_billno <", value, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoLessThanOrEqualTo(String value) {
            addCriterion("bank_billno <=", value, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoLike(String value) {
            addCriterion("bank_billno like", value, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoNotLike(String value) {
            addCriterion("bank_billno not like", value, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoIn(List<String> values) {
            addCriterion("bank_billno in", values, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoNotIn(List<String> values) {
            addCriterion("bank_billno not in", values, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoBetween(String value1, String value2) {
            addCriterion("bank_billno between", value1, value2, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andBank_billnoNotBetween(String value1, String value2) {
            addCriterion("bank_billno not between", value1, value2, "bank_billno");
            return (Criteria) this;
        }

        public Criteria andTotal_feeIsNull() {
            addCriterion("total_fee is null");
            return (Criteria) this;
        }

        public Criteria andTotal_feeIsNotNull() {
            addCriterion("total_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTotal_feeEqualTo(Integer value) {
            addCriterion("total_fee =", value, "total_fee");
            return (Criteria) this;
        }

        public Criteria andTotal_feeNotEqualTo(Integer value) {
            addCriterion("total_fee <>", value, "total_fee");
            return (Criteria) this;
        }

        public Criteria andTotal_feeGreaterThan(Integer value) {
            addCriterion("total_fee >", value, "total_fee");
            return (Criteria) this;
        }

        public Criteria andTotal_feeGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_fee >=", value, "total_fee");
            return (Criteria) this;
        }

        public Criteria andTotal_feeLessThan(Integer value) {
            addCriterion("total_fee <", value, "total_fee");
            return (Criteria) this;
        }

        public Criteria andTotal_feeLessThanOrEqualTo(Integer value) {
            addCriterion("total_fee <=", value, "total_fee");
            return (Criteria) this;
        }

        public Criteria andTotal_feeIn(List<Integer> values) {
            addCriterion("total_fee in", values, "total_fee");
            return (Criteria) this;
        }

        public Criteria andTotal_feeNotIn(List<Integer> values) {
            addCriterion("total_fee not in", values, "total_fee");
            return (Criteria) this;
        }

        public Criteria andTotal_feeBetween(Integer value1, Integer value2) {
            addCriterion("total_fee between", value1, value2, "total_fee");
            return (Criteria) this;
        }

        public Criteria andTotal_feeNotBetween(Integer value1, Integer value2) {
            addCriterion("total_fee not between", value1, value2, "total_fee");
            return (Criteria) this;
        }

        public Criteria andFee_typeIsNull() {
            addCriterion("fee_type is null");
            return (Criteria) this;
        }

        public Criteria andFee_typeIsNotNull() {
            addCriterion("fee_type is not null");
            return (Criteria) this;
        }

        public Criteria andFee_typeEqualTo(String value) {
            addCriterion("fee_type =", value, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeNotEqualTo(String value) {
            addCriterion("fee_type <>", value, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeGreaterThan(String value) {
            addCriterion("fee_type >", value, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeGreaterThanOrEqualTo(String value) {
            addCriterion("fee_type >=", value, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeLessThan(String value) {
            addCriterion("fee_type <", value, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeLessThanOrEqualTo(String value) {
            addCriterion("fee_type <=", value, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeLike(String value) {
            addCriterion("fee_type like", value, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeNotLike(String value) {
            addCriterion("fee_type not like", value, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeIn(List<String> values) {
            addCriterion("fee_type in", values, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeNotIn(List<String> values) {
            addCriterion("fee_type not in", values, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeBetween(String value1, String value2) {
            addCriterion("fee_type between", value1, value2, "fee_type");
            return (Criteria) this;
        }

        public Criteria andFee_typeNotBetween(String value1, String value2) {
            addCriterion("fee_type not between", value1, value2, "fee_type");
            return (Criteria) this;
        }

        public Criteria andNotify_idIsNull() {
            addCriterion("notify_id is null");
            return (Criteria) this;
        }

        public Criteria andNotify_idIsNotNull() {
            addCriterion("notify_id is not null");
            return (Criteria) this;
        }

        public Criteria andNotify_idEqualTo(String value) {
            addCriterion("notify_id =", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idNotEqualTo(String value) {
            addCriterion("notify_id <>", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idGreaterThan(String value) {
            addCriterion("notify_id >", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idGreaterThanOrEqualTo(String value) {
            addCriterion("notify_id >=", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idLessThan(String value) {
            addCriterion("notify_id <", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idLessThanOrEqualTo(String value) {
            addCriterion("notify_id <=", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idLike(String value) {
            addCriterion("notify_id like", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idNotLike(String value) {
            addCriterion("notify_id not like", value, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idIn(List<String> values) {
            addCriterion("notify_id in", values, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idNotIn(List<String> values) {
            addCriterion("notify_id not in", values, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idBetween(String value1, String value2) {
            addCriterion("notify_id between", value1, value2, "notify_id");
            return (Criteria) this;
        }

        public Criteria andNotify_idNotBetween(String value1, String value2) {
            addCriterion("notify_id not between", value1, value2, "notify_id");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noIsNull() {
            addCriterion("out_trade_no is null");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noIsNotNull() {
            addCriterion("out_trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noEqualTo(String value) {
            addCriterion("out_trade_no =", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotEqualTo(String value) {
            addCriterion("out_trade_no <>", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noGreaterThan(String value) {
            addCriterion("out_trade_no >", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noGreaterThanOrEqualTo(String value) {
            addCriterion("out_trade_no >=", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLessThan(String value) {
            addCriterion("out_trade_no <", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLessThanOrEqualTo(String value) {
            addCriterion("out_trade_no <=", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLike(String value) {
            addCriterion("out_trade_no like", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotLike(String value) {
            addCriterion("out_trade_no not like", value, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noIn(List<String> values) {
            addCriterion("out_trade_no in", values, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotIn(List<String> values) {
            addCriterion("out_trade_no not in", values, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noBetween(String value1, String value2) {
            addCriterion("out_trade_no between", value1, value2, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noNotBetween(String value1, String value2) {
            addCriterion("out_trade_no not between", value1, value2, "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andAttachIsNull() {
            addCriterion("attach is null");
            return (Criteria) this;
        }

        public Criteria andAttachIsNotNull() {
            addCriterion("attach is not null");
            return (Criteria) this;
        }

        public Criteria andAttachEqualTo(String value) {
            addCriterion("attach =", value, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachNotEqualTo(String value) {
            addCriterion("attach <>", value, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachGreaterThan(String value) {
            addCriterion("attach >", value, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachGreaterThanOrEqualTo(String value) {
            addCriterion("attach >=", value, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachLessThan(String value) {
            addCriterion("attach <", value, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachLessThanOrEqualTo(String value) {
            addCriterion("attach <=", value, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachLike(String value) {
            addCriterion("attach like", value, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachNotLike(String value) {
            addCriterion("attach not like", value, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachIn(List<String> values) {
            addCriterion("attach in", values, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachNotIn(List<String> values) {
            addCriterion("attach not in", values, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachBetween(String value1, String value2) {
            addCriterion("attach between", value1, value2, "attach");
            return (Criteria) this;
        }

        public Criteria andAttachNotBetween(String value1, String value2) {
            addCriterion("attach not between", value1, value2, "attach");
            return (Criteria) this;
        }

        public Criteria andTime_endIsNull() {
            addCriterion("time_end is null");
            return (Criteria) this;
        }

        public Criteria andTime_endIsNotNull() {
            addCriterion("time_end is not null");
            return (Criteria) this;
        }

        public Criteria andTime_endEqualTo(String value) {
            addCriterion("time_end =", value, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endNotEqualTo(String value) {
            addCriterion("time_end <>", value, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endGreaterThan(String value) {
            addCriterion("time_end >", value, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endGreaterThanOrEqualTo(String value) {
            addCriterion("time_end >=", value, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endLessThan(String value) {
            addCriterion("time_end <", value, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endLessThanOrEqualTo(String value) {
            addCriterion("time_end <=", value, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endLike(String value) {
            addCriterion("time_end like", value, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endNotLike(String value) {
            addCriterion("time_end not like", value, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endIn(List<String> values) {
            addCriterion("time_end in", values, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endNotIn(List<String> values) {
            addCriterion("time_end not in", values, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endBetween(String value1, String value2) {
            addCriterion("time_end between", value1, value2, "time_end");
            return (Criteria) this;
        }

        public Criteria andTime_endNotBetween(String value1, String value2) {
            addCriterion("time_end not between", value1, value2, "time_end");
            return (Criteria) this;
        }

        public Criteria andTransport_feeIsNull() {
            addCriterion("transport_fee is null");
            return (Criteria) this;
        }

        public Criteria andTransport_feeIsNotNull() {
            addCriterion("transport_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTransport_feeEqualTo(Integer value) {
            addCriterion("transport_fee =", value, "transport_fee");
            return (Criteria) this;
        }

        public Criteria andTransport_feeNotEqualTo(Integer value) {
            addCriterion("transport_fee <>", value, "transport_fee");
            return (Criteria) this;
        }

        public Criteria andTransport_feeGreaterThan(Integer value) {
            addCriterion("transport_fee >", value, "transport_fee");
            return (Criteria) this;
        }

        public Criteria andTransport_feeGreaterThanOrEqualTo(Integer value) {
            addCriterion("transport_fee >=", value, "transport_fee");
            return (Criteria) this;
        }

        public Criteria andTransport_feeLessThan(Integer value) {
            addCriterion("transport_fee <", value, "transport_fee");
            return (Criteria) this;
        }

        public Criteria andTransport_feeLessThanOrEqualTo(Integer value) {
            addCriterion("transport_fee <=", value, "transport_fee");
            return (Criteria) this;
        }

        public Criteria andTransport_feeIn(List<Integer> values) {
            addCriterion("transport_fee in", values, "transport_fee");
            return (Criteria) this;
        }

        public Criteria andTransport_feeNotIn(List<Integer> values) {
            addCriterion("transport_fee not in", values, "transport_fee");
            return (Criteria) this;
        }

        public Criteria andTransport_feeBetween(Integer value1, Integer value2) {
            addCriterion("transport_fee between", value1, value2, "transport_fee");
            return (Criteria) this;
        }

        public Criteria andTransport_feeNotBetween(Integer value1, Integer value2) {
            addCriterion("transport_fee not between", value1, value2, "transport_fee");
            return (Criteria) this;
        }

        public Criteria andProduct_feeIsNull() {
            addCriterion("product_fee is null");
            return (Criteria) this;
        }

        public Criteria andProduct_feeIsNotNull() {
            addCriterion("product_fee is not null");
            return (Criteria) this;
        }

        public Criteria andProduct_feeEqualTo(Integer value) {
            addCriterion("product_fee =", value, "product_fee");
            return (Criteria) this;
        }

        public Criteria andProduct_feeNotEqualTo(Integer value) {
            addCriterion("product_fee <>", value, "product_fee");
            return (Criteria) this;
        }

        public Criteria andProduct_feeGreaterThan(Integer value) {
            addCriterion("product_fee >", value, "product_fee");
            return (Criteria) this;
        }

        public Criteria andProduct_feeGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_fee >=", value, "product_fee");
            return (Criteria) this;
        }

        public Criteria andProduct_feeLessThan(Integer value) {
            addCriterion("product_fee <", value, "product_fee");
            return (Criteria) this;
        }

        public Criteria andProduct_feeLessThanOrEqualTo(Integer value) {
            addCriterion("product_fee <=", value, "product_fee");
            return (Criteria) this;
        }

        public Criteria andProduct_feeIn(List<Integer> values) {
            addCriterion("product_fee in", values, "product_fee");
            return (Criteria) this;
        }

        public Criteria andProduct_feeNotIn(List<Integer> values) {
            addCriterion("product_fee not in", values, "product_fee");
            return (Criteria) this;
        }

        public Criteria andProduct_feeBetween(Integer value1, Integer value2) {
            addCriterion("product_fee between", value1, value2, "product_fee");
            return (Criteria) this;
        }

        public Criteria andProduct_feeNotBetween(Integer value1, Integer value2) {
            addCriterion("product_fee not between", value1, value2, "product_fee");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNull() {
            addCriterion("discount is null");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNotNull() {
            addCriterion("discount is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountEqualTo(Integer value) {
            addCriterion("discount =", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotEqualTo(Integer value) {
            addCriterion("discount <>", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThan(Integer value) {
            addCriterion("discount >", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThanOrEqualTo(Integer value) {
            addCriterion("discount >=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThan(Integer value) {
            addCriterion("discount <", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThanOrEqualTo(Integer value) {
            addCriterion("discount <=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountIn(List<Integer> values) {
            addCriterion("discount in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotIn(List<Integer> values) {
            addCriterion("discount not in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountBetween(Integer value1, Integer value2) {
            addCriterion("discount between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotBetween(Integer value1, Integer value2) {
            addCriterion("discount not between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andData_openidIsNull() {
            addCriterion("data_openid is null");
            return (Criteria) this;
        }

        public Criteria andData_openidIsNotNull() {
            addCriterion("data_openid is not null");
            return (Criteria) this;
        }

        public Criteria andData_openidEqualTo(String value) {
            addCriterion("data_openid =", value, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidNotEqualTo(String value) {
            addCriterion("data_openid <>", value, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidGreaterThan(String value) {
            addCriterion("data_openid >", value, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidGreaterThanOrEqualTo(String value) {
            addCriterion("data_openid >=", value, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidLessThan(String value) {
            addCriterion("data_openid <", value, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidLessThanOrEqualTo(String value) {
            addCriterion("data_openid <=", value, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidLike(String value) {
            addCriterion("data_openid like", value, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidNotLike(String value) {
            addCriterion("data_openid not like", value, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidIn(List<String> values) {
            addCriterion("data_openid in", values, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidNotIn(List<String> values) {
            addCriterion("data_openid not in", values, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidBetween(String value1, String value2) {
            addCriterion("data_openid between", value1, value2, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_openidNotBetween(String value1, String value2) {
            addCriterion("data_openid not between", value1, value2, "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeIsNull() {
            addCriterion("data_issubscribe is null");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeIsNotNull() {
            addCriterion("data_issubscribe is not null");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeEqualTo(String value) {
            addCriterion("data_issubscribe =", value, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeNotEqualTo(String value) {
            addCriterion("data_issubscribe <>", value, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeGreaterThan(String value) {
            addCriterion("data_issubscribe >", value, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeGreaterThanOrEqualTo(String value) {
            addCriterion("data_issubscribe >=", value, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeLessThan(String value) {
            addCriterion("data_issubscribe <", value, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeLessThanOrEqualTo(String value) {
            addCriterion("data_issubscribe <=", value, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeLike(String value) {
            addCriterion("data_issubscribe like", value, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeNotLike(String value) {
            addCriterion("data_issubscribe not like", value, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeIn(List<String> values) {
            addCriterion("data_issubscribe in", values, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeNotIn(List<String> values) {
            addCriterion("data_issubscribe not in", values, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeBetween(String value1, String value2) {
            addCriterion("data_issubscribe between", value1, value2, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeNotBetween(String value1, String value2) {
            addCriterion("data_issubscribe not between", value1, value2, "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andTrade_typeIsNull() {
            addCriterion("trade_type is null");
            return (Criteria) this;
        }

        public Criteria andTrade_typeIsNotNull() {
            addCriterion("trade_type is not null");
            return (Criteria) this;
        }

        public Criteria andTrade_typeEqualTo(String value) {
            addCriterion("trade_type =", value, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeNotEqualTo(String value) {
            addCriterion("trade_type <>", value, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeGreaterThan(String value) {
            addCriterion("trade_type >", value, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeGreaterThanOrEqualTo(String value) {
            addCriterion("trade_type >=", value, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeLessThan(String value) {
            addCriterion("trade_type <", value, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeLessThanOrEqualTo(String value) {
            addCriterion("trade_type <=", value, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeLike(String value) {
            addCriterion("trade_type like", value, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeNotLike(String value) {
            addCriterion("trade_type not like", value, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeIn(List<String> values) {
            addCriterion("trade_type in", values, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeNotIn(List<String> values) {
            addCriterion("trade_type not in", values, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeBetween(String value1, String value2) {
            addCriterion("trade_type between", value1, value2, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTrade_typeNotBetween(String value1, String value2) {
            addCriterion("trade_type not between", value1, value2, "trade_type");
            return (Criteria) this;
        }

        public Criteria andTransaction_idLikeInsensitive(String value) {
            addCriterion("upper(transaction_id) like", value.toUpperCase(), "transaction_id");
            return (Criteria) this;
        }

        public Criteria andAppidLikeInsensitive(String value) {
            addCriterion("upper(appid) like", value.toUpperCase(), "appid");
            return (Criteria) this;
        }

        public Criteria andSign_typeLikeInsensitive(String value) {
            addCriterion("upper(sign_type) like", value.toUpperCase(), "sign_type");
            return (Criteria) this;
        }

        public Criteria andInput_charsetLikeInsensitive(String value) {
            addCriterion("upper(input_charset) like", value.toUpperCase(), "input_charset");
            return (Criteria) this;
        }

        public Criteria andSignLikeInsensitive(String value) {
            addCriterion("upper(sign) like", value.toUpperCase(), "sign");
            return (Criteria) this;
        }

        public Criteria andPartnerLikeInsensitive(String value) {
            addCriterion("upper(partner) like", value.toUpperCase(), "partner");
            return (Criteria) this;
        }

        public Criteria andBank_typeLikeInsensitive(String value) {
            addCriterion("upper(bank_type) like", value.toUpperCase(), "bank_type");
            return (Criteria) this;
        }

        public Criteria andBank_billnoLikeInsensitive(String value) {
            addCriterion("upper(bank_billno) like", value.toUpperCase(), "bank_billno");
            return (Criteria) this;
        }

        public Criteria andFee_typeLikeInsensitive(String value) {
            addCriterion("upper(fee_type) like", value.toUpperCase(), "fee_type");
            return (Criteria) this;
        }

        public Criteria andNotify_idLikeInsensitive(String value) {
            addCriterion("upper(notify_id) like", value.toUpperCase(), "notify_id");
            return (Criteria) this;
        }

        public Criteria andOut_trade_noLikeInsensitive(String value) {
            addCriterion("upper(out_trade_no) like", value.toUpperCase(), "out_trade_no");
            return (Criteria) this;
        }

        public Criteria andAttachLikeInsensitive(String value) {
            addCriterion("upper(attach) like", value.toUpperCase(), "attach");
            return (Criteria) this;
        }

        public Criteria andTime_endLikeInsensitive(String value) {
            addCriterion("upper(time_end) like", value.toUpperCase(), "time_end");
            return (Criteria) this;
        }

        public Criteria andData_openidLikeInsensitive(String value) {
            addCriterion("upper(data_openid) like", value.toUpperCase(), "data_openid");
            return (Criteria) this;
        }

        public Criteria andData_issubscribeLikeInsensitive(String value) {
            addCriterion("upper(data_issubscribe) like", value.toUpperCase(), "data_issubscribe");
            return (Criteria) this;
        }

        public Criteria andTrade_typeLikeInsensitive(String value) {
            addCriterion("upper(trade_type) like", value.toUpperCase(), "trade_type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_wx_notify
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 12 10:00:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table pay_wx_notify
     *
     * @mbg.generated Mon Feb 12 10:00:28 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	微信支付回调通知数据
		//--------------------------------------------------
		/** 交易号 */									transaction_id(1,Types.VARCHAR,false),					
														appid(2,Types.VARCHAR,false),
		/** 签名类型 [DV=>MD5] */						sign_type(2,Types.VARCHAR,false),
		/** 字符集 [DV=>GBK] */							input_charset(2,Types.VARCHAR,false),
		/** 签名 */										sign(2,Types.VARCHAR,false),
		/** 交易模式 [DV=>1] */							trade_mode(2,Types.INTEGER,false),
		/** 支付结果，0 成功，其它保留 */				trade_state(2,Types.INTEGER,false),
		/** 商户号 */									partner(2,Types.VARCHAR,false),
		/** 付款银行，银行类型，在微信中使用WX */		bank_type(2,Types.VARCHAR,false),
		/** 银行订单号 */								bank_billno(2,Types.VARCHAR,false),
		/** 总金额 */									total_fee(2,Types.INTEGER,false),
		/** 现金支付币种,目前只支持人民币 1 */			fee_type(2,Types.VARCHAR,false),
		/** 支付结果通知id，对于某些特定商户，只返回通知id，要求商户据此查询交易结果 */
														notify_id(2,Types.VARCHAR,false),
		/** 商户订单号 */								out_trade_no(2,Types.VARCHAR,false),
		/** 商户数据包 */								attach(2,Types.VARCHAR,false),
		/** 支付完成时间 */								time_end(2,Types.VARCHAR,false),
		/** 物流费用，单位分，默认0。如果有值， 必须保证transport_fee +product_fee = total_fee */
														transport_fee(2,Types.INTEGER,false),
		/** 物品费用，单位分。如果有值，必须保证transport_fee +product_fee=total_fee */
														product_fee(2,Types.INTEGER,false),
		/** 折扣价格，单位分，如果有值，通知的total_fee + discount = 请求的total_fee */
														discount(2,Types.INTEGER,false),					
														data_openid(2,Types.VARCHAR,false),					
														data_issubscribe(2,Types.VARCHAR,false),
		/** JSAPI、NATIVE、APP */						trade_type(2,Types.VARCHAR,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}