package com.aobei.train.model;

import com.aobei.train.model.PlanExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class PlanExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_plan
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public PlanExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_plan
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_plan
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train_plan
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table train_plan
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andTrain_plan_idIsNull() {
            addCriterion("train_plan_id is null");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idIsNotNull() {
            addCriterion("train_plan_id is not null");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idEqualTo(Long value) {
            addCriterion("train_plan_id =", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idNotEqualTo(Long value) {
            addCriterion("train_plan_id <>", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idGreaterThan(Long value) {
            addCriterion("train_plan_id >", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idGreaterThanOrEqualTo(Long value) {
            addCriterion("train_plan_id >=", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idLessThan(Long value) {
            addCriterion("train_plan_id <", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idLessThanOrEqualTo(Long value) {
            addCriterion("train_plan_id <=", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idIn(List<Long> values) {
            addCriterion("train_plan_id in", values, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idNotIn(List<Long> values) {
            addCriterion("train_plan_id not in", values, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idBetween(Long value1, Long value2) {
            addCriterion("train_plan_id between", value1, value2, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idNotBetween(Long value1, Long value2) {
            addCriterion("train_plan_id not between", value1, value2, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_beginIsNull() {
            addCriterion("train_begin is null");
            return (Criteria) this;
        }

        public Criteria andTrain_beginIsNotNull() {
            addCriterion("train_begin is not null");
            return (Criteria) this;
        }

        public Criteria andTrain_beginEqualTo(Date value) {
            addCriterion("train_begin =", value, "train_begin");
            return (Criteria) this;
        }

        public Criteria andTrain_beginNotEqualTo(Date value) {
            addCriterion("train_begin <>", value, "train_begin");
            return (Criteria) this;
        }

        public Criteria andTrain_beginGreaterThan(Date value) {
            addCriterion("train_begin >", value, "train_begin");
            return (Criteria) this;
        }

        public Criteria andTrain_beginGreaterThanOrEqualTo(Date value) {
            addCriterion("train_begin >=", value, "train_begin");
            return (Criteria) this;
        }

        public Criteria andTrain_beginLessThan(Date value) {
            addCriterion("train_begin <", value, "train_begin");
            return (Criteria) this;
        }

        public Criteria andTrain_beginLessThanOrEqualTo(Date value) {
            addCriterion("train_begin <=", value, "train_begin");
            return (Criteria) this;
        }

        public Criteria andTrain_beginIn(List<Date> values) {
            addCriterion("train_begin in", values, "train_begin");
            return (Criteria) this;
        }

        public Criteria andTrain_beginNotIn(List<Date> values) {
            addCriterion("train_begin not in", values, "train_begin");
            return (Criteria) this;
        }

        public Criteria andTrain_beginBetween(Date value1, Date value2) {
            addCriterion("train_begin between", value1, value2, "train_begin");
            return (Criteria) this;
        }

        public Criteria andTrain_beginNotBetween(Date value1, Date value2) {
            addCriterion("train_begin not between", value1, value2, "train_begin");
            return (Criteria) this;
        }

        public Criteria andTrain_endIsNull() {
            addCriterion("train_end is null");
            return (Criteria) this;
        }

        public Criteria andTrain_endIsNotNull() {
            addCriterion("train_end is not null");
            return (Criteria) this;
        }

        public Criteria andTrain_endEqualTo(Date value) {
            addCriterion("train_end =", value, "train_end");
            return (Criteria) this;
        }

        public Criteria andTrain_endNotEqualTo(Date value) {
            addCriterion("train_end <>", value, "train_end");
            return (Criteria) this;
        }

        public Criteria andTrain_endGreaterThan(Date value) {
            addCriterion("train_end >", value, "train_end");
            return (Criteria) this;
        }

        public Criteria andTrain_endGreaterThanOrEqualTo(Date value) {
            addCriterion("train_end >=", value, "train_end");
            return (Criteria) this;
        }

        public Criteria andTrain_endLessThan(Date value) {
            addCriterion("train_end <", value, "train_end");
            return (Criteria) this;
        }

        public Criteria andTrain_endLessThanOrEqualTo(Date value) {
            addCriterion("train_end <=", value, "train_end");
            return (Criteria) this;
        }

        public Criteria andTrain_endIn(List<Date> values) {
            addCriterion("train_end in", values, "train_end");
            return (Criteria) this;
        }

        public Criteria andTrain_endNotIn(List<Date> values) {
            addCriterion("train_end not in", values, "train_end");
            return (Criteria) this;
        }

        public Criteria andTrain_endBetween(Date value1, Date value2) {
            addCriterion("train_end between", value1, value2, "train_end");
            return (Criteria) this;
        }

        public Criteria andTrain_endNotBetween(Date value1, Date value2) {
            addCriterion("train_end not between", value1, value2, "train_end");
            return (Criteria) this;
        }

        public Criteria andCourse_idIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourse_idIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourse_idEqualTo(Long value) {
            addCriterion("course_id =", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idNotEqualTo(Long value) {
            addCriterion("course_id <>", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idGreaterThan(Long value) {
            addCriterion("course_id >", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idGreaterThanOrEqualTo(Long value) {
            addCriterion("course_id >=", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idLessThan(Long value) {
            addCriterion("course_id <", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idLessThanOrEqualTo(Long value) {
            addCriterion("course_id <=", value, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idIn(List<Long> values) {
            addCriterion("course_id in", values, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idNotIn(List<Long> values) {
            addCriterion("course_id not in", values, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idBetween(Long value1, Long value2) {
            addCriterion("course_id between", value1, value2, "course_id");
            return (Criteria) this;
        }

        public Criteria andCourse_idNotBetween(Long value1, Long value2) {
            addCriterion("course_id not between", value1, value2, "course_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idIsNull() {
            addCriterion("school_id is null");
            return (Criteria) this;
        }

        public Criteria andSchool_idIsNotNull() {
            addCriterion("school_id is not null");
            return (Criteria) this;
        }

        public Criteria andSchool_idEqualTo(Long value) {
            addCriterion("school_id =", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idNotEqualTo(Long value) {
            addCriterion("school_id <>", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idGreaterThan(Long value) {
            addCriterion("school_id >", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idGreaterThanOrEqualTo(Long value) {
            addCriterion("school_id >=", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idLessThan(Long value) {
            addCriterion("school_id <", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idLessThanOrEqualTo(Long value) {
            addCriterion("school_id <=", value, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idIn(List<Long> values) {
            addCriterion("school_id in", values, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idNotIn(List<Long> values) {
            addCriterion("school_id not in", values, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idBetween(Long value1, Long value2) {
            addCriterion("school_id between", value1, value2, "school_id");
            return (Criteria) this;
        }

        public Criteria andSchool_idNotBetween(Long value1, Long value2) {
            addCriterion("school_id not between", value1, value2, "school_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idIsNull() {
            addCriterion("classroom_id is null");
            return (Criteria) this;
        }

        public Criteria andClassroom_idIsNotNull() {
            addCriterion("classroom_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassroom_idEqualTo(Long value) {
            addCriterion("classroom_id =", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idNotEqualTo(Long value) {
            addCriterion("classroom_id <>", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idGreaterThan(Long value) {
            addCriterion("classroom_id >", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idGreaterThanOrEqualTo(Long value) {
            addCriterion("classroom_id >=", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idLessThan(Long value) {
            addCriterion("classroom_id <", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idLessThanOrEqualTo(Long value) {
            addCriterion("classroom_id <=", value, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idIn(List<Long> values) {
            addCriterion("classroom_id in", values, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idNotIn(List<Long> values) {
            addCriterion("classroom_id not in", values, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idBetween(Long value1, Long value2) {
            addCriterion("classroom_id between", value1, value2, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andClassroom_idNotBetween(Long value1, Long value2) {
            addCriterion("classroom_id not between", value1, value2, "classroom_id");
            return (Criteria) this;
        }

        public Criteria andTeacher_idIsNull() {
            addCriterion("teacher_id is null");
            return (Criteria) this;
        }

        public Criteria andTeacher_idIsNotNull() {
            addCriterion("teacher_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeacher_idEqualTo(Long value) {
            addCriterion("teacher_id =", value, "teacher_id");
            return (Criteria) this;
        }

        public Criteria andTeacher_idNotEqualTo(Long value) {
            addCriterion("teacher_id <>", value, "teacher_id");
            return (Criteria) this;
        }

        public Criteria andTeacher_idGreaterThan(Long value) {
            addCriterion("teacher_id >", value, "teacher_id");
            return (Criteria) this;
        }

        public Criteria andTeacher_idGreaterThanOrEqualTo(Long value) {
            addCriterion("teacher_id >=", value, "teacher_id");
            return (Criteria) this;
        }

        public Criteria andTeacher_idLessThan(Long value) {
            addCriterion("teacher_id <", value, "teacher_id");
            return (Criteria) this;
        }

        public Criteria andTeacher_idLessThanOrEqualTo(Long value) {
            addCriterion("teacher_id <=", value, "teacher_id");
            return (Criteria) this;
        }

        public Criteria andTeacher_idIn(List<Long> values) {
            addCriterion("teacher_id in", values, "teacher_id");
            return (Criteria) this;
        }

        public Criteria andTeacher_idNotIn(List<Long> values) {
            addCriterion("teacher_id not in", values, "teacher_id");
            return (Criteria) this;
        }

        public Criteria andTeacher_idBetween(Long value1, Long value2) {
            addCriterion("teacher_id between", value1, value2, "teacher_id");
            return (Criteria) this;
        }

        public Criteria andTeacher_idNotBetween(Long value1, Long value2) {
            addCriterion("teacher_id not between", value1, value2, "teacher_id");
            return (Criteria) this;
        }

        public Criteria andAssistantIsNull() {
            addCriterion("assistant is null");
            return (Criteria) this;
        }

        public Criteria andAssistantIsNotNull() {
            addCriterion("assistant is not null");
            return (Criteria) this;
        }

        public Criteria andAssistantEqualTo(Long value) {
            addCriterion("assistant =", value, "assistant");
            return (Criteria) this;
        }

        public Criteria andAssistantNotEqualTo(Long value) {
            addCriterion("assistant <>", value, "assistant");
            return (Criteria) this;
        }

        public Criteria andAssistantGreaterThan(Long value) {
            addCriterion("assistant >", value, "assistant");
            return (Criteria) this;
        }

        public Criteria andAssistantGreaterThanOrEqualTo(Long value) {
            addCriterion("assistant >=", value, "assistant");
            return (Criteria) this;
        }

        public Criteria andAssistantLessThan(Long value) {
            addCriterion("assistant <", value, "assistant");
            return (Criteria) this;
        }

        public Criteria andAssistantLessThanOrEqualTo(Long value) {
            addCriterion("assistant <=", value, "assistant");
            return (Criteria) this;
        }

        public Criteria andAssistantIn(List<Long> values) {
            addCriterion("assistant in", values, "assistant");
            return (Criteria) this;
        }

        public Criteria andAssistantNotIn(List<Long> values) {
            addCriterion("assistant not in", values, "assistant");
            return (Criteria) this;
        }

        public Criteria andAssistantBetween(Long value1, Long value2) {
            addCriterion("assistant between", value1, value2, "assistant");
            return (Criteria) this;
        }

        public Criteria andAssistantNotBetween(Long value1, Long value2) {
            addCriterion("assistant not between", value1, value2, "assistant");
            return (Criteria) this;
        }

        public Criteria andTrain_wayIsNull() {
            addCriterion("train_way is null");
            return (Criteria) this;
        }

        public Criteria andTrain_wayIsNotNull() {
            addCriterion("train_way is not null");
            return (Criteria) this;
        }

        public Criteria andTrain_wayEqualTo(Integer value) {
            addCriterion("train_way =", value, "train_way");
            return (Criteria) this;
        }

        public Criteria andTrain_wayNotEqualTo(Integer value) {
            addCriterion("train_way <>", value, "train_way");
            return (Criteria) this;
        }

        public Criteria andTrain_wayGreaterThan(Integer value) {
            addCriterion("train_way >", value, "train_way");
            return (Criteria) this;
        }

        public Criteria andTrain_wayGreaterThanOrEqualTo(Integer value) {
            addCriterion("train_way >=", value, "train_way");
            return (Criteria) this;
        }

        public Criteria andTrain_wayLessThan(Integer value) {
            addCriterion("train_way <", value, "train_way");
            return (Criteria) this;
        }

        public Criteria andTrain_wayLessThanOrEqualTo(Integer value) {
            addCriterion("train_way <=", value, "train_way");
            return (Criteria) this;
        }

        public Criteria andTrain_wayIn(List<Integer> values) {
            addCriterion("train_way in", values, "train_way");
            return (Criteria) this;
        }

        public Criteria andTrain_wayNotIn(List<Integer> values) {
            addCriterion("train_way not in", values, "train_way");
            return (Criteria) this;
        }

        public Criteria andTrain_wayBetween(Integer value1, Integer value2) {
            addCriterion("train_way between", value1, value2, "train_way");
            return (Criteria) this;
        }

        public Criteria andTrain_wayNotBetween(Integer value1, Integer value2) {
            addCriterion("train_way not between", value1, value2, "train_way");
            return (Criteria) this;
        }

        public Criteria andTrainingIsNull() {
            addCriterion("training is null");
            return (Criteria) this;
        }

        public Criteria andTrainingIsNotNull() {
            addCriterion("training is not null");
            return (Criteria) this;
        }

        public Criteria andTrainingEqualTo(String value) {
            addCriterion("training =", value, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingNotEqualTo(String value) {
            addCriterion("training <>", value, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingGreaterThan(String value) {
            addCriterion("training >", value, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingGreaterThanOrEqualTo(String value) {
            addCriterion("training >=", value, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingLessThan(String value) {
            addCriterion("training <", value, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingLessThanOrEqualTo(String value) {
            addCriterion("training <=", value, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingLike(String value) {
            addCriterion("training like", value, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingNotLike(String value) {
            addCriterion("training not like", value, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingIn(List<String> values) {
            addCriterion("training in", values, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingNotIn(List<String> values) {
            addCriterion("training not in", values, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingBetween(String value1, String value2) {
            addCriterion("training between", value1, value2, "training");
            return (Criteria) this;
        }

        public Criteria andTrainingNotBetween(String value1, String value2) {
            addCriterion("training not between", value1, value2, "training");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberIsNull() {
            addCriterion("trainers_number is null");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberIsNotNull() {
            addCriterion("trainers_number is not null");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberEqualTo(Integer value) {
            addCriterion("trainers_number =", value, "trainers_number");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberNotEqualTo(Integer value) {
            addCriterion("trainers_number <>", value, "trainers_number");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberGreaterThan(Integer value) {
            addCriterion("trainers_number >", value, "trainers_number");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberGreaterThanOrEqualTo(Integer value) {
            addCriterion("trainers_number >=", value, "trainers_number");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberLessThan(Integer value) {
            addCriterion("trainers_number <", value, "trainers_number");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberLessThanOrEqualTo(Integer value) {
            addCriterion("trainers_number <=", value, "trainers_number");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberIn(List<Integer> values) {
            addCriterion("trainers_number in", values, "trainers_number");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberNotIn(List<Integer> values) {
            addCriterion("trainers_number not in", values, "trainers_number");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberBetween(Integer value1, Integer value2) {
            addCriterion("trainers_number between", value1, value2, "trainers_number");
            return (Criteria) this;
        }

        public Criteria andTrainers_numberNotBetween(Integer value1, Integer value2) {
            addCriterion("trainers_number not between", value1, value2, "trainers_number");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andTrainingLikeInsensitive(String value) {
            addCriterion("upper(training) like", value.toUpperCase(), "training");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table train_plan
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 01 11:23:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
        
        /**
         * 等于老师或助教
         * @param teacher_id
         * @return
         */
        public Criteria andTeacherAll(Long teacher_id) {
            addCriterion(String.format("teacher_id=%d or assistant=%d",teacher_id,teacher_id));
            return (Criteria) this;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table train_plan
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	培训计划
		//--------------------------------------------------
		/** 培训计划编号 */								train_plan_id(1,Types.BIGINT,false),
		/** 培训开始日期 */								train_begin(2,Types.TIMESTAMP,false),
		/** 培训结束日期 */								train_end(2,Types.TIMESTAMP,false),
		/** 培训课程id */								course_id(2,Types.BIGINT,false),
		/** 培训学校id */								school_id(2,Types.BIGINT,false),
		/** 培训教室id */								classroom_id(2,Types.BIGINT,false),
		/** 培训教师id */								teacher_id(2,Types.BIGINT,false),
		/** 培训助教老师id */							assistant(2,Types.BIGINT,false),
		/** 培训方式 '0'为面授 '1'为在线 */				train_way(2,Types.INTEGER,false),
		/** 培训/考核 [DV=>培训+考核] */				training(2,Types.CHAR,false),
		/** 培训人数 */									trainers_number(2,Types.INTEGER,false),
		/** 是否删除 0 未删除  1 已删除 [DV=>0] */		deleted(2,Types.INTEGER,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}