package com.aobei.train.model;

import com.aobei.train.model.ProSkuExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class ProSkuExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psku
     *
     * @mbg.generated Tue Aug 14 15:50:09 CST 2018
     */
    public ProSkuExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psku
     *
     * @mbg.generated Tue Aug 14 15:50:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psku
     *
     * @mbg.generated Tue Aug 14 15:50:09 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table psku
     *
     * @mbg.generated Tue Aug 14 15:50:09 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table psku
     *
     * @mbg.generated Tue Aug 14 15:50:09 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andPsku_idIsNull() {
            addCriterion("psku_id is null");
            return (Criteria) this;
        }

        public Criteria andPsku_idIsNotNull() {
            addCriterion("psku_id is not null");
            return (Criteria) this;
        }

        public Criteria andPsku_idEqualTo(Long value) {
            addCriterion("psku_id =", value, "psku_id");
            return (Criteria) this;
        }

        public Criteria andPsku_idNotEqualTo(Long value) {
            addCriterion("psku_id <>", value, "psku_id");
            return (Criteria) this;
        }

        public Criteria andPsku_idGreaterThan(Long value) {
            addCriterion("psku_id >", value, "psku_id");
            return (Criteria) this;
        }

        public Criteria andPsku_idGreaterThanOrEqualTo(Long value) {
            addCriterion("psku_id >=", value, "psku_id");
            return (Criteria) this;
        }

        public Criteria andPsku_idLessThan(Long value) {
            addCriterion("psku_id <", value, "psku_id");
            return (Criteria) this;
        }

        public Criteria andPsku_idLessThanOrEqualTo(Long value) {
            addCriterion("psku_id <=", value, "psku_id");
            return (Criteria) this;
        }

        public Criteria andPsku_idIn(List<Long> values) {
            addCriterion("psku_id in", values, "psku_id");
            return (Criteria) this;
        }

        public Criteria andPsku_idNotIn(List<Long> values) {
            addCriterion("psku_id not in", values, "psku_id");
            return (Criteria) this;
        }

        public Criteria andPsku_idBetween(Long value1, Long value2) {
            addCriterion("psku_id between", value1, value2, "psku_id");
            return (Criteria) this;
        }

        public Criteria andPsku_idNotBetween(Long value1, Long value2) {
            addCriterion("psku_id not between", value1, value2, "psku_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProduct_idIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProduct_idEqualTo(Long value) {
            addCriterion("product_id =", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idNotEqualTo(Long value) {
            addCriterion("product_id <>", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idGreaterThan(Long value) {
            addCriterion("product_id >", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idGreaterThanOrEqualTo(Long value) {
            addCriterion("product_id >=", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idLessThan(Long value) {
            addCriterion("product_id <", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idLessThanOrEqualTo(Long value) {
            addCriterion("product_id <=", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idIn(List<Long> values) {
            addCriterion("product_id in", values, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idNotIn(List<Long> values) {
            addCriterion("product_id not in", values, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idBetween(Long value1, Long value2) {
            addCriterion("product_id between", value1, value2, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idNotBetween(Long value1, Long value2) {
            addCriterion("product_id not between", value1, value2, "product_id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptIsNull() {
            addCriterion("descript is null");
            return (Criteria) this;
        }

        public Criteria andDescriptIsNotNull() {
            addCriterion("descript is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptEqualTo(String value) {
            addCriterion("descript =", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotEqualTo(String value) {
            addCriterion("descript <>", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptGreaterThan(String value) {
            addCriterion("descript >", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptGreaterThanOrEqualTo(String value) {
            addCriterion("descript >=", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLessThan(String value) {
            addCriterion("descript <", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLessThanOrEqualTo(String value) {
            addCriterion("descript <=", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLike(String value) {
            addCriterion("descript like", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotLike(String value) {
            addCriterion("descript not like", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptIn(List<String> values) {
            addCriterion("descript in", values, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotIn(List<String> values) {
            addCriterion("descript not in", values, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptBetween(String value1, String value2) {
            addCriterion("descript between", value1, value2, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotBetween(String value1, String value2) {
            addCriterion("descript not between", value1, value2, "descript");
            return (Criteria) this;
        }

        public Criteria andPricevIsNull() {
            addCriterion("pricev is null");
            return (Criteria) this;
        }

        public Criteria andPricevIsNotNull() {
            addCriterion("pricev is not null");
            return (Criteria) this;
        }

        public Criteria andPricevEqualTo(Integer value) {
            addCriterion("pricev =", value, "pricev");
            return (Criteria) this;
        }

        public Criteria andPricevNotEqualTo(Integer value) {
            addCriterion("pricev <>", value, "pricev");
            return (Criteria) this;
        }

        public Criteria andPricevGreaterThan(Integer value) {
            addCriterion("pricev >", value, "pricev");
            return (Criteria) this;
        }

        public Criteria andPricevGreaterThanOrEqualTo(Integer value) {
            addCriterion("pricev >=", value, "pricev");
            return (Criteria) this;
        }

        public Criteria andPricevLessThan(Integer value) {
            addCriterion("pricev <", value, "pricev");
            return (Criteria) this;
        }

        public Criteria andPricevLessThanOrEqualTo(Integer value) {
            addCriterion("pricev <=", value, "pricev");
            return (Criteria) this;
        }

        public Criteria andPricevIn(List<Integer> values) {
            addCriterion("pricev in", values, "pricev");
            return (Criteria) this;
        }

        public Criteria andPricevNotIn(List<Integer> values) {
            addCriterion("pricev not in", values, "pricev");
            return (Criteria) this;
        }

        public Criteria andPricevBetween(Integer value1, Integer value2) {
            addCriterion("pricev between", value1, value2, "pricev");
            return (Criteria) this;
        }

        public Criteria andPricevNotBetween(Integer value1, Integer value2) {
            addCriterion("pricev not between", value1, value2, "pricev");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthIsNull() {
            addCriterion("service_time_length is null");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthIsNotNull() {
            addCriterion("service_time_length is not null");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthEqualTo(Integer value) {
            addCriterion("service_time_length =", value, "service_time_length");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthNotEqualTo(Integer value) {
            addCriterion("service_time_length <>", value, "service_time_length");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthGreaterThan(Integer value) {
            addCriterion("service_time_length >", value, "service_time_length");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_time_length >=", value, "service_time_length");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthLessThan(Integer value) {
            addCriterion("service_time_length <", value, "service_time_length");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthLessThanOrEqualTo(Integer value) {
            addCriterion("service_time_length <=", value, "service_time_length");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthIn(List<Integer> values) {
            addCriterion("service_time_length in", values, "service_time_length");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthNotIn(List<Integer> values) {
            addCriterion("service_time_length not in", values, "service_time_length");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthBetween(Integer value1, Integer value2) {
            addCriterion("service_time_length between", value1, value2, "service_time_length");
            return (Criteria) this;
        }

        public Criteria andService_time_lengthNotBetween(Integer value1, Integer value2) {
            addCriterion("service_time_length not between", value1, value2, "service_time_length");
            return (Criteria) this;
        }

        public Criteria andService_timesIsNull() {
            addCriterion("service_times is null");
            return (Criteria) this;
        }

        public Criteria andService_timesIsNotNull() {
            addCriterion("service_times is not null");
            return (Criteria) this;
        }

        public Criteria andService_timesEqualTo(String value) {
            addCriterion("service_times =", value, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesNotEqualTo(String value) {
            addCriterion("service_times <>", value, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesGreaterThan(String value) {
            addCriterion("service_times >", value, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesGreaterThanOrEqualTo(String value) {
            addCriterion("service_times >=", value, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesLessThan(String value) {
            addCriterion("service_times <", value, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesLessThanOrEqualTo(String value) {
            addCriterion("service_times <=", value, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesLike(String value) {
            addCriterion("service_times like", value, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesNotLike(String value) {
            addCriterion("service_times not like", value, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesIn(List<String> values) {
            addCriterion("service_times in", values, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesNotIn(List<String> values) {
            addCriterion("service_times not in", values, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesBetween(String value1, String value2) {
            addCriterion("service_times between", value1, value2, "service_times");
            return (Criteria) this;
        }

        public Criteria andService_timesNotBetween(String value1, String value2) {
            addCriterion("service_times not between", value1, value2, "service_times");
            return (Criteria) this;
        }

        public Criteria andSort_numIsNull() {
            addCriterion("sort_num is null");
            return (Criteria) this;
        }

        public Criteria andSort_numIsNotNull() {
            addCriterion("sort_num is not null");
            return (Criteria) this;
        }

        public Criteria andSort_numEqualTo(Integer value) {
            addCriterion("sort_num =", value, "sort_num");
            return (Criteria) this;
        }

        public Criteria andSort_numNotEqualTo(Integer value) {
            addCriterion("sort_num <>", value, "sort_num");
            return (Criteria) this;
        }

        public Criteria andSort_numGreaterThan(Integer value) {
            addCriterion("sort_num >", value, "sort_num");
            return (Criteria) this;
        }

        public Criteria andSort_numGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort_num >=", value, "sort_num");
            return (Criteria) this;
        }

        public Criteria andSort_numLessThan(Integer value) {
            addCriterion("sort_num <", value, "sort_num");
            return (Criteria) this;
        }

        public Criteria andSort_numLessThanOrEqualTo(Integer value) {
            addCriterion("sort_num <=", value, "sort_num");
            return (Criteria) this;
        }

        public Criteria andSort_numIn(List<Integer> values) {
            addCriterion("sort_num in", values, "sort_num");
            return (Criteria) this;
        }

        public Criteria andSort_numNotIn(List<Integer> values) {
            addCriterion("sort_num not in", values, "sort_num");
            return (Criteria) this;
        }

        public Criteria andSort_numBetween(Integer value1, Integer value2) {
            addCriterion("sort_num between", value1, value2, "sort_num");
            return (Criteria) this;
        }

        public Criteria andSort_numNotBetween(Integer value1, Integer value2) {
            addCriterion("sort_num not between", value1, value2, "sort_num");
            return (Criteria) this;
        }

        public Criteria andBuy_limitIsNull() {
            addCriterion("buy_limit is null");
            return (Criteria) this;
        }

        public Criteria andBuy_limitIsNotNull() {
            addCriterion("buy_limit is not null");
            return (Criteria) this;
        }

        public Criteria andBuy_limitEqualTo(Integer value) {
            addCriterion("buy_limit =", value, "buy_limit");
            return (Criteria) this;
        }

        public Criteria andBuy_limitNotEqualTo(Integer value) {
            addCriterion("buy_limit <>", value, "buy_limit");
            return (Criteria) this;
        }

        public Criteria andBuy_limitGreaterThan(Integer value) {
            addCriterion("buy_limit >", value, "buy_limit");
            return (Criteria) this;
        }

        public Criteria andBuy_limitGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_limit >=", value, "buy_limit");
            return (Criteria) this;
        }

        public Criteria andBuy_limitLessThan(Integer value) {
            addCriterion("buy_limit <", value, "buy_limit");
            return (Criteria) this;
        }

        public Criteria andBuy_limitLessThanOrEqualTo(Integer value) {
            addCriterion("buy_limit <=", value, "buy_limit");
            return (Criteria) this;
        }

        public Criteria andBuy_limitIn(List<Integer> values) {
            addCriterion("buy_limit in", values, "buy_limit");
            return (Criteria) this;
        }

        public Criteria andBuy_limitNotIn(List<Integer> values) {
            addCriterion("buy_limit not in", values, "buy_limit");
            return (Criteria) this;
        }

        public Criteria andBuy_limitBetween(Integer value1, Integer value2) {
            addCriterion("buy_limit between", value1, value2, "buy_limit");
            return (Criteria) this;
        }

        public Criteria andBuy_limitNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_limit not between", value1, value2, "buy_limit");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleIsNull() {
            addCriterion("buy_multiple is null");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleIsNotNull() {
            addCriterion("buy_multiple is not null");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleEqualTo(Integer value) {
            addCriterion("buy_multiple =", value, "buy_multiple");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleNotEqualTo(Integer value) {
            addCriterion("buy_multiple <>", value, "buy_multiple");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleGreaterThan(Integer value) {
            addCriterion("buy_multiple >", value, "buy_multiple");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_multiple >=", value, "buy_multiple");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleLessThan(Integer value) {
            addCriterion("buy_multiple <", value, "buy_multiple");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleLessThanOrEqualTo(Integer value) {
            addCriterion("buy_multiple <=", value, "buy_multiple");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleIn(List<Integer> values) {
            addCriterion("buy_multiple in", values, "buy_multiple");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleNotIn(List<Integer> values) {
            addCriterion("buy_multiple not in", values, "buy_multiple");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleBetween(Integer value1, Integer value2) {
            addCriterion("buy_multiple between", value1, value2, "buy_multiple");
            return (Criteria) this;
        }

        public Criteria andBuy_multipleNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_multiple not between", value1, value2, "buy_multiple");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minIsNull() {
            addCriterion("buy_multiple_min is null");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minIsNotNull() {
            addCriterion("buy_multiple_min is not null");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minEqualTo(Integer value) {
            addCriterion("buy_multiple_min =", value, "buy_multiple_min");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minNotEqualTo(Integer value) {
            addCriterion("buy_multiple_min <>", value, "buy_multiple_min");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minGreaterThan(Integer value) {
            addCriterion("buy_multiple_min >", value, "buy_multiple_min");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_multiple_min >=", value, "buy_multiple_min");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minLessThan(Integer value) {
            addCriterion("buy_multiple_min <", value, "buy_multiple_min");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minLessThanOrEqualTo(Integer value) {
            addCriterion("buy_multiple_min <=", value, "buy_multiple_min");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minIn(List<Integer> values) {
            addCriterion("buy_multiple_min in", values, "buy_multiple_min");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minNotIn(List<Integer> values) {
            addCriterion("buy_multiple_min not in", values, "buy_multiple_min");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minBetween(Integer value1, Integer value2) {
            addCriterion("buy_multiple_min between", value1, value2, "buy_multiple_min");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_minNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_multiple_min not between", value1, value2, "buy_multiple_min");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxIsNull() {
            addCriterion("buy_multiple_max is null");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxIsNotNull() {
            addCriterion("buy_multiple_max is not null");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxEqualTo(Integer value) {
            addCriterion("buy_multiple_max =", value, "buy_multiple_max");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxNotEqualTo(Integer value) {
            addCriterion("buy_multiple_max <>", value, "buy_multiple_max");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxGreaterThan(Integer value) {
            addCriterion("buy_multiple_max >", value, "buy_multiple_max");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_multiple_max >=", value, "buy_multiple_max");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxLessThan(Integer value) {
            addCriterion("buy_multiple_max <", value, "buy_multiple_max");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxLessThanOrEqualTo(Integer value) {
            addCriterion("buy_multiple_max <=", value, "buy_multiple_max");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxIn(List<Integer> values) {
            addCriterion("buy_multiple_max in", values, "buy_multiple_max");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxNotIn(List<Integer> values) {
            addCriterion("buy_multiple_max not in", values, "buy_multiple_max");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxBetween(Integer value1, Integer value2) {
            addCriterion("buy_multiple_max between", value1, value2, "buy_multiple_max");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_maxNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_multiple_max not between", value1, value2, "buy_multiple_max");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oIsNull() {
            addCriterion("buy_multiple_o2o is null");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oIsNotNull() {
            addCriterion("buy_multiple_o2o is not null");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oEqualTo(Integer value) {
            addCriterion("buy_multiple_o2o =", value, "buy_multiple_o2o");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oNotEqualTo(Integer value) {
            addCriterion("buy_multiple_o2o <>", value, "buy_multiple_o2o");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oGreaterThan(Integer value) {
            addCriterion("buy_multiple_o2o >", value, "buy_multiple_o2o");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_multiple_o2o >=", value, "buy_multiple_o2o");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oLessThan(Integer value) {
            addCriterion("buy_multiple_o2o <", value, "buy_multiple_o2o");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oLessThanOrEqualTo(Integer value) {
            addCriterion("buy_multiple_o2o <=", value, "buy_multiple_o2o");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oIn(List<Integer> values) {
            addCriterion("buy_multiple_o2o in", values, "buy_multiple_o2o");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oNotIn(List<Integer> values) {
            addCriterion("buy_multiple_o2o not in", values, "buy_multiple_o2o");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oBetween(Integer value1, Integer value2) {
            addCriterion("buy_multiple_o2o between", value1, value2, "buy_multiple_o2o");
            return (Criteria) this;
        }

        public Criteria andBuy_multiple_o2oNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_multiple_o2o not between", value1, value2, "buy_multiple_o2o");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idIsNull() {
            addCriterion("bespeak_strategy_id is null");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idIsNotNull() {
            addCriterion("bespeak_strategy_id is not null");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idEqualTo(Integer value) {
            addCriterion("bespeak_strategy_id =", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idNotEqualTo(Integer value) {
            addCriterion("bespeak_strategy_id <>", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idGreaterThan(Integer value) {
            addCriterion("bespeak_strategy_id >", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("bespeak_strategy_id >=", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idLessThan(Integer value) {
            addCriterion("bespeak_strategy_id <", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idLessThanOrEqualTo(Integer value) {
            addCriterion("bespeak_strategy_id <=", value, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idIn(List<Integer> values) {
            addCriterion("bespeak_strategy_id in", values, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idNotIn(List<Integer> values) {
            addCriterion("bespeak_strategy_id not in", values, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idBetween(Integer value1, Integer value2) {
            addCriterion("bespeak_strategy_id between", value1, value2, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andBespeak_strategy_idNotBetween(Integer value1, Integer value2) {
            addCriterion("bespeak_strategy_id not between", value1, value2, "bespeak_strategy_id");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("unit is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("unit is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("unit =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("unit <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("unit >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("unit >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("unit <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("unit <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("unit like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("unit not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("unit in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("unit not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("unit between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("unit not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andDispalyIsNull() {
            addCriterion("dispaly is null");
            return (Criteria) this;
        }

        public Criteria andDispalyIsNotNull() {
            addCriterion("dispaly is not null");
            return (Criteria) this;
        }

        public Criteria andDispalyEqualTo(Integer value) {
            addCriterion("dispaly =", value, "dispaly");
            return (Criteria) this;
        }

        public Criteria andDispalyNotEqualTo(Integer value) {
            addCriterion("dispaly <>", value, "dispaly");
            return (Criteria) this;
        }

        public Criteria andDispalyGreaterThan(Integer value) {
            addCriterion("dispaly >", value, "dispaly");
            return (Criteria) this;
        }

        public Criteria andDispalyGreaterThanOrEqualTo(Integer value) {
            addCriterion("dispaly >=", value, "dispaly");
            return (Criteria) this;
        }

        public Criteria andDispalyLessThan(Integer value) {
            addCriterion("dispaly <", value, "dispaly");
            return (Criteria) this;
        }

        public Criteria andDispalyLessThanOrEqualTo(Integer value) {
            addCriterion("dispaly <=", value, "dispaly");
            return (Criteria) this;
        }

        public Criteria andDispalyIn(List<Integer> values) {
            addCriterion("dispaly in", values, "dispaly");
            return (Criteria) this;
        }

        public Criteria andDispalyNotIn(List<Integer> values) {
            addCriterion("dispaly not in", values, "dispaly");
            return (Criteria) this;
        }

        public Criteria andDispalyBetween(Integer value1, Integer value2) {
            addCriterion("dispaly between", value1, value2, "dispaly");
            return (Criteria) this;
        }

        public Criteria andDispalyNotBetween(Integer value1, Integer value2) {
            addCriterion("dispaly not between", value1, value2, "dispaly");
            return (Criteria) this;
        }

        public Criteria andDefault_skuIsNull() {
            addCriterion("default_sku is null");
            return (Criteria) this;
        }

        public Criteria andDefault_skuIsNotNull() {
            addCriterion("default_sku is not null");
            return (Criteria) this;
        }

        public Criteria andDefault_skuEqualTo(Integer value) {
            addCriterion("default_sku =", value, "default_sku");
            return (Criteria) this;
        }

        public Criteria andDefault_skuNotEqualTo(Integer value) {
            addCriterion("default_sku <>", value, "default_sku");
            return (Criteria) this;
        }

        public Criteria andDefault_skuGreaterThan(Integer value) {
            addCriterion("default_sku >", value, "default_sku");
            return (Criteria) this;
        }

        public Criteria andDefault_skuGreaterThanOrEqualTo(Integer value) {
            addCriterion("default_sku >=", value, "default_sku");
            return (Criteria) this;
        }

        public Criteria andDefault_skuLessThan(Integer value) {
            addCriterion("default_sku <", value, "default_sku");
            return (Criteria) this;
        }

        public Criteria andDefault_skuLessThanOrEqualTo(Integer value) {
            addCriterion("default_sku <=", value, "default_sku");
            return (Criteria) this;
        }

        public Criteria andDefault_skuIn(List<Integer> values) {
            addCriterion("default_sku in", values, "default_sku");
            return (Criteria) this;
        }

        public Criteria andDefault_skuNotIn(List<Integer> values) {
            addCriterion("default_sku not in", values, "default_sku");
            return (Criteria) this;
        }

        public Criteria andDefault_skuBetween(Integer value1, Integer value2) {
            addCriterion("default_sku between", value1, value2, "default_sku");
            return (Criteria) this;
        }

        public Criteria andDefault_skuNotBetween(Integer value1, Integer value2) {
            addCriterion("default_sku not between", value1, value2, "default_sku");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceIsNull() {
            addCriterion("settlement_base_price is null");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceIsNotNull() {
            addCriterion("settlement_base_price is not null");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceEqualTo(Integer value) {
            addCriterion("settlement_base_price =", value, "settlement_base_price");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceNotEqualTo(Integer value) {
            addCriterion("settlement_base_price <>", value, "settlement_base_price");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceGreaterThan(Integer value) {
            addCriterion("settlement_base_price >", value, "settlement_base_price");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceGreaterThanOrEqualTo(Integer value) {
            addCriterion("settlement_base_price >=", value, "settlement_base_price");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceLessThan(Integer value) {
            addCriterion("settlement_base_price <", value, "settlement_base_price");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceLessThanOrEqualTo(Integer value) {
            addCriterion("settlement_base_price <=", value, "settlement_base_price");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceIn(List<Integer> values) {
            addCriterion("settlement_base_price in", values, "settlement_base_price");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceNotIn(List<Integer> values) {
            addCriterion("settlement_base_price not in", values, "settlement_base_price");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceBetween(Integer value1, Integer value2) {
            addCriterion("settlement_base_price between", value1, value2, "settlement_base_price");
            return (Criteria) this;
        }

        public Criteria andSettlement_base_priceNotBetween(Integer value1, Integer value2) {
            addCriterion("settlement_base_price not between", value1, value2, "settlement_base_price");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeIsNull() {
            addCriterion("booking_date_type is null");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeIsNotNull() {
            addCriterion("booking_date_type is not null");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeEqualTo(Integer value) {
            addCriterion("booking_date_type =", value, "booking_date_type");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeNotEqualTo(Integer value) {
            addCriterion("booking_date_type <>", value, "booking_date_type");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeGreaterThan(Integer value) {
            addCriterion("booking_date_type >", value, "booking_date_type");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("booking_date_type >=", value, "booking_date_type");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeLessThan(Integer value) {
            addCriterion("booking_date_type <", value, "booking_date_type");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeLessThanOrEqualTo(Integer value) {
            addCriterion("booking_date_type <=", value, "booking_date_type");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeIn(List<Integer> values) {
            addCriterion("booking_date_type in", values, "booking_date_type");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeNotIn(List<Integer> values) {
            addCriterion("booking_date_type not in", values, "booking_date_type");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeBetween(Integer value1, Integer value2) {
            addCriterion("booking_date_type between", value1, value2, "booking_date_type");
            return (Criteria) this;
        }

        public Criteria andBooking_date_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("booking_date_type not between", value1, value2, "booking_date_type");
            return (Criteria) this;
        }

        public Criteria andService_cycleIsNull() {
            addCriterion("service_cycle is null");
            return (Criteria) this;
        }

        public Criteria andService_cycleIsNotNull() {
            addCriterion("service_cycle is not null");
            return (Criteria) this;
        }

        public Criteria andService_cycleEqualTo(String value) {
            addCriterion("service_cycle =", value, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleNotEqualTo(String value) {
            addCriterion("service_cycle <>", value, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleGreaterThan(String value) {
            addCriterion("service_cycle >", value, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleGreaterThanOrEqualTo(String value) {
            addCriterion("service_cycle >=", value, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleLessThan(String value) {
            addCriterion("service_cycle <", value, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleLessThanOrEqualTo(String value) {
            addCriterion("service_cycle <=", value, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleLike(String value) {
            addCriterion("service_cycle like", value, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleNotLike(String value) {
            addCriterion("service_cycle not like", value, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleIn(List<String> values) {
            addCriterion("service_cycle in", values, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleNotIn(List<String> values) {
            addCriterion("service_cycle not in", values, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleBetween(String value1, String value2) {
            addCriterion("service_cycle between", value1, value2, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_cycleNotBetween(String value1, String value2) {
            addCriterion("service_cycle not between", value1, value2, "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_dateIsNull() {
            addCriterion("service_date is null");
            return (Criteria) this;
        }

        public Criteria andService_dateIsNotNull() {
            addCriterion("service_date is not null");
            return (Criteria) this;
        }

        public Criteria andService_dateEqualTo(String value) {
            addCriterion("service_date =", value, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateNotEqualTo(String value) {
            addCriterion("service_date <>", value, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateGreaterThan(String value) {
            addCriterion("service_date >", value, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateGreaterThanOrEqualTo(String value) {
            addCriterion("service_date >=", value, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateLessThan(String value) {
            addCriterion("service_date <", value, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateLessThanOrEqualTo(String value) {
            addCriterion("service_date <=", value, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateLike(String value) {
            addCriterion("service_date like", value, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateNotLike(String value) {
            addCriterion("service_date not like", value, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateIn(List<String> values) {
            addCriterion("service_date in", values, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateNotIn(List<String> values) {
            addCriterion("service_date not in", values, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateBetween(String value1, String value2) {
            addCriterion("service_date between", value1, value2, "service_date");
            return (Criteria) this;
        }

        public Criteria andService_dateNotBetween(String value1, String value2) {
            addCriterion("service_date not between", value1, value2, "service_date");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(name) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andDescriptLikeInsensitive(String value) {
            addCriterion("upper(descript) like", value.toUpperCase(), "descript");
            return (Criteria) this;
        }

        public Criteria andService_timesLikeInsensitive(String value) {
            addCriterion("upper(service_times) like", value.toUpperCase(), "service_times");
            return (Criteria) this;
        }

        public Criteria andUnitLikeInsensitive(String value) {
            addCriterion("upper(unit) like", value.toUpperCase(), "unit");
            return (Criteria) this;
        }

        public Criteria andService_cycleLikeInsensitive(String value) {
            addCriterion("upper(service_cycle) like", value.toUpperCase(), "service_cycle");
            return (Criteria) this;
        }

        public Criteria andService_dateLikeInsensitive(String value) {
            addCriterion("upper(service_date) like", value.toUpperCase(), "service_date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table psku
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 14 15:50:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table psku
     *
     * @mbg.generated Tue Aug 14 15:50:09 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	商品单项
		//--------------------------------------------------					
														psku_id(1,Types.BIGINT,false),
		/** 商品id */									product_id(2,Types.BIGINT,false),
		/** 名称 */										name(2,Types.VARCHAR,false),
		/** 描述 */										descript(2,Types.VARCHAR,false),
		/** 市场价 ，单位分 */							pricev(2,Types.INTEGER,false),
		/** 价格 ，单位分 */							price(2,Types.INTEGER,false),
		/** 服务时长，单位 分钟 */						service_time_length(2,Types.INTEGER,false),
		/** 服务时间段 JSON 数据 [{s:5,e:6}]   s e 的值为 0-47 ,1=30 分钟 */
														service_times(2,Types.VARCHAR,false),
		/** 排序号 1 开始 升序 */						sort_num(2,Types.INTEGER,false),
		/** 一天最多购买次数 */							buy_limit(2,Types.INTEGER,false),
		/** 删除状态  1 已删除  0 未删除 */				deleted(2,Types.INTEGER,false),
		/** 一次购买多件  是否允许    1 是 0 否 */		buy_multiple(2,Types.INTEGER,false),
		/** 一次购买多件  最小购买件数 */				buy_multiple_min(2,Types.INTEGER,false),
		/** 一次购买多件  最大购买件数  无最大限制时 0 */
														buy_multiple_max(2,Types.INTEGER,false),
		/** 一次购买多件  派遣服务人员一对一   1 是 0 否 */
														buy_multiple_o2o(2,Types.INTEGER,false),
		/** 预约策略id */								bespeak_strategy_id(2,Types.INTEGER,false),
		/** sku的单位。如米，件，个等 直接存文字 */		unit(2,Types.VARCHAR,false),
		/** 展示位置 0 顾客端，1服务人员端  [DV=>0] */	dispaly(2,Types.INTEGER,false),
		/** 默认sku   1 是 0 否 */						default_sku(2,Types.INTEGER,false),
		/** 约定结算基准价 */							settlement_base_price(2,Types.INTEGER,false),
		/** 预约日期类型：0按长期，1按星期  2按日期 [DV=>0] */
														booking_date_type(2,Types.INTEGER,false),
		/** 按星期    [1,2,3,4,5,6,7]   周一从1开始 */	service_cycle(2,Types.VARCHAR,false),
		/** 按日期  [{m:"8",d:"1,2,4,23,24"},{m:"9",d:"3,4,5"}] m:月份  d：m月份内不可用的日期 */
														service_date(2,Types.VARCHAR,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}