package com.aobei.train.model;

import com.aobei.train.model.RefundExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class RefundExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbg.generated Sun Apr 08 11:15:25 CST 2018
     */
    public RefundExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbg.generated Sun Apr 08 11:15:25 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbg.generated Sun Apr 08 11:15:25 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbg.generated Sun Apr 08 11:15:25 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table refund
     *
     * @mbg.generated Sun Apr 08 11:15:25 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andRefund_idIsNull() {
            addCriterion("refund_id is null");
            return (Criteria) this;
        }

        public Criteria andRefund_idIsNotNull() {
            addCriterion("refund_id is not null");
            return (Criteria) this;
        }

        public Criteria andRefund_idEqualTo(Long value) {
            addCriterion("refund_id =", value, "refund_id");
            return (Criteria) this;
        }

        public Criteria andRefund_idNotEqualTo(Long value) {
            addCriterion("refund_id <>", value, "refund_id");
            return (Criteria) this;
        }

        public Criteria andRefund_idGreaterThan(Long value) {
            addCriterion("refund_id >", value, "refund_id");
            return (Criteria) this;
        }

        public Criteria andRefund_idGreaterThanOrEqualTo(Long value) {
            addCriterion("refund_id >=", value, "refund_id");
            return (Criteria) this;
        }

        public Criteria andRefund_idLessThan(Long value) {
            addCriterion("refund_id <", value, "refund_id");
            return (Criteria) this;
        }

        public Criteria andRefund_idLessThanOrEqualTo(Long value) {
            addCriterion("refund_id <=", value, "refund_id");
            return (Criteria) this;
        }

        public Criteria andRefund_idIn(List<Long> values) {
            addCriterion("refund_id in", values, "refund_id");
            return (Criteria) this;
        }

        public Criteria andRefund_idNotIn(List<Long> values) {
            addCriterion("refund_id not in", values, "refund_id");
            return (Criteria) this;
        }

        public Criteria andRefund_idBetween(Long value1, Long value2) {
            addCriterion("refund_id between", value1, value2, "refund_id");
            return (Criteria) this;
        }

        public Criteria andRefund_idNotBetween(Long value1, Long value2) {
            addCriterion("refund_id not between", value1, value2, "refund_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIsNull() {
            addCriterion("pay_order_id is null");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIsNotNull() {
            addCriterion("pay_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andPay_order_idEqualTo(String value) {
            addCriterion("pay_order_id =", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotEqualTo(String value) {
            addCriterion("pay_order_id <>", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idGreaterThan(String value) {
            addCriterion("pay_order_id >", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idGreaterThanOrEqualTo(String value) {
            addCriterion("pay_order_id >=", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLessThan(String value) {
            addCriterion("pay_order_id <", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLessThanOrEqualTo(String value) {
            addCriterion("pay_order_id <=", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLike(String value) {
            addCriterion("pay_order_id like", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotLike(String value) {
            addCriterion("pay_order_id not like", value, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idIn(List<String> values) {
            addCriterion("pay_order_id in", values, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotIn(List<String> values) {
            addCriterion("pay_order_id not in", values, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idBetween(String value1, String value2) {
            addCriterion("pay_order_id between", value1, value2, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andPay_order_idNotBetween(String value1, String value2) {
            addCriterion("pay_order_id not between", value1, value2, "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andFeeIsNull() {
            addCriterion("fee is null");
            return (Criteria) this;
        }

        public Criteria andFeeIsNotNull() {
            addCriterion("fee is not null");
            return (Criteria) this;
        }

        public Criteria andFeeEqualTo(Integer value) {
            addCriterion("fee =", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotEqualTo(Integer value) {
            addCriterion("fee <>", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThan(Integer value) {
            addCriterion("fee >", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fee >=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThan(Integer value) {
            addCriterion("fee <", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThanOrEqualTo(Integer value) {
            addCriterion("fee <=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeIn(List<Integer> values) {
            addCriterion("fee in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotIn(List<Integer> values) {
            addCriterion("fee not in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeBetween(Integer value1, Integer value2) {
            addCriterion("fee between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("fee not between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andInfoIsNull() {
            addCriterion("info is null");
            return (Criteria) this;
        }

        public Criteria andInfoIsNotNull() {
            addCriterion("info is not null");
            return (Criteria) this;
        }

        public Criteria andInfoEqualTo(String value) {
            addCriterion("info =", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotEqualTo(String value) {
            addCriterion("info <>", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThan(String value) {
            addCriterion("info >", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThanOrEqualTo(String value) {
            addCriterion("info >=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThan(String value) {
            addCriterion("info <", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThanOrEqualTo(String value) {
            addCriterion("info <=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLike(String value) {
            addCriterion("info like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotLike(String value) {
            addCriterion("info not like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoIn(List<String> values) {
            addCriterion("info in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotIn(List<String> values) {
            addCriterion("info not in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoBetween(String value1, String value2) {
            addCriterion("info between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotBetween(String value1, String value2) {
            addCriterion("info not between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andRefund_dateIsNull() {
            addCriterion("refund_date is null");
            return (Criteria) this;
        }

        public Criteria andRefund_dateIsNotNull() {
            addCriterion("refund_date is not null");
            return (Criteria) this;
        }

        public Criteria andRefund_dateEqualTo(Date value) {
            addCriterion("refund_date =", value, "refund_date");
            return (Criteria) this;
        }

        public Criteria andRefund_dateNotEqualTo(Date value) {
            addCriterion("refund_date <>", value, "refund_date");
            return (Criteria) this;
        }

        public Criteria andRefund_dateGreaterThan(Date value) {
            addCriterion("refund_date >", value, "refund_date");
            return (Criteria) this;
        }

        public Criteria andRefund_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("refund_date >=", value, "refund_date");
            return (Criteria) this;
        }

        public Criteria andRefund_dateLessThan(Date value) {
            addCriterion("refund_date <", value, "refund_date");
            return (Criteria) this;
        }

        public Criteria andRefund_dateLessThanOrEqualTo(Date value) {
            addCriterion("refund_date <=", value, "refund_date");
            return (Criteria) this;
        }

        public Criteria andRefund_dateIn(List<Date> values) {
            addCriterion("refund_date in", values, "refund_date");
            return (Criteria) this;
        }

        public Criteria andRefund_dateNotIn(List<Date> values) {
            addCriterion("refund_date not in", values, "refund_date");
            return (Criteria) this;
        }

        public Criteria andRefund_dateBetween(Date value1, Date value2) {
            addCriterion("refund_date between", value1, value2, "refund_date");
            return (Criteria) this;
        }

        public Criteria andRefund_dateNotBetween(Date value1, Date value2) {
            addCriterion("refund_date not between", value1, value2, "refund_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_dateEqualTo(Date value) {
            addCriterion("create_date =", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateGreaterThan(Date value) {
            addCriterion("create_date >", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateLessThan(Date value) {
            addCriterion("create_date <", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIn(List<Date> values) {
            addCriterion("create_date in", values, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "create_date");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRtypeIsNull() {
            addCriterion("rtype is null");
            return (Criteria) this;
        }

        public Criteria andRtypeIsNotNull() {
            addCriterion("rtype is not null");
            return (Criteria) this;
        }

        public Criteria andRtypeEqualTo(Integer value) {
            addCriterion("rtype =", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeNotEqualTo(Integer value) {
            addCriterion("rtype <>", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeGreaterThan(Integer value) {
            addCriterion("rtype >", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("rtype >=", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeLessThan(Integer value) {
            addCriterion("rtype <", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeLessThanOrEqualTo(Integer value) {
            addCriterion("rtype <=", value, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeIn(List<Integer> values) {
            addCriterion("rtype in", values, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeNotIn(List<Integer> values) {
            addCriterion("rtype not in", values, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeBetween(Integer value1, Integer value2) {
            addCriterion("rtype between", value1, value2, "rtype");
            return (Criteria) this;
        }

        public Criteria andRtypeNotBetween(Integer value1, Integer value2) {
            addCriterion("rtype not between", value1, value2, "rtype");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Long value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Long value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Long value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Long> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andR_infoIsNull() {
            addCriterion("r_info is null");
            return (Criteria) this;
        }

        public Criteria andR_infoIsNotNull() {
            addCriterion("r_info is not null");
            return (Criteria) this;
        }

        public Criteria andR_infoEqualTo(String value) {
            addCriterion("r_info =", value, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoNotEqualTo(String value) {
            addCriterion("r_info <>", value, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoGreaterThan(String value) {
            addCriterion("r_info >", value, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoGreaterThanOrEqualTo(String value) {
            addCriterion("r_info >=", value, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoLessThan(String value) {
            addCriterion("r_info <", value, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoLessThanOrEqualTo(String value) {
            addCriterion("r_info <=", value, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoLike(String value) {
            addCriterion("r_info like", value, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoNotLike(String value) {
            addCriterion("r_info not like", value, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoIn(List<String> values) {
            addCriterion("r_info in", values, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoNotIn(List<String> values) {
            addCriterion("r_info not in", values, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoBetween(String value1, String value2) {
            addCriterion("r_info between", value1, value2, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_infoNotBetween(String value1, String value2) {
            addCriterion("r_info not between", value1, value2, "r_info");
            return (Criteria) this;
        }

        public Criteria andR_dateIsNull() {
            addCriterion("r_date is null");
            return (Criteria) this;
        }

        public Criteria andR_dateIsNotNull() {
            addCriterion("r_date is not null");
            return (Criteria) this;
        }

        public Criteria andR_dateEqualTo(Date value) {
            addCriterion("r_date =", value, "r_date");
            return (Criteria) this;
        }

        public Criteria andR_dateNotEqualTo(Date value) {
            addCriterion("r_date <>", value, "r_date");
            return (Criteria) this;
        }

        public Criteria andR_dateGreaterThan(Date value) {
            addCriterion("r_date >", value, "r_date");
            return (Criteria) this;
        }

        public Criteria andR_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("r_date >=", value, "r_date");
            return (Criteria) this;
        }

        public Criteria andR_dateLessThan(Date value) {
            addCriterion("r_date <", value, "r_date");
            return (Criteria) this;
        }

        public Criteria andR_dateLessThanOrEqualTo(Date value) {
            addCriterion("r_date <=", value, "r_date");
            return (Criteria) this;
        }

        public Criteria andR_dateIn(List<Date> values) {
            addCriterion("r_date in", values, "r_date");
            return (Criteria) this;
        }

        public Criteria andR_dateNotIn(List<Date> values) {
            addCriterion("r_date not in", values, "r_date");
            return (Criteria) this;
        }

        public Criteria andR_dateBetween(Date value1, Date value2) {
            addCriterion("r_date between", value1, value2, "r_date");
            return (Criteria) this;
        }

        public Criteria andR_dateNotBetween(Date value1, Date value2) {
            addCriterion("r_date not between", value1, value2, "r_date");
            return (Criteria) this;
        }

        public Criteria andR_user_idIsNull() {
            addCriterion("r_user_id is null");
            return (Criteria) this;
        }

        public Criteria andR_user_idIsNotNull() {
            addCriterion("r_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andR_user_idEqualTo(Long value) {
            addCriterion("r_user_id =", value, "r_user_id");
            return (Criteria) this;
        }

        public Criteria andR_user_idNotEqualTo(Long value) {
            addCriterion("r_user_id <>", value, "r_user_id");
            return (Criteria) this;
        }

        public Criteria andR_user_idGreaterThan(Long value) {
            addCriterion("r_user_id >", value, "r_user_id");
            return (Criteria) this;
        }

        public Criteria andR_user_idGreaterThanOrEqualTo(Long value) {
            addCriterion("r_user_id >=", value, "r_user_id");
            return (Criteria) this;
        }

        public Criteria andR_user_idLessThan(Long value) {
            addCriterion("r_user_id <", value, "r_user_id");
            return (Criteria) this;
        }

        public Criteria andR_user_idLessThanOrEqualTo(Long value) {
            addCriterion("r_user_id <=", value, "r_user_id");
            return (Criteria) this;
        }

        public Criteria andR_user_idIn(List<Long> values) {
            addCriterion("r_user_id in", values, "r_user_id");
            return (Criteria) this;
        }

        public Criteria andR_user_idNotIn(List<Long> values) {
            addCriterion("r_user_id not in", values, "r_user_id");
            return (Criteria) this;
        }

        public Criteria andR_user_idBetween(Long value1, Long value2) {
            addCriterion("r_user_id between", value1, value2, "r_user_id");
            return (Criteria) this;
        }

        public Criteria andR_user_idNotBetween(Long value1, Long value2) {
            addCriterion("r_user_id not between", value1, value2, "r_user_id");
            return (Criteria) this;
        }

        public Criteria andApply_typeIsNull() {
            addCriterion("apply_type is null");
            return (Criteria) this;
        }

        public Criteria andApply_typeIsNotNull() {
            addCriterion("apply_type is not null");
            return (Criteria) this;
        }

        public Criteria andApply_typeEqualTo(Integer value) {
            addCriterion("apply_type =", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeNotEqualTo(Integer value) {
            addCriterion("apply_type <>", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeGreaterThan(Integer value) {
            addCriterion("apply_type >", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_type >=", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeLessThan(Integer value) {
            addCriterion("apply_type <", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeLessThanOrEqualTo(Integer value) {
            addCriterion("apply_type <=", value, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeIn(List<Integer> values) {
            addCriterion("apply_type in", values, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeNotIn(List<Integer> values) {
            addCriterion("apply_type not in", values, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeBetween(Integer value1, Integer value2) {
            addCriterion("apply_type between", value1, value2, "apply_type");
            return (Criteria) this;
        }

        public Criteria andApply_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_type not between", value1, value2, "apply_type");
            return (Criteria) this;
        }

        public Criteria andOrder_nameIsNull() {
            addCriterion("order_name is null");
            return (Criteria) this;
        }

        public Criteria andOrder_nameIsNotNull() {
            addCriterion("order_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_nameEqualTo(String value) {
            addCriterion("order_name =", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameNotEqualTo(String value) {
            addCriterion("order_name <>", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameGreaterThan(String value) {
            addCriterion("order_name >", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameGreaterThanOrEqualTo(String value) {
            addCriterion("order_name >=", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameLessThan(String value) {
            addCriterion("order_name <", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameLessThanOrEqualTo(String value) {
            addCriterion("order_name <=", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameLike(String value) {
            addCriterion("order_name like", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameNotLike(String value) {
            addCriterion("order_name not like", value, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameIn(List<String> values) {
            addCriterion("order_name in", values, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameNotIn(List<String> values) {
            addCriterion("order_name not in", values, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameBetween(String value1, String value2) {
            addCriterion("order_name between", value1, value2, "order_name");
            return (Criteria) this;
        }

        public Criteria andOrder_nameNotBetween(String value1, String value2) {
            addCriterion("order_name not between", value1, value2, "order_name");
            return (Criteria) this;
        }

        public Criteria andCunameIsNull() {
            addCriterion("cuname is null");
            return (Criteria) this;
        }

        public Criteria andCunameIsNotNull() {
            addCriterion("cuname is not null");
            return (Criteria) this;
        }

        public Criteria andCunameEqualTo(String value) {
            addCriterion("cuname =", value, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameNotEqualTo(String value) {
            addCriterion("cuname <>", value, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameGreaterThan(String value) {
            addCriterion("cuname >", value, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameGreaterThanOrEqualTo(String value) {
            addCriterion("cuname >=", value, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameLessThan(String value) {
            addCriterion("cuname <", value, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameLessThanOrEqualTo(String value) {
            addCriterion("cuname <=", value, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameLike(String value) {
            addCriterion("cuname like", value, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameNotLike(String value) {
            addCriterion("cuname not like", value, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameIn(List<String> values) {
            addCriterion("cuname in", values, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameNotIn(List<String> values) {
            addCriterion("cuname not in", values, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameBetween(String value1, String value2) {
            addCriterion("cuname between", value1, value2, "cuname");
            return (Criteria) this;
        }

        public Criteria andCunameNotBetween(String value1, String value2) {
            addCriterion("cuname not between", value1, value2, "cuname");
            return (Criteria) this;
        }

        public Criteria andUphoneIsNull() {
            addCriterion("uphone is null");
            return (Criteria) this;
        }

        public Criteria andUphoneIsNotNull() {
            addCriterion("uphone is not null");
            return (Criteria) this;
        }

        public Criteria andUphoneEqualTo(String value) {
            addCriterion("uphone =", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotEqualTo(String value) {
            addCriterion("uphone <>", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneGreaterThan(String value) {
            addCriterion("uphone >", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneGreaterThanOrEqualTo(String value) {
            addCriterion("uphone >=", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneLessThan(String value) {
            addCriterion("uphone <", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneLessThanOrEqualTo(String value) {
            addCriterion("uphone <=", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneLike(String value) {
            addCriterion("uphone like", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotLike(String value) {
            addCriterion("uphone not like", value, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneIn(List<String> values) {
            addCriterion("uphone in", values, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotIn(List<String> values) {
            addCriterion("uphone not in", values, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneBetween(String value1, String value2) {
            addCriterion("uphone between", value1, value2, "uphone");
            return (Criteria) this;
        }

        public Criteria andUphoneNotBetween(String value1, String value2) {
            addCriterion("uphone not between", value1, value2, "uphone");
            return (Criteria) this;
        }

        public Criteria andCus_addressIsNull() {
            addCriterion("cus_address is null");
            return (Criteria) this;
        }

        public Criteria andCus_addressIsNotNull() {
            addCriterion("cus_address is not null");
            return (Criteria) this;
        }

        public Criteria andCus_addressEqualTo(String value) {
            addCriterion("cus_address =", value, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressNotEqualTo(String value) {
            addCriterion("cus_address <>", value, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressGreaterThan(String value) {
            addCriterion("cus_address >", value, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressGreaterThanOrEqualTo(String value) {
            addCriterion("cus_address >=", value, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressLessThan(String value) {
            addCriterion("cus_address <", value, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressLessThanOrEqualTo(String value) {
            addCriterion("cus_address <=", value, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressLike(String value) {
            addCriterion("cus_address like", value, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressNotLike(String value) {
            addCriterion("cus_address not like", value, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressIn(List<String> values) {
            addCriterion("cus_address in", values, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressNotIn(List<String> values) {
            addCriterion("cus_address not in", values, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressBetween(String value1, String value2) {
            addCriterion("cus_address between", value1, value2, "cus_address");
            return (Criteria) this;
        }

        public Criteria andCus_addressNotBetween(String value1, String value2) {
            addCriterion("cus_address not between", value1, value2, "cus_address");
            return (Criteria) this;
        }

        public Criteria andPrice_totalIsNull() {
            addCriterion("price_total is null");
            return (Criteria) this;
        }

        public Criteria andPrice_totalIsNotNull() {
            addCriterion("price_total is not null");
            return (Criteria) this;
        }

        public Criteria andPrice_totalEqualTo(Integer value) {
            addCriterion("price_total =", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalNotEqualTo(Integer value) {
            addCriterion("price_total <>", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalGreaterThan(Integer value) {
            addCriterion("price_total >", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalGreaterThanOrEqualTo(Integer value) {
            addCriterion("price_total >=", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalLessThan(Integer value) {
            addCriterion("price_total <", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalLessThanOrEqualTo(Integer value) {
            addCriterion("price_total <=", value, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalIn(List<Integer> values) {
            addCriterion("price_total in", values, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalNotIn(List<Integer> values) {
            addCriterion("price_total not in", values, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalBetween(Integer value1, Integer value2) {
            addCriterion("price_total between", value1, value2, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_totalNotBetween(Integer value1, Integer value2) {
            addCriterion("price_total not between", value1, value2, "price_total");
            return (Criteria) this;
        }

        public Criteria andPrice_payIsNull() {
            addCriterion("price_pay is null");
            return (Criteria) this;
        }

        public Criteria andPrice_payIsNotNull() {
            addCriterion("price_pay is not null");
            return (Criteria) this;
        }

        public Criteria andPrice_payEqualTo(Integer value) {
            addCriterion("price_pay =", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payNotEqualTo(Integer value) {
            addCriterion("price_pay <>", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payGreaterThan(Integer value) {
            addCriterion("price_pay >", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payGreaterThanOrEqualTo(Integer value) {
            addCriterion("price_pay >=", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payLessThan(Integer value) {
            addCriterion("price_pay <", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payLessThanOrEqualTo(Integer value) {
            addCriterion("price_pay <=", value, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payIn(List<Integer> values) {
            addCriterion("price_pay in", values, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payNotIn(List<Integer> values) {
            addCriterion("price_pay not in", values, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payBetween(Integer value1, Integer value2) {
            addCriterion("price_pay between", value1, value2, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPrice_payNotBetween(Integer value1, Integer value2) {
            addCriterion("price_pay not between", value1, value2, "price_pay");
            return (Criteria) this;
        }

        public Criteria andPartner_idIsNull() {
            addCriterion("partner_id is null");
            return (Criteria) this;
        }

        public Criteria andPartner_idIsNotNull() {
            addCriterion("partner_id is not null");
            return (Criteria) this;
        }

        public Criteria andPartner_idEqualTo(Long value) {
            addCriterion("partner_id =", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotEqualTo(Long value) {
            addCriterion("partner_id <>", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idGreaterThan(Long value) {
            addCriterion("partner_id >", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idGreaterThanOrEqualTo(Long value) {
            addCriterion("partner_id >=", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idLessThan(Long value) {
            addCriterion("partner_id <", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idLessThanOrEqualTo(Long value) {
            addCriterion("partner_id <=", value, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idIn(List<Long> values) {
            addCriterion("partner_id in", values, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotIn(List<Long> values) {
            addCriterion("partner_id not in", values, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idBetween(Long value1, Long value2) {
            addCriterion("partner_id between", value1, value2, "partner_id");
            return (Criteria) this;
        }

        public Criteria andPartner_idNotBetween(Long value1, Long value2) {
            addCriterion("partner_id not between", value1, value2, "partner_id");
            return (Criteria) this;
        }

        public Criteria andStudent_nameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudent_nameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudent_nameEqualTo(String value) {
            addCriterion("student_name =", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameGreaterThan(String value) {
            addCriterion("student_name >", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameLessThan(String value) {
            addCriterion("student_name <", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameLike(String value) {
            addCriterion("student_name like", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameNotLike(String value) {
            addCriterion("student_name not like", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameIn(List<String> values) {
            addCriterion("student_name in", values, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "student_name");
            return (Criteria) this;
        }

        public Criteria andPay_order_idLikeInsensitive(String value) {
            addCriterion("upper(pay_order_id) like", value.toUpperCase(), "pay_order_id");
            return (Criteria) this;
        }

        public Criteria andInfoLikeInsensitive(String value) {
            addCriterion("upper(info) like", value.toUpperCase(), "info");
            return (Criteria) this;
        }

        public Criteria andR_infoLikeInsensitive(String value) {
            addCriterion("upper(r_info) like", value.toUpperCase(), "r_info");
            return (Criteria) this;
        }

        public Criteria andOrder_nameLikeInsensitive(String value) {
            addCriterion("upper(order_name) like", value.toUpperCase(), "order_name");
            return (Criteria) this;
        }

        public Criteria andCunameLikeInsensitive(String value) {
            addCriterion("upper(cuname) like", value.toUpperCase(), "cuname");
            return (Criteria) this;
        }

        public Criteria andUphoneLikeInsensitive(String value) {
            addCriterion("upper(uphone) like", value.toUpperCase(), "uphone");
            return (Criteria) this;
        }

        public Criteria andCus_addressLikeInsensitive(String value) {
            addCriterion("upper(cus_address) like", value.toUpperCase(), "cus_address");
            return (Criteria) this;
        }

        public Criteria andStudent_nameLikeInsensitive(String value) {
            addCriterion("upper(student_name) like", value.toUpperCase(), "student_name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table refund
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 08 11:15:25 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table refund
     *
     * @mbg.generated Sun Apr 08 11:15:25 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	退款记录
		//--------------------------------------------------
		/** 商家退款申请 id */							refund_id(1,Types.BIGINT,false),
		/** 订单号 */									pay_order_id(2,Types.VARCHAR,false),
		/** 退款金额 单位分 */							fee(2,Types.INTEGER,false),
		/** 退款原因 */									info(2,Types.VARCHAR,false),
		/** 退款时间 */									refund_date(2,Types.TIMESTAMP,false),
		/** 创建时间 */									create_date(2,Types.TIMESTAMP,false),
		/** 0 待退款 1 退款中 2 已退款  3 退款调用失败 4 申请被拒绝 */
														status(2,Types.INTEGER,false),
		/** 1 自动退订 2 系统退订 */					rtype(2,Types.INTEGER,false),
		/** 系统退订操作人员 id */						user_id(2,Types.BIGINT,false),
		/** 拒绝原因 */									r_info(2,Types.VARCHAR,false),
		/** 拒绝时间 */									r_date(2,Types.TIMESTAMP,false),
		/** 拒绝操作人 id */							r_user_id(2,Types.BIGINT,false),
		/** 退款申请类型  1 顾客申请  2 客服申请 */		apply_type(2,Types.INTEGER,false),
		/** 服务名称 */									order_name(2,Types.VARCHAR,false),
		/** 用户姓名（被服务者） */						cuname(2,Types.VARCHAR,false),
		/** 顾客电话（被服务者） */						uphone(2,Types.VARCHAR,false),
		/** 服务地址 */									cus_address(2,Types.VARCHAR,false),
		/** 服务价格 */									price_total(2,Types.INTEGER,false),
		/** 实付金额 */									price_pay(2,Types.INTEGER,false),
		/** 合伙人（商家）id */							partner_id(2,Types.BIGINT,false),
		/** 服务人员姓名 */								student_name(2,Types.VARCHAR,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}