package com.aobei.train.model;

import com.aobei.train.model.ServiceunitPersonExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class ServiceunitPersonExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceunit_person
     *
     * @mbg.generated Thu Apr 19 09:33:32 CST 2018
     */
    public ServiceunitPersonExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceunit_person
     *
     * @mbg.generated Thu Apr 19 09:33:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceunit_person
     *
     * @mbg.generated Thu Apr 19 09:33:32 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceunit_person
     *
     * @mbg.generated Thu Apr 19 09:33:32 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table serviceunit_person
     *
     * @mbg.generated Thu Apr 19 09:33:32 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andServiceunit_person_idIsNull() {
            addCriterion("serviceunit_person_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idIsNotNull() {
            addCriterion("serviceunit_person_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idEqualTo(Long value) {
            addCriterion("serviceunit_person_id =", value, "serviceunit_person_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idNotEqualTo(Long value) {
            addCriterion("serviceunit_person_id <>", value, "serviceunit_person_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idGreaterThan(Long value) {
            addCriterion("serviceunit_person_id >", value, "serviceunit_person_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idGreaterThanOrEqualTo(Long value) {
            addCriterion("serviceunit_person_id >=", value, "serviceunit_person_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idLessThan(Long value) {
            addCriterion("serviceunit_person_id <", value, "serviceunit_person_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idLessThanOrEqualTo(Long value) {
            addCriterion("serviceunit_person_id <=", value, "serviceunit_person_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idIn(List<Long> values) {
            addCriterion("serviceunit_person_id in", values, "serviceunit_person_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idNotIn(List<Long> values) {
            addCriterion("serviceunit_person_id not in", values, "serviceunit_person_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idBetween(Long value1, Long value2) {
            addCriterion("serviceunit_person_id between", value1, value2, "serviceunit_person_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_person_idNotBetween(Long value1, Long value2) {
            addCriterion("serviceunit_person_id not between", value1, value2, "serviceunit_person_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idIsNull() {
            addCriterion("serviceunit_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idIsNotNull() {
            addCriterion("serviceunit_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idEqualTo(Long value) {
            addCriterion("serviceunit_id =", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idNotEqualTo(Long value) {
            addCriterion("serviceunit_id <>", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idGreaterThan(Long value) {
            addCriterion("serviceunit_id >", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idGreaterThanOrEqualTo(Long value) {
            addCriterion("serviceunit_id >=", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idLessThan(Long value) {
            addCriterion("serviceunit_id <", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idLessThanOrEqualTo(Long value) {
            addCriterion("serviceunit_id <=", value, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idIn(List<Long> values) {
            addCriterion("serviceunit_id in", values, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idNotIn(List<Long> values) {
            addCriterion("serviceunit_id not in", values, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idBetween(Long value1, Long value2) {
            addCriterion("serviceunit_id between", value1, value2, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andServiceunit_idNotBetween(Long value1, Long value2) {
            addCriterion("serviceunit_id not between", value1, value2, "serviceunit_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudent_idIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudent_idEqualTo(Long value) {
            addCriterion("student_id =", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idNotEqualTo(Long value) {
            addCriterion("student_id <>", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idGreaterThan(Long value) {
            addCriterion("student_id >", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idGreaterThanOrEqualTo(Long value) {
            addCriterion("student_id >=", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idLessThan(Long value) {
            addCriterion("student_id <", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idLessThanOrEqualTo(Long value) {
            addCriterion("student_id <=", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idIn(List<Long> values) {
            addCriterion("student_id in", values, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idNotIn(List<Long> values) {
            addCriterion("student_id not in", values, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idBetween(Long value1, Long value2) {
            addCriterion("student_id between", value1, value2, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idNotBetween(Long value1, Long value2) {
            addCriterion("student_id not between", value1, value2, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_nameIsNull() {
            addCriterion("student_name is null");
            return (Criteria) this;
        }

        public Criteria andStudent_nameIsNotNull() {
            addCriterion("student_name is not null");
            return (Criteria) this;
        }

        public Criteria andStudent_nameEqualTo(String value) {
            addCriterion("student_name =", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameNotEqualTo(String value) {
            addCriterion("student_name <>", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameGreaterThan(String value) {
            addCriterion("student_name >", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameGreaterThanOrEqualTo(String value) {
            addCriterion("student_name >=", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameLessThan(String value) {
            addCriterion("student_name <", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameLessThanOrEqualTo(String value) {
            addCriterion("student_name <=", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameLike(String value) {
            addCriterion("student_name like", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameNotLike(String value) {
            addCriterion("student_name not like", value, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameIn(List<String> values) {
            addCriterion("student_name in", values, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameNotIn(List<String> values) {
            addCriterion("student_name not in", values, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameBetween(String value1, String value2) {
            addCriterion("student_name between", value1, value2, "student_name");
            return (Criteria) this;
        }

        public Criteria andStudent_nameNotBetween(String value1, String value2) {
            addCriterion("student_name not between", value1, value2, "student_name");
            return (Criteria) this;
        }

        public Criteria andWork_statusIsNull() {
            addCriterion("work_status is null");
            return (Criteria) this;
        }

        public Criteria andWork_statusIsNotNull() {
            addCriterion("work_status is not null");
            return (Criteria) this;
        }

        public Criteria andWork_statusEqualTo(Integer value) {
            addCriterion("work_status =", value, "work_status");
            return (Criteria) this;
        }

        public Criteria andWork_statusNotEqualTo(Integer value) {
            addCriterion("work_status <>", value, "work_status");
            return (Criteria) this;
        }

        public Criteria andWork_statusGreaterThan(Integer value) {
            addCriterion("work_status >", value, "work_status");
            return (Criteria) this;
        }

        public Criteria andWork_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("work_status >=", value, "work_status");
            return (Criteria) this;
        }

        public Criteria andWork_statusLessThan(Integer value) {
            addCriterion("work_status <", value, "work_status");
            return (Criteria) this;
        }

        public Criteria andWork_statusLessThanOrEqualTo(Integer value) {
            addCriterion("work_status <=", value, "work_status");
            return (Criteria) this;
        }

        public Criteria andWork_statusIn(List<Integer> values) {
            addCriterion("work_status in", values, "work_status");
            return (Criteria) this;
        }

        public Criteria andWork_statusNotIn(List<Integer> values) {
            addCriterion("work_status not in", values, "work_status");
            return (Criteria) this;
        }

        public Criteria andWork_statusBetween(Integer value1, Integer value2) {
            addCriterion("work_status between", value1, value2, "work_status");
            return (Criteria) this;
        }

        public Criteria andWork_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("work_status not between", value1, value2, "work_status");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeIsNull() {
            addCriterion("work_1_datetime is null");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeIsNotNull() {
            addCriterion("work_1_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeEqualTo(Date value) {
            addCriterion("work_1_datetime =", value, "work_1_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeNotEqualTo(Date value) {
            addCriterion("work_1_datetime <>", value, "work_1_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeGreaterThan(Date value) {
            addCriterion("work_1_datetime >", value, "work_1_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("work_1_datetime >=", value, "work_1_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeLessThan(Date value) {
            addCriterion("work_1_datetime <", value, "work_1_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("work_1_datetime <=", value, "work_1_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeIn(List<Date> values) {
            addCriterion("work_1_datetime in", values, "work_1_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeNotIn(List<Date> values) {
            addCriterion("work_1_datetime not in", values, "work_1_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeBetween(Date value1, Date value2) {
            addCriterion("work_1_datetime between", value1, value2, "work_1_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_1_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("work_1_datetime not between", value1, value2, "work_1_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeIsNull() {
            addCriterion("work_2_datetime is null");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeIsNotNull() {
            addCriterion("work_2_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeEqualTo(Date value) {
            addCriterion("work_2_datetime =", value, "work_2_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeNotEqualTo(Date value) {
            addCriterion("work_2_datetime <>", value, "work_2_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeGreaterThan(Date value) {
            addCriterion("work_2_datetime >", value, "work_2_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("work_2_datetime >=", value, "work_2_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeLessThan(Date value) {
            addCriterion("work_2_datetime <", value, "work_2_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("work_2_datetime <=", value, "work_2_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeIn(List<Date> values) {
            addCriterion("work_2_datetime in", values, "work_2_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeNotIn(List<Date> values) {
            addCriterion("work_2_datetime not in", values, "work_2_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeBetween(Date value1, Date value2) {
            addCriterion("work_2_datetime between", value1, value2, "work_2_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_2_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("work_2_datetime not between", value1, value2, "work_2_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeIsNull() {
            addCriterion("work_3_datetime is null");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeIsNotNull() {
            addCriterion("work_3_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeEqualTo(Date value) {
            addCriterion("work_3_datetime =", value, "work_3_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeNotEqualTo(Date value) {
            addCriterion("work_3_datetime <>", value, "work_3_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeGreaterThan(Date value) {
            addCriterion("work_3_datetime >", value, "work_3_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("work_3_datetime >=", value, "work_3_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeLessThan(Date value) {
            addCriterion("work_3_datetime <", value, "work_3_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("work_3_datetime <=", value, "work_3_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeIn(List<Date> values) {
            addCriterion("work_3_datetime in", values, "work_3_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeNotIn(List<Date> values) {
            addCriterion("work_3_datetime not in", values, "work_3_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeBetween(Date value1, Date value2) {
            addCriterion("work_3_datetime between", value1, value2, "work_3_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_3_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("work_3_datetime not between", value1, value2, "work_3_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeIsNull() {
            addCriterion("work_4_datetime is null");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeIsNotNull() {
            addCriterion("work_4_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeEqualTo(Date value) {
            addCriterion("work_4_datetime =", value, "work_4_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeNotEqualTo(Date value) {
            addCriterion("work_4_datetime <>", value, "work_4_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeGreaterThan(Date value) {
            addCriterion("work_4_datetime >", value, "work_4_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("work_4_datetime >=", value, "work_4_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeLessThan(Date value) {
            addCriterion("work_4_datetime <", value, "work_4_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("work_4_datetime <=", value, "work_4_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeIn(List<Date> values) {
            addCriterion("work_4_datetime in", values, "work_4_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeNotIn(List<Date> values) {
            addCriterion("work_4_datetime not in", values, "work_4_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeBetween(Date value1, Date value2) {
            addCriterion("work_4_datetime between", value1, value2, "work_4_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_4_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("work_4_datetime not between", value1, value2, "work_4_datetime");
            return (Criteria) this;
        }

        public Criteria andWork_remarkIsNull() {
            addCriterion("work_remark is null");
            return (Criteria) this;
        }

        public Criteria andWork_remarkIsNotNull() {
            addCriterion("work_remark is not null");
            return (Criteria) this;
        }

        public Criteria andWork_remarkEqualTo(String value) {
            addCriterion("work_remark =", value, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkNotEqualTo(String value) {
            addCriterion("work_remark <>", value, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkGreaterThan(String value) {
            addCriterion("work_remark >", value, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkGreaterThanOrEqualTo(String value) {
            addCriterion("work_remark >=", value, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkLessThan(String value) {
            addCriterion("work_remark <", value, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkLessThanOrEqualTo(String value) {
            addCriterion("work_remark <=", value, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkLike(String value) {
            addCriterion("work_remark like", value, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkNotLike(String value) {
            addCriterion("work_remark not like", value, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkIn(List<String> values) {
            addCriterion("work_remark in", values, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkNotIn(List<String> values) {
            addCriterion("work_remark not in", values, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkBetween(String value1, String value2) {
            addCriterion("work_remark between", value1, value2, "work_remark");
            return (Criteria) this;
        }

        public Criteria andWork_remarkNotBetween(String value1, String value2) {
            addCriterion("work_remark not between", value1, value2, "work_remark");
            return (Criteria) this;
        }

        public Criteria andStatus_activeIsNull() {
            addCriterion("status_active is null");
            return (Criteria) this;
        }

        public Criteria andStatus_activeIsNotNull() {
            addCriterion("status_active is not null");
            return (Criteria) this;
        }

        public Criteria andStatus_activeEqualTo(Integer value) {
            addCriterion("status_active =", value, "status_active");
            return (Criteria) this;
        }

        public Criteria andStatus_activeNotEqualTo(Integer value) {
            addCriterion("status_active <>", value, "status_active");
            return (Criteria) this;
        }

        public Criteria andStatus_activeGreaterThan(Integer value) {
            addCriterion("status_active >", value, "status_active");
            return (Criteria) this;
        }

        public Criteria andStatus_activeGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_active >=", value, "status_active");
            return (Criteria) this;
        }

        public Criteria andStatus_activeLessThan(Integer value) {
            addCriterion("status_active <", value, "status_active");
            return (Criteria) this;
        }

        public Criteria andStatus_activeLessThanOrEqualTo(Integer value) {
            addCriterion("status_active <=", value, "status_active");
            return (Criteria) this;
        }

        public Criteria andStatus_activeIn(List<Integer> values) {
            addCriterion("status_active in", values, "status_active");
            return (Criteria) this;
        }

        public Criteria andStatus_activeNotIn(List<Integer> values) {
            addCriterion("status_active not in", values, "status_active");
            return (Criteria) this;
        }

        public Criteria andStatus_activeBetween(Integer value1, Integer value2) {
            addCriterion("status_active between", value1, value2, "status_active");
            return (Criteria) this;
        }

        public Criteria andStatus_activeNotBetween(Integer value1, Integer value2) {
            addCriterion("status_active not between", value1, value2, "status_active");
            return (Criteria) this;
        }

        public Criteria andStudent_nameLikeInsensitive(String value) {
            addCriterion("upper(student_name) like", value.toUpperCase(), "student_name");
            return (Criteria) this;
        }

        public Criteria andWork_remarkLikeInsensitive(String value) {
            addCriterion("upper(work_remark) like", value.toUpperCase(), "work_remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table serviceunit_person
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 19 09:33:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table serviceunit_person
     *
     * @mbg.generated Thu Apr 19 09:33:32 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	服务单 关联的服务人员
		//--------------------------------------------------					
														serviceunit_person_id(1,Types.BIGINT,false),
		/** 服务单id */									serviceunit_id(2,Types.BIGINT,false),
		/** 服务人员id */								student_id(2,Types.BIGINT,false),
		/** 服务人员姓名 */								student_name(2,Types.VARCHAR,false),
		/** 人员工作状态1 到达 2 开始 3 结束 4 离开 */	work_status(2,Types.INTEGER,false),
		/** 工作人员到达时间 */							work_1_datetime(2,Types.TIMESTAMP,false),
		/** 工作开始时间 */								work_2_datetime(2,Types.TIMESTAMP,false),
		/** 工作结束时间 */								work_3_datetime(2,Types.TIMESTAMP,false),
		/** 工作人员离开时间 */							work_4_datetime(2,Types.TIMESTAMP,false),
		/** 工作人员备注 */								work_remark(2,Types.VARCHAR,false),
		/** 订单表示状态点    1 待付款  2 待确认  3 待服务 4 已取消 5 已完成 */
														status_active(2,Types.INTEGER,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}