package com.aobei.train.model;

import com.aobei.train.model.ServiceitemExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class ServiceitemExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceitem
     *
     * @mbg.generated Thu Feb 01 16:52:23 CST 2018
     */
    public ServiceitemExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceitem
     *
     * @mbg.generated Thu Feb 01 16:52:23 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceitem
     *
     * @mbg.generated Thu Feb 01 16:52:23 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serviceitem
     *
     * @mbg.generated Thu Feb 01 16:52:23 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table serviceitem
     *
     * @mbg.generated Thu Feb 01 16:52:23 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andServiceitem_idIsNull() {
            addCriterion("serviceitem_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idIsNotNull() {
            addCriterion("serviceitem_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idEqualTo(Long value) {
            addCriterion("serviceitem_id =", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idNotEqualTo(Long value) {
            addCriterion("serviceitem_id <>", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idGreaterThan(Long value) {
            addCriterion("serviceitem_id >", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idGreaterThanOrEqualTo(Long value) {
            addCriterion("serviceitem_id >=", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idLessThan(Long value) {
            addCriterion("serviceitem_id <", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idLessThanOrEqualTo(Long value) {
            addCriterion("serviceitem_id <=", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idIn(List<Long> values) {
            addCriterion("serviceitem_id in", values, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idNotIn(List<Long> values) {
            addCriterion("serviceitem_id not in", values, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idBetween(Long value1, Long value2) {
            addCriterion("serviceitem_id between", value1, value2, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idNotBetween(Long value1, Long value2) {
            addCriterion("serviceitem_id not between", value1, value2, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescrIsNull() {
            addCriterion("descr is null");
            return (Criteria) this;
        }

        public Criteria andDescrIsNotNull() {
            addCriterion("descr is not null");
            return (Criteria) this;
        }

        public Criteria andDescrEqualTo(String value) {
            addCriterion("descr =", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotEqualTo(String value) {
            addCriterion("descr <>", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrGreaterThan(String value) {
            addCriterion("descr >", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrGreaterThanOrEqualTo(String value) {
            addCriterion("descr >=", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLessThan(String value) {
            addCriterion("descr <", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLessThanOrEqualTo(String value) {
            addCriterion("descr <=", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLike(String value) {
            addCriterion("descr like", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotLike(String value) {
            addCriterion("descr not like", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrIn(List<String> values) {
            addCriterion("descr in", values, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotIn(List<String> values) {
            addCriterion("descr not in", values, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrBetween(String value1, String value2) {
            addCriterion("descr between", value1, value2, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotBetween(String value1, String value2) {
            addCriterion("descr not between", value1, value2, "descr");
            return (Criteria) this;
        }

        public Criteria andOnline_dateIsNull() {
            addCriterion("online_date is null");
            return (Criteria) this;
        }

        public Criteria andOnline_dateIsNotNull() {
            addCriterion("online_date is not null");
            return (Criteria) this;
        }

        public Criteria andOnline_dateEqualTo(Date value) {
            addCriterion("online_date =", value, "online_date");
            return (Criteria) this;
        }

        public Criteria andOnline_dateNotEqualTo(Date value) {
            addCriterion("online_date <>", value, "online_date");
            return (Criteria) this;
        }

        public Criteria andOnline_dateGreaterThan(Date value) {
            addCriterion("online_date >", value, "online_date");
            return (Criteria) this;
        }

        public Criteria andOnline_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("online_date >=", value, "online_date");
            return (Criteria) this;
        }

        public Criteria andOnline_dateLessThan(Date value) {
            addCriterion("online_date <", value, "online_date");
            return (Criteria) this;
        }

        public Criteria andOnline_dateLessThanOrEqualTo(Date value) {
            addCriterion("online_date <=", value, "online_date");
            return (Criteria) this;
        }

        public Criteria andOnline_dateIn(List<Date> values) {
            addCriterion("online_date in", values, "online_date");
            return (Criteria) this;
        }

        public Criteria andOnline_dateNotIn(List<Date> values) {
            addCriterion("online_date not in", values, "online_date");
            return (Criteria) this;
        }

        public Criteria andOnline_dateBetween(Date value1, Date value2) {
            addCriterion("online_date between", value1, value2, "online_date");
            return (Criteria) this;
        }

        public Criteria andOnline_dateNotBetween(Date value1, Date value2) {
            addCriterion("online_date not between", value1, value2, "online_date");
            return (Criteria) this;
        }

        public Criteria andOffline_dateIsNull() {
            addCriterion("offline_date is null");
            return (Criteria) this;
        }

        public Criteria andOffline_dateIsNotNull() {
            addCriterion("offline_date is not null");
            return (Criteria) this;
        }

        public Criteria andOffline_dateEqualTo(Date value) {
            addCriterion("offline_date =", value, "offline_date");
            return (Criteria) this;
        }

        public Criteria andOffline_dateNotEqualTo(Date value) {
            addCriterion("offline_date <>", value, "offline_date");
            return (Criteria) this;
        }

        public Criteria andOffline_dateGreaterThan(Date value) {
            addCriterion("offline_date >", value, "offline_date");
            return (Criteria) this;
        }

        public Criteria andOffline_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("offline_date >=", value, "offline_date");
            return (Criteria) this;
        }

        public Criteria andOffline_dateLessThan(Date value) {
            addCriterion("offline_date <", value, "offline_date");
            return (Criteria) this;
        }

        public Criteria andOffline_dateLessThanOrEqualTo(Date value) {
            addCriterion("offline_date <=", value, "offline_date");
            return (Criteria) this;
        }

        public Criteria andOffline_dateIn(List<Date> values) {
            addCriterion("offline_date in", values, "offline_date");
            return (Criteria) this;
        }

        public Criteria andOffline_dateNotIn(List<Date> values) {
            addCriterion("offline_date not in", values, "offline_date");
            return (Criteria) this;
        }

        public Criteria andOffline_dateBetween(Date value1, Date value2) {
            addCriterion("offline_date between", value1, value2, "offline_date");
            return (Criteria) this;
        }

        public Criteria andOffline_dateNotBetween(Date value1, Date value2) {
            addCriterion("offline_date not between", value1, value2, "offline_date");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCategory_idIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategory_idIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategory_idEqualTo(Long value) {
            addCriterion("category_id =", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idNotEqualTo(Long value) {
            addCriterion("category_id <>", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idGreaterThan(Long value) {
            addCriterion("category_id >", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idGreaterThanOrEqualTo(Long value) {
            addCriterion("category_id >=", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idLessThan(Long value) {
            addCriterion("category_id <", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idLessThanOrEqualTo(Long value) {
            addCriterion("category_id <=", value, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idIn(List<Long> values) {
            addCriterion("category_id in", values, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idNotIn(List<Long> values) {
            addCriterion("category_id not in", values, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idBetween(Long value1, Long value2) {
            addCriterion("category_id between", value1, value2, "category_id");
            return (Criteria) this;
        }

        public Criteria andCategory_idNotBetween(Long value1, Long value2) {
            addCriterion("category_id not between", value1, value2, "category_id");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andNameLikeInsensitive(String value) {
            addCriterion("upper(name) like", value.toUpperCase(), "name");
            return (Criteria) this;
        }

        public Criteria andDescrLikeInsensitive(String value) {
            addCriterion("upper(descr) like", value.toUpperCase(), "descr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table serviceitem
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 01 16:52:23 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table serviceitem
     *
     * @mbg.generated Thu Feb 01 16:52:23 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	服务项
		//--------------------------------------------------
		/** 服务项目id */							serviceitem_id(1,Types.BIGINT,false),
		/** 名称 */									name(2,Types.VARCHAR,false),
		/** 描述 */									descr(2,Types.VARCHAR,false),
		/** 上线时间 */								online_date(2,Types.TIMESTAMP,false),
		/** 下线时间 */								offline_date(2,Types.TIMESTAMP,false),
		/** 状态(0:下线 1:上线) */					state(2,Types.INTEGER,false),
		/** 分类id */								category_id(2,Types.BIGINT,false),
		/** 0 未删除，1 已删除 [DV=>0] */			deleted(2,Types.INTEGER,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}