package com.aobei.train.model;

import com.aobei.train.model.StudentServiceitemExample.Criteria;
import com.github.liyiorg.mbg.support.example.CInterface;
import com.github.liyiorg.mbg.support.example.CItem;
import com.github.liyiorg.mbg.support.example.ColumnListAble;
import com.github.liyiorg.mbg.support.example.MbgExample;
import com.github.liyiorg.mbg.support.example.MbgGeneratedCriteria;
import com.github.liyiorg.mbg.support.example.PaginationAble;
import com.github.liyiorg.mbg.util.CUtil;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

@SuppressWarnings("unused")
public class StudentServiceitemExample extends MbgExample<Criteria> implements PaginationAble, Serializable, ColumnListAble {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student__serviceitem
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public StudentServiceitemExample() {
        databaseType = "MySQL";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student__serviceitem
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student__serviceitem
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public void includeColumns(C... cs) {
        CUtil.includeColumns(C.class, this, cs);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student__serviceitem
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public void excludeColumns(C... cs) {
        CUtil.excludeColumns(C.class, this, cs);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student__serviceitem
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    protected abstract static class GeneratedCriteria extends MbgGeneratedCriteria {

        public Criteria andStudent_idIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudent_idIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudent_idEqualTo(Long value) {
            addCriterion("student_id =", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idNotEqualTo(Long value) {
            addCriterion("student_id <>", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idGreaterThan(Long value) {
            addCriterion("student_id >", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idGreaterThanOrEqualTo(Long value) {
            addCriterion("student_id >=", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idLessThan(Long value) {
            addCriterion("student_id <", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idLessThanOrEqualTo(Long value) {
            addCriterion("student_id <=", value, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idIn(List<Long> values) {
            addCriterion("student_id in", values, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idNotIn(List<Long> values) {
            addCriterion("student_id not in", values, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idBetween(Long value1, Long value2) {
            addCriterion("student_id between", value1, value2, "student_id");
            return (Criteria) this;
        }

        public Criteria andStudent_idNotBetween(Long value1, Long value2) {
            addCriterion("student_id not between", value1, value2, "student_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idIsNull() {
            addCriterion("serviceitem_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idIsNotNull() {
            addCriterion("serviceitem_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idEqualTo(Long value) {
            addCriterion("serviceitem_id =", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idNotEqualTo(Long value) {
            addCriterion("serviceitem_id <>", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idGreaterThan(Long value) {
            addCriterion("serviceitem_id >", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idGreaterThanOrEqualTo(Long value) {
            addCriterion("serviceitem_id >=", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idLessThan(Long value) {
            addCriterion("serviceitem_id <", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idLessThanOrEqualTo(Long value) {
            addCriterion("serviceitem_id <=", value, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idIn(List<Long> values) {
            addCriterion("serviceitem_id in", values, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idNotIn(List<Long> values) {
            addCriterion("serviceitem_id not in", values, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idBetween(Long value1, Long value2) {
            addCriterion("serviceitem_id between", value1, value2, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andServiceitem_idNotBetween(Long value1, Long value2) {
            addCriterion("serviceitem_id not between", value1, value2, "serviceitem_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idIsNull() {
            addCriterion("train_plan_id is null");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idIsNotNull() {
            addCriterion("train_plan_id is not null");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idEqualTo(Long value) {
            addCriterion("train_plan_id =", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idNotEqualTo(Long value) {
            addCriterion("train_plan_id <>", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idGreaterThan(Long value) {
            addCriterion("train_plan_id >", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idGreaterThanOrEqualTo(Long value) {
            addCriterion("train_plan_id >=", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idLessThan(Long value) {
            addCriterion("train_plan_id <", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idLessThanOrEqualTo(Long value) {
            addCriterion("train_plan_id <=", value, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idIn(List<Long> values) {
            addCriterion("train_plan_id in", values, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idNotIn(List<Long> values) {
            addCriterion("train_plan_id not in", values, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idBetween(Long value1, Long value2) {
            addCriterion("train_plan_id between", value1, value2, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andTrain_plan_idNotBetween(Long value1, Long value2) {
            addCriterion("train_plan_id not between", value1, value2, "train_plan_id");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andCreate_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "create_datetime");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeIsNull() {
            addCriterion("active_datetime is null");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeIsNotNull() {
            addCriterion("active_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeEqualTo(Date value) {
            addCriterion("active_datetime =", value, "active_datetime");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeNotEqualTo(Date value) {
            addCriterion("active_datetime <>", value, "active_datetime");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeGreaterThan(Date value) {
            addCriterion("active_datetime >", value, "active_datetime");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("active_datetime >=", value, "active_datetime");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeLessThan(Date value) {
            addCriterion("active_datetime <", value, "active_datetime");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeLessThanOrEqualTo(Date value) {
            addCriterion("active_datetime <=", value, "active_datetime");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeIn(List<Date> values) {
            addCriterion("active_datetime in", values, "active_datetime");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeNotIn(List<Date> values) {
            addCriterion("active_datetime not in", values, "active_datetime");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeBetween(Date value1, Date value2) {
            addCriterion("active_datetime between", value1, value2, "active_datetime");
            return (Criteria) this;
        }

        public Criteria andActive_datetimeNotBetween(Date value1, Date value2) {
            addCriterion("active_datetime not between", value1, value2, "active_datetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student__serviceitem
     *
     * @mbg.generated do_not_delete_during_merge Thu Feb 01 11:23:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table student__serviceitem
     *
     * @mbg.generated Thu Feb 01 11:23:32 CST 2018
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]	学员 服务项
		//--------------------------------------------------
		/** 学员id */							student_id(1,Types.BIGINT,false),
		/** 服务项id */							serviceitem_id(1,Types.BIGINT,false),
		/** 培训计划id  已学课程关联 */			train_plan_id(2,Types.BIGINT,false),
		/** 0 无效，1 有效 */					status(2,Types.INTEGER,false),
		/** 创建日期 */							create_datetime(2,Types.TIMESTAMP,false),
		/** 服务项生效时间 */					active_datetime(2,Types.TIMESTAMP,false);

        private final CItem C_I_T_E_M;

        private C(int type, int jdbcType, boolean delimited) {
            C_I_T_E_M = new CItem(type, jdbcType, delimited, name(), null , "`", "`");
        }

        public int getType() {
            return C_I_T_E_M.getType();
        }

        public int getJdbcType() {
            return C_I_T_E_M.getJdbcType();
        }

        public boolean isDelimited() {
            return C_I_T_E_M.isDelimited();
        }

        public String delimitedName() {
            return C_I_T_E_M.delimitedName();
        }

        public String delimitedAliasName() {
            return C_I_T_E_M.delimitedAliasName();
        }
    }
}